### ISSUE TITLE
Table properties toolbar is scrolling through non-editor content section also

### ISSUE THREAD

**Issue by srikantyasam** [ckeditor/ckeditor5#14559] opened 2023-07-10 14:14 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Opened the ckeditor feature demo url 'https://ckeditor.com/ckeditor-5/demo/feature-rich/'
2. Removed the OOTB content , added some text along with a table as shown below.

![image](https://github.com/ckeditor/ckeditor5/assets/60339448/c2659db3-619c-4f78-85ed-49d3bc354ab7)
    
3. Select the table. Table properties toolbar section is opened
4. Now scroll-down the page through the vertical scroll bar
![image](https://github.com/ckeditor/ckeditor5/assets/60339448/ec6a8d52-ae27-4359-b92a-bd2063c8bca5)

5. Scroll the page down further. The table properties toolbar is scrolled through non-editor section( editor toolbar section, in this case) though the actual table is not visible in the current DOM view.

![image](https://github.com/ckeditor/ckeditor5/assets/60339448/d97a28d8-6e47-49a8-8451-1b94df854012)

 
### ✔️ Expected result

Table properties toolbar should only be visible when the table is present in the DOM view. It should not be positioned beyond the editor content area and should automatically hide when the table is no-longer visible in the view(due to scroll-up/down actions)

### ❌ Actual result

Table properties toolbar is still shown on the UI, though table is not visible.

### ❓ Possible solution

?

## 📃 Other details

?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-07-13 07:22
Thanks for reporting, this is a duplicate of #5328.

**Closed by Witoso** 2023-07-13 07:22 UTC
Labels: type:bug

**Comment by srikantyasam** [comment] 2023-07-26 07:12
> Thanks for reporting, this is a duplicate of #5328.

@Witoso Thanks for the response on this issue. 
As you marked the issue as duplicate to [5328](https://github.com/ckeditor/ckeditor5/issues/5328) , and #5328 was marked closed through the recently merged PR [14630](https://github.com/ckeditor/ckeditor5/pull/14630). 

Does it mean we need to upgrade to latest version(38.1.1) to get this issue resolved???

We are using 'ckeditor5-build-classic' and currently on version '36.0.1' .. Please confirm ..

**Comment by Witoso** [comment] 2023-07-31 09:45
[#5328](https://github.com/ckeditor/ckeditor5/issues/5328) needed to be reopened as the testing phase showed some regressions, we will most likely add it to the the release after the next one.
