### ISSUE TITLE
Support Angular SSR ?

### ISSUE THREAD

**Issue by sauravraj95** [ckeditor/ckeditor5#1499] opened 2019-01-31 15:54 UTC

**Comment by sauravraj95** [comment] 2019-02-01 09:45
![screenshot at jan 31 21-46-49](https://user-images.githubusercontent.com/44743752/52115089-b8600980-2633-11e9-9c59-a03954932c11.png)

**Comment by sauravraj95** [comment] 2019-02-03 15:50
it's not supporting SSR in my case and giving window location reff. error.

**Comment by sauravraj95** [comment] 2019-02-03 15:51
But still I have done some hack and now it's working. But still it needs to be fixed.

**Comment by sauravraj95** [comment] 2019-02-03 15:54
maybe it'll help others:- 

// Initially make it false so that it'll load after browser load
ckEditorLoaded = false;


ngOnInit() {
    if (isPlatformBrowser(this.platform)) {
      this.loadCkEditor();
    }
  }

  // TODO: adding a hack to load to ckEditor as it doesn't support SSR.
  loadCkEditor() {
    const jsElmCK = document.createElement('script');
    jsElmCK.type = 'application/javascript';
    jsElmCK.src = 'https://cdn.ckeditor.com/ckeditor5/11.2.0/classic/ckeditor.js';
    document.body.appendChild(jsElmCK);
    jsElmCK.onload = () => {
      this.editor = (window as any).ClassicEditor;
      this.ckEditorLoaded = true;
    };
  }

**Comment by oleq** [comment] 2019-02-05 10:16
I think this issue should be transferred to https://github.com/ckeditor/ckeditor5-angular and triaged by @ma2ciek.

**Comment by pomek** [comment] 2019-02-05 11:32
In this topic, I recommend reading a discussion in React repository – https://github.com/ckeditor/ckeditor5-react/issues/31.

**Comment by Reinmar** [comment] 2019-02-06 08:38
I'll move [ckeditor/ckeditor5-react#31](https://github.com/ckeditor/ckeditor5-react/issues/31) to this repo since it's quite general. Then we can merge this ticket into that one.

**Comment by Reinmar** [comment] 2019-02-06 08:39
Closed as DUP of https://github.com/ckeditor/ckeditor5/issues/1511.

**Closed by Reinmar** 2019-02-06 08:39 UTC
Labels: status:pending

**Comment by mickprev** [comment] 2021-11-20 15:55
Even if the issue is closed, I put it here because it can always help. 

Another solution is to use [a custom Ckeditor 5 build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build) and add the following lines at the beginning of your JS file (the generated Ckeditor file):

```
if (typeof window === 'undefined') {
  return;
}
```

**Comment by sdavid501** [comment] 2022-01-31 20:46
if(isPlatformBrowser(this.platformId)){
  import('@ckeditor/ckeditor5-build-classic').then(i => {
    this.ClassicEditor = i.default;
  };
}

**Comment by FatihBaycu** [comment] 2024-02-20 21:01
I solved like that
https://gist.github.com/FatihBaycu/e14a81680e2d2f7ff8741ca2bf4402ab
