### ISSUE TITLE
custom mention with text formatting is lost

### ISSUE THREAD

**Issue by kjakub** [ckeditor/ckeditor5#6831] opened 2020-05-15 14:53 UTC
## 📝 Provide detailed reproduction steps (if any)

1. follow customizing mention plugin instructions upcast, downcast methods [https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#customizing-the-output](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#customizing-the-output) 
2. create mention
3. format mention with italic, bold etc..
4. load content back to editor `editor.setData('<a class="mention" data-mention="@swarley" data-user-id="1" href="https://www.imdb.com/title/tt0460649/characters/nm0000439"><strong>@swarley</strong></a>'`

### ✔️ Expected result

customized mention will be in editor `<a ...`

### ❌ Actual result

customized mention is gone and only formatted text remains

* Browser: Chrome Version 81.0.4044.138 (Official Build) unknown (64-bit)
* OS: ubuntu 16.05
* CKEditor version: 18
* Installed CKEditor plugins: mention

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by kjakub** [comment] 2020-05-15 14:54
:+1:

**Comment by jodator** [comment] 2020-05-18 07:22
Hi @kjakub - the guide is being updated with some fixes. The clue of those changes is to document how the View `AttributeElement` should be handled for mentions: https://github.com/ckeditor/ckeditor5/pull/6739/files#diff-90c0d3b0e4fce9c9ce5ec1bf3bbbc2fb. The missing part is to use `priority: 20` that should change how the mention attribute element wrapped by other attribute elements (like bold, italic).

**Comment by kjakub** [comment] 2020-05-18 08:03
@jodator thank you a lot, i will give a try

**Comment by Mgsy** [comment] 2020-05-18 09:13
This is a duplicate of #6587.

**Closed by Mgsy** 2020-05-18 09:13 UTC
Labels: type:bug
