### ISSUE TITLE
imageStyle:full is missing

### ISSUE THREAD

**Issue by awmartin** [ckeditor/ckeditor5#11090] opened 2022-01-09 20:55 UTC
## 📝 Provide detailed reproduction steps (if any)

Include the ImageStyle and ImageToolbar plugins and incorporate `imageStyle:full` in a toolbar as noted in the documentation [here](https://ckeditor.com/docs/ckeditor5/11.1.1/api/module_image_imagestyle_utils.html#constant-defaultStyles) and [here](https://ckeditor.com/docs/ckeditor5/11.1.1/api/module_image_image-ImageConfig.html#member-toolbar).

    image: {
      toolbar: [ 'imageTextAlternative', '|', 'imageStyle:full', 'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight' ],
      styles: ['full', 'alignLeft', 'alignCenter', 'alignRight']
    },

### ✔️ Expected result

A button should appear in the toolbar that when clicked, enables an image to span the full width of the editor.

According to the [ImageStyle documentation](https://ckeditor.com/docs/ckeditor5/11.1.1/features/image.html#image-styles) (and as was available in previous versions), this style should be available as a predefined style:

> The code sample above uses predefined image styles: 'full', 'alignLeft' and 'alignRight'.

Also the [ImageToolbar documentation](https://ckeditor.com/docs/ckeditor5/11.1.1/api/module_image_image-ImageConfig.html#member-toolbar):

    const imageConfig = {
      toolbar: [ 'imageStyle:full', 'imageStyle:side', '|', 'imageTextAlternative' ]
    };

### ❌ Actual result

The button does not appear and a warning appears instead, stating:

> toolbarview-item-unavailable Object { name: "imageStyle:full" }
 
### ❓ Possible solution

No idea. 🤔

## 📃 Other details

In addition, it seems that `imageStyle:block` and `imageStyle:alignCenter` behave identically, both producing the same button to align center.

* Browser: Firefox 95.0.2
* OS: macOS 12.1
* First affected CKEditor version: 31.0.0 (also appears in 31.1.0)
* Installed CKEditor plugins:
    "@ckeditor/ckeditor5-alignment": "^31.1.0",
    "@ckeditor/ckeditor5-autoformat": "^31.1.0",
    "@ckeditor/ckeditor5-basic-styles": "^31.1.0",
    "@ckeditor/ckeditor5-block-quote": "^31.1.0",
    "@ckeditor/ckeditor5-dev-utils": "^27.4.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^27.4.0",
    "@ckeditor/ckeditor5-editor-balloon": "^31.1.0",
    "@ckeditor/ckeditor5-editor-classic": "^31.1.0",
    "@ckeditor/ckeditor5-essentials": "^31.1.0",
    "@ckeditor/ckeditor5-heading": "^31.1.0",
    "@ckeditor/ckeditor5-highlight": "^31.1.0",
    "@ckeditor/ckeditor5-horizontal-line": "^31.1.0",
    "@ckeditor/ckeditor5-image": "^31.1.0",
    "@ckeditor/ckeditor5-indent": "^31.1.0",
    "@ckeditor/ckeditor5-link": "^31.1.0",
    "@ckeditor/ckeditor5-list": "^31.1.0",
    "@ckeditor/ckeditor5-media-embed": "^31.1.0",
    "@ckeditor/ckeditor5-mention": "31.1.0",
    "@ckeditor/ckeditor5-paragraph": "^31.1.0",
    "@ckeditor/ckeditor5-paste-from-office": "^31.1.0",
    "@ckeditor/ckeditor5-remove-format": "^31.1.0",
    "@ckeditor/ckeditor5-table": "^31.1.0",
    "@ckeditor/ckeditor5-theme-lark": "^31.1.0",
    "@ckeditor/ckeditor5-vue": "^2.0.1",
    "@ckeditor/ckeditor5-word-count": "^31.1.0",

**Comment by shahzebgit** [comment] 2022-01-10 10:48
Can confirm it's not working, i'm using decoupled-document editor
![image](https://user-images.githubusercontent.com/51449693/148753614-a9a90e59-7494-43d6-b0ca-b528d17b0e57.png)

**Comment by Madejczyk** [comment] 2022-01-17 18:08
Can you check imageStyle:block? Or this is not the same?

**Comment by awmartin** [comment] 2022-01-17 22:11
> Can you check imageStyle:block? Or this is not the same?

It doesn't seem to be the same as :full, as I noted in the original issue.

**Comment by dufipl** [comment] 2022-01-21 15:53
Hello @awmartin,
There are some things that need to be clarified here: `imageStyle:full` is not supported anymore starting CKEditor 5 version 29.0.0. The documentation you are referring to is prepared for CKEditor 5 in version 11.1.1. This form of styling was replaced by the `block` style. Please take migration to version 29.0.0 guide as a reference in that matter: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-to-29.html#image-styles
You can also take a look at the current version of documentation for image styling (https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html) which I hope will provide you sufficient and up to date information on that topic.
Therefore, this is not a bug so I will close the issue. 
In case of additional issues/problems please do not hesitate to reach us out in the comments below.

**Closed by dufipl** 2022-01-21 15:53 UTC
Labels: type:bug

**Comment by awmartin** [comment] 2022-01-22 20:50
Thanks!
