### ISSUE TITLE
Styles + HtmlSupport plugins - Source added allowed-classes replicate on every following element

### ISSUE THREAD

**Issue by ndanvers** [ckeditor/ckeditor5#13183] opened 2022-12-30 00:36 UTC
``## 📝 Provide detailed reproduction steps (if any)

1. … From source, create & build a CKEditor with 
```
//package.json
    "@ckeditor/ckeditor5-html-support": "^34.0.0",
    "@ckeditor/ckeditor5-style": "^34.0.0",

//ckeditor.js
import Style from "@ckeditor/ckeditor5-style/src/style";
import GeneralHtmlSupport from "@ckeditor/ckeditor5-html-support/src/generalhtmlsupport";

style: {
		definitions: [
			{
				name: 'Article category',
				element: 'h3',
				classes: [ 'ck-category' ]
			},
			{
				name: 'Info box',
				element: 'p',
				classes: [ 'ck-info-box' ]
			},
		]
	},
	htmlSupport: {
		allow: [
			{
				name: /.*/,
				attributes: true,
				classes: true,
				styles: true
			}
		]
	},
	```

2. In editor Go to source and add `<div class="button-wrapper"><input type="button" value="test"></div>`
- Exit source
- Add any content after the HtmlElement that appears
- Check source, all elements will have the button-wrapper class given to the div
- try to use styles plugin - highlight a P tag after the button and apply "info-box" 
- Check source, now the P tag has button-wrapper & info-box classes

### ✔️ Expected result
<div class='button-wrapper'> with input element can be created and rendered as an "htmlElement", elements after this has been created should not be given the "button-wrapper" class.

### ❌ Actual result
button-wrapper is applied to all elements after inserting it in source, there is no way for me to remove the class without going into source and removing it from a following element.

## 📃 Other details

* Browser: Chromium @ latest
* OS: NixOS 21.05
* First affected CKEditor version:34
* Installed CKEditor plugins:
```"dependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^34.0.0",
    "@ckeditor/ckeditor5-autoformat": "^34.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^34.0.0",
    "@ckeditor/ckeditor5-block-quote": "^34.0.0",
    "@ckeditor/ckeditor5-ckfinder": "^34.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^34.0.0",
    "@ckeditor/ckeditor5-essentials": "^34.0.0",
    "@ckeditor/ckeditor5-heading": "^34.0.0",
    "@ckeditor/ckeditor5-horizontal-line": "^34.0.0",
    "@ckeditor/ckeditor5-html-support": "^34.0.0",
    "@ckeditor/ckeditor5-image": "^34.0.0",
    "@ckeditor/ckeditor5-indent": "^34.0.0",
    "@ckeditor/ckeditor5-link": "^34.0.0",
    "@ckeditor/ckeditor5-list": "^34.0.0",
    "@ckeditor/ckeditor5-media-embed": "^34.0.0",
    "@ckeditor/ckeditor5-paragraph": "^34.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^34.0.0",
    "@ckeditor/ckeditor5-source-editing": "^34.0.0",
    "@ckeditor/ckeditor5-style": "^34.0.0",
    "@ckeditor/ckeditor5-table": "^34.0.0",
    "@ckeditor/ckeditor5-typing": "^34.0.0"
  },
  "
devDependencies": {
    "@ckeditor/ckeditor5-alignment": "^34.0.0",
    "@ckeditor/ckeditor5-core": "^34.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^20.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^20.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^34.0.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^4.0.1",
    "style-loader": "^1.2.1",
    "terser-webpack-plugin": "^3.0.2",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2023-01-02 13:05
Duplicate of https://github.com/ckeditor/ckeditor5/issues/11518

**Closed by FilipTokarski** 2023-01-02 13:05 UTC
Labels: type:bug
