### ISSUE TITLE
An error thrown when setting a data containing a list element with an inline font-weight (regression)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#1399] opened 2018-12-10 10:42 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

11.2.0

## 📋 Steps to reproduce

1. https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html
2. `editor.setData( '<ol><li style="font-weight: bold">foo</li></ol>' )`

## ✅ Expected result

Data is set. In 11.1.1 it wasn't quite valid but at least there was no error:

![image](https://user-images.githubusercontent.com/1099479/49727373-6375c780-fc70-11e8-998d-ddd97a9dfaf5.png)

## ❎ Actual result

An error is thrown

```
converters.js:827 Uncaught TypeError: Cannot read property 'start' of null
    at converters.js:827
    at Ia.Jm (converters.js:369)
    at Ia.fire (emittermixin.js:196)
    at Ia._convertItem (upcastdispatcher.js:218)
    at Ia._convertChildren (upcastdispatcher.js:249)
    at Ia.La.upcastDispatcher.on (upcast-converters.js:583)
    at Ia.fire (emittermixin.js:196)
    at Ia._convertItem (upcastdispatcher.js:218)
    at Ia._convertChildren (upcastdispatcher.js:249)
    at Ia.La.upcastDispatcher.on (upcast-converters.js:583)
```

## 📃 Other details that might be useful

It's a regression of 11.2.0.

**Comment by scofalik** [comment] 2018-12-10 14:59
Could be related to changes done by @f1ames, related with lists pasting?

**Comment by f1ames** [comment] 2018-12-11 08:05
Yes, it seems the issue was introduced together with https://github.com/ckeditor/ckeditor5-list/pull/113 PR. However, the cause is more general as @scofalik pointed out. What happens is:

1. The `font-weight` converter (from `basic-styles` plugin) is executed on `<li>` element.
1. The text itself is not yet converted.
1. Text gets converted to `<p>foo</p>` (looks like `autoparagraphing` mechanism kicks in).
1. Bold is set on text.
1. Now, the list converter is executed on the same `<li>` element.
1. Since the above converter also tries to convert `<li>` children and the text was already consumed/converted the error is thrown (as conversion result for the text is empty).

Now, there are few things to consider:
* Why attribute conversion is executed before element conversion?
* Is the [bold converter in `basic-styles` plugin](https://github.com/ckeditor/ckeditor5-basic-styles/blob/51244ecb5a38bc5ae07cc7583cf3e44d0de6fa67/src/bold/boldediting.js#L34-L45) created/configured correctly or maybe it can be adjusted to solve this issue?

**Comment by f1ames** [comment] 2018-12-11 11:49
When `editor.setData( '<ol><li style="font-weight: bold">foo</li></ol>' )` is run the conversions order is as follows (`--- convertItem:*` indicates that conversion event was fired for the given item and doesn't mean that any converter was actually executed):

```
01 editor.setData( '<ol><li style="font-weight: bold">foo</li></ol>' )
02 --- convertItem:documentFragment {viewItem: DocumentFragment, modelCursor: Position, modelRange: null} DocumentFragment {_children: Array(1)}
03 --- convertItem:element ol Element {parent: DocumentFragment, name: "ol", _attrs: Map(0), _children: Array(1), _classes: Set(0), …}
04 OL/UL conversion - cleanList
05 --- convertItem:element li Element {parent: Element, name: "li", _attrs: Map(0), _children: Array(1), _classes: Set(0), …}
06 LI conversion - cleanListItem
07 AttributeConversion li {view: {…}, model: {…}, priority: undefined}
08 --- convertItem:text {viewItem: Text, modelCursor: Position, modelRange: null} Text {parent: Element, _textData: "foo"}
09 TEXT conversion - paragraph plugin autoparagraphing
10 --- convertItem:text {viewItem: Text, modelCursor: Position, modelRange: null} Text {parent: Element, _textData: "foo"}
11 LI conversion - viewModelConverter
12 --- convertItem:text {viewItem: Text, modelCursor: Position, modelRange: null} Text {parent: Element, _textData: "foo"}
13 Uncaught TypeError: Cannot read property 'start' of null
```

So in line **07**, the `font-weight` from `<li>` is converted which then causes autoparagraphing the `<li>`'s text (line **09**).

When `font-weight` converter from `basic-styles` plugin is disabled, lines **07-10** are not executed and everything converts fine (which means attribute conversion on `<li>` somehow triggers autoparagraphing - needs to be checked):

```
01 editor.setData( '<ol><li style="font-weight: bold">foo</li></ol>' )
02 --- convertItem:documentFragment {viewItem: DocumentFragment, modelCursor: Position, modelRange: null} DocumentFragment {_children: Array(1)}
03 --- convertItem:element ol Element {parent: DocumentFragment, name: "ol", _attrs: Map(0), _children: Array(1), _classes: Set(0), …}
04 OL/UL conversion - cleanList
05 --- convertItem:element li Element {parent: Element, name: "li", _attrs: Map(0), _children: Array(1), _classes: Set(0), …}
06 LI conversion - cleanListItem
07 LI conversion - viewModelConverter
08 --- convertItem:text {viewItem: Text, modelCursor: Position, modelRange: null} Text {parent: Element, _textData: "foo"}
```

and the same happens when [`li:viewModelConverter`](https://github.com/ckeditor/ckeditor5-list/blob/f5315c25a03a24d777a48e8079cb8926042ee1ca/src/listediting.js#L93) has priority higher then default one (e.g. `{ priority: 'high' }`).

---

Another thing I have noticed is that [autoparagraphing converter has the `lowest` priority](https://github.com/ckeditor/ckeditor5-paragraph/blob/c400b59f6027b835f4bf3699d533aeefe72616d0/src/paragraph.js#L93-L102), still it executes before the `li` one (`LI conversion - viewModelConverter`) which seems strange TBH.

**Comment by scofalik** [comment] 2018-12-11 12:18
Isn't it because li converter explicitly converts it's children first and then it creates an element for itself? I am not looking into the code so this may be totally wrong :P.

**Comment by f1ames** [comment] 2018-12-11 12:44
> Isn't it because li converter explicitly converts it's children first and then it creates an element for itself? I am not looking into the code so this may be totally wrong :P.

I was thinking about it, but from what I see `li` is converted first - basically it is marked as consumed and then processed (see https://github.com/ckeditor/ckeditor5-list/blob/f5315c25a03a24d777a48e8079cb8926042ee1ca/src/converters.js#L340). And after that it's children are converted.

I think there are at least two issues here:
* The `<li>` children converter doesn't check if child can be consumed (however I'm not sure if that's mandatory during such conversions).
* The unexpected order of list children/paragraph converters.

☝️ I was wondering if the order is not caused by the fact that priority is respected only for the same type of converters. So when `li font-weight` is converted (attribute conversion) it also converts text inside which goes through all text converters and then element conversion on `li` occurs.

**Comment by f1ames** [comment] 2018-12-12 10:13
> * The `<li>` children converter doesn't check if child can be consumed (however I'm not sure if that's mandatory during such conversions).
> * The unexpected order of list children/paragraph converters.

@scofalik Do you think we should treat it as two separate issues and go with the 1 point here (which restores the previous behaviour of setting such data). And then in another issue try to improve converters (investigate the execution order) so setting content as above will result in correct list?

**Comment by scofalik** [comment] 2018-12-12 12:17
In upcast the situation is a little stinky cause we have the same event for elements upcasting and attributes upcasting. For this reason, we need to manage it using priorities. Attributes upcasting should happen always after elements upcasting. AFAICS the default priority for `elementToAttribute` upcast is `normal`. We should try changing it to `low`.

**Closed** 2018-12-13 16:12 UTC
Labels: package:engine, package:list, status:confirmed, type:bug
