### ISSUE TITLE
Link decorators with the same attribute duplicates A tag

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#13326] opened 2023-01-24 10:04 UTC
## 📝 Provide detailed reproduction steps (if any)

If I add two link decorators which have the same attribute, ckeditor insterts second `A` tag

```
link: {
            decorators: {
                targetBlank: {
                    mode: 'manual',
                    label: 'Otwórz w nowej zakładce',
                    attributes: {
                        target: '_blank',
                        rel: 'noopener norefferer'
                    }
                },
                nofollow: {
                    mode: 'manual',
                    label: 'Nofollow',
                    attributes: {
                        rel: 'nofollow'
                    }
                }
            }
        },
```
### ✔️ Expected result

Attributes should be joined with spacebar

### ❌ Actual result

```
<a rel="nooppener norefferer">
<a rel="nofollow">
</a></a>
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: chrome
* OS: windows
* Installed CKEditor plugins: 35

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2023-01-25 09:43
Thank you for the report. I'll close this one as in general it looks like a duplicate of https://github.com/ckeditor/ckeditor5/issues/6436.

**Closed by FilipTokarski** 2023-01-25 09:43 UTC
Labels: type:bug
