### ISSUE TITLE
Error during cleanup of component in unit tests

### ISSUE THREAD

**Issue by fkoepke** [ckeditor/ckeditor5#1794] opened 2019-06-01 13:11 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

"@ckeditor/ckeditor5-angular": "^1.1.0",
"@ckeditor/ckeditor5-build-classic": "^12.1.0",

## 📋 Steps to reproduce

1. add an editor (ClassicEditor) in a component
2. run unit tests for this component where you import CKEditorModule in TestBed

## ✅ Expected result
No Errors in console output of unit tests
## ❎ Actual result
```
ERROR: 'Error during cleanup of component', Object{component: PollComponent{activatedRoute: Object{paramMap: ...}, apiService: Object{getTest: ..., test: ...}, modalService: BsModalService{clf: ..., config: ..., onShow: ..., onShown: ..., onHide: ..., onHidden: ..., isBodyOverflowing: ..., originalBodyPadding: ..., scrollbarWidth: ..., modalsCount: ..., lastDismissReason: ..., loaders: ..., _backdropLoader: ..., _renderer: ...}, notificationService: Object{addNotification: ...}, navigateAwaySelection$: Subject{_isScalar: ..., observers: ..., closed: ..., isStopped: ..., hasError: ..., thrownError: ...}, subscriptions: [], modalTemplate: TemplateRef_{_parentView: ..., _def: ...}, Editor: class Qg extends $l{ ... }, testForm: FormGroup{validator: ..., asyncValidator: ..., _onCollectionChange: ..., pristine: ..., touched: ..., _onDisabledChange: ..., controls: ..., valueChanges: ..., statusChanges: ..., status: ..., value: ..., errors: ...}, activeId: null, poll: Object{uuid: ..., title: ..., answer: ...}, oldText: 'Test'}, stacktrace: TypeError: Cannot read property 'data-ck-expando' of undefined
TypeError: Cannot read property 'data-ck-expando' of undefined
    at ur (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:175196)
    at Yl._getProxyEmitter (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:175109)
    at Yl.stopListening (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:174909)
    at Yl.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:346438)
    at Yl.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:346746)
    at hl.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:337322)
    at Qg.destroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:354769)
    at CKEditorComponent.ngOnDestroy (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ckeditor/ckeditor5-angular/fesm2015/ckeditor-ckeditor5-angular.js:165:1)
    at callProviderLifecycles (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:24913:1)
    at callElementProvidersLifecycles (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:24872:1)}
HeadlessChrome 74.0.3729 (Mac OS X 10.14.2): Executed 22 of 49 SUCCESS (0 secs / 0.642 secs)
```
## 📃 Other details that might be useful
The error appears after update to Angular 8. 
Before update to Angular 8 I used Angular 7.2 and there were no errors in unit tests

**Comment by Mgsy** [comment] 2019-06-03 07:31
cc @ma2ciek

**Comment by ma2ciek** [comment] 2019-06-03 09:09
Duplicate of https://github.com/ckeditor/ckeditor5-angular/issues/109.

**Closed by ma2ciek** 2019-06-03 09:09 UTC
