### ISSUE TITLE
CKEditor crashes on Chrome 80

### ISSUE THREAD

**Issue by wojciechkoszyk** [ckeditor/ckeditor5#6222] opened 2020-02-11 09:13 UTC
## 📝 Provide detailed reproduction steps (if any)

type few sentences, focus in the middle of previous sentence some letters, start to type, error in console appears, user can type but can't go to new line or delete characters

ckeditorerror.js:89 Uncaught TypeError: Cannot read property 'name' of undefined
    at Differ.getChanges (differ.js:627)
    at tableLayoutPostFixer (table-layout-post-fixer.js:240)
    at eval (table-layout-post-fixer.js:231)
    at Document._callPostFixers (document.js:517)
    at Document._handleChangeBlock (document.js:373)
    at Model._runPendingChanges (model.js:952)
    at Model.enqueueChange (model.js:295)
    at deleteSelectionContent (injectunsafekeystrokeshandling.js:129)
    at handleUnsafeKeystroke (injectunsafekeystrokeshandling.js:100)
    at Document.view.document.on.priority (injectunsafekeystrokeshandling.js:45)

from some tests on other computers it seems that on chrome79 and on firefox is OK

### ✔️ Expected result

no error in console, normal functioning of editor

### ❌ Actual result

error in console causes problems with basic ckeditor usage

## 📃 Other details

* Browser: chrome80
* OS: osx/win
* CKEditor version: ckeditor5-react @ 2.1.0, custom but basic build from 16.0.0 packages (but can be reproduced on 15.0.0 packages as well)
* Installed CKEditor plugins: 

    "@ckeditor/ckeditor5-basic-styles": "16.0.0",
    "@ckeditor/ckeditor5-core": "16.0.0",
    "@ckeditor/ckeditor5-dev-utils": "12.0.7",
    "@ckeditor/ckeditor5-editor-classic": "16.0.0",
    "@ckeditor/ckeditor5-essentials": "16.0.0",
    "@ckeditor/ckeditor5-font": "16.0.0",
    "@ckeditor/ckeditor5-heading": "16.0.0",
    "@ckeditor/ckeditor5-highlight": "16.0.0",
    "@ckeditor/ckeditor5-image": "16.0.0",
    "@ckeditor/ckeditor5-list": "16.0.0",
    "@ckeditor/ckeditor5-paragraph": "16.0.0",
    "@ckeditor/ckeditor5-react": "2.1.0",
    "@ckeditor/ckeditor5-table": "16.0.0",
    "@ckeditor/ckeditor5-theme-lark": "16.0.0",
    "@ckeditor/ckeditor5-ui": "16.0.0",
    "@ckeditor/ckeditor5-word-count": "16.0.0",

**Comment by mlewand** [comment] 2020-02-11 09:21
I can confirm this issue, I started to experience it since Chrome 80 has been rolled out too. It looks like a severe issue to me.

Here's an example screencast on our demo:

![](https://user-images.githubusercontent.com/5353898/74224029-44c9f100-4cb8-11ea-891c-a3959ba64938.png)

**Comment by wojciechkoszyk** [comment] 2020-02-11 09:23
I dont know whats with chrome80 but I cant even edit my ticket on github.com :( anyway, here's the video showing the problem: https://drive.google.com/file/d/1I63hC03jya1hVDBhfQZKWOWKWEVWUKam/view

we have "clean" browser without any plugins like grammarly etc.

**Comment by mlewand** [comment] 2020-02-11 09:24
Thanks @wojciechkoszyk for detailed information. That's actually in line with my assumption, overwriting a ranged selection seems to be causing the error.

**Comment by wojciechkoszyk** [comment] 2020-02-11 09:28
Thank you for confirming. Do you have any idea how to quickly fix it or is there any workaround for that? Am I right that Chrome80 is responsible for that bug?

**Comment by mlewand** [comment] 2020-02-11 09:31
We'll update this issue as soon as we have some workaround, though it doesn't seem to be trivial at the first glance.

Yes, you're correct that Chrome 80 seems to be causing this, we didn't pick these issues earlier - so temporarily going back to v79 is a short term workaround.

**Comment by Mgsy** [comment] 2020-02-11 09:35
Note: It occurs also in the previous CKEditor 5 releases, i.e. `11.1.0`.

**Comment by wojciechkoszyk** [comment] 2020-02-11 09:40
Thank you! I'll also try to find solution on my own

**Comment by Reinmar** [comment] 2020-02-11 09:43
I'm going to look into this. I know that Chrome 80 was released with a quite critical bug. I wonder if we're hitting it...

**Comment by mlewand** [comment] 2020-02-11 09:44
@wojciechkoszyk / all there's one more thing you can do until the issue is resolved: there's a watchdog feature. It does some extra job to preserve the content and reload the editor in case of crash.

You'll find more information about this in the [Watchdog guide](https://ckeditor.com/docs/ckeditor5/latest/features/watchdog.html).

Chrome@80 introduced some new bugs, like [array.reduce being called wrong accumulator](https://bugs.chromium.org/p/chromium/issues/detail?id=1049982) - these might be a reason for the isseu.

**Comment by wojciechkoszyk** [comment] 2020-02-11 10:03
seems like watchdog is not supported in ckeditor integrations (I'm using ckeditor5-react)?

**Comment by Reinmar** [comment] 2020-02-11 10:09
Unfortunately not yet :(

**Comment by Reinmar** [comment] 2020-02-11 10:20
This is a weird bug. So far I managed to reproduce it once. And then I clicked and clicked and clicked and nothing's happening.

Unfortunately, unless we have a scenario that keeps crashing in a more predictable way, I can't debug it. 

@Mgsy, @mlewand do you have more luck here?

**Comment by Mgsy** [comment] 2020-02-11 10:26
Interesting. I've reproduced it, then instantly I tried to repeat the scenario and I'm not able to do it again. I'll keep trying and try to figure out some pattern.

**Comment by wojciechkoszyk** [comment] 2020-02-11 10:33
Few people from our company also have problems with reproducing it. For me it's 100% reproducable. And here is my quick finding:

file: ckeditor5-engine/src/model/nodelist.js
method `getNodeStartOffset` and getter `maxOffset`
if you change reduce function to forEach it just works... 😭

**Comment by Reinmar** [comment] 2020-02-11 11:26
So that's the reduce bug :D https://twitter.com/JanBenedictus/status/1227168801604677632

Thanks for letting us know. It means that we need to wait for the new Chrome version. It's going to ship faster than we'd ship (and people deploy) a hotfix in our code base. Also, we should probably also replace all other `reduce()` calls to avoid this issue.

**Comment by Reinmar** [comment] 2020-02-11 11:38
I can confirm that the workaround proposed by @wojciechkoszyk works:

```diff
diff --git a/src/model/nodelist.js b/src/model/nodelist.js
index 50aaa391..48cf1b26 100644
--- a/src/model/nodelist.js
+++ b/src/model/nodelist.js
@@ -99,7 +99,17 @@ export default class NodeList {
     getNodeStartOffset( node ) {
         const index = this.getNodeIndex( node );

-        return index === null ? null : this._nodes.slice( 0, index ).reduce( ( sum, node ) => sum + node.offsetSize, 0 );
+        return index === null ? null : sum( this._nodes.slice( 0, index ) );
+
+        function sum( nodes ) {
+            let sum = 0;
+
+            nodes.forEach( node => {
+                sum += node.offsetSize;
+            } );
+
+            return sum;
+        }
     }
```

If anyone's hitting this bug, this would be the first thing to try until the new version of Chrome is released.

However, there's a chance that some other use of `reduce()` in our codebase will also cause the editor to crash at some other scenario.

**Comment by wojciechkoszyk** [comment] 2020-02-11 14:16
OK now how to add that change into custom ckeditor build? 🤔 I've forked ckeditor5-core and ckeditor5-engine and use it in my project (pointed ckeditor5-core to my github fork and inside it in package.json pointed ckeditor5-engine to my github fork) and it builds fine but ckeditor doesn't load (this.config.names is not a function). Can you help applying that change? ;)

**Comment by ma2ciek** [comment] 2020-02-11 15:08
Did you do the fix on the `stable` branch? The `master` branch may contain some breaking changes not compatible with older versions of other packages. Also, we don't allow that as it results often in a dependency duplication error.

**Comment by wojciechkoszyk** [comment] 2020-02-11 17:30
Thank you, seems like switching to `stable` branch did the job.

**Comment by wojciechkoszyk** [comment] 2020-02-12 09:39
Just FYI, Chrome released new version `80.0.3987.100` but unfortunately problem still occurs.

**Comment by Reinmar** [comment] 2020-02-12 14:47
The issue is on the Chrome side now officially closed (https://bugs.chromium.org/p/chromium/issues/detail?id=1049982#c75).

**Comment by danyal14** [comment] 2020-02-13 10:12
> The issue is on the Chrome side now officially closed (https://bugs.chromium.org/p/chromium/issues/detail?id=1049982#c75).

Thanks for the reply, if issue is fixed officially & closed, what would be the next step for us. Since writers are totally unable to write in ckeditor due to this issue.

Is there a way to know which upcoming version of chrome has this fix? and can we download this pre officially launched?

**Comment by Reinmar** [comment] 2020-02-13 12:06
If you need a quick fix you can introduce the patch mentioned in https://github.com/ckeditor/ckeditor5/issues/6222#issuecomment-584594975. This will instantly solve at least the one issue that we saw the most.

Unfortunately, IDK when the new version of Chrome will be available. Most likely in a couple of days. But whether it's tomorrow or on Wednesday, I can't tell.

**Comment by danyal14** [comment] 2020-02-13 13:21
> If you need a quick fix you can introduce the patch mentioned in [#6222 (comment)](https://github.com/ckeditor/ckeditor5/issues/6222#issuecomment-584594975). This will instantly solve at least the one issue that we saw the most.
> 
> Unfortunately, IDK when the new version of Chrome will be available. Most likely in a couple of days. But whether it's tomorrow or on Wednesday, I can't tell.


We are using CDN version of CK Editor, where to put patch when using 
https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js

And even if I host it by self the spaces are not allowed again.

**Comment by Reinmar** [comment] 2020-02-13 14:17
It seems that the new version of Chrome will be available even today: https://bugs.chromium.org/p/chromium/issues/detail?id=1049982#c82



> We are using CDN version of CK Editor, where to put patch when using
> https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js

Unfortunately, you can't patch it like that. The other option for you would be to polyfill `Array.prototype.reduce`.

> And even if I host it by self the spaces are not allowed again.

I don't understand what you mean.

**Comment by mlewand** [comment] 2020-02-14 07:37
The fix has been deployed in `80.0.3987.106` which now available in Chrome stable channel.

**Closed by mlewand** 2020-02-14 07:37 UTC
Labels: status:confirmed, support:1, type:bug

**Comment by Reinmar** [comment] 2020-02-14 08:25
Special thanks to @wojciechkoszyk and his team for providing the workaround ❤️

**Comment by stasyabezruk** [comment] 2020-06-16 10:58
From official tutorial for inline widget - still problem with cursor/focus in chrome (my version is 83.0.4103.106)
I've used code form here
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html
