### ISSUE TITLE
中文输入法书写错误 Chinese input method writing error

### ISSUE THREAD

**Issue by wry1314** [ckeditor/ckeditor5#11056] opened 2021-12-30 08:20 UTC
## 📝 Provide detailed reproduction steps (if any)

1. 切换中文输入法先输入一些中文
Switch the Chinese input method. Input some Chinese first
2. 在中文后连续输入俩个或俩个以上的空格
Enter two or more spaces after Chinese
3. 紧接着再输入中文
Then enter Chinese

_What is the expected result of the above steps?_

结果：第三个步骤中第一个字符会是英文，详见下面文件
Result: the first character in the third step will be English. See the following documents for details

https://user-images.githubusercontent.com/10495479/147733220-9f0918e0-98e6-4fad-ab24-1a092dcee0b8.mp4

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser:chrome
* OS: …
* First affected CKEditor version:CKEditor5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mdddj** [comment] 2021-12-31 02:38
同样的错误

**Comment by FilipTokarski** [comment] 2022-01-04 15:12
Thanks for the report, this is basically a duplicate of https://github.com/ckeditor/ckeditor5/issues/5895, so I'll close this one for now.

**Closed by FilipTokarski** 2022-01-04 15:12 UTC
Labels: type:bug
