### ISSUE TITLE
IME Typing issue

### ISSUE THREAD

**Issue by Clouds101** [ckeditor/ckeditor5#1117] opened 2018-06-28 02:13 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

CKEditor 5 v10.1.0

## 📋 Steps to reproduce

1.Korean Typing . 안녕하세요 => dkssudgktpdy
2.Enter

## 📃 Other details that might be useful
CKEditor4 is successful
![ckeditor4_korea_ime](https://user-images.githubusercontent.com/21264714/42009101-ce6945e6-7ac3-11e8-8e9c-d41fa64d1d78.gif) 

CKEditor5 Problem
![ckeditor5_ime](https://user-images.githubusercontent.com/21264714/42009227-5b91fddc-7ac4-11e8-841c-77239b97682a.gif) 

Chrome 67.0.3396.99(64bit) windows 10 in tested

**Comment by f1ames** [comment] 2018-06-28 06:20
Thanks for reporting @Clouds101, this is duplicate of #777. You can track the progress there.

**Closed by f1ames** 2018-06-28 06:20 UTC
Labels: resolution:duplicate
