### ISSUE TITLE
GHS converts `href` on linked images and loses link element in the data

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#14622] opened 2023-07-20 08:11 UTC
## 📝 Provide detailed reproduction steps (if any)

*   Go to http://localhost:8125/ckeditor5-html-support/tests/manual/ghs-all-features.html
*   Call:

```
editor.setData(`<figure class="image">
    <a href="test">
       <img src="https://upload.wikimedia.org/wikipedia/en/a/ab/CKEditor_4_and_CKEditor_5_logos.png" alt="Google Play">
   </a>
</figure>`)
```

*   Open the link balloon (CMD+K).
*   Open the source editing view.

### ✔️ Expected result

_Link is converted to `linkHref` model attribute and `<a>` element is visible in the data._

### ❌ Actual result

_Link's `href` attribute is converted to `htmlAttribute`_ and `<a>` element is invisible in the data.

Related: #12831 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-07-26 08:36
Duplicate of the https://github.com/ckeditor/ckeditor5/issues/12831.

**Closed by Witoso** 2023-07-26 08:36 UTC
Labels: type:bug, support:2, squad:core, package:html-support
