### ISSUE TITLE
Cursor gets placed at start of line when clicking to the right of a bullet point with children

### ISSUE THREAD

**Issue by adamerose** [ckeditor/ckeditor5#13148] opened 2022-12-23 12:22 UTC
## 📝 Reproduction steps

1. Create a bulleted list with multiple indentation levels
2. Left click to the right of a bullet with children

### ✔️ Expected result

The cursor should be placed at the end of the line

### ❌ Actual result

The cursor gets placed at the beginning of the line. It seems to always happen on bullets with children, and also happens if a bullet had children even after they are deleted

![Alt Text](https://imgur.com/9omAdP8.gif)

I am reproducing this bug on the current live demo: https://ckeditor.com/ckeditor-5/demo/#classic

**Comment by FilipTokarski** [comment] 2023-01-02 14:40
Duplicate of https://github.com/ckeditor/ckeditor5/issues/8961

**Closed by FilipTokarski** 2023-01-02 14:40 UTC
Labels: type:bug
