### ISSUE TITLE
Error on Chrome@43

### ISSUE THREAD

**Issue by xty1992a** [ckeditor/ckeditor5#6205] opened 2019-09-25 07:33 UTC
use  script tag inject this module on Chrome 43 got an error like this:
```
Uncaught SyntaxError: Unexpected token )
```
unfortunately, I can`t find the error in devtool (the brower version is to low).
but I think maybe the build config cause this error.

ps. sorroy for my poor English😂

**Comment by ma2ciek** [comment] 2020-02-06 22:50
I guess that you comment on the CKEditor 5, though I'm not certain about it.

**Comment by IgorKurkov** [comment] 2020-02-07 10:10
You need to know, I'm not a hater, sure, I saw your **Browser compatibility section**, but too late as for me. My fault. btw I worked with TinyMCE for a long time with SPA's & it was not the best ever variant for me and for my customers. As for my old projects, the CKEditor (probably v.3, v.4) always was like the best solution. Now I also tested froala editor and some else editors but they are buggy with angular SSR & cetra. So as for me - your huge robust and well-known software had to be best on the market. Now as a temporary solution I switched to ckeditor4 because it works as I expect, and I hope I can customizing it old styles well. also, I will test ckeditor5 with babel transpiling (thank you for guide link), because it definitely looks very cool and modern but I use this trick usually only for old libs, so this point a bit confusing me because you can easily make this option (I mean transpile it to es5) before sending the package to npm. I know it would be have a little bit bigger size bundle, but it will solve the appearing of a bunch of issues on GitHub by end-user-devs. 
Nevertheless, thanks for the answers and useful links!

**Comment by ma2ciek** [comment] 2020-02-07 10:41
\> I will test ckeditor5 with babel transpiling (thank you for guide link), because it definitely looks very cool and modern but I use this trick usually only for old libs, so this point a bit confusing me because you can easily make this option (I mean transpile it to es5) before sending the package to npm. I know it would be have a little bit bigger size bundle, but it will solve the appearing of a bunch of issues on GitHub by end-user-devs.

We're considering this option - [https://github.com/ckeditor/ckeditor5/issues/2152](https://github.com/ckeditor/ckeditor5/issues/2152), but TBH there's nobody interested in it. Give a :+1: there, please, if you're interested.

> Now I also tested froala editor and some else editors but they are buggy with angular SSR & cetra.

If you use Angular, then, there should be also an option to target ES5 and transpile dependencies, but I'm not sure how to force TypeScript or Angular to do so.

> Nevertheless, thanks for the answers and useful links!

You're welcome :slightly\_smiling\_face:, I hope that you find a solution that would allow you to use CKEditor 5 :crossed\_fingers: 

I'll close this issue as a duplicate of the [https://github.com/ckeditor/ckeditor5/issues/2152](https://github.com/ckeditor/ckeditor5/issues/2152).

**Closed by ma2ciek** 2020-02-07 10:41 UTC
Labels: browser:chrome, pending:feedback
