### ISSUE TITLE
Source editing doesn't work for certain HTML content

### ISSUE THREAD

**Issue by shabab477** [ckeditor/ckeditor5#10961] opened 2021-12-06 09:50 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Go to [CKEDITOR 5 - Source Editor](https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html)
2. Insert the following HTML in the source editing area:

```
<div>
   Vi ......
   <a href="#">
      <span style="background-color:rgb(255,255,255);color:rgb(45,62,80);font-size:1.3em;">
         <span class="lt-name entityTitle">
            <strong>Somethign</strong>
         </span>
      </span>
   </a>
   <span style="background-color:rgb(255,255,255);color:rgb(45,62,80);font-size:11px;">
      <span>,</span>
   </span>
   <span style="background-color:rgb(255,255,255);color:rgb(45,62,80);">
      <span>....</span>
   </span>
</div>
```
3. Open console and look for `Uncaught TypeError: e[i] is not iterable`

### ✔️ Expected result

_What is the expected result of the above steps?_

Not throw an error, show content.

### ❌ Actual result

_What is the actual result of the above steps?_

Throwing an error: `Uncaught TypeError: e[i] is not iterable`

### ❓ Possible solution

Check whether `target[ key ]`  is iterable at `conversionutils.js#mergeViewElementAttributes`  

## 📃 Other details

* Browser: Google Chrome
* OS: Ubuntu 20.04
* First affected CKEditor version: 
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by shahzebgit** [comment] 2021-12-06 10:47
This case looks like it's a duplicate of #10657

**Comment by shabab477** [comment] 2021-12-06 11:38
Yes this is the same issue.

**Comment by FilipTokarski** [comment] 2021-12-06 12:49
As mentioned above, it's a duplicate of https://github.com/ckeditor/ckeditor5/issues/10657. I'll close this for now.

**Closed by FilipTokarski** 2021-12-06 12:49 UTC
Labels: type:bug
