### ISSUE TITLE
bad interaction between boomerang.js and CKEditor 5 alpha 2

### ISSUE THREAD

**Issue by gustafn** [ckeditor/ckeditor5#793] opened 2018-01-26 14:13 UTC
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js

## 📋 Steps to reproduce

1. Initialization of a basic ckeditor5 alpha2 configuration fails, when boomerang is active
2. issue can be reproduced on a public website (see in provided link below)

## ✅ Expected result

ckeditor5 should initialize with and without boomerang installed

## ❎ Actual result

initialization fails

```javascript
boomerang-1.0.1514200883.min.js:10:20662
TypeError: e.on is not a function
Stack trace:
listenTo@http://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:79447
listenTo@http://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:222410
add@http://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:256269
init@http://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:5:319846
````
## 📃 Other details that might be useful

The problem is most likely an issue of boomerang, and it has been reported on the following link (including examples and more details)
https://github.com/SOASTA/boomerang/issues/180

It seems, that the boomerang people are trying to look into the issue, but maybe an experience ckeditor5 developer can quickly identify the issue.

**Comment by Reinmar** [comment] 2018-01-26 14:41
Thanks for letting us know. This issue was reported to us a couple of times already but concerning other libraries.

See e.g.:

* https://github.com/ckeditor/ckeditor5-build-classic/issues/34
* https://github.com/ckeditor/ckeditor5-editor-balloon/issues/12
* https://github.com/ckeditor/ckeditor5/issues/413
* https://github.com/ckeditor/ckeditor5/issues/683#issuecomment-346582285

This issue is caused by other libraries overriding native `Element#addEventListener()` in a rather poor way (and breaking the `toString()` method). Zone.js fixed it on their side, but since it occurs so often with so many libraries (which is sooo disappointing ;(), we decided to switch to a different check for whether an object is a native DOM Element.

The fix will be available in the next release (about a month time). 

If you'd like to have it immediately, you'd need to patch this file:

https://github.com/ckeditor/ckeditor5-utils/blob/master/src/dom/isdomnode.js

Instead of:

https://github.com/ckeditor/ckeditor5-utils/blob/06a33c40cdd7b3a0697f53f5e75d9a1bae29148a/src/dom/isdomnode.js#L18-L20

You should have this:

https://github.com/ckeditor/ckeditor5-utils/blob/f316584a3ac17198b6774fa95e38ad036136964d/src/dom/isdomnode.js#L16-L26

**Comment by Reinmar** [comment] 2018-01-26 14:41
Please let us know if this change helps. And, first of all, if that's the same issue :D

**Comment by gustafn** [comment] 2018-01-26 21:09
Reinmar, many tanks for the feedback! i did now the following

- cloned ckeditor5-build-classic repo  from github
- git checkout v1.0.0-alpha.2
- modified isDomNode() as indicated above
- npm run build

but the problem persists with the generated  `build/ckeditor.js`. I've deactivate minifaction to obtain better error messages, and got an error about a non-existing `emitter` function:
```javascript
boomerang.usertiming: [warn] UserTimingCompression library not found
boomerang-1.0.1514200883.min.js:10:20662
TypeError: emitter.on is not a function
Stack trace:
listenTo@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:2079:3
listenTo@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:34557:3
render@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:45552:3
viewcollection_ViewCollection/<@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:42503:5
fire@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:2169:5
add@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:42081:3
render@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:46205:3
init@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:41871:3
create/</<@http://localhost:8100/resources/richtext-ckeditor5/1.0.0-alpha.2/classic/ckeditor.js:46411:19
boomerang-1.0.1514200883.min.js:12:29036
boomerang.rt: [debug] Called done: load
```
As a reference, here is the relevant place from my ckeditor.js where line 2079 (the failing invocation of `emitter.on`) is the last line of code
```javascript
	listenTo( emitter, event, callback, options ) {
		let emitterInfo, eventCallbacks;
...
		const emitterId = _getEmitterId( emitter );

		if ( !( emitterInfo = emitters[ emitterId ] ) ) {
			emitterInfo = emitters[ emitterId ] = {
				emitter,
				callbacks: {}
			};
		}

		if ( !( eventCallbacks = emitterInfo.callbacks[ event ] ) ) {
			eventCallbacks = emitterInfo.callbacks[ event ] = [];
		}

		eventCallbacks.push( callback );

		// Finally register the callback to the event.
		emitter.on( event, callback, options );
	},
```

**Comment by Reinmar** [comment] 2018-01-29 11:41
Hm... this is weird. When I try to debug it on <> it's not about `emitter.on` being undefined but the whole `emitter` being undefined:

![image](https://user-images.githubusercontent.com/156149/35508668-7e99a44a-04f1-11e8-9ab6-bb45af5ca1a5.png)

So, it's either something wrong with Chrome's debugger, or the issue is somewhere else. Unfortunately, I can't help you debug this. What would help though was if you could check if `emitter` is really undefined or if this is something with the debugger.

**Comment by gustafn** [comment] 2018-01-29 19:00
I did some debugging. It is not the case, that the `emitter` object is undefined, but it is for - whatever reasons - an instance of a seemingly wrong class: In the failing case, it is a instance of `Window`!

The symptoms can be cured via inserting the following `if` statement in the function `listenTo` in `emittermixin.js`:

```javascript
         listenTo( emitter, event, callback, options ) {

	        if (emitter instanceof Window) {
		    return;
	        }

		let emitterInfo, eventCallbacks;
                // _listeningTo contains a list of emitters that this object is listening to.
       ...
      }
```
With this change in place, the CKEditor 5 is rendered, but i can't say whether this has some further implications. Another question is certainly, why this happens, when boomerang is used.

**Comment by Reinmar** [comment] 2018-01-30 09:47
OK, I missed that. We made more changes – not only to the `isDomNode()` but also introduced `isWindow()` and used it. So, the changes were bigger (https://github.com/ckeditor/ckeditor5-utils/commit/bec2fac049a1fe2ca3c845e2af7d17da5017eaa4). However, based on your feedback, I think that you're encountering exactly this issue, so it should be fixed with the next release of CKEditor 5.

PS. I didn't change my mind and the root of the issue is still Boomerang or something overriding native `addEventListener()`.

**Comment by gustafn** [comment] 2018-01-30 19:59
i've now built the most recent version of classic CKEditor5 from github, and indeed, it seems the problem is gone. Many thanks for your help!

**Comment by Reinmar** [comment] 2018-01-31 09:08
Thank for the info!

**Closed by Reinmar** 2018-01-31 09:08 UTC
Labels: status:pending
