### ISSUE TITLE
Missing doc example for multi-layered toolbar dropdown

### ISSUE THREAD

**Issue by gumatias** [ckeditor/ckeditor5#9947] opened 2021-06-22 15:55 UTC
## 📝 Provide a description of requested docs changes

Is there doc that adds more color on how to accomplish one of the following?

## Option 1 (Preferred)
Toolbar dropdown that drills down into a secondary sub-dropdown by replacing the first one. Ideally the secondary dropdown would have buttons in itself like checkboxes and a "go back" button on the header for instance.

![Image 2021-06-22 at 8 48 12 AM](https://user-images.githubusercontent.com/681278/122957425-c8790080-d336-11eb-8a44-73c501694196.jpg)

## Option 2:
Toolbar dropdown that drills down into a secondary sub-dropdown to the side of the primary dropdown.

![Image 2021-06-22 at 8 49 49 AM](https://user-images.githubusercontent.com/681278/122957522-de86c100-d336-11eb-8122-d18dc781f0c2.jpg)

**Comment by oleq** [comment] 2021-06-23 09:15
Looks like a duplicate of https://github.com/ckeditor/ckeditor5/issues/6399.

**Comment by gumatias** [comment] 2021-06-24 01:10
I managed to get Option 1 implemented by basically creating two wrapper containers for the dropdown view, each with its respective buttons, views, etc. that got added as children. Then added click handlers to toggle between adding and removing those two wrapper views when applicable.

**Closed** 2021-06-28 13:00 UTC
Labels: type:docs
