### ISSUE TITLE
I have a question for word

### ISSUE THREAD

**Issue by lujiapengshocksoft** [ckeditor/ckeditor5#1710] opened 2019-04-17 09:12 UTC
When I was using CkEditor, I found some problems when pasting documents in word format.I hope you can deal with it. Thank you.
For example Word : 
![image](https://user-images.githubusercontent.com/49714104/56275590-94409e80-6133-11e9-83c4-ea8628a760ab.png)
In FireFox ：
![image](https://user-images.githubusercontent.com/49714104/56275716-cfdb6880-6133-11e9-9fa5-3bbf58cd4abb.png)
In Chorme : 
![image](https://user-images.githubusercontent.com/49714104/56275766-e84b8300-6133-11e9-90de-f30024c68c2e.png)

Then, What should I do  ?

**Comment by Hubmayun123** [comment] 2019-04-18 08:15
这好像是个兼容的问题,我也遇到了,在谷歌只要文档中有带有word标题格式的文字,图片就不能正常的显示

**Comment by Mgsy** [comment] 2019-04-18 08:26
Hello, CKEditor 5 paste from office plugin is still under development and some types of content might be pasted not as expected. Could you provide a sample .*doc file so we could check the problem?

**Comment by lujiapengshocksoft** [comment] 2019-04-18 08:31
of course ， see accessory



lujiapeng@aliyun.com
 
From: Kacper Tomporowski
Date: 2019-04-18 16:26
To: ckeditor/ckeditor5
CC: lujiapengshocksoft; Author
Subject: Re: [ckeditor/ckeditor5] I have a question for word (#1710)
Hello, CKEditor 5 paste from office plugin is still under development and some types of content might be pasted not as expected. Could you provide a sample .*doc file so we could check the problem?

**Comment by Mgsy** [comment] 2019-04-18 13:27
@lujiapengshocksoft, you haven't included any file in your message. Could you try again?

**Comment by lujiapengshocksoft** [comment] 2019-04-18 13:44
see again , thanks . if the doc is not exits , please email me . thanks .


------------------------------------------------------------------
发件人：Kacper Tomporowski <notifications@github.com>
发送时间：2019年4月18日(星期四) 21:27
收件人：ckeditor/ckeditor5 <ckeditor5@noreply.github.com>
抄　送：lujiapengshocksoft <lujiapeng@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [ckeditor/ckeditor5] I have a question for word (#1710)

@lujiapengshocksoft, you haven't included any file in your message. Could you try again?

**Comment by mlewand** [comment] 2019-04-18 14:56
@lujiapengshocksoft there's still no docx attached. Please log to github and upload it using GitHub website.

**Comment by lujiapengshocksoft** [comment] 2019-04-18 15:35
I have uploaded the word document to github, you can check it out https://github.com/lujiapengshocksoft/word.git 。 thanks .

Time is too late, I have to rest (because I am Chinese), thank you.



lujiapeng@aliyun.com
 
From: Marek Lewandowski
Date: 2019-04-18 22:57
To: ckeditor/ckeditor5
CC: lujiapengshocksoft; Mention
Subject: Re: [ckeditor/ckeditor5] I have a question for word (#1710)
@lujiapengshocksoft there's still no docx attached. Please log to github and upload it using GitHub website.

**Comment by Mgsy** [comment] 2019-04-25 09:20
Thanks for a file. I've checked what happens after pasting the content from the document to the editor and images don't paste at all in Chrome. 

It looks like this is the same issue as one described in https://github.com/ckeditor/ckeditor5-paste-from-office/issues/51, so I'll close this one as a duplicate and move the discussion to this ticket.

**Comment by Mgsy** [comment] 2019-04-25 09:40
Actually, I've dug a little more into this issue and it seems to be unrelated to ckeditor/ckeditor5-paste-from-office#51. 

After pasting the content to the editor running on localhost, it throws errors related to CSP:
```
utils.js:36 Refused to connect to 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUQEBIVFhUVFxcXGBUYFhUYGhoaFhcYGh4XGBoaHyggGB8lGxcVITEiJSkrLi4uGB8zODMtNygtLisBCgoKDg0OFRAQFysdHR8rLS0tLS0rLSsrKystLS0rKy0rLSsrKy03LSsrLS03Ky0tLSstKy03KysrLSsrKy0rK//AABEIAMwAzAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAABAAIDBAUGBwj/xAA+EAABAwIEAggDBgUDBQEAAAABAAIRAyEEEjFBBVEGEyJhcYGRoTKx0QcUI0LB8DNSYuHxcrLSU3OSk+IV/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAECAwT/xAAfEQEBAQADAAIDAQAAAAAAAAAAARECEiEDMRNBUWH/2gAMAwEAAhEDEQA/APTkgkivS44CKSMIYCQRRAQwEUYRhQNRhOhK...wqfSPhjcMJogv7VTMCDnOU5eyW6T4KmyhIMuedPzO8f0SpMLbhzwRp2ja4NlncurczFIUS9ji6nUY0GDmOZsnYZ9dDeExnA3MdmGcM7jla4wdoj2WvUwzXDtCZdmMkntR8Xj395Uowo5u/8jsP7K/mSfFrP4dhXtqx93qtaaZeatyBDmjq5ygQQZmfy+latiKb64wrn1c06xSDTHa8eW2y2sQXFgYXvLRo0ucQIIAgE2VrF8GotDaobLz+YxOmxiVj8krf47Is4XgtAUG1673VMpygHWCdssSN1zPFKbGublpOIdUay2c5Q6TmMHQLYyC6idTHLXVJyTK5jDYWjiQSKAcWZ5gvLpDi0Ns6TJHuuv6K9CsI6kyu+i5jjJyuNQQOUFdxwsfg0f8Ats/2D6qcXh26zee/S9c+3kXGek/UV6tE4ep2HuaLxIBMEW0LY9VA3pYSJFA+br/7Vv8ASHhNM4qrWJdmzTGbs/CLRy+ix3MAtlHovTw9cuXj/9k=' because it violates the following Content Security Policy directive: "connect-src 'self' https://cksource.com http://*.cke-cs.com".

Uncaught (in promise) TypeError: Failed to fetch
    at utils.js:36
    at new Promise (<anonymous>)
    at fetchLocalImage (utils.js:32)
    at imageuploadediting.js:104
    at Array.map (<anonymous>)
    at Clipboard.<anonymous> (imageuploadediting.js:104)
    at Clipboard.fire (emittermixin.js:207)
    at Document.listenTo.priority (clipboard.js:78)
    at Document.fire (emittermixin.js:207)
    at Document.handleInput (clipboardobserver.js:51)
```

It works fine on our [documentation sample](https://ckeditor.com/docs/ckeditor5/latest/features/paste-from-word.html).

@lujiapengshocksoft, could you please check whether your console throws some errors and if so, paste them here?

**Comment by lujiapengshocksoft** [comment] 2019-04-25 09:59
Error is as follows ：

Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image004.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image006.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image008.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image004.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image006.jpg
index.html:1 Not allowed to load local resource: file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image008.jpg

eg : I wil push project to github . 



lujiapeng@aliyun.com
 
From: Kacper Tomporowski
Date: 2019-04-25 17:40
To: ckeditor/ckeditor5
CC: lujiapengshocksoft; Mention
Subject: Re: [ckeditor/ckeditor5] I have a question for word (#1710)
Actually, I've dug a little more into this issue and it seems to be unrelated to ckeditor/ckeditor5-paste-from-office#51.
After pasting the content to the editor running on localhost, it throws errors related to CSP:
utils.js:36 Refused to connect to 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUQEBIVFhUVFxcXGBUYFhUYGhoaFhcYGh4XGBoaHyggGB8lGxcVITEiJSkrLi4uGB8zODMtNygtLisBCgoKDg0OFRAQFysdHR8rLS0tLS0rLSsrKystLS0rKy0rLSsrKy03LSsrLS03Ky0tLSstKy03KysrLSsrKy0rK//AABEIAMwAzAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAABAAIDBAUGBwj/xAA+EAABAwIEAggDBgUDBQEAAAABAAIRAyEEEjFBBVEGEyJhcYGRoTKx0QcUI0LB8DNSYuHxcrLSU3OSk+IV/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAECAwT/xAAfEQEBAQADAAIDAQAAAAAAAAAAARECEiEDMRNBUWH/2gAMAwEAAhEDEQA/APTkgkivS44CKSMIYCQRRAQwEUYRhQNRhOhK...wqfSPhjcMJogv7VTMCDnOU5eyW6T4KmyhIMuedPzO8f0SpMLbhzwRp2ja4NlncurczFIUS9ji6nUY0GDmOZsnYZ9dDeExnA3MdmGcM7jla4wdoj2WvUwzXDtCZdmMkntR8Xj395Uowo5u/8jsP7K/mSfFrP4dhXtqx93qtaaZeatyBDmjq5ygQQZmfy+latiKb64wrn1c06xSDTHa8eW2y2sQXFgYXvLRo0ucQIIAgE2VrF8GotDaobLz+YxOmxiVj8krf47Is4XgtAUG1673VMpygHWCdssSN1zPFKbGublpOIdUay2c5Q6TmMHQLYyC6idTHLXVJyTK5jDYWjiQSKAcWZ5gvLpDi0Ns6TJHuuv6K9CsI6kyu+i5jjJyuNQQOUFdxwsfg0f8Ats/2D6qcXh26zee/S9c+3kXGek/UV6tE4ep2HuaLxIBMEW0LY9VA3pYSJFA+br/7Vv8ASHhNM4qrWJdmzTGbs/CLRy+ix3MAtlHovTw9cuXj/9k=' because it violates the following Content Security Policy directive: "connect-src 'self' https://cksource.com http://*.cke-cs.com".
Uncaught (in promise) TypeError: Failed to fetch
    at utils.js:36
    at new Promise (<anonymous>)
    at fetchLocalImage (utils.js:32)
    at imageuploadediting.js:104
    at Array.map (<anonymous>)
    at Clipboard.<anonymous> (imageuploadediting.js:104)
    at Clipboard.fire (emittermixin.js:207)
    at Document.listenTo.priority (clipboard.js:78)
    at Document.fire (emittermixin.js:207)
    at Document.handleInput (clipboardobserver.js:51)

It works fine on our documentation sample.
@lujiapengshocksoft, could you please check whether your console throws some errors and if so, paste them here?

**Comment by Mgsy** [comment] 2019-04-29 07:27
Thanks for the error log. So, this information confirms my first thought that this is a duplicate of https://github.com/ckeditor/ckeditor5-paste-from-office/issues/51. I'll close this issue and leave the comment in that ticket.

**Closed by Mgsy** 2019-04-29 07:27 UTC
Labels: pending:feedback
