### ISSUE TITLE
Problem with entering text right after MathType\ChemType formula

### ISSUE THREAD

**Issue by yura-tovt** [ckeditor/ckeditor5#2070] opened 2019-09-24 13:36 UTC
🐞 Bug report

Hello. Found this bug today. Could you please help to resolve it ?

## 💻 Version of CKEditor

CKEditor 5

## 📋 Steps to reproduce

1. Go to https://ckeditor.com/mathtype/demo/#ckeditor5
2. Put cursor right after last MathType formula try to type something

OR

1. Go to https://ckeditor.com/mathtype/demo/#ckeditor5
2. Go to new line
3. Input some text
4. Add space
5. Add MathType\ChemType formula
6. Type something

## ✅ Expected result

Ability to type something right after MathType\ChemType formula

## ❎ Actual result

Not able to input any text (except "Enter" key) right after MathType\ChemType formula

**Comment by duzhihao-github** [comment] 2019-09-25 08:31
the formulas are <img> and you can set display in CSS

**Comment by yura-tovt** [comment] 2019-09-25 08:37
> the formulas are  and you can set display in CSS

Hi. What do you mean? I'm not able to enter any text after formula. I don't think this can be fixed or even somehow connected to css. I think the problem is somewhere in MutationHandler::_handleContainerChildrenMutations method.

**Comment by Mgsy** [comment] 2019-09-30 10:31
Hi, thank you for the report. Actually, this is a duplicate of https://github.com/ckeditor/ckeditor5/issues/1874.

**Closed by Mgsy** 2019-09-30 10:31 UTC
