### ISSUE TITLE
ckeditor 5 wrong rendering for target _blank links

### ISSUE THREAD

**Issue by confettidc** [ckeditor/ckeditor5#8225] opened 2020-10-07 09:55 UTC
We found that ckeditor rendered wrong link with target _blank structure as below:

<a target="_blank" rel="noopener noreferrer"><span style="font-size:36px;"><span class="ck-fake-link-selection">Testing url (open in new tab)</span><a target="_top" rel="noopener noreferrer" href="https://www.google.com"></a></span></a>

As a result, the link cannot be clicked and link disappeared when load editor again.

Please help check, thanks.

**Comment by Mgsy** [comment] 2020-10-07 12:45
Hi, can you provide more information about your issue? It would be great if you can add steps to reproduce, expected result and actual result.

**Comment by confettidc** [comment] 2020-10-07 13:48
Hi,

I'm following to make target _blank links with below instructions:
https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-target-and-rel-attributes-to-external-links

Due to program structure, I need to use updateSourceElement() to update data back to textarea

To reproduce the issue, please refer to below video:
[2020-10-07_21-43-00.zip](https://github.com/ckeditor/ckeditor5/files/5341069/2020-10-07_21-43-00.zip)

Expected result: should be simple format like below:
<a href="https://www.google.com" target="_blank">text</a>

Thanks.

**Comment by FilipTokarski** [comment] 2020-10-08 10:19
Hi, thanks for the report. I tried using link decrators and always got the expected data. I'd suggest that this double link issue might be caused by your integration and not by the bug in the feature itself. Hovewer, if you are sure that there's a bug in the feature, I guess we'll need a step-by-step guide to reproduce this, together with the editor configuration.

**Comment by confettidc** [comment] 2020-10-08 11:09
Hi,

Thanks and I have spoted out the issue that there may be conflicts between making target _blank and target _top links, here is my configuration:

link: {
	            decorators: {
	                isExternal: {
	                    mode: 'manual',
	                    label: '<?php echo __('Open in a new tab'); ?>',
	                    attributes: {
	                        target: '_blank',
	                        rel: 'noopener noreferrer'
	                    }
	                },
	                targetTop: {
	                	mode: 'automatic',
                    	callback: url => /^(https?:)?\/\//.test( url ),
                    	attributes: {
                    	    target: '_top',
                    	    rel: 'noopener noreferrer'
                    	}
	                }
	            }
	        }

My idea is automatically convert http links to target _top, and switch to target _blank if the switch is turned on, any suggestions can archive this?

Thanks.

**Comment by confettidc** [comment] 2020-10-08 11:17
It's the best if end user can self define target _self, _blank, _top, thanks

**Comment by FilipTokarski** [comment] 2020-10-08 13:36
Ok, I think now I see what happens here. There seems to be a bug when adding a manual decorator with some other `target` attribute. As it comes to your integration, it seems that unfortunately there is no out-of-the box way to fix things right away.  
 I'll close this ticket as a duplicate and we'll be tracking this issue here https://github.com/ckeditor/ckeditor5/issues/8230. Please add there 👍  if you'd like to see it fixed faster and also feel free to add there anything you find important.

**Closed by FilipTokarski** 2020-10-08 13:36 UTC
Labels: pending:feedback, type:question
