### ISSUE TITLE
beforeinput: Trying to replace code within code block on Safari don't work and results in error

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#12575] opened 2022-10-05 11:55 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open: http://localhost:8125/ckeditor5/tests/manual/all-features.html on `ck/11438-beforeinput-ime-research-vol1.1-android`
2. Set editor's data to:
```
<pre><code class="language-plaintext">&lt;?php

function dump( array ...$args ) {
	foreach ( $args as $item ) {
		var_dump( $item );
	}

	die;
}</code></pre>
```
3. Select the whole code inside the code block **starting selection from the left** and press any character on the keyboard (with the intention to replace that code with that character)

### ✔️ Expected result

Code is replaced.

### ❌ Actual result

Code is not replaced, error in the console:
```
CKEditorError: view-selection-add-range-not-range
```
![code replace issue](https://user-images.githubusercontent.com/32898551/194054175-26c5d409-8b71-4ad0-9d3f-53a98df6f976.gif)

## 📃 Other details

* Browser: Safari

**If the selection is starting from right to left, everything works fine.** 

It is reproducible only on the IME branch.

I was not able to reproduce the issue on Safari@iOS, Firefox and Chrome. 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment] 2022-10-06 16:25
This is not related to the code block. It's enough to start selection just before any `<br>`.

**Comment by niegowski** [comment] 2022-10-11 15:39
Should be fixed by 17c7c49 in #12446.

**Comment by dufipl** [comment] 2022-10-12 10:15
The issue does not reproduce anymore on `ck/11438-beforeinput-ime-research-vol1.1-android`. @Acrophost please confirm this and if so, we can close this. :)

**Comment by Acrophost** [comment] 2022-10-12 10:21
I confirm - can't reproduce this issue anymore, thus, closing ;>

**Closed by Acrophost** 2022-10-12 10:21 UTC
Labels: type:bug, browser:safari, package:code-block, domain:ime, squad:core, status:in-progress
