### ISSUE TITLE
Docs issue report from "features/lists/lists.html"

### ISSUE THREAD

**Issue by sureshNani** [ckeditor/ckeditor5#12017] opened 2022-07-06 05:53 UTC
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html

### Project version

34.2.0

### Is the information outdated? How?

issue details:-
1) Existing styles not applying along with bullet & number list. 
2) For example :- one div element having font-size:32px, color : red. If i apply bullet or ordered list then its overwriting the existing font-size & color.

Expected Result:- Bullet or Ordered list style should apply along with existing styles (i.e, font-size & color) as per above example

### Is there something missing in the guide? What is it?

issue details:-
1) Existing styles not applying along with bullet & number list. 
2) For example :- one div element having font-size:32px, color : red. If i apply bullet or ordered list then its overwriting the existing font-size & color.

Expected Result:- Bullet or Ordered list style should apply along with existing styles (i.e, font-size & color) as per above example

### Is there anything else you would like to add?

issue details:-
1) Existing styles not applying along with bullet & number list. 
2) For example :- one div element having font-size:32px, color : red. If i apply bullet or ordered list then its overwriting the existing font-size & color.

Expected Result:- Bullet or Ordered list style should apply along with existing styles (i.e, font-size & color) as per above example

### User agent

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

**Comment by Mgsy** [comment] 2022-07-11 07:40
This issue is a duplicate of https://github.com/ckeditor/ckeditor5/issues/5752.

**Closed by Mgsy** 2022-07-11 07:40 UTC
Labels: type:docs, squad:ccx
