### ISSUE TITLE
Android v 8 - When typing, if you hit enter for a new line it does not work unless you have a space, comma, or period. 

### ISSUE THREAD

**Issue by tomtomu** [ckeditor/ckeditor5#11308] opened 2022-02-17 16:59 UTC
## 📝 Provide detailed reproduction steps (if any)

Tested in android v8 - when you start typing then hit the return key for a new line - nothing happens.

### ✔️ Expected result

Cursor should move to new line.

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2022-03-09 12:39
Thanks for the report. Could you add also which browser and keyboard do you use?

**Comment by tomtomu** [comment] 2022-03-09 16:48
If you add a space, comma or period, then it works as expected.

**Comment by jswiderski** [comment] 2022-06-17 09:12
I'm marking this ticket as a duplicate of https://github.com/ckeditor/ckeditor5/issues/11906.

**Closed by jswiderski** 2022-06-17 09:12 UTC
Labels: type:bug, browser:android
