### ISSUE TITLE
Shift + Enter (soft enter) makes the scroll moves upwards and again downwards.

### ISSUE THREAD

**Issue by Rashid101** [ckeditor/ckeditor5#14976] opened 2023-09-12 17:55 UTC
## 📝 Provide detailed reproduction steps (if any)

1. https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
2. Open Chrome DevTools and give a fixed height say 105px to the div with class -- ".ck.ck-editor__main"
3. Clear all the contents of the first demo editor and Start type one word on each line followed by Shift + Enter
4. As soon as the content starts overflowing and the scroll appears, the scroll will misbehave- it will keep going to the top at alternate shift+enter (say odd times) and keep coming to the bottom on the next alternate shift+enter (say even times).

### ✔️ Expected result

The scroll should always stay at the bottom of the content

### ❌ Actual result

The scroll is mis behaving. 
1. On the first Shift +Enter it is moving upwards. (Here is the issue; It should not move upwards)
2. On the second Shift + Enter it is going to the bottom. (Going to the actual position)

### ❓ Possible solution

Must be some event getting fired from ckeditor internally due to which it behaves like this.

## 📃 Other details

* Browser: Chrome
* OS: MacOS Ventura
* First affected CKEditor version: Ckeditor5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-09-13 08:10
Duplicate of: #14028. Details why this is happening are in the comments.

**Closed by Witoso** 2023-09-13 08:10 UTC
Labels: type:bug
