### ISSUE TITLE
Pasting <p><br></p> Inserts Two New Lines

### ISSUE THREAD

**Issue by scottfr** [ckeditor/ckeditor5#5564] opened 2019-10-10 08:57 UTC
## 📝 Provide detailed reproduction steps (if any)

Paste `<p>a</p><p><br></p><p>b</p>` into the editor.

### ✔️ Expected result

The editor will have:

```
a

b
```

This is the CKEditor 4 behavior and the behavior of most other editors.

### ❌ Actual result

The editor will have (note the two blank lines instead of one):

```
a


b
```

---

If you'd like to see this fixed sooner, add 👍 to this post.

**Comment by mlewand** [comment] 2019-10-10 09:11
Issue is being caused by the fact that extra filler is added to the paragraph, and this is in fact different from CKE4. Here's how the view is rendered:

```
<p>a</p>

<p><br><br data-cke-filler="true"></p>

<p>b</p>
```

**Comment by mstermaaten** [comment] 2019-10-15 12:59
Jupp, pretty annoying.... Need this fixed 2
https://github.com/ckeditor/ckeditor5/issues/5589

**Comment by Reinmar** [comment] 2019-10-16 08:37
Is this a regression, guys? Did it work well in previous versions of CKEditor 5? It seems suspicious that there are two bug reports about this in a short period of time.

**Comment by andreyalikberov** [comment] 2019-10-16 21:28
Pretty annoying indeed. Does anyone know if this can be fixed?

**Comment by jodator** [comment] 2019-10-22 12:11
@mlewand & @Reinmar is this a bug or expected conversion an empty paragraph with s soft break inside?

```html
<p>foo<br>bar</p>
```
will be rendered as:
```
foo
bar
```
and for me the `<p><br></p>` is just a special case of the above (two empty lines in a paragraph)

More importantly the `editor.getData()` will return `""` for empty two-line paragraph and `<p>foo<br>bar</p>` for the latter case.

**Comment by jodator** [comment] 2019-10-22 12:26
ps.: The same will happen if you press <kbd>shift</kbd>+<kbd>enter</kbd> in empty editor - you will get `<p><br></p>` in the data. But to display those two lines we must but a [block filler](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_filler.html#static-function-BR_FILLER) in the editing area do **only in editing area** you will have `<p><br><br data-cke-filler="true"></p>` so user can put selection in the second line (after a soft-break).

**Comment by scottfr** [comment] 2019-10-22 19:29
Lacking a formal specification for RTE on the web, I think the correct approach is to by default follow the behavior of a vanilla contenteditable field.

In Chrome, if you paste thee sample html into a vanilla contenteditable you will get a single blank line between the A and B.

If CKEditor 5 (and other editors), doesn't align with the vanilla contenteditable behavior where there isn't a compelling reason to do something different, it creates unnecessary divergence between itself and other Rich Text Editor's on the web*. This creates costs for web developers as if every RTE is doing its own thing, it makes it hard for developers to correctly format their text to be pasted across editors.

* Most editors will put a single space including CKEditor 4, TinyMCE, Google Docs, Gmail. The only one I've tested which diverges is Facebook's DraftJS which strips all blank lines on pasting.

**Comment by mstermaaten** [comment] 2019-10-25 10:28
Did someone solve this already?

**Comment by mlewand** [comment] 2019-10-28 09:16
I gave it a quick check and this behavior was changed in **10.1.0**, was good in 10.0.1 - so it can be considered a regression.

I agree that it's a tricky case.

Let's make a clear list of pros and cons of both solutions:

## Current solution (displaying `<p><br></p>` as _two_ paragraphs)

* ➕ allowing to actually remove the `<br>`,
* ➖ showing a different content from what the user will actually see in output page (and other apps when working with this particular data).

## Proposed (displaying `<p><br></p>` as a _single_ paragraph)

* ➕ same content in editor as in output and other apps,
* ➖ currently user would not be able to remove or tell that there's an extra tailing `<br>` at the end of the line


From my point of view better interoperability is more desired, so proposed solution seems to add some value here.

**Comment by jodator** [comment] 2019-10-28 10:45
>     * currently user would not be able to remove or tell that there's an extra tailing `<br>` at the end of the line

What will happen on <kbd>shift</kbd>+<kbd>enter</kbd> in empty paragraph? Displaying single line is not an option I think. So if pasting this causes problems I'd remove `<br>` from `<p>` if we want to fix this.

**Comment by andreyalikberov** [comment] 2019-10-31 19:26
does anyone know what the guestimate in getting this issue fixed is?

**Comment by mstermaaten** [comment] 2019-11-11 11:49
To prevent the editor for adding extra <br/> tags i actually removed the <br data-cke-filler="true"> manually by `data.replace(/<br data-cke-filler="true">/g, "&nbsp;");` before setting the data. 
This has solved the annoying adding of extra breaks bug for me.

**Comment by Reinmar** [comment] 2019-11-14 13:54
- It's definitely not a good behaviour. I agree with @scottfr that we shouldn't diverge from what would happen in other editors unless we have very good reasons. This behaviour is a bug.
- It changed in 10.1.0 with the introduction of the soft break feature. Simply, before that all `<br>`s were completely ignored.
- This issue does not affect data created in the editor as the editor will never output `<p><br></p>`. However, it's annoying because it affects pasting and, potentially, content ported from other editors (especially those which use plain contentEditable).
- A correct solution isn't that trivial because we need to add support for an alternative block filler. Right now, the DOMConverter instance which handles the data pipeline is configured to use `&nbsp;`s. `<br>` is used as a block filler but only in the editing pipeline. We assumed that one DOMConverter needs to handle just one type of block filler. It turns out that one of them will have to handle two types. It will be an "ugly" change.
- Additionally, the actual `<br>` filler that we use is detected by the `data-cke-filler` attribute. The `<br>` we're dealing with in this case will not have it. So, actually, it's also not that filler.
- My plan for now is to patch `DOMConverter#isBlockFiller()` to handle a special case there that if the `domNode` passed is a single child of a block element, it's considered a filler (despite `DOMConverter#blockFillerMode` being set to `nbsp`. The confusing logic will be enclosed in this method and easy to document.
- However, I do not plan to handle cases like `<p>  <br>   </p>`. From what I can see Chrome and Firefox output exactly `<p>x</p><p><br></p><p>x</p>` when you type `x<ENTER><ENTER>x`. So, my goal is to handle pasting that to CKEditor 5.

**Comment by Reinmar** [comment] 2019-11-14 14:34
PR landed in https://github.com/ckeditor/ckeditor5-engine/pull/1808.

**Closed** 2019-11-15 15:46 UTC
Labels: status:confirmed, support:1, type:bug, type:regression

**Comment by winwintogether** [comment] 2021-02-11 20:34
![image](https://user-images.githubusercontent.com/25000032/107695389-cc25b800-6cb0-11eb-86e4-042543966c08.png)
I setData right HTML data, but I see that the empty `<p><br><br data-cke-filler="true"></p>` line is added.
What is the solution?
