### ISSUE TITLE
[Android] Letter after the carriage is removed on backspace

### ISSUE THREAD

**Issue by iEgit** [ckeditor/ckeditor5#613] opened 2017-10-17 13:24 UTC
1. Enter a line
2. Place carriage at the beginning of the line 
3. Press Backspace

**Actual result**: the line moves up but the letter after carriage is also removed
**Expected result:** the line moves up
**Reproduced on**: nexus 6/7.0, xperia (5.1.1), LG g4 and xiaomi mi 5 (6.0.1)

Video: https://yadi.sk/i/sS9ViCU33NEgh9

**Comment by Mgsy** [comment] 2017-10-17 14:37
Indeed, there is a problem with <kbd>Backspace</kbd>, but the issue is different to me. Pressing <kbd>Backspace</kbd> doesn't work at all on Nexus (Android 4.4.4).

On LG K8  (Android 7.0) everything works properly.

**Comment by Reinmar** [comment] 2017-10-17 15:17
Which browsers do you test? Chrome or the stock one? Android version is one thing, but the browser is more important.

**Comment by iEgit** [comment] 2017-10-19 10:08
We are testing in webviews

**Comment by f1ames** [comment] 2018-06-19 11:17
Checked on Chrome `67.0.3396.87` on Android `4.4.4` and I've got slightly different results:

* When caret is on the line beginning (or rather block element beginning), <kbd>backspace</kbd> does not remove letters after but also does not remove anything before (so nothing happens, normally blocks would be merged in such case).
* When there is non-collapsed selection (but within single block element) <kbd>backspace</kbd> works fine. Same for collapsed selection not on the beginning of the block element.
* When there is non-collapsed selection which contains more than one block element, nothing gets removed on <kbd>backspace</kbd> and selection collapses.

---

I think we should also check on newer Android version, because `4.4.4` is quite old already.

**Comment by Reinmar** [comment] 2018-06-19 11:19
These behaviours are completely coincidental so I wouldn't pay much attention to them. They come from the mutation observer in the typing feature. Normally, they would be handled by backspace observer but it's missing on Android due to the lack of `keyCode`s.

**Comment by f1ames** [comment] 2018-06-22 14:21
> On LG K8 (Android 7.0, Chrome) everything works properly.

I have tested it also on `Huawei MediaPad M5` device (`Android 8`, `Chrome`) and the issue does not occur. However, behaviour which I described in the comment above happens:

> <kbd>Backspace</kbd> does not remove letters after but also does not remove anything before (so nothing happens, normally blocks would be merged in such case).

@Mgsy is it the same as on LG K8 you tested?

Basically the behaviour on `Huawei MediaPad M5` is the same as the one described in https://github.com/ckeditor/ckeditor5/issues/613#issuecomment-398363722.

**Comment by vladikoff** [comment] 2018-06-27 00:45
Also filed in https://github.com/ckeditor/ckeditor5/issues/1106#issuecomment-399838054 

Is there a workaround that can be added here?  🤔

**Comment by f1ames** [comment] 2018-06-27 09:13
@vladikoff The original issue (_Letter after the carriage is removed on backspace_) is not present on newer Android versions (starting from `6` or `5` I believe). I'm not sure about a workaround ATM, but we are actively working on typing improvements for Android, especially <kbd>Backspace</kbd> handling (which is covered in a little more details in https://github.com/ckeditor/ckeditor5/issues/614). So there is a good chance that it will be fixed in some reasonable time :)

**Comment by f1ames** [comment] 2018-07-04 13:45
I have rechecked this issue on Android `6.0.1` and `8.0.0` with latest Chrome (`67`) and a `WebView` and was not able to reproduce it in the exact way it is described. However, there is an issue with non-working <kbd>Backspace</kbd> on the line beginning, which is reported as #1106 and can be tracked there.

As for this one I'm closing it. @iEgit if you have any comments feel free to add it here.

**Closed by f1ames** 2018-07-04 13:45 UTC
Labels: resolution:invalid, status:confirmed, type:bug
