### ISSUE TITLE
Most Chinese use WPS，I hope to support the paste function

### ISSUE THREAD

**Issue by add2ws** [ckeditor/ckeditor5#11650] opened 2022-04-20 02:27 UTC
Most Chinese use WPS，I hope to support the paste function

_Originally posted by @xunyidaixu in https://github.com/ckeditor/ckeditor5/issues/2488#issuecomment-841703225_

**Comment by PKXZ** [comment] 2022-04-20 02:54
Yes, I'm also looking for one that supports WPS replication. Please support

**Comment by yoyo837** [comment] 2022-04-20 03:02
Duplicate of #2488

**Comment by yoyo837** [comment] 2022-04-20 03:02
@add2ws 本地编译修改一下代码能解决。

**Comment by PKXZ** [comment] 2022-04-20 03:06
> @add2ws 本地编译修改一下代码能解决。

For example? I can't use WPS stickers

**Comment by yoyo837** [comment] 2022-04-20 03:14
https://github.com/ckeditor/ckeditor5/pull/10471

**Comment by Mgsy** [comment] 2022-04-27 18:55
As mentioned above, it's a duplicate of #2488.

**Closed by Mgsy** 2022-04-27 18:55 UTC
