### ISSUE TITLE
[Package - table]Long text element does not break line inside a table cell

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#9450] opened 2021-04-11 09:00 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Insert table
2. Write some text as single word

### ✔️ Expected result
When space is done the cell break the text and move a line.
![image](https://user-images.githubusercontent.com/59637560/114297719-f7633280-9aba-11eb-8334-0964e53047f0.png)

### ❌ Actual result
Table exit out of boundaries.
![image](https://user-images.githubusercontent.com/59637560/114297732-06e27b80-9abb-11eb-9137-87141166c769.png)

Demo on: https://stackblitz.com/edit/table-issue-9450?file=index.js

## 📃 Other details

* Browser: Chrome 89
* OS: Windows 10
* First affected CKEditor version:*
* Installed CKEditor plugins:27

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-04-12 10:10
Hi, this behaviour is basically how the table width behaves and is not a bug, please see the [explanation in this comment](https://github.com/ckeditor/ckeditor5/issues/7377#issuecomment-640374827). I'm closing this as a duplicate.

**Closed by FilipTokarski** 2021-04-12 10:10 UTC
Labels: type:bug
