### ISSUE TITLE
It's not possible to unset a table style

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6230] opened 2020-02-11 15:52 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Set bg color to "red"
2. Select "red" and press backspace

![Feb-11-2020 16-50-06](https://user-images.githubusercontent.com/156149/74253080-e704cb80-4cee-11ea-9184-b1a8fcc9c668.gif)

### ✔️ Expected result

Color was removed.

### ❌ Actual result

Table is still styled.

## 📃 Other details

If you'd try to backspace 3x to delete "d", "e", "r" one after another, you'd be left with `background-color: r`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2020-02-11 15:55
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/6183.

**Closed by Mgsy** 2020-02-11 15:55 UTC
Labels: domain:ui/ux, package:table, status:confirmed, type:bug
