### ISSUE TITLE
[GHS] Stabilize and release a production-ready General HTML support feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9856] opened 2021-06-13 09:34 UTC
## 📝 Provide a description of the new feature

Placeholder for all followups for the GHS feature that we'll need to close to make it production-ready.

List of issues:

*   ~\[GHS\] Applying attributes to existing features - table~ - #9914 :white\_check\_mark:
*   ~\[GHS\] Applying attributes to existing features - image~ - #9916
*   \[GHS\] Applying attributes to existing features - lists - #9917
*   ~\[GHS\] Applying attributes to existing features - media embed~ - #9918
*   \[GHS\] Support for empty elements - #9960
*   \[GHS\] Handling content being a part of the object - #9936
*   ~\[GHS\] Add a demo with all HTML features enabled~ - #9987

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by ariane-er** [comment] 2021-08-10 00:01
I'd love to see this stable! Thanks for your hard work :)

**Comment by reciprocityFailure** [comment] 2021-09-14 17:33
It would be great to have this stable. I like many of the improvements in CKEditor5, but we need code view!

**Comment by mmichaelis** [comment] 2021-09-28 08:46
Some first thoughts after rough evaluation (we are migrating from CKEditor 4 to CKEditor 5 and this may solve some of our challenges):

* **Term:** While GHS is a good name to get a grasp of the feature, it may be important to note, that it is essentially about any XML structure. Perhaps with some extra candy, that we distinguish between inline and block elements.

* **Alignment Integration:** I think, we may require an `Alignment` integration as well. For example: We have to map alignment to classes (e.g., `align-right`), while the very same element may also carry other classes for styling. The challenge would be, that some class-attribute values have to be transformed for the _Alignment_ feature, while others should be kept "for other purpose".
From what I have seen so far, the existing feature set could also be extended by customers requiring such an extra mapping.

* **Data Processor Integration?** From the documentation it is not clear to me, how GHS integrates with a custom data-processor. At first glance, it read, as if GHS **is** a data-processor (it tells something about `setData` and `getData`). Now it seems, that it is on data layer a downcast to the data view (see [Editing Engine](https://ckeditor.com/docs/ckeditor5/29.2.0/framework/guides/architecture/editing-engine.html)), which again means, that you could still apply any data-processor. It may be important to add a corresponding note to the documentation.

All in all, it looks very promising, and it may help us in our current migration efforts.

What we essentially require achieving, seems to be a perfect match with the GHS goal:

> While not necessarily providing editing capabilities for data read from a server, data from the server are not necessarily corrupted/modified, just because the editor cannot create such structures.

**Logging/Reporting?** Perhaps one more remark: From my point of view, such "data preserving approach" is always just a workaround, for something which should better be handled by the editing UI with clear model/view/data structure. Thus, some reporting feature when handlers of GHS "have to come to the rescue" would be a real nice feature to identify implementation gaps.

**Comment by shabab477** [comment] 2021-11-03 08:31
This is an awesome feature to have. Thank you for the good work! :+1:

**Comment by Mgsy** [comment] 2022-05-19 09:48
General HTML Support has been tested multiple times in production environments and it is considered a stable feature. It still misses some features, but it's safe to use it. I'm closing this issue, as it's considered as done.

**Closed by Mgsy** 2022-05-19 09:48 UTC
Labels: type:feature, Epic, squad:core, package:html-support, status:in-progress

**Comment by Vik925** [comment] 2023-06-19 13:07
Hello! I have a problem with htmlSupport.
I need the <p> and <h2> tags to have the default attributes itemprop="articleBody" and itemprop="alternativeHeadline" and the ability to manually add the id attribute.

I constantly have these problems, or one or the other works, but does not work at the same time. I tried adding constant attributes through the heading2 model, and variable id through htmlSupport. There is also a difficulty in adding a constant attribute to paragraph by default. I'm using strapi's dll method integration.

**Comment by yoyo837** [comment] 2023-06-19 14:04
> Hello! I have a problem with htmlSupport. I need the `<p>` and `<h2>` tags to have the default attributes `itemprop="articleBody"` and `itemprop="alternativeHeadline"` and the ability to manually add the `id` attribute.
> 
> I constantly have these problems, or one or the other works, but does not work at the same time. I tried adding constant attributes through the heading2 model, and variable `id` through htmlSupport. There is also a difficulty in adding a constant attribute to paragraph by default. I'm using dll method integration in the strapi.

<img width="350" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/6134547/1ac3aa66-64a9-4fc8-9092-f2dd0ecb91ec">

Try this.

**Comment by Vik925** [comment] 2023-06-19 14:10
> 

![image](https://github.com/ckeditor/ckeditor5/assets/66090231/643d1868-8545-40c9-b594-2bf6c3608394)
![image](https://github.com/ckeditor/ckeditor5/assets/66090231/4f0884b4-0243-41b3-80e6-87d52c5d4461)
These two codes conflict.

**Comment by Vik925** [comment] 2023-06-20 18:23
@Witoso, this solution helped me.

![image](https://github.com/ckeditor/ckeditor5/assets/66090231/e9b4b6d8-f59e-43c0-a0d0-b1951342db70)
![image](https://github.com/ckeditor/ckeditor5/assets/66090231/d92d752e-dcfc-4a6e-96ae-95dd3f25c817)

Result
![image](https://github.com/ckeditor/ckeditor5/assets/66090231/65143081-a68f-40aa-a3bf-f1345851fa94)

I think the problem is in the title. The filter removed the identifier from headers that were overridden. That is, you need to correctly write the expression for the filter in the title. But I dont know how.
