### ISSUE TITLE
How to use autosave functionality/plugin in this library

### ISSUE THREAD

**Issue by abhijitkc** [ckeditor/ckeditor5#6043] opened 2020-01-03 14:29 UTC
## How to use autosave functionality/plugin in ckeditor5-react library.

Guide me in proper way to autosave in react.

## I am using this library for integrating ckeditor in react. When I try to autosave with dispatching the action to redux, it is calling continuously after "waitingTime", suppose 10 sec. If I just console log the it is working properly. Can anyone help me. I am pasting the code below.

```
<CKEditor
              editor={ClassicEditor}
              data={projectDetails.lyrics_xml ? projectDetails.lyrics_xml : ''}
              config={{
                autosave: {
                  save(editor) {
                    console.log('here');
                    return dispatch(
                      projects.update({
                        property: 'lyrics_xml',
                        value: editor.getData(),
                        id: projectId,
                      }),
                    );
                  },
                  waitingTime: 10000,
                },
              }}
              onInit={editor => {
                this.setState({ mainEditor: editor });
                editor.ui.view.toolbar.element.hidden = true;
                // You can store the "editor" and use when it is needed.
                console.log('Editor is ready to use!', editor);
              }}
              onChange={(event, editor) => {
                // const data = editor.getData();
                // console.log({ event, editor, data });
                this.setState({ saveIcon: true });
              }}
              onBlur={(event, editor) => {
                const data = editor.getData();
                if (lyricsData !== editor.getData()) {
                  this.saveEditorData();
                }
                console.log('Blur.', { event, editor, data });
              }}
              onFocus={(event, editor) => {
                // const saveData = setInterval(() => {
                //   console.log('here');
                //   this.saveEditorData(editor.getData());
                //   // hide save button
                // }, 10000);
                // return () => clearInterval(saveData);
                // console.log('Focus.', editor);
              }}
            />

```

* Browser: Chrome
* OS: ubuntu
* CKEditor version: ckeditor 5
* Installed CKEditor plugins: autosave

**Comment by Mgsy** [comment] 2020-01-07 15:38
It's a duplicate of https://github.com/ckeditor/ckeditor5-react/issues/129.

**Closed by Mgsy** 2020-01-07 15:38 UTC
Labels: type:task
