### ISSUE TITLE
`<button type="button">` causes reverse typing in Safari

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#14830] opened 2023-08-21 11:52 UTC
## 📝 Provide detailed reproduction steps (if any)

The following is a minimal reproducer for the observed behavior. The code creates a simple button that does nothing at all and this will play an important role.

```js
const button = document.createElement("button"); button.type = "button"; button.textContent = "Test"; document.getElementById("b-demo-editor").prepend(button);
```

1. Go to https://ckeditor.com/ckeditor-5/demo/feature-rich/
2. Execute the above JavaScript code in the console.
3. Clear the editor. (Note: Not required, you can just type in the existing content, it doesn’t matter.)
4. Type `abc` and observe how `abc` is properly inserted.
5. Click the “Test" button above the editor once.
6. Without doing anything else, type `def` on your keyboard.

### ✔️ Expected result

The string `abcdef` is typed into the editor.

### ❌ Actual result

The editor now reads `abcfed`.

### ❓ Possible solution

In Chrome and Firefox the focus is moved to the button “Test" and the editor is being blurred. In Safari however the editor remains active and accepts keystrokes which are being added to the right of the caret, causing the input to be reversed as you type.

Important observation: There is a reproducible delay before the character `d` is inserted. Any following keystroke is registered immediately, there seems to be some debounced action running when the first keystroke is processed.

Important observation 2: `document.activeElement` is not within the editor after the button is clicked. Typing text still shows that `document.activeElement` is something else. Once the user explicitly clicks inside the editor, the `document.activeElement` will point to `.ck-editor__editable` and typing takes place as expected. I tried focusing `document.body` and explicitly calling `.blur()` on `.ck-editor__editable` but CKEditor continues to evaluate global keystrokes and shows the caret.

## 📃 Other details

* Browser: Safari 16.6
* OS: macOS 13.5
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Demo

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-08-21 12:09
I will close it as a duplicate of #14702 and let's move the discussion there.

**Closed** 2023-08-22 11:18 UTC
Labels: type:bug, resolution:duplicate
