### ISSUE TITLE
Table Toolbar not showing CKEditor 5

### ISSUE THREAD

**Issue by thamibn** [ckeditor/ckeditor5#9942] opened 2021-06-22 01:06 UTC
## 📝 Provide detailed reproduction steps (if any)

1. I have download the ckedito5 from online build
2. Copied the code from sample/index.html
```
ClassicEditor
            .create( document.querySelector( '.editor' ), {
                toolbar: {
                    items: [
                        'insertTable',
                    ]
                },
                language: 'en',
                licenseKey: '',
                table: {
                    contentToolbar: [
                        'tableColumn', 'tableRow', 'mergeTableCells',
                    ],
                }
            } )
            .then( editor => {
                window.editor = editor;
            } )
            .catch( error => {
                console.error( 'Oops, something went wrong!' );
                console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
                console.warn( 'Build id: pfu4lrkfhqu7-hd57n2m0uarx' );
                console.error( error );
            } );
            
```
3. But table toolbar is not showing, but when i open the sample/index.html it works perfect, what am i missing or any clash

### ✔️ Expected result

_What is the expected result of the above steps?_
![Screenshot from 2021-06-22 03-03-01](https://user-images.githubusercontent.com/28577943/122846591-78824580-d306-11eb-8ebe-590a5093e846.png)

### ❌ Actual result

_What is the actual result of the above steps?_
![Screenshot from 2021-06-22 03-02-45](https://user-images.githubusercontent.com/28577943/122846603-7e782680-d306-11eb-9a8c-d2d7a93808a4.png)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: chrome
* OS: linux
* First affected CKEditor version: 5
* Installed CKEditor plugins: latest 28....

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by thamibn** [comment] 2021-06-22 01:22
found the issue

if the ckeditor is on a bootstrap modal the table toolbar does not show may its behind the modal not sure.

so i have tested on a full page not modal it worked.
![Screenshot from 2021-06-22 03-20-18](https://user-images.githubusercontent.com/28577943/122848019-07905d00-d309-11eb-8107-44890465fb93.png)

**Comment by FilipTokarski** [comment] 2021-06-22 07:13
Hi @thamibn, I'm glad everything works now, I'll close this ticket as solved then.

**Closed by FilipTokarski** 2021-06-22 07:13 UTC
Labels: type:bug

**Comment by gaojianzhuang** [comment] 2022-06-26 01:33
I have this issue, too. It occures in the bootstrap modal and caused by the z-index value less than bootstrap modal z-index. My solution is change the modal z-index css value to 104 (default 1040).
```
.modal {
 z-index: 105;
}

.modal-backdrop {
 z-index: 104;
}
```
It works for me.
FYI.
