### ISSUE TITLE
[Installing Plugins] ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

### ISSUE THREAD

**Issue by BlakeBrown** [ckeditor/ckeditor5#7545] opened 2020-07-03 07:11 UTC
### 📝 Provide detailed reproduction steps

Follow the steps at [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build)

### ✔️ Expected result

Editor builds with alignment plugin

### ❌ Actual result

Editor builds, but when you open sample/index.html in chrome, you get the following error:

**Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.**

Isn't the point of running your own build to get rid of this error?! :/

**Comment by FilipTokarski** [comment] 2020-07-03 13:06
Hi, thanks for the report.  I guess it might be caused by different versions of ckeditor plugins. The latest one is `20.0.0` and I see that repo from docs you linked still has `19.0.0`. You can bump old ones using for example [ncu](https://www.npmjs.com/package/npm-check-updates) or install `alignment` in version `19.0.0`. Please let me know if this helps.

**Comment by BlakeBrown** [comment] 2020-07-09 08:55
Thanks man, appreciate the speedy response!

Working fine after downgrading the plugin to 19.0.0 😄

**Comment by FilipTokarski** [comment] 2020-07-09 09:27
I'm glad it works now 😃  I'll close this ticket for now.

**Closed by FilipTokarski** 2020-07-09 09:27 UTC
Labels: pending:feedback, type:bug
