### ISSUE TITLE
editor.setData(editor.getData()) drops inline element in table cell

### ISSUE THREAD

**Issue by mike-hogan** [ckeditor/ckeditor5#6037] opened 2019-12-31 10:28 UTC
I added the Table plugin to the Inline Widget tutorial code (https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html).  So I could create this model:

```
<$root>
    <table>
        <tableRow>
            <tableCell>
                <paragraph>
                    <placeholder name="date">
                    </placeholder>
                </paragraph>
            </tableCell>
        </tableRow>
    </table>
</$root>
```

When I do this:

`editor.setData(editor.getData())`, my model turns into this:

```
<$root>
    <table>
        <tableRow>
            <tableCell>
                <paragraph>
                    "{date}"
                </paragraph>
            </tableCell>
        </tableRow>
    </table>
</$root>
```

I know this has something to do with the handling of inline content in table cells, as detailed here (https://ckeditor.com/docs/ckeditor5/latest/features/table.html), but I don't quite get it.

I want to be able to round-trip data like this.  Please help me understand how I can round-trip a placeholder in a table cell :)

Thanks.

**Comment by Mgsy** [comment] 2020-01-02 08:18
I can confirm this behaviour. cc @jodator

**Comment by jodator** [comment] 2020-01-14 10:01
@Mgsy I cannot confirm that issue on current master:

![Peek 2020-01-14 10-59](https://user-images.githubusercontent.com/247363/72334041-03e0bb80-36bd-11ea-93bb-76fa4b8d720e.gif)

I've used inline widget demo and performed steps as in GIF above - everything works.

@mike-hogan do you still expierence this issue? What are your inline-widget converters looks like?

**Comment by Mgsy** [comment] 2020-01-14 10:10
It seems to be fixed on the latest master.

**Closed** 2020-01-14 12:02 UTC
Labels: support:2, type:task

**Comment by remigasas** [comment] 2020-03-02 09:49
We still experience same issue.
We use modified version of placeholder demo plugin.
Placeholder must be the only thin inside table cell, if it is, after "reloading" placeholder becomes plain text. It probably is related to: https://github.com/ckeditor/ckeditor5/issues/1464

**Comment by Reinmar** [comment] 2020-03-04 09:44
@remigasas, could you open a new ticket for this and provide a reproducible scenario?
