### ISSUE TITLE
restrictedEditing and TodoList plugins not compatible

### ISSUE THREAD

**Issue by lolocava** [ckeditor/ckeditor5#6592] opened 2020-04-09 15:48 UTC
## 📝 Provide detailed reproduction steps (if any)

Hello,

I used CKEditor with TodoList for a while to add checkbox in my content.
I recently added RestrictedEditingMode plugin to make editable only some textarea.
Concretely that adds `<span class="restricted-editing-exception">` tags.

These 2 plugins are not compatibles to work together ?

Thank you

### ✔️ Expected result

But I don't understand how to make clickable checkbox when restrict mode is activated.

### ❌ Actual result

When restrict mode is on, we can't check checkbox.

## 📃 Other details

* Browser: Chrome 80
* OS: Windows 10
* CKEditor version: 5
* Installed CKEditor plugins: ClassicEditor/Alignment/Bold/FontSize/Heading/HorizontalLine/Indent/Italic/List/PageBreak/Table/TodoList/Underline/Link/StandardEditingMode/Essentials/Paragraph

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment] 2020-04-10 14:08
This is because changing to-do list state is done via `todoListCheck` command. It is disabled by default by the Restricted editing.

Please add :+1: to first post in #6010. I'm closing this as a duplicate of #6010.

~~You should be able to enable it by adding it to~ [~allowedCommands~](https://ckeditor.com/docs/ckeditor5/latest/api/module_restricted-editing_restrictededitingmode-RestrictedEditingModeConfig.html#member-allowedCommands)~.~  This doesn't work (cc @Reinmar ) because this will only enable this command if whole content of the todo list item is allowed.

If you wish to always enable this command there is not official way of doing this. For now you can use a simple plugin and add it to a private set of globally enabled commands:

```js
ClassicEditor.create( document.querySelector( '#editor' ), {
	plugins: [ ArticlePluginSet, Table, RestrictedEditingMode, TodoList, function( editor ) {
		// Not recommended, but it works.
		editor.plugins.get( 'RestrictedEditingModeEditing' )._alwaysEnabled.add( 'todoListCheck' );
	} ]
);
```

**Closed** 2020-04-10 14:08 UTC
Labels: package:restricted-editing, resolution:duplicate, type:bug

**Comment by lolocava** [comment] 2020-04-14 09:51
Hello Jodator,

I still can't check checkboxes when clicking on it.
I don't understand how you declare plugins in `create()` method so I add it to `then()`.
I tried to add it to `_allowedInException` too.

Do you have an idea to make checkboxes clickable in RestrictedEditingMode ?

<pre>ClassicEditor.create( document.querySelector( '#section_460' ), {
    toolbar: {
		items: [
			'heading',
			'|',
			'fontSize',
			'bold',
			'underline',
			'italic',
			'link',
			'|',
			'alignment',
			'indent',
			'outdent',
			'todoList',
			'bulletedList',
			'numberedList',
			'|',
			'insertTable',
			'horizontalLine',
			'pageBreak',
			'|',
			'restrictedEditingException',
			'|',
			'undo',
			'redo'
		]
	},
    language: 'fr',
    table: {
        contentToolbar: [
            'tableColumn',
            'tableRow',
            'mergeTableCells',
            'tableProperties',
            'tableCellProperties'
        ]
    },
    licenseKey: '',
} )
.then( editor => {
	editor.plugins.get( 'RestrictedEditingModeEditing' )._alwaysEnabled.add( 'todoListCheck' );
	editor.plugins.get( 'RestrictedEditingModeEditing' )._allowedInException.add( 'todoListCheck' );
	console.log(editor.plugins.get( 'RestrictedEditingModeEditing' ));
    window.editor = editor;
} )
.catch( error => {
    console.error( 'Oops, something gone wrong!' );
    console.error( 'Please, report the following error in the https://github.com/ckeditor/ckeditor5 with the build id and the error stack trace:' );
    console.warn( 'Build id: ryncyjbmbult-h974qw1eppnk' );
    console.error( error );
} );</pre>

**Comment by lolocava** [comment] 2020-04-14 12:59
I achieve what I want by doing `editor.plugins.get( 'RestrictedEditingModeEditing' ).enableCommand('todoListCheck');`

Thank you !
