### ISSUE TITLE
Source Editing crashes when pasting specific content

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#10698] opened 2021-10-14 13:16 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html#demo and enable **Source Editing** mode.
1. Paste in `<iframe><br></br>` and switch back to **Regular Editing** mode.
1. Switch back to **Source Editing** mode.

### ✔️ Expected result

The markup is shown in the Source Editing mode.

### ❌ Actual result

The editor is unable to switch to Source Editing mode and this error is thrown in the console:
```
Uncaught RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at a (snippet.js:4)
    at snippet.js:4
    at Array.map (<anonymous>)
    at r (snippet.js:4)
    at c (snippet.js:4)
    at l._showSourceEditing (snippet.js:4)
    at l.<anonymous> (snippet.js:4)
    at l.fire (snippet.js:4)
    at l.set [as isSourceEditingMode] (snippet.js:4)
```
### ❓ Preliminary research

- To reproduce the problem in e.g. manual tests you have to load GHS with rules allowing all elements.
- Instead of `<br></br>` you can use any other element that has **`isVoid: true`** property in `formathtml.js` file: https://github.com/ckeditor/ckeditor5/blob/30adc9d5756491e7c35533b2fcd162d8fded305c/packages/ckeditor5-source-editing/src/utils/formathtml.js#L28-L69

## 📃 Other details

* Browser: Chrome
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment] 2022-05-26 14:32
For the record, http://localhost:8125/ckeditor5-html-support/tests/manual/ghs-all-features.html is just as good to reproduce this issue.

## Where it came from?

True, the error comes from source editing's formatter

https://github.com/ckeditor/ckeditor5/blob/208296ff85c33fd50a1dceefb90e3d0ad3e9a3bc/packages/ckeditor5-source-editing/src/utils/formathtml.js#L141

because `indentCount` is negative.

IMO, though, the real problem is somewhere else. Let's have a look at the data loading process in detail.

In `HtmlDataProcessor.toView()`, the initial data (`<iframe><br></br>`) goes through native `DOMParser`. Before it gets processed, to preserve leading `<scripts>` and `<styles>`, it gets wrapped in `<body>...</body>` first:

https://github.com/ckeditor/ckeditor5/blob/9deac3dcfdace007638587b269cce66b176f2eaf/packages/ckeditor5-engine/src/dataprocessor/htmldataprocessor.js#L117-L122

So what we have at this stage is:

```html
<body><iframe><br></br></body>
```

and that, when parsed by DOM parser turns into the following DOM structure

<img width="541" alt="Screenshot 2022-05-26 at 16 17 35" src="https://user-images.githubusercontent.com/1099479/170508674-ace6d7f3-405b-4117-bd03-3bd4117f52bb.png">

which in fact has nothing to do with `<br>`

<img width="497" alt="Screenshot 2022-05-26 at 16 17 40" src="https://user-images.githubusercontent.com/1099479/170508781-8e9d19cb-d285-46d6-960d-c1a7b0e09bf2.png">


but an `<iframe>` tag left open:

<img width="479" alt="Screenshot 2022-05-26 at 16 17 44" src="https://user-images.githubusercontent.com/1099479/170508814-60a26959-f5f4-4ee8-a530-a331822643c6.png">


When the following document fragment lands in the model, it results in the following structure

<img width="347" alt="Screenshot 2022-05-26 at 16 18 41" src="https://user-images.githubusercontent.com/1099479/170508832-75a474b2-e478-45c0-9e66-14c1e1e9a6b6.png">

and finally, when formatted by the source editing, the original error is thrown because the extra `</body>` should have never landed there.

## Options

### Fix the data input pipeline

The way I see it, we'd need to somehow close `<iframe>` while still a string, which IMO is pretty impossible (reliably) using the toolkit that we have (`RegExp`...). We're using `DOMParser` for a reason: we didn't want to deal with DOM parsing in the first place. 

I'm not sure why `DOMParser` puts `'</body>'` (string) in the `<iframe>` instead of closing the `<iframe>` but this is what it is. At least, this is consistent across the browsers. 

### Fix the source editing's formatter

The very first fix off the top of my head looks like this

```diff
diff --git a/packages/ckeditor5-source-editing/src/utils/formathtml.js b/packages/ckeditor5-source-editing/src/utils/formathtml.js
index 348179cc27..0bef39e985 100644
--- a/packages/ckeditor5-source-editing/src/utils/formathtml.js
+++ b/packages/ckeditor5-source-editing/src/utils/formathtml.js
@@ -138,5 +138,5 @@ function isClosingTag( line, elementsToFormat ) {
 // @param {String} [indentChar] Indentation character(s). 4 spaces by default.
 // @returns {String}
 function indentLine( line, indentCount, indentChar = '    ' ) {
-         return `${ indentChar.repeat( indentCount ) }${ line }`;
+         return `${ indentChar.repeat( Math.max( 0, indentCount ) ) }${ line }`;
 }
```

and it does the trick. If you see the content in the source editing again, it looks like this

```
<p>
    <iframe>
    <br>
</br>
</body></iframe>
</p>
```

which is not great but at least it does not throw.

**Closed** 2022-06-14 04:49 UTC
Labels: type:bug, squad:core, package:source-editing, status:in-progress
