### ISSUE TITLE
Minified editor with a placeholder crashes

### ISSUE THREAD

**Issue by philippescher** [ckeditor/ckeditor5#1758] opened 2019-04-01 18:28 UTC
I built my own FormControl to wrap CKEditor and make it available in forms in Angular. Every time I use that component in dev mode it works fine. But building it in production mode turns out the following error: **TypeError: Cannot read property 'childCount' of undefined**

`main.431acef81eadd6e278df.js:1 TypeError: Cannot read property 'childCount' of undefined
    at 6.60d03c575b32ccb858be.js:1
    at qr (6.60d03c575b32ccb858be.js:1)
    at jr (6.60d03c575b32ccb858be.js:1)
    at 6.60d03c575b32ccb858be.js:1
    at wl.change (6.60d03c575b32ccb858be.js:1)
    at Lr (6.60d03c575b32ccb858be.js:1)
    at zr._initPlaceholder (6.60d03c575b32ccb858be.js:1)
    at zr.init (6.60d03c575b32ccb858be.js:1)
    at 6.60d03c575b32ccb858be.js:1
    at t.invoke (polyfills.6082c74956d5f30a31fd.js:1)
    at e.run (polyfills.6082c74956d5f30a31fd.js:1)
    at polyfills.6082c74956d5f30a31fd.js:1
    at t.invokeTask (polyfills.6082c74956d5f30a31fd.js:1)
    at e.runTask (polyfills.6082c74956d5f30a31fd.js:1)
    at g (polyfills.6082c74956d5f30a31fd.js:1)
    at e.invokeTask [as invoke] (polyfills.6082c74956d5f30a31fd.js:1)
    at y (polyfills.6082c74956d5f30a31fd.js:1)
    at XMLHttpRequest.b (polyfills.6082c74956d5f30a31fd.js:1)`

**Comment by Reinmar** [comment] 2019-05-14 07:14
> @Mgsy, @Reinmar, could you transfer the issue to the main repository? The problem is more generic as it touches all builds and it's angular independent.

Done.

**Comment by Reinmar** [comment] 2019-06-26 15:08
I can see that the Terser issue didn't see any activity. I'm moving this to the next iteration, but I guess we'll have to propose the fix.

**Comment by ma2ciek** [comment] 2019-07-09 13:00
The question is where to fix it, IMO we could try to spend 1-2h on https://github.com/terser-js/terser/issues/348#issuecomment-508917788 and investigate the problem.

**Comment by Reinmar** [comment] 2019-07-09 14:29
Yep, certainly. I meant proposing a PR for terser.

**Comment by existentialist1888** [comment] 2019-07-19 15:15
I have been having this issue for a while now, but just assumed that it was a problem on our build server.  That said, from the thread above I'm unclear what the status of this is.  Has this been fixed?  Is there a workaround in the meantime?  What do we need to do on our end to clear this up since our cloud instance is completely broken?

**Comment by ma2ciek** [comment] 2019-07-22 10:04
@existentialist1888,

The status is that this error still isn't fixed by the minifier that you use on the server-side (terser.js). It actually has nothing to do with the CKEditor 5 except the fact that it breaks on this particular part of code.

**Comment by ma2ciek** [comment] 2019-07-22 13:22
Maybe the `"buildOptimizer": false` option in the `angular.json` will do the trick?

**Comment by MrBandaruk** [comment] 2019-08-05 14:11
I have the sane issue. Any updates?

**Comment by philippescher** [comment] 2019-08-05 14:24
Not really, just don't use the placeholder attribute and you are finde..

**Comment by ma2ciek** [comment] 2019-08-05 14:27
The bug is caused by the Terser minifier used in Angular's webpack configuration, which is still not resolved - https://github.com/terser-js/terser/issues/348.

**Comment by rezonjov** [comment] 2019-08-28 07:19
@l0v3w4v3 here's the workaround that i use on angular, definitely not ideal and hacky but at least it works for the time being. It may not work if the first element in the ckeditor is an empty <p>, that's the downside of this.

```
 BalloonEditor.create(this.editorElement.nativeElement, this.editorConfig)
        .then(editor => {
          editor.model.document.on('change:data', (evt, data) => {
            this.debouncer.next({
              content: this.ckEditor.getData(),
              editorDocument: editor.model.document,
            });
            
            // we have content, let's remove the placeholder
            if (this.countChars(editor.model.document)) {
              this.renderer.removeAttribute(
                this.editorElement.nativeElement.children[0],
                'data-placeholder'
              );
              this.renderer.removeClass(
                this.editorElement.nativeElement.children[0],
                'ck-placeholder'
              );
            } else { // no content found let's add the placeholder
              this.renderer.addClass(
                this.editorElement.nativeElement.children[0],
                'ck-placeholder'
              );
              this.renderer.setAttribute(
                this.editorElement.nativeElement.children[0],
                'data-placeholder',
                'Start writing...'
              );
            }
          });
          this.ckEditor = editor;
          this.ckEditor.setData(this.content);
          if (!this.content) { // we don't have content, let's add the placeholder
            this.renderer.setAttribute(
              this.editorElement.nativeElement.children[0],
              'data-placeholder',
              'Start writing...'
            );
            // we need to add the following class as well
            this.renderer.addClass(this.editorElement.nativeElement.children[0], 'ck-placeholder');
          }
        })
        .catch(err => {
          console.error(err.stack);
        });
```

**Comment by Admiraal** [comment] 2019-09-23 13:22
I currently am facing this same issue. Can I do something about this right now? How can I build my app into production keeping ckeditor working?

**Comment by jlamarr22** [comment] 2019-10-09 16:21
I wanted to leave a comment on a workaround for this since I just dealt with this issue as well. The following is a more complete outline on what you would need to do to implement placeholders yourself. I omitted some of the other stuff I have going on in the component, but this will get placeholders set properly to whatever you pass in to the component. I also have it working with form validation, so ping me if anyone wants to see the complete working example I have.

```
import { Component, Input, AfterViewInit, Renderer2 } from '@angular/core';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor';

@Component({
  selector: 'rich-text-editor',
  templateUrl: 'rich-text-editor.component.html',
  styleUrls: ['rich-text-editor.component.scss']
})
export class RichTextEditorComponent implements AfterViewInit {
  public editorInstance;
  public isFocused;

  @Input()
  placeholder: string = '';

  @Input()
  value: string;

  // Other stuff

  constructor(private renderer: Renderer2) {}

  ngAfterViewInit() {
    const comp = this;
    ClassicEditor.create(document.querySelector( '#editor' ), {
      toolbar: {
        items: ['bold', 'italic', 'link', 'numberedList', 'bulletedList']
      }
    })
    .then(editor => {
      comp.editorInstance = editor;
      comp.addOrRemovePlaceholder();
      comp.editorInstance.model.document.on('change:data', () => {
        comp.textValueChanged();
      });
      comp.editorInstance.ui.focusTracker.on('change:isFocused', (evt, name, value) => {
        comp.focusChanged(value);
      });
    })
    .catch(err => {
      console.error(err.stack);
    });
  }

  textValueChanged() {
    this.addOrRemovePlaceholder();
    // Other stuff
  }

  focusChanged(isFocused: boolean) {
    this.isFocused = isFocused;
    this.addOrRemovePlaceholder();
    // Other stuff
  }

  addOrRemovePlaceholder() {
    let hasData = this.isFocused || this.getData();
    if (hasData) {
      this.removePlaceholder();
    } else {
      this.addPlaceholder();
    }
  }

  addPlaceholder() {
    let editableElement = this.getEditableElement();
    this.renderer.addClass(editableElement.children[0], 'ck-placeholder');
    this.renderer.setAttribute(editableElement.children[0], 'data-placeholder', this.placeholder);
  }

  removePlaceholder() {
    let editableElement = this.getEditableElement();
    this.renderer.removeAttribute(editableElement.children[0], 'data-placeholder');
    this.renderer.removeClass(editableElement.children[0], 'ck-placeholder');
  }

  getEditableElement() {
    return this.editorInstance.ui.getEditableElement();
  }

  getData() {
    return this.editorInstance.getData();
  }
}
```

```
<textarea id="editor">
    {{ value }}
</textarea>
<!-- Other stuff -->
```

**Comment by ma2ciek** [comment] 2019-10-25 14:02
I just tried to reproduce this error with the latest dependencies and this problem no longer occurs.

If anybody faces this problem, then please reinstall all `@angular` and `@ckeditor` dependencies.

If you can't update your deps, the `target: es5` in the `tsconfig.json` should be taken into consideration.

**Closed by ma2ciek** 2019-10-25 14:02 UTC
Labels: status:confirmed, type:bug

**Comment by gvreddy04** [comment] 2019-11-15 05:04
I have same issue, below changes worked for me:

in tsconfig.json:

- from "target": "es2015" to "target": "es6"
- removed placeholder.

Note: I'm using my own customized ckEditor build: https://www.npmjs.com/package/@gvreddy04/ckeditor5-build-classic-all-features
