### ISSUE TITLE
Range-deleting multiple paragraphs leads to corrupt state

### ISSUE THREAD

**Issue by Discordius** [ckeditor/ckeditor5#8219] opened 2020-10-06 20:11 UTC
In CkEditor, create four paragraphs, like this:
```
1

2

3

4
```
Place the cursor before the '4'. Shift-select after the '1' to create a selection that includes paragraphs 2 and 3 and all of the paragraph-dividers. Press backslash. The result should be:
```
14
```
but instead it's
```
13

4
```
Now press Cmd+Z to undo what you just did. The result should have all four paragraphs, but instead it's
```
1

2

4
```
(paragraph 3 is missing)

## 📃 Other details

* Browser: Chrome
* OS: Mac OS
* CKEditor version: Latest (happens even on the example CKEDitor at https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)

## Comments

As you can imagine, this is pretty bad. This is a pretty trivial way to end up in a state in which undo doesn't work, the devtools crash, and all kinds of weird stuff starts happening. So my guess is that fixing this is pretty high priority.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment] 2020-10-07 05:43
Oh, it looks like we've fixed that right after a release: #8145.

I've checked `master` branch and [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html) and the problem does not occur there. I'm closing this as a duplicate of #8145.

The fix should be available in [the upcoming release](https://github.com/ckeditor/ckeditor5/issues/8189).

**Closed by jodator** 2020-10-07 05:43 UTC
Labels: type:bug
