### ISSUE TITLE
Feature Request : Maximize option for ckeditor 5

### ISSUE THREAD

**Issue by vershas** [ckeditor/ckeditor5#1652] opened 2019-03-26 14:51 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by vershas** [comment] 2019-03-26 14:56
Currently i am using ckeditor5....In which i was not able to include the maximize option for editor which is present in ckeditor4 and also i couldn't figure out how to include target to links in ckeditor5...
Could you please kindly update whether these features are implemented in version5, if so what is the way or plugin available to achieve it or else when can i expect these features available in version5

**Comment by Mgsy** [comment] 2019-03-26 15:03
Hello, this is a duplicate of https://github.com/ckeditor/ckeditor5/issues/1235.

**Closed by Mgsy** 2019-03-26 15:03 UTC

**Comment by leknoppix** [comment] 2020-06-16 21:00
Hello, I'm searching how i can activate the fullscreen.
I think y have found.
```
.ck-editor__editable_inline{
			/*height: 400px;*/
			min-height: 100%;
		}
		.ck.ck-editor{
			position: absolute !important;
			top:0;
			left: 0;
			right:0;
			bottom: 0;
		}
```

**Comment by pikulinpw** [comment] 2023-10-28 05:27
Following the discussion about the feature to maximize the editor to full screen, I developed a plugin that solves this problem. I would appreciate it if you tried it and share your experience using it. Any additions, suggestions or questions are welcome. Your feedback will help make the plugin even better!

https://github.com/pikulinpw/ckeditor5-fullscreen
