### ISSUE TITLE
how to resize the image ?

### ISSUE THREAD

**Issue by 100cm** [ckeditor/ckeditor5#1330] opened 2018-10-30 10:13 UTC
i cant find any API / doc for this ,just can change image position by toolbar.

**Comment by 100cm** [comment] 2018-10-30 12:00
i really need your help.

**Comment by oleq** [comment] 2018-10-30 12:38
Duplicate of https://github.com/ckeditor/ckeditor5-image/issues/216.

**Closed by oleq** 2018-10-30 12:38 UTC

**Comment by Reinmar** [comment] 2018-10-30 12:54
Is that a duplicate? Setting height/width is something different than resizing.  For me "resizing" == UI. width/height can be just about conversion. We should treat these separately. If you want to close this ticket, we should have one that covers image resizing somewhere else.

**Comment by 100cm** [comment] 2018-10-30 13:37
I am very sad for your attitude. @oleq 。ckeditor4 is excellent,bug version 5 seems to have a long way to go

**Comment by Reinmar** [comment] 2018-10-30 13:49
@100cm, could you explain a bit more what you mean by "resizing"? Do you mean the ability to choose the size of an image by grabbing some handle (usually in the bottom right corner of the image) and dragging?

Like here:

![image](https://user-images.githubusercontent.com/156149/47722540-ed367c00-dc52-11e8-97d4-b7eafbb6e495.png)

**Comment by 100cm** [comment] 2018-10-30 15:48
@Reinmar Yes,I  am confused about this,

1. Are there any official plugins for this feature?Or any api to reach this feature (just like some config api ?) ,Even If set image's width and height by input .

2. IF not , when will the plugin provide  or how to write this by myself (i can do this by myself but if you can help is better)

**Comment by oleq** [comment] 2018-10-30 16:59
@100cm 

> 1. Are there any official plugins for this feature?Or any api to reach this feature (just like some config api ?) ,Even If set image's width and height by input .

No, there are no such plugins or API at this moment. We [plan](https://github.com/ckeditor/ckeditor5-image/issues/241) implementing it but there's no ETA.

> 2\. IF not , when will the plugin provide  or how to write this by myself (i can do this by myself but if you can help is better)

The feature comes down to porting the UI part of the [enhanced image plugin](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/image2/plugin.js) and adapting it to the view mechanics and document model of v5. It's a complex feature and, unless you're familiar with the concept of widgets in CKEditor 5, it will be very hard for us to give you a hand in this project.

For now, you can give use a "thumb up" in this issue https://github.com/ckeditor/ckeditor5-image/issues/241.

**Comment by programad** [comment] 2018-12-06 17:11
Any news on this issue, guys?

**Comment by parthkhanna150** [comment] 2019-07-02 14:41
Any news, yet?

**Comment by mechanicals** [comment] 2019-07-16 13:30
Its a really important feature. Any ETA on when it can be implemented.

**Comment by dkrahn** [comment] 2019-07-16 18:41
Look at [**Iteration 26 roadmap**](https://github.com/ckeditor/ckeditor5/issues/1887) they have put issue https://github.com/ckeditor/ckeditor5-image/issues/241 that IMO will solve this issue.
