### ISSUE TITLE
null reference

### ISSUE THREAD

**Issue by jrit** [ckeditor/ckeditor5#8756] opened 2021-01-07 00:25 UTC
https://github.com/ckeditor/ckeditor5/blob/a26c6532e2090b47816961c8344b258d237f28d0/packages/ckeditor5-table/src/converters/downcast.js#L382

When attempting ctrl+x (cut) on an image inside of a table, `firstChild` === null. When `firstChild` is passed to `hasAnyAttribute()` that null causes an exception. It seems like the safest resolution is to check for `element === null` in `hasAnyAttribute()`

**Comment by Mgsy** [comment] 2021-01-11 08:40
Hi! Thanks for the report. Can you provide step-by-step instruction showing how to reproduce the exception in CKEditor 5?

**Comment by mlewand** [comment] 2021-04-27 08:21
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

I'll just add that I tried to reproduce mentioned issue (by inserting a table to a beginning of a document, adding an image to the first cell, then cutting it and it worked fine) so it might be that it got fixed down the road.

**Closed by mlewand** 2021-04-27 08:21 UTC
Labels: pending:feedback
