### ISSUE TITLE
<br> tag doesn't work inside <a> tag

### ISSUE THREAD

**Issue by rrajan0308** [ckeditor/ckeditor5#15512] opened 2023-12-12 11:19 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Add a link to a group of words ( in a line) like, "[try this](https://www.google.com)"
2. Add a <br/> among the words, to make it a 2 line link. So in source it would look like this <a href="https://www.googe.com">try <br/> this</a>
3. But this creates an extra <a> tag to the new line, making it <a href="https://www.google.com">try</a><br/><a href="https://www.google.com"> this </a>

### ✔️ Expected result

<a href="https://www.googe.com">try <br/> this</a>

### ❌ Actual result

<a href="https://www.google.com">try</a><br/><a href="https://www.google.com"> this </a>

## 📃 Other details

* Browser: all
* OS: windows
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment] 2023-12-12 16:02
Looks like a duplicate of https://github.com/ckeditor/ckeditor5/issues/9093 and https://github.com/ckeditor/ckeditor5/issues/1068.

**Comment by rrajan0308** [comment] 2023-12-13 05:58
@niegowski Thank you! will try the plugin suggested.

**Comment by Witoso** [comment] 2023-12-14 08:25
DUP: [#9093](https://github.com/ckeditor/ckeditor5/issues/9093) and [#1068](https://github.com/ckeditor/ckeditor5/issues/1068).

**Closed by Witoso** 2023-12-14 08:25 UTC
Labels: type:bug
