### ISSUE TITLE
Seeing a triangle kind of image inside ckeditor in test env not in dev env

### ISSUE THREAD

**Issue by renjithap07** [ckeditor/ckeditor5#7504] opened 2020-06-25 20:27 UTC
## 📝 Provide detailed reproduction steps (if any)

1. …Getting a triangle like svg in ckeditor in initial load.
![20200625_151406](https://user-images.githubusercontent.com/24940952/85791969-b2733880-b700-11ea-9ca0-f20400f613f8.jpg)

2. …while clicking on the ckeditor, the toolbar getting doubled
3. … getting console.error after i click on the ckeditor 'cannot read property 'parent' of undefined', it's angular 6,
Using ckeditor5-anguar and usinh package for document editor

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2020-06-26 06:16
Hi, it's a duplicate of ckeditor/ckeditor5-angular#210. You can find there a solution, so you can check if it solves your problem.

**Closed by Mgsy** 2020-06-26 06:16 UTC
Labels: type:bug

**Comment by renjithap07** [comment] 2020-06-26 14:48
Thanks @Mgsy for the response, I understand that changing the value ' optimization": false ' in angular.json will fix the issue but that may affect the performance of the site. Please let me know if you can suggest any other solution without impacting the overall  performance of the website.
