### ISSUE TITLE
[GHS] Unable to remove bold styling with toolbar

### ISSUE THREAD

**Issue by mlh758** [ckeditor/ckeditor5#10548] opened 2021-09-16 15:54 UTC
### Steps to reproduce:

1. Open editor with GHS plugin with all features enabled and initial content that contains `<strong>` tags. Alternatively, you can check it on [source editing docs](https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html).
2. Select this content and un-bold
3. Open source view or just `editor.getData()`

![bolding_gif](https://user-images.githubusercontent.com/4331955/133644885-925a9f9d-d394-4a99-93bb-038008ceebd6.gif)

### ✔️ Expected result

The text should not have wrapping `<strong>` tag.

### ❌ Actual result

The text still has the wrapping `<strong>` tag. Happens also for other tags.

## 📃 Other details

* Browser: Firefox Developer Edition 93.0b4
* OS: MacOS 11.6
* First affected CKEditor version: …
* Installed CKEditor plugins: …

```
"@ckeditor/ckeditor5-adapter-ckfinder": "^29.1.0",
"@ckeditor/ckeditor5-autoformat": "^29.1.0",
"@ckeditor/ckeditor5-autosave": "^29.1.0",
"@ckeditor/ckeditor5-basic-styles": "^29.1.0",
"@ckeditor/ckeditor5-block-quote": "^29.1.0",
"@ckeditor/ckeditor5-ckfinder": "^29.1.0",
"@ckeditor/ckeditor5-core": "^29.1.0",
"@ckeditor/ckeditor5-dev-utils": "^23.3.4",
"@ckeditor/ckeditor5-dev-webpack-plugin": "^25.3.0",
"@ckeditor/ckeditor5-editor-classic": "^29.1.0",
"@ckeditor/ckeditor5-essentials": "^29.1.0",
"@ckeditor/ckeditor5-heading": "^29.1.0",
"@ckeditor/ckeditor5-html-embed": "^29.1.0",
"@ckeditor/ckeditor5-html-support": "^29.1.0",
"@ckeditor/ckeditor5-image": "^29.1.0",
"@ckeditor/ckeditor5-indent": "^29.1.0",
"@ckeditor/ckeditor5-link": "^29.1.0",
"@ckeditor/ckeditor5-list": "^29.1.0",
"@ckeditor/ckeditor5-media-embed": "^29.1.0",
"@ckeditor/ckeditor5-paragraph": "^29.1.0",
"@ckeditor/ckeditor5-paste-from-office": "^29.1.0",
"@ckeditor/ckeditor5-source-editing": "^29.1.0",
"@ckeditor/ckeditor5-table": "^29.1.0",
"@ckeditor/ckeditor5-theme-lark": "^29.1.0",
"@ckeditor/ckeditor5-typing": "^29.1.0",
```
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-09-20 07:33
Hi, thanks for the report. I was not able to reproduce this by using autosave plugin and getting the data. Are you sure it's a bug inside the editor and not caused by your custom implementation? In such case, we will need more details on how to reproduce this.

**Comment by mlh758** [comment] 2021-09-20 13:55
It might be hard to untangle. One additional detail I can provide right away is that after removing the bold styling, the source mode view still shows it with a `<strong>` tag wrapping it. This is after removing the bold styling:

![image](https://user-images.githubusercontent.com/4331955/134014461-600d72f9-a3d5-49ca-9bc6-55ebc7ba5701.png)

**Comment by mlh758** [comment] 2021-09-20 13:59
Also, here's a gist of our ckeditor build: https://gist.github.com/mlh758/7f7357aaabdc55fb40030e06c152613c

Most of this is just copied from the docs.

**Comment by mlh758** [comment] 2021-09-24 14:17
I was able to narrow this down to specifically being an issue with `GeneralHtmlSupport`. When I removed that it would bold/unbold just fine. When I added it back in the text could be made bold but it would not remove the bold.

**Comment by mlh758** [comment] 2021-09-28 19:49
This also seems to lead to `<figure>` tags being leftover if you add an image to the page with drag+drop. After removing the image the `<figure>` tag will still be in the source editor. If I remove the general HTML support plugin that no longer happens.

**Comment by FilipTokarski** [comment] 2021-09-29 07:10
Thanks for the details. I tried again to reproduce it specifically with the combination of `GeneralHtmlSupport`, `Autosave` and `SourceEditing` plugins, with the configuration you provided, but still no luck. Not sure if I understood correctly from the screencast, but maybe there's something additionally going on during the page reload?
  
As it comes to the bug with `<figure>` tag, it is a known case and [we are tracking it here](https://github.com/ckeditor/ckeditor5/issues/10279).

**Comment by mlh758** [comment] 2021-09-29 12:29
I don't think `AutoSave` is part of the problem. When I open the developer console and watch what is actually being sent, the text is still bolded and (without reloading the page or anything) if I open source editor I can see that the text is still wrapped in `<strong>` tags.

I guess the next step is to provide a whole GitHub repo that reproduces the behavior on its own. Our app where this is happening is basically just the config I already sent with an autosave callback configured so it shouldn't be too hard to put together if I can ensure the versions stay exactly the same.

**Comment by mlh758** [comment] 2021-09-29 12:34
I can reproduce this on your docs page: https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html

If I go to the text "Chris Austin Hadfield" which is bolded, highlight that text, then click the bold control to remove the bold styling then open the source editor I can see that it is still wrapped in `<strong>` tags.

**Comment by FilipTokarski** [comment] 2021-09-29 13:43
Thanks for the last comment! I think I get it now - I can reproduce it 100% when I try to un-bold content that **was loaded into editor** with `<strong>` tags. If I bold it myself and then remove bold it works fine:


https://user-images.githubusercontent.com/34380544/135280415-20bd6d92-b92a-4e3c-803a-2dd346134957.mp4

**Comment by FilipTokarski** [comment] 2021-09-29 13:52
@mlh758 I updated your first post, so that we have easier steps to reproduce this. Thanks once again for reporting the issue.

**Comment by stefandobre** [comment] 2021-11-20 23:28
This can be seen when editing Markdown as well

![markdownPlusSource](https://user-images.githubusercontent.com/20504443/142743769-44929e93-309d-415e-892d-e8c00e46f5f5.gif)

**Comment by timtempel** [comment] 2022-01-12 18:27
We have the exact same issue, and it's even worse as it's basically affecting all text styling (Bold, Italic, Underline, Strikethrough, Anchors, super- and subscript). Anybody found a workaround / fix for this already?

**Comment by timtempel** [comment] 2022-01-12 22:20
I've found a temporary "solution". If you exclude the Bold, Italic, Underline, Strikethrough, Subscript and Superscript from the Allowed and Disallowed contentFilter, the bug doesn't arise. It's far from ideal but a sacrifice I was willing to make.

To clarify, instead of addressing **all** elements, only specify the elements that are allowed and don't include the above elements. 

**Example:**

```
name: /^(p|span|div|img|iframe|table|tbody|thead|tfoot|tr|td|th|col|colgroup|caption|hr|br|ul|ol|li|blockquote|em|h[2-6])$/,
        attributes: {
            'dir'   :true,
            'align' :true,
            'alt'   :true,
            'title' :true,
            'id'    :true,
            'name'  :true,
        },
        classes: true,
        styles: {
            'color'         : true,
            'text-align'    : true
        }
```

**Comment by bpeterm** [comment] 2022-01-14 10:40
> contentFilter

Thanks! That's a big help!
Where can I set this? Thanks in advance!

**Comment by timtempel** [comment] 2022-01-14 13:37
> > contentFilter
> 
> Thanks! That's a big help! Where can I set this? Thanks in advance!

You can set those in the htmlSupport property of your CK config, example:

```
toolbar: {
  items: [
      "bold",
      "italic",
      "underline",                                
      "link",                              
      "subscript",
      "superscript"
  ]
}, 
htmlSupport: {
    allow: [
        {
  name: /^(p|span|div|img|iframe|table|tbody|thead|tfoot|tr|td|th|col|colgroup|caption|hr|br|ul|ol|li|blockquote|em|h[2-6])$/,
        attributes: {
            'dir'   :true,
            'align' :true,
            'alt'   :true,
            'title' :true,
            'id'    :true,
            'name'  :true,
        },
        classes: true,
        styles: {
            'color'         : true,
            'text-align'    : true
        }
      },
}
```

**Comment by shabab477** [comment] 2022-01-24 15:31
An easier way to recreate this is by following the steps to reproduce in #11152

**Comment by Reinmar** [comment] 2022-03-24 12:41
cc @niegowski It seems to be a part of what you're researching.

**Comment by steve-safarilaw** [comment] 2022-03-29 23:39
It is really a poor user experience to have such basic functionality broken.  This is a customer facing issue for us now and it's a little embarrassing that basic formatting doesn't work!  Please raise the priority if you can and try to get this fixed ASAP!

Thanks!

**Comment by niegowski** [comment] 2022-07-14 11:59
@ckeditor/qa-team could you check if this issue is still valid? This should be resolved with #10800 which was released in v34.1.0.

**Comment by FilipTokarski** [comment] 2022-07-15 10:31
I'm not able to reproduce it now. 
@webdev51 Can you confirm that in version `34.1.0` it works fine for you?

**Comment by webdev51** [comment] 2022-07-15 11:02
> I'm not able to reproduce it now. @webdev51 Can you confirm that in version `34.1.0` it works fine for you?

Verified! The issue does not exist in 34.1.0. Thank you! 🎉

**Comment by FilipTokarski** [comment] 2022-07-15 11:56
Thanks! Closing the ticket then.

**Closed by FilipTokarski** 2022-07-15 11:56 UTC
Labels: type:bug, support:2, squad:core, package:html-support
