### ISSUE TITLE
[Edge] Visual Cursor stays in editor after moving focua out of it with TAB key

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#5738] opened 2019-11-14 11:45 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html
2. Place your cursor at the start of "Walking the capitals of Europe: Warsaw" in last editor
3. Press tab key

### ✔️ Expected result

Focus is moved out of the editor and there is no blinking cursor inside it.

### ❌ Actual result

Focus is moved out of the editor however you can still see crspr blinking.

## 📃 Other details

Problem can be reproduced in any sample. Please for example go to https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html, place the cursor somewhere in the first line e.g. "The three greatest things yo^u learn from traveling" and press Shift+Tab.

* Browser: Edge
* OS: Win10
* CKEditor version: 15
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2019-11-14 12:13
I can reproduce this issue.

![bug_cke5](https://user-images.githubusercontent.com/20988892/68856305-7d215980-06e0-11ea-8382-335888318a47.gif)

**Comment by FilipTokarski** [comment] 2019-12-27 15:26
It still happens in old Edge but seems to be fixed in new beta version

**Closed** 2020-01-30 10:32 UTC
Labels: browser:edge, domain:accessibility, status:confirmed, support:2, type:bug

**Comment by Mgsy** [comment] 2020-01-30 10:33
Fixed in the new Edge release.
