### ISSUE TITLE
safari table td enter other language bug

### ISSUE THREAD

**Issue by hongz1125** [ckeditor/ckeditor5#8759] opened 2021-01-07 06:26 UTC
## 📝 Provide detailed reproduction steps (if any)

![image](https://user-images.githubusercontent.com/674559/103858483-606d8f80-50f3-11eb-9768-80c3031582f7.png)

Insert table; no cursor; unable to enter a language other than English (e.g. Chinese)

![image](https://user-images.githubusercontent.com/674559/103858794-ef7aa780-50f3-11eb-8a0c-23fa9d711847.png)

The expectation is 2; at present it is 1

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser:  just in  safari
* OS:mac
* CKEditor version:last 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-01-08 14:39
Hi, thanks for the report. I am not able to reproduce this exactly as on the image you provided. I can create a composition but I'm getting other bug, which is that letter `h` is inserted before the Chinese characters:  
![0_ime1](https://user-images.githubusercontent.com/34380544/104026840-d0007f00-51c6-11eb-96ef-9344511bac7b.gif)  
Could you provide some more information and steps on how to reproduce your exact issue?  

Apart from that, we are aware of such issues and we plan to continue our work on IME support - you can [track the progress here](https://github.com/ckeditor/ckeditor5/issues/7462).

**Comment by LukaszGudel** [comment] 2021-01-11 13:30
It looks like this issue is related to #1333 and using steps from [this comment](https://github.com/ckeditor/ckeditor5/issues/1333#issuecomment-757883699) you can exactly reproduce this issue

**Comment by mlewand** [comment] 2021-03-01 08:38
Closing as a duplicate of #1333.

**Closed by mlewand** 2021-03-01 08:38 UTC
Labels: browser:safari, domain:ime, type:bug
