### ISSUE TITLE
tel protocol not supported in the link balloon

### ISSUE THREAD

**Issue by odgey** [ckeditor/ckeditor5#11855] opened 2022-05-31 09:59 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Highlight text
2. Create link
3. Enter a valid tel link  e.g.  tel:123456

### ✔️ Expected result

Tel link is added to the selected text

### ❌ Actual result

Link is getting set to placeholder hash

### ❓ Possible solution

The regex within ckeditore-link/src/utils.js is flagging the link as valid, update the safe URL regex to allow tel links. The following is in our custom build now, could do with it applying at source if possible. 

const SAFE_URL = /^(?:(?:https?|ftps?|mailto|tel):|[^a-z]|[a-z+.-]+(?:[^a-z+.:-]|$))/i;

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by maxfenton** [comment] 2023-06-29 15:27
Noting that `sms:` is also a valid URL type that should also be added to the test set. 

`<a href="sms:+15551234567&body=Hi%20there">Text Us</a>`

**Comment by Witoso** [comment] 2023-06-30 07:10
Closing as a duplicate of #14304.

**Closed by Witoso** 2023-06-30 07:10 UTC
Labels: type:bug, package:link, squad:core
