### ISSUE TITLE
the img tool overflow

### ISSUE THREAD

**Issue by 2507483326** [ckeditor/ckeditor5#1705] opened 2019-04-14 03:50 UTC
![image](https://user-images.githubusercontent.com/10804157/56088478-49fdba00-5eb4-11e9-9a35-f3abcd22e29b.png)

**Comment by Mgsy** [comment] 2019-04-15 07:11
It's a duplicate of https://github.com/ckeditor/ckeditor5-ui/issues/181.

**Closed by Mgsy** 2019-04-15 07:11 UTC
