### ISSUE TITLE
Pasting lists from Google Docs in the CKE5 docs fails to retain marker formatting

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#9042] opened 2021-02-17 10:54 UTC
## 📝 Provide detailed reproduction steps (if any)

1.  Paste multi-level list with different markers from google docs (see screenshots attached).

### ✔️ Expected result

The formatting of the markers is retained.

### ❌ Actual result

It isn't.

## 📃 Other details

*   Browser: latest Chrome
*   OS: Last but one MacOS
*   First affected CKEditor version: latest CKE5
*   Installed CKEditor plugins: as in the docs: [https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html)  
     

The list pasted from Google Docs:

![](https://user-images.githubusercontent.com/68123541/108194234-a831fe80-7116-11eb-8768-822dd6a119b8.png)

The list pasted into CKE5 editor demo:

![](https://user-images.githubusercontent.com/68123541/108194284-bc75fb80-7116-11eb-90a2-2e165df51355.png)

**Comment by FilipTokarski** [comment] 2021-02-17 13:03
Isn't it a duplicate of - https://github.com/ckeditor/ckeditor5/issues/8845?

**Comment by godai78** [comment] 2021-02-17 13:09
Yes, this seems to be the case.

**Closed** 2021-02-17 13:30 UTC
Labels: type:bug
