### ISSUE TITLE
upload adapter example

### ISSUE THREAD

**Issue by vespino** [ckeditor/ckeditor5#704] opened 2017-12-06 14:33 UTC
I implemented ckeditor in my project and would also like to include image uploads. Is there an example for creating an upload adapter? This is the error I'm currently getting when trying to drag-and-drop an image:

filerepository-no-adapter: Upload adapter is not defined. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#filerepository-no-adapter

One more thing: when selecting a text and setting it to "heading 1", H2 tags are added where I would expect H1. Is this a bug?

This is the code I'm currently using:

`<script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/inline/ckeditor.js"></script>`

```
<script>
InlineEditor
	.create( document.querySelector( '#editor' ), {
		image: {
			// You need to configure the image toolbar too, so it uses the new style buttons.
			toolbar: [ 'imageTextAlternative', '|', 'imageStyleAlignLeft', 'imageStyleFull', 'imageStyleAlignRight' ],

			styles: [
				// This option is equal to a situation where no style is applied.
				'imageStyleFull',

				// This represents an image aligned to left.
				'imageStyleAlignLeft',

				// This represents an image aligned to right.
				'imageStyleAlignRight'
			]
		}
	} )
	.catch( error => {
		console.error( error );
	} );
</script>
```

**Comment by davidpolberger** [comment] 2017-12-06 23:07
The heading issue you mention is by design. Refer to https://github.com/ckeditor/ckeditor5-heading/issues/72 for more information.

**Comment by vespino** [comment] 2017-12-08 10:14
@davidpolberger thanks, that works. Any thoughts on the image upload thing?

**Comment by davidpolberger** [comment] 2017-12-10 00:14
Not yet, @vespino. We're writing the server infrastructure for image uploads as I write this, but we aren't scheduled to write the corresponding image upload adapter for CKEditor 5 until January.

**Comment by Reinmar** [comment] 2017-12-11 11:42
As for the upload adapter thing, we don't have it covered properly in the docs (I reported https://github.com/ckeditor/ckeditor5/issues/709 to track that). However, https://github.com/ckeditor/ckeditor5-adapter-ckfinder/blob/master/src/uploadadapter.js implements a simple adapter and I think the code should be easy to customize for other backend services.

**Comment by Reinmar** [comment] 2017-12-11 11:42
I think that all the questions mentioned in this topic were answered (thanks, @davidpolberger!), so I'm closing this ticket.

**Closed by Reinmar** 2017-12-11 11:42 UTC

**Comment by vespino** [comment] 2017-12-11 19:16
One more question. Adding the upload URL is handled in the file:

```
ClassicEditor
  .create( editorElement, {
    ckfinder: {
      uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
    }
  } )
  .then( ... )
  .catch( ... );
```

But could I trouble you to tell me where I should put this file and will this also enable drag-and-drop automatically like in [this example](https://ckeditor.com/ckeditor-5-builds/#inline)?

**Comment by learning-hubs** [comment] 2020-05-16 19:16
![logo192](https://user-images.githubusercontent.com/63396575/82128306-c493ba00-97d7-11ea-956a-d1d781eeb0ed.png)
![logo512](https://user-images.githubusercontent.com/63396575/82128315-d5dcc680-97d7-11ea-8ad0-add4926059df.png)

**Comment by learning-hubs** [comment] 2020-05-16 19:16
amazing
