### ISSUE TITLE
Link plugin with internal links

### ISSUE THREAD

**Issue by marcellofuschi** [ckeditor/ckeditor5#7618] opened 2020-07-13 21:44 UTC
**Internal link**: link pointing to another spot in the same document instead of an external URL.

I noticed that the official link plugin doesn't properly handle internal links by default. For example, when you click on an existing internal link it tries to open it in a new tab (`target=_blank` behavior).

**Comment by Reinmar** [comment] 2020-08-10 07:54
Hi! Do you mean anchor links `#some-anchor`? You'd expect that when clicking such a link you get scrolled to this point in the document?

**Comment by marcellofuschi** [comment] 2020-08-10 08:21
Hi! Yes, that's what I would expect.

**Comment by jswiderski** [comment] 2022-05-02 07:36
Duplicate of #1944.

**Closed by jswiderski** 2022-05-02 07:36 UTC
Labels: resolution:duplicate, type:improvement, package:link, domain:ui/ux, squad:core
