### ISSUE TITLE
How to add a <img> tag inside a  <p> tag ?

### ISSUE THREAD

**Issue by woshiliujia** [ckeditor/ckeditor5#7635] opened 2020-07-16 13:13 UTC
## 📝 Provide a description of the new feature
I recently updated our CK editor from CK3 to CK5 and found that I cannot add a <img> tag inside a  <p> tag.
Do you support this? Because I have much old data to deal with.
I have solved all other issues, this is the LAST one. 
_What is the expected behavior of the proposed feature?_
Would you please tell if there would be any good idea to solve this problem?
--- 

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment] 2020-07-20 07:43
This is a duplicate of #2052.

**Closed by mlewand** 2020-07-20 07:43 UTC
Labels: type:feature
