### ISSUE TITLE
beforeInput: The mention marker inserts twice on Android

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12567] opened 2022-10-05 08:23 UTC
Tested on:

*   `ck/11438-beforeinput-ime-research-vol1.1-android` branch
*   Nexus 10 emulator
*   GalaxyTab real device

## 📝 Provide detailed reproduction steps (if any)

1.  Switch to GBoard.
2.  Open the all features manual test.
3.  Insert `@` character.

### ✔️ Expected result

The character is inserted once.

### ❌ Actual result

The character is inserted twice.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment] 2022-10-10 13:19
I was unable to reproduce this issue. Could you provide more reproduction details?

**Comment by Acrophost** [comment] 2022-10-12 10:04
The issue still persists.

@niegowski click at the end of any header/paragraph/list item, add a whitespace and put `@` character to start a mention - at this point we already get doubled `@`.

**Comment by dufipl** [comment] 2022-10-12 10:46
Same experience as above ☝️ Scenario when mention is put at the end still results in the doubled mention marker.

**Comment by mabryl** [comment] 2023-08-24 09:40
Just retested this on this kind of setup:

Device: Samsung A52s 5G
OS: Android 13
Keyboard: Gboard 13.2.04
Browsers: Chrome 116.0.5845.92 | Firefox 116.3.0

And I can confirm that the issue is no longer reproducible. Hence, closing the ticket.

**Closed by mabryl** 2023-08-24 09:40 UTC
Labels: type:bug, browser:android, domain:typing/ime, squad:core
