### ISSUE TITLE
[Edge] Link / Table - Move selection from editing link to table requires two clicks

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1157] opened 2018-07-16 09:50 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest masers

## 📋 Steps to reproduce

1. Build docs and open **Features / Table**
2. Click on the link.
3. _Edit link_.
4. Click on the table.

## ✅ Expected result

The table will be selected.

## ❎ Actual result

After the first click, an input with the URL disappeared. After the second click, the selection was moved.

## 📃 Other details that might be useful

Edge.

![edge-link-table](https://user-images.githubusercontent.com/2270764/42752480-571d3b12-88ee-11e8-8c60-7f6d69067d8a.gif)

cc: @oleq

**Comment by oleq** [comment] 2018-07-17 07:47
@jodator Could it be a table widget issue?

**Comment by jodator** [comment] 2018-07-17 08:18
@oleq Nah... it's Edge:

On the screencast below:
1. The confirm link changes button behaves the same (lol).
2. Also image caption behaves the same.

![peek 2018-07-17 10-16](https://user-images.githubusercontent.com/247363/42804917-a3d64144-89aa-11e8-969d-b1618d3c8a37.gif)

**Comment by oleq** [comment] 2018-07-17 09:51
Duplicate of https://github.com/ckeditor/ckeditor5/issues/848.

**Closed by oleq** 2018-07-17 09:51 UTC
Labels: type:bug
