### ISSUE TITLE
Deprecation warnings in webpack 5

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10980] opened 2021-12-08 09:58 UTC
## 📝 Provide detailed reproduction steps (if any)

A few tasks may print logs related to API deprecation.

### `dll:build`

```
(node:27547) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Let's see what we can do to remove them.

**Comment by j2s** [comment] 2023-02-17 15:41
This actually stops the build (yarn dll:build ), so needs some kind of resolution. 
BTW adding node '--trace-deprecation' to script invocation in packages.json does not change output

**Comment by pomek** [comment] 2023-02-17 19:32
I can't reproduce it using the latest dependencies (`yarn run reinstall` executed before `yarn run dll:build`). I mean, builds are fine, and logs still are present.

**Comment by j2s** [comment] 2023-02-17 20:04
Thanks @pomek 
BTW I had to add webpack-cli as initially got an error about that (and it was not in package.json) - did you?

I deleted whole directory and re-cloned etc and get same result:
$ git clone https://github.com/ckeditor/ckeditor5.git
$ cd ckeditor5
$ yarn install
$ yarn run dll:build  #(uses scripts/dll/webpack.config.dll.js)
_💥 Build ended with an error:
/home/jon/nsrc/cke5ex/dcke/ckeditor5/.pnp.cjs:40653
      Error.captureStackTrace(firstError);
            ^
Error: webpack tried to access webpack-cli (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
Required package: webpack-cli (via "webpack-cli/package.json")_

$yarn add -D webpack-cli  # adds "webpack-cli": "^5.0.1",

$ yarn run dll:build  
_💥 Build ended with an error:
(node:22072) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* _as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
[CKEditorTranslationsPlugin] Error: No translation has been found for the en language.
🛠️  To reproduce this error, run:
 - cd /home/jon/nsrc/cke5ex/dcke/ckeditor5
 - yarn webpack --config=scripts/dll/webpack.config.dll.js --mode=development
Halting the script due to failed base DLL build._

Googling the error found:
https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/61
https://github.com/webpack-contrib/terser-webpack-plugin/issues/449 

I tried to remove terser-webpack-plugin use as it was suggested as a possible cause in issues/449 but no difference.
I tried the 'npm ls webpack' (after npm install) as mentioned in issues/61 and v4 of webpack were present as well as v5, but no idea what to do about that! 

BTW The [CKEditorTranslationsPlugin] error can be bypassed by commenting out use in webpack.config.dll.js  plugins section

**Comment by pomek** [comment] 2023-02-17 20:20
Could you let us check the issue with the instruction you gave us? We will be back next week with more details.

**Comment by martnpaneq** [comment] 2023-02-20 09:16
I tried reproducing the issue, but I could not do that. I tested this for node v18 and v14.
I run: 
```
$ git clone https://github.com/ckeditor/ckeditor5.git
$ cd ckeditor5
$ yarn install
$ yarn run dll:build
```

When I checked the version of `webpack-cli` that is installed for me, it prints `4.10.0`.
Could you list what version of `webpack-cli` is installed for you on a fresh clone of the repo?
You can check that by running `yarn list webpack-cli`.

**Comment by j2s** [comment] 2023-02-20 11:51
Hi @martnpaneq 
Thanks, this is strange, I'm seeing the same result I had before. I'm on Ubuntu 22.04.  
So no webpack-cli is installed as it's not in my package.json
-rw-rw-r-- 1 jon jon 8512 Feb 20 11:35 package.json
   ```
    "wait-on": "^6.0.1",
    "webpack": "^5.58.1",
    "wrapper-webpack-plugin": "^2.2.2"
  }
```
```
$ yarn list webpack-cli
Usage Error: Couldn't find a script named "list".
$ which yarn
/home/jon/.nvm/versions/node/v18.8.0/bin/yarn
$ yarn help
━━━ Yarn Package Manager - 3.3.1  ...

$ yarn add webpack-cli
# completed with 24+ warnings 

$ yarn info webpack-cli   # note info not list
└─ webpack-cli@npm:5.0.1
   ├─ Instances: 1
   ├─ Version: 5.0.1
   │
   ├─ Exported Binaries
   │  └─ webpack-cli
   │
   └─ Dependencies
      ├─ @discoveryjs/json-ext@npm:^0.5.0 → npm:0.5.7
      ├─ @webpack-cli/configtest@npm:^2.0.1
...

```

**Comment by martnpaneq** [comment] 2023-02-20 12:19
CKEditor5 uses yarn workspaces to manage dependencies. That means that `webpack-cli` does not have to be specified in the main `package.json` file, but if any dependency uses it (e.g. `ckeditor5/packages/ckeditor5-core`), it will be installed, and available in the main `node_modules` and visible for all packages.

The information that `yarn list` is not working for you is very important. It may suggest that you are using yarn v2, which is not supported.
![image](https://user-images.githubusercontent.com/114912428/220104914-dee7a6a2-ae3b-4c9c-8e89-cb8eae6dbbf9.png)

Please try using yarn v1 or npm to install the dependencies and check again.

**Comment by j2s** [comment] 2023-02-20 14:46
yep yarn was at 3.3.1
I removed that and installed v1
$npm install --global yarn@^1
$ yarn -v
1.22.19

I removed all local installed files and did yarn install & build and this built OK.
$ yarn list webpack-cli
yarn list v1.22.19

I can see that v1 creates node_modues rather than .yarn 
Is there a way for the script to check for yarn version - I'm fairly new to node related programming?

**Comment by martnpaneq** [comment] 2023-02-21 10:16
I'm glad to hear that you managed to get it to work.

It's a good idea for us to show some error that yarn v2 and yarn v3 are not supported. Unfortunately yarn v2 and v3 ignore the `"engines"` mechanism that enforces a specific version, so we are not able to do that right now - https://github.com/yarnpkg/yarn/issues/2800#issuecomment-1305771298

I'm hoping at least this thread could help someone that would have this problem in the future.

**Comment by j2s** [comment] 2023-02-22 11:40
Thanks for help - was trying to debug a problem with a custom tag plugin https://github.com/ckeditor/ckeditor5/issues/13340 
I haven't tracked down where 'data-ck-unsafe-element' is being applied but could prove a work-round.  Any thoughts on how to understand what is happening and also how to program a plugin to support optional attributes?

**Comment by przemyslaw-zan** [comment] 2023-07-26 13:51
I can reproduce the warning by running:

```bash
yarn run dll:build --verbose --skip-packages-dll
```

The cause is [wrapper-webpack-plugin](https://www.npmjs.com/package/wrapper-webpack-plugin) which we use [here](https://github.com/ckeditor/ckeditor5/blob/43055d857eebd23085edb0456de2f4360577da21/scripts/dll/webpack.config.dll.js#L108). A relevant issue is open in the repository, but it looks like its not going anywhere, judging by long inactivity: https://github.com/levp/wrapper-webpack-plugin/issues/11.

After a rather short search I could not find any replacement plugins readily available. However, due to simple nature of the plugin in question, I think that it would be rather easy to replicate its functionality on our own.

I suggest that we drop the plugin in favour of our own plugin for our own needs.

**Closed** 2023-07-28 08:41 UTC
Labels: type:bug, squad:devops, status:in-progress
