### ISSUE TITLE
Font sizes and Font family don't show all options and even scroll?

### ISSUE THREAD

**Issue by kinju4374** [ckeditor/ckeditor5#10470] opened 2021-09-03 12:10 UTC
Hi,

I added some custom font sizes and font family in my CKEditor and I am facing a scroll issue as shown in the following screenshots, all options are not visible (From the example still two more font size 19 and 21 are available but they are not visible)

![image](https://user-images.githubusercontent.com/17248153/132002775-042fbcc4-e625-4cda-ad2f-d8e65ecd51fc.png)

Same with font family (there are 5 more font-family available at the top)

![image](https://user-images.githubusercontent.com/17248153/132002988-7f0f9bf0-2374-4d41-a9d0-948d4eec5c0e.png)

The same thing happened in CKEditor document example too (Default, Arial and Courier New) are not visible.

![image](https://user-images.githubusercontent.com/17248153/132006854-a1879732-8f02-4c80-8d47-6bafe4571e46.png)

Can you please suggest how can I fix this issue?

**Comment by FilipTokarski** [comment] 2021-09-20 08:18
Hi, sorry for the late reply. It seems to be a duplicate of https://github.com/ckeditor/ckeditor5/issues/952. Please let us know if if [this answer](https://github.com/ckeditor/ckeditor5/issues/952#issuecomment-379767264) fixes your use case.

**Comment by kinju4374** [comment] 2021-09-20 08:57
Thanks, @FilipTokarski I have added the same CSS and it works fine now.

**Closed** 2021-09-20 08:58 UTC
Labels: type:bug, pending:feedback
