### ISSUE TITLE
how  can I define an interface like AutosaveAdapter receive config callback function

### ISSUE THREAD

**Issue by LouisMing** [ckeditor/ckeditor5#1688] opened 2019-04-08 03:03 UTC
## Is this a bug report or feature request? (choose one)

 🆕 Feature request  

## 📋 Steps to reproduce

1.i want develop a plugin like 'autosave', it's a button could save page data to service.but getting the callback function is difficute for me .plz help me  thx
2.

**Comment by Mgsy** [comment] 2019-04-08 07:18
> want develop a plugin like 'autosave', it's a button could save page data to service

Hi, did you check our [getting and saving data guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html)? You'll find there a few ways how to save the content to your service.

**Comment by Mgsy** [comment] 2019-04-10 08:42
Actually, it's a duplicate of https://github.com/ckeditor/ckeditor5/issues/1687.

**Closed by Mgsy** 2019-04-10 08:42 UTC
Labels: status:pending
