### ISSUE TITLE
Pasting content with headings and tables from google docs results in multiple UI discrepancies  

### ISSUE THREAD

**Issue by balzzac** [ckeditor/ckeditor5#10158] opened 2021-07-15 03:26 UTC
## 📝 Provide detailed reproduction steps (if any)

1. In google docs recreate a structure
<img width="1254" alt="Screen Shot 2021-07-14 at 8 24 38 PM" src="https://user-images.githubusercontent.com/25731726/125724340-c348dbc6-bb27-4026-b565-70b6775edea5.png">
<img width="1299" alt="Screen Shot 2021-07-14 at 8 24 42 PM" src="https://user-images.githubusercontent.com/25731726/125724462-384473b4-82cf-437e-b7a1-0c9593e35052.png">

2. Paste to https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html example editor

### ✔️ Expected result

This feature allows you to paste content from Google Docs and maintain the original structure and formatting. After creating a document in Google Docs you can simply copy it to CKEditor 5 and retain basic text styling, heading levels, links, lists, tables and images.

### ❌ Actual result

Headings are inline aligned with the tables
Tables don't retain column width
Content vertical spacing is increased
<img width="1253" alt="Screen Shot 2021-07-14 at 8 24 13 PM" src="https://user-images.githubusercontent.com/25731726/125724405-93a3734d-202a-42ae-9571-9b9e99910adf.png">
<img width="1276" alt="Screen Shot 2021-07-14 at 8 24 20 PM" src="https://user-images.githubusercontent.com/25731726/125724412-51f76d0e-2c91-47ed-9673-cfa97922be5c.png">

## 📃 Other details

* Browser: Google Chrome is up to date
Version 91.0.4472.114 (Official Build) (x86_64)
* OS: MacOS Catalina 10.17.7
* First affected CKEditor version: not sure
* Installed CKEditor plugins: not sure what is installed in here https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-google-docs.html 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-07-28 09:28
Hi, thanks for the report. It's seems to be a regression since `26.0.0`, [it's being tracked here](https://github.com/ckeditor/ckeditor5/issues/10217). I'll close this as a duplicate

**Closed by FilipTokarski** 2021-07-28 09:28 UTC
Labels: type:bug
