### ISSUE TITLE
[Chrome, Safari] Pressing delete on empty editor breaks an interline

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#459] opened 2017-06-05 14:11 UTC
## Steps to reproduce
1. Open a sample.
2. Select whole content with <kbd>CTRL</kbd> + <kbd>A</kbd> and press <kbd>Delete</kbd>.
3. Press <kbd>Delete</kbd> once again (<kbd>Fn</kbd>+<kbd>Delete</kbd> on macOS).
4. Type something, i.e. "test".
5. Press <kbd>Backspace</kbd> few times.

## Current result
- Editor's height changes
- Caret moves upward ignoring an interline
- <kbd>Backspace</kbd> returns correct position and deletes word from step 4.

## Notes
Bug isn't reproducable on https://ckeditor5.github.io/

## GIF
![bug](https://cloud.githubusercontent.com/assets/20988892/26787213/801c6544-4a09-11e7-83b5-dcfab8f43290.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Opera
Release: 0.10.0

**Comment by Reinmar** [comment] 2017-06-21 19:46
I'm not able to reproduce it. Could you test it again? I'm afraid that you tested it on some incomplete manual test.

**Comment by Mgsy** [comment] 2017-06-22 10:10
@Reinmar, I checked it once again and I'm still able to reproduce it (on my local build and `/ckeditor5-presets/tests/manual/article.html` preset).

I wonder, as you are a Mac user, do you use <kbd>Fn</kbd> + <kbd>Delete</kbd> combination while performing step 3?

**Comment by Reinmar** [comment] 2017-06-22 13:20
OK, I forgot that by <kbd>Delete</kbd> you mean "forward delete" when checking on Windows/Linux.

I can confirm this issue.

**Comment by pomek** [comment] 2017-07-28 10:25
I'm trying to reproduce this issue on my latest Safari (10.1.2 (12603.3.8)) but everything works.

**Comment by Reinmar** [comment] 2017-07-28 10:40
Hm... Interesting. I don't know when we fixed this – we'd need to do a bisect because it all works even before https://github.com/ckeditor/ckeditor5-engine/issues/1012.

But I wasn't able to reproduce any similar issues now, so let's close this. Something may still be buggy, but let's not chase it while it's not visible at all.

**Closed by Reinmar** 2017-07-28 10:40 UTC
Labels: candidate:1.0.0, module:engine, module:typing, status:confirmed, type:bug
