### ISSUE TITLE
Cannot tab out of CKEditor 5 if a table is displayed

### ISSUE THREAD

**Issue by pkliesch** [ckeditor/ckeditor5#13308] opened 2023-01-19 17:21 UTC
## 📝 Provide detailed reproduction steps (if any)

Setup:
Just open any editor with the table plugin enabled.
Simply add a table via the toolbar button.

Usually you can `[tab]` over the editor via keyboard navigation just like anywhere else in the browser.
The first `[tab]` jumps into the editor, the next `[tab]` leaves the editor and focuses the next element on the page.

This behavior changes if a table is displayed in the editor. Whenever a table is present, the next tab will focus the first table cell. And it is also not possible to just tab through the table and reach the end, because pressing tab just adds cells when you react the last table cell.

This may break accessibility requirements on websites with CKEditor 5.

### ✔️ Expected result

Press `[tab]` to jump into the editor. Press `[tab]` again to jump out.

### ❌ Actual result

Press `[tab]` to jump into the editor. Next `[tab]` jumps into the first table cell. If you keep on pressing `[tab]`, more and more table cells appear but you cannot jump out of the editor again. (You can use `[shift] + [tab]` but you can never reach elements after the editor)

### ❓ Possible solution

Don't use `[tab]` to focus any tables in the editor.

## 📃 Other details

The described behavior can be observed in the online demo:
https://ckeditor.com/ckeditor-5/demo/feature-rich/

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2023-02-07 12:32
Looks like a duplicate of https://github.com/ckeditor/ckeditor5/issues/11834 and https://github.com/ckeditor/ckeditor5/issues/1709 combined.

**Comment by ilapavuluri** [comment] 2024-02-08 05:21
Waiting for this fix, this is very crucial for accessibility users, appreciate if someone let us know when this will be available?

Thanks
Ashok.

**Comment by Witoso** [comment] 2024-02-08 07:47
Closing as duplicate of https://github.com/ckeditor/ckeditor5/issues/11834 and https://github.com/ckeditor/ckeditor5/issues/1709.

**Closed by Witoso** 2024-02-08 07:47 UTC
Labels: type:bug, support:2
