### ISSUE TITLE
Strange behaviour with inline images inside numbered list

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#10450] opened 2021-08-30 14:59 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Create a numbered list with two items
2. Create a 3rd item or hit shift+enter in order to go to the next line without creating a new numbered item
3. Add an image on number 3 or the blank line

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

Bug 1 - Icons for creating a new paragraph before/after the image are not available.

Those are available if you just add an image to a blank description.

Bug 2 - on Firefox (78.11.0esr), after adding an image in the bulleted list, you are not able to click anywhere meaning you cannot continue with the bulleted list.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: Windows
* First affected CKEditor version: Latest (v29)
* Installed CKEditor plugins: 
// Plugins to include in the build.
Editor.builtinPlugins = [
    Autoformat,
	BlockQuote,
	Bold,
	Code,
	CodeBlock,
	Essentials,
	FontBackgroundColor,
	FontColor,
	FontFamily,
	FontSize,
	Heading,
	Image,
	ImageCaption,
	ImageResize,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Italic,
    Link,
    AutoLink,
	List,
	Mention,
	Paragraph,
	PasteFromOffice,
	RemoveFormat,
	SimpleUploadAdapter,
	Strikethrough,
	Table,
	// TableCellProperties,
	// TableProperties,
	TableToolbar,
    Underline,
    Comments,
	// TrackChanges,
	MediaEmbed,
    LinkImage,
    Alignment,
    TodoList,

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-09-22 07:52
Hi, thanks for the report and sorry for the late reply. 

As it comes to _Bug 1_ - inline images serve a different purpose than block images and do not have buttons for inserting paragraphs before/after by design. So I would not consider this as a bug, unless I did not understand correctly what you meant. 
Now, as it comes to _Bug 2_ - indeed there is an issue in Firefox. The caret is missing and in order to use it again, you need to select the image, press `arrow right` and then start typing. It's also not limited to lists, but occurs in general when there is no other content after the image.

I extracted the second issue here: https://github.com/ckeditor/ckeditor5/issues/10575 and will close this one, just to keep things clear.

**Closed by FilipTokarski** 2021-09-22 07:52 UTC
Labels: type:bug
