### ISSUE TITLE
Broken documentation links to source code after monorepo migration

### ISSUE THREAD

**Issue by rshipp** [ckeditor/ckeditor5#7265] opened 2020-05-21 18:09 UTC
I noticed this "See source" link in the table docs is broken; not sure how many others there might be: https://ckeditor.com/docs/ckeditor5/latest/api/module_table_tableediting-TableEditing.html

**Comment by Reinmar** [comment] 2020-05-22 06:30
Thanks! We're on it.

**Comment by mlewand** [comment] 2020-05-22 11:17
@pomek isn't it a duplicate of #6763?

**Comment by pomek** [comment] 2020-05-22 11:23
No, it's a different URL. The issue describes URLs in API Docs while #6763 is about "Contribute to the guide".

**Comment by Reinmar** [comment] 2020-05-25 13:14
Fixed staging, should be fixed on prod tomorrow.

**Closed by Reinmar** 2020-05-25 13:14 UTC
Labels: squad:devops, type:docs
