### ISSUE TITLE
Hello, I found a problem with the code

### ISSUE THREAD

**Issue by gongzhiq** [ckeditor/ckeditor5#1319] opened 2018-10-19 02:54 UTC
My version of ckeditor5 is v11.1.1, and the code is as follows:

```
const model = editor.model;
const doc = editor.model.document;

doc.on( 'change:data', () => {
    const changes = doc.differ.getChanges();

    model.change( writer => {
        for ( const entry of changes ) {
            if ( entry.type == 'insert' && entry.name == 'image' ) {
                const image = entry.position.nodeAfter;
                const paragraph = writer.createElement( 'paragraph' );

                writer.insert( paragraph, image, 'after' );
            }
        }
    } );
} );
```

![small4](https://user-images.githubusercontent.com/5800062/47195760-e032a680-d38f-11e8-9571-1182c0e966c8.gif)

All newly added paragraphs are below the first picture.I want to under each picture.

**Comment by ma2ciek** [comment] 2018-10-19 09:12
Duplicate of https://github.com/ckeditor/ckeditor5/issues/1255. The answer for the current codebase is written later in this thread.

**Closed by ma2ciek** 2018-10-19 09:12 UTC
