### ISSUE TITLE
lag when typing fast using react component

### ISSUE THREAD

**Issue by farshad-abb** [ckeditor/ckeditor5#8240] opened 2020-10-10 15:32 UTC
## 📝 Provide detailed reproduction steps (if any)

1. use [react component of CKEditor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)
2. use **editor.getData()** in **onChange** event to get the content of CKEditor5 whenever it changes to save it in a state

### ✔️ Expected result

_What is the expected result of the above steps? 
we face an annoying lag when typing fast.
I debugged the code and I found out that when we do not use the getData method we don't have this lag. and I found out that the getData method has (**50-100 miliseconds**) delay and that is why we have this lag when typing fast.

**is there any other way rather than using onchange and getData to retrieve the current content of the CKEditor and save it in a state?**

**Comment by FilipTokarski** [comment] 2020-10-12 07:17
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/8239.

**Closed by FilipTokarski** 2020-10-12 07:17 UTC
Labels: type:bug
