### ISSUE TITLE
Build Error showing ( Works fine in Dev version ) in NextJs

### ISSUE THREAD

**Issue by RetiFier** [ckeditor/ckeditor5#8266] opened 2020-10-15 13:22 UTC
The problem is when we try to run build mode of Next JS which includes CK Editor, it shows the following error.
`> Build error occurred
ReferenceError: window is not defined
    at Object.<anonymous> (D:\Project\Reallyy\reallyy-client\node_modules\@ckeditor\ckeditor5-react\dist\ckeditor.js:5:244)`

This error doesn't exist in development version. It works all the fine in our development server but once we try to build it, things go nasty this way. Couldn't figure out a way to solve yet. Thanks in advance. :))

**Comment by FilipTokarski** [comment] 2020-10-16 12:26
Duplicate of https://github.com/ckeditor/ckeditor5-react/issues/191. Closing.

**Closed by FilipTokarski** 2020-10-16 12:26 UTC
Labels: type:bug

**Comment by Yondo202** [comment] 2021-06-22 05:41
baba

**Comment by Yondo202** [comment] 2021-06-22 05:42
Duplicate of ckeditor/ckeditor5-react#191.
