### ISSUE TITLE
Can code block auto formatting support select language? 

### ISSUE THREAD

**Issue by frankcbliu** [ckeditor/ckeditor5#9560] opened 2021-04-26 07:12 UTC
## 📝 Provide a description of the new feature

Now, we can use ` ``` ` to quickly create a code block, but the code block's language is default value, like this:

![image](https://user-images.githubusercontent.com/36353894/116042377-e876a580-a6a0-11eb-9121-4486f6f51d4b.png)

if i want to change language, i must use mouse to click the code block button to modify.

In my opinion,  this way may be a better chioce:
1. type ` ```c++` 
2. type `Enter`

and then, will get a code block like this:

![image](https://user-images.githubusercontent.com/36353894/116042674-45725b80-a6a1-11eb-8954-35dac66a235d.png)

also, if i want a default code block, just type` ``` ` and `Enter`.

Because using the mouse will interrupt my editing, i think this way can get a better edit experience.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-06-30 12:37
lt's a duplicate of https://github.com/ckeditor/ckeditor5/issues/8437.

**Closed by FilipTokarski** 2021-06-30 12:37 UTC
Labels: type:feature
