### ISSUE TITLE
Incorrect styles on source editing text area on GHS docs page

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#10037] opened 2021-07-01 10:26 UTC
### Steps:

1. Open general-html-support docs page.
2. Use dev tools to simulate mobile viewport.
3. Open source editing.

### Result:
The source text area is wider than viewport and it's not possible to scroll horizontally to see the whole content.
![image](https://user-images.githubusercontent.com/58658048/124109388-5bb4e300-da67-11eb-836a-bcb363eed9ed.png)

### Notes:
- this is not a case on the source-editing docs page, as there source editing text area is scaled properly

**Comment by godai78** [comment] 2021-08-20 12:46
It allows me to scroll horizontally in the first demo.

![](https://user-images.githubusercontent.com/68123541/130235246-e44f403b-51db-4dcf-be85-4ca799d21831.png)

It scales correctly for me on Chrome/mac in the second demo.

![](https://user-images.githubusercontent.com/68123541/130235304-c1593347-0b0e-4232-8660-53c527beb3f1.png)

This MAY have something to do with the max-height parameter. I'll try looking into it.

**Comment by FilipTokarski** [comment] 2021-09-20 09:17
We checked it once again and could not reproduce this issue. Closing this for now.

**Closed by FilipTokarski** 2021-09-20 09:17 UTC
Labels: type:bug, type:docs, squad:ccx
