### ISSUE TITLE
Unable to visually select more than one cells in the table

### ISSUE THREAD

**Issue by brucebrit** [ckeditor/ckeditor5#6140] opened 2020-01-26 02:32 UTC
Hi,
At the https://ckeditor.com/ckeditor-5/demo/, i try playing with this editor. I create a table, and tries to interactively select more than one cell, but it seems not possible.  
Is this a bug? Or is it meant to be this way?  if it is the latter, then I would say that this would make the usability of the table low.  

Note that ckeditor-4 does not experience such issue.  So I am more incline to think that the aforementioned could be a bug.

**Comment by mlewand** [comment] 2020-01-27 09:13
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/3202.

I have some good news, as we're going to start working on this in iteration 30th, although it will be challenging and time consuming task. Be sure to subscribe to mentioned task to get the updates.

**Closed by mlewand** 2020-01-27 09:13 UTC
Labels: type:bug
