### ISSUE TITLE
Issue with <br> and codeblock

### ISSUE THREAD

**Issue by ElliottBrand** [ckeditor/ckeditor5#6065] opened 2020-01-11 21:56 UTC
## 📝 Provide detailed reproduction steps (if any)

When I write code into a codeblock, everything looks fine. It is adding a `<br>` tag whenever I add a new line of code into the codeblock area of the editor. I save it and it displays in the post fine.

`public void ItsFineTheFirstTime(){`
 `    var SomeVar = GetSomething();`
`}`

 However, when I go back to edit the post, it seems the editor is forcing the `<br>` that was saved in the codeblock to create a new line to be displayed as code, instead of just adding a new line. So this is what I see when editing:

`public void ItsFineTheFirstTime(){   <br>var SomeVar = GetSomething();<br>}`

**Comment by ElliottBrand** [comment] 2020-01-12 01:00
This isn't a solution for most people, but for me, I searched through the code and adjusted the end of the coverters.js file to:
```
function extractDataFromCodeElement( stringifiedElement ) {
	const data = new RegExp( /^<code[^>]*>([\S\s]*)<\/code>$/ ).exec( stringifiedElement )[ 1 ];

	return data
		.replace( /&lt;/g, '<' )
		.replace(/&gt;/g, '>')
		.replace(/<br>/g, '\n');
}
```
I added the last .replace line to replace <br> with \n. This works fine for me, as I'll just use <br/> if I want to mention the br tag in an HTML code block...which would be rare, if ever.

**Comment by Mgsy** [comment] 2020-01-14 09:12
Hi! I'm not able to reproduce your issue. Could you please provide exact steps to reproduce and information how you save/load your data?

**Comment by ElliottBrand** [comment] 2020-01-16 00:14
It may very well be something to do with the way I've implemented it then. I'm using Asp.Net Core 3.1 and the latest version of Firefox. 

Since the editor loads in a div, I wrote some JavaScript to copy the contents of the div into a hidden input (in the View) on keyup. 
```
$('#editor').on('keyup', function () {
    $('#Article').attr('value', $('#editor').html());
});
```
This is the only way I saw to pass the text back to the Controller. Then, when used in an edit view I just load the contents into the editor div.

```
<div id="editor" class="editordiv">@Html.Raw(Model.Article)</div>
<input hidden="hidden" asp-for="Article" />
```
However, all I need to do is manually enter something like
```
<pre><code>test<br>test</code></pre>
```
directly into the editor div code and it renders with `<br>` showing in the code area instead of just moving it to the next line like it would outside the code tag. I'm guessing the JS must be converting all tags within the code tags. If I enter this into the editor div: `test<br>test<pre><code>test<br>test</code><pre>` it results in:
test
test
test`<br>`test

So, like I mentioned before, all I did was adjust the end of the extractDataFromCodeElement function in the \ckeditor5-build-balloon-block\node_modules\@ckeditor\ckeditor5-code-block\src\converters.js file to the following:
```
function extractDataFromCodeElement( stringifiedElement ) {
	const data = new RegExp( /^<code[^>]*>([\S\s]*)<\/code>$/ ).exec( stringifiedElement )[ 1 ];

	return data
		.replace( /&lt;/g, '<' )
		.replace(/&gt;/g, '>')
		.replace(/<br>/g, '\n')
		.replace(/&amp;/g, '&');
}
```
and it's working fine for me now. I also added that last line after my post, since I needed to be able to display the ampersand within code examples that contained query strings. I realize this isn't a perfect solution, since if anyone tried to insert `<br>` into an html code example it would cause a new line instead of displaying, but I always close it like `<br />`, so it won't affect me.

**Comment by Mgsy** [comment] 2020-01-16 08:49
Thanks for the details. As I can see you don't use the editor's API for getting and setting data. You can get the editor's HTML by calling [`editor.getData()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-getData). Also, CKEditor 5 exposes [events](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_document-Document.html#event-event:keyup) which could be used for your case. Please, see the example below:
```js
editor.editing.view.document.on( 'keyup', () => {
    console.log( editor.getData() ); // returns editor's HTML
} );
```
If you use the code blocks plugin, you'll notice that returned HTML doesn't contain `<br>` (but those are present in DOM thanks to the conversion) and after setting the data back to the editor by using [`editor.setData()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-classic_classiceditor-ClassicEditor.html#function-setData), `<br>` is rendered correctly inside the code block instead of displaying as text.

Let me know if using the editor's API solved your problem.

**Comment by ElliottBrand** [comment] 2020-01-18 20:20
If I use editor.getData() and editor.setData(), it removes the `<br>` tag that's in the DOM, but when the value is copied into the input tag (with id of Article), it saves it without a `<br>` or any kind of line break. So my code ends up displaying without line breaks inside the code block area.

```
    BalloonEditor
        .create(document.querySelector('#editor'), {
            link: {
                decorators: {
                    addTargetToLinks: {
                        mode: 'manual',
                        label: 'Open in a new tab',
                        attributes: {
                            target: '_blank',
                            rel: 'noopener noreferrer'
                        }
                    }
                }
            },
            codeBlock: {
                languages: [
                    { language: 'plaintext', label: 'Plain text' }, // The default language.
                    { language: 'c', label: 'C' },
                    { language: 'cs', label: 'C#' },
                    { language: 'cpp', label: 'C++' },
                    { language: 'css', label: 'CSS' },
                    { language: 'diff', label: 'Diff' },
                    { language: 'xml', label: 'HTML/XML' },
                    { language: 'java', label: 'Java' },
                    { language: 'javascript', label: 'JavaScript' },
                    { language: 'php', label: 'PHP' },
                    { language: 'python', label: 'Python' },
                    { language: 'ruby', label: 'Ruby' },
                    { language: 'typescript', label: 'TypeScript' },
                ]
            }
        })
        .then(editor => {
            editor.editing.view.document.on('keyup', () => {
                $('#Article').val(editor.getData());
                console.log(editor.getData());
            });
            editor.setData($('#Article').val());
        })
        .catch(error => {
            console.error(error);
        });
```

**Comment by Mgsy** [comment] 2020-01-20 10:39
>If I use editor.getData() and editor.setData(), it removes the <br> tag that's in the DOM, but when the value is copied into the input tag (with id of Article), it saves it without a <br> or any kind of line break.

Are you sure that your input allows line breaks? If you use, for example, `<input type="text">` it will remove line breaks because this element doesn't allow them. Can you try to use `<textarea>` for storing your content?

**Comment by ElliottBrand** [comment] 2020-01-20 23:35
Sorry, I should have noticed that. Changing the input to textarea does allow line breaks to work. I am still seeing the ampersand (&) in query strings get converted to `&amp;` unless I add `.replace(/&amp;/g, '&');` to the extractDataFromCodeElement function in the ckeditor5-code-block converters.js file.

**Comment by Mgsy** [comment] 2020-01-21 08:42
I'm glad it solved your issue :)

> I am still seeing the ampersand (&) in query strings get converted to &amp;

We're aware of this problem - right now HTML entities are displayed in a code block - https://github.com/ckeditor/ckeditor5/issues/5901. 

As the main issue has been solved, I'm closing this one.

**Closed by Mgsy** 2020-01-21 08:42 UTC
Labels: pending:feedback, type:question
