### ISSUE TITLE
Incorrect behavior after link decorator was deleted

### ISSUE THREAD

**Issue by B4rtes** [ckeditor/ckeditor5#8355] opened 2020-10-27 12:05 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open CKEditor 5 documentation with extending output (the [link](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-extending-output.html) )
2. Scroll to _Adding a CSS class to inline elements_ section
3. Press unlink button for the selected link
![image](https://user-images.githubusercontent.com/73192848/97298641-c7a1d480-1864-11eb-8b8e-d386ad05e7cc.png)

### ✔️ Expected result

Decorator should disappear. Selected text is not link anymore.

### ❌ Actual result

Looks like text is not link anymore. But decorator didn't disappear. Strange select behavior.
![image](https://user-images.githubusercontent.com/73192848/97298893-28c9a800-1865-11eb-9d84-2a35c807c275.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2020-10-27 12:35
Hi, thanks for the report. It's a duplicate of https://github.com/ckeditor/ckeditor5/issues/6385, so I'll close this ticket.

**Closed by FilipTokarski** 2020-10-27 12:35 UTC
Labels: type:bug
