### ISSUE TITLE
 Error when selecting including table merge cells

### ISSUE THREAD

**Issue by topi09** [ckeditor/ckeditor5#13123] opened 2022-12-21 01:45 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Create a 3*3 table
2. Merge the bottom two lines on the right.
3. Select an area by dragging the mouse from the top left to the bottom right

### ✔️ Expected result

_What is the expected result of the above steps?_

**The entire table area must be selected**

### ❌ Actual result

_What is the actual result of the above steps?_

**tr under merged td not selected**

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

![image](https://user-images.githubusercontent.com/121141493/208800905-d2fa13cd-c958-41ee-9db5-438fd3d0c8c1.png)

* Browser: chrome
* OS: Window10
* First affected CKEditor version: …
* Installed CKEditor plugins: …@29.1.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2022-12-21 11:09
This is by design, it is how the current table implementation behaves. To select all cells in this case, you need to start from bottom-left or top-right.
Closing as this is not a valid bug report.

**Closed by FilipTokarski** 2022-12-21 11:09 UTC
Labels: type:bug
