### ISSUE TITLE
Heading styles are inconsistent from ckeditor headings vs headings pasted from google docs

### ISSUE THREAD

**Issue by tista-chatterjee** [ckeditor/ckeditor5#11340] opened 2022-02-25 07:45 UTC
See image:

Bold H1 test - content that has been typed directly into CKEditor (H1).

Non-bold 'Google Docs - Test Content for UAT' - content that has been pasted from Google Docs, then an H1 tag applied to the words.
<img width="767" alt="ckeditor heading" src="https://user-images.githubusercontent.com/91665085/155675392-95c112dc-ad34-4702-a478-53fcfdca3590.png">

Expectation would be that all content displays the same:

**Comment by FilipTokarski** [comment] 2022-03-09 12:36
Hi, thanks for the report. It's a duplicate of https://github.com/ckeditor/ckeditor5/issues/11339. 
I'll close this one and let's continue the discussion there.

**Closed by FilipTokarski** 2022-03-09 12:36 UTC
Labels: type:bug
