### ISSUE TITLE
[FF][Firefox][IME] Left arrow breaks Japanese (Hiragana) composition in some cases

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#973] opened 2018-04-17 13:23 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Checked on `v0.10.0`, `alpha.1` and `beta.2`

## 📋 Steps to reproduce

1. Go to https://ckeditor5.github.io/.
1. Start typing Hiragana.
1. Navigate with <kbd>up</kbd>/<kbd>down</kbd> arrow to change composed text.
1. Type few characters more (we need to create situations in which composition can be partially changed so you can navigate with <kbd>left</kbd>/<kbd>right</kbd> arrow inside it).
1. Press <kbd>left</kbd> arrow few times.

_Looks like steps 3. and 4. could be skipped, just press <kbd>left</kbd> arrow few times after typing and it should break composition too._

## ✅ Expected result

Selection should move to the beginning of the composition and stay there.

## ❎ Actual result

Composition gets broken.

![jp hiragana ff](https://user-images.githubusercontent.com/1061942/38872159-ded54e06-4252-11e8-9cb0-f18bcc48afa6.gif)

## 📃 Other details that might be useful

Firefox `59.0.2 (64-bit)` on macOS `10.13.3`.

**Comment by f1ames** [comment] 2018-06-20 11:43
Changed the description because it said <kbd>right</kbd> arrow and in fact it is caused by <kbd>left</kbd> arrow 🤔 

Retested on Firefox `60.0.2 (64-bit)` and `v10.0.1`, still occurs:

![japanese ff 2](https://user-images.githubusercontent.com/1061942/41656300-c4b49e5e-748f-11e8-90fc-7e4fb6bb670e.gif)

**Comment by FilipTokarski** [comment] 2020-03-17 09:59
Checked it on Firefox 74.0 (64-bit) on [demo page](https://ckeditor.com/ckeditor-5/demo/#classic) and `article manual test` on latest master. I cannot reproduce this anymore - composition in Hiragana works fine and navigating with arrows ( especially left ) works as expected. I'm closing this.

**Closed by FilipTokarski** 2020-03-17 09:59 UTC
Labels: browser:firefox, domain:ime, package:typing, status:confirmed, type:bug
