### ISSUE TITLE
Ckeditor5 editor.setData() issue

### ISSUE THREAD

**Issue by rathiayush** [ckeditor/ckeditor5#1920] opened 2019-07-29 08:20 UTC
🐞 Bug report  
## 📋 Steps to reproduce

1. Add table 2*2 in editor

<figure class="table"><table><tbody><tr><td>ABC</td><td><br data-cke-filler="true"></td></tr><tr><td><br data-cke-filler="true"></td><td><br data-cke-filler="true"></td></tr></tbody></table></figure><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p>
2. Get Data through editor.getData()

- getData will return HTML string with some br tags inside it

In my case it has returned:-
```
<figure class="table"><table><tbody><tr><td>1</td><td><br data-cke-filler="true"></td></tr><tr><td><br data-cke-filler="true"></td><td><br data-cke-filler="true"></td></tr></tbody></table></figure><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p><p style="text-align:center;"><br data-cke-filler="true"></p>
```

**NOTE:-** I am saving sanitized string in db and reteriveing HTML string as same as above

4. On page load i am setting above HTML string in ckeditor through editor.setData()

## ✅ Expected result
The table with contents should set to ckeditor

## ❎ Actual result
Js is breaking at xmldataprocessor.js 
`const parsedDocument = this._domParser.parseFromString( data, 'text/xml' );`
with error msg:-
"Parse error - This page contains the following errors:error on line 1 at column 93: Opening and ending tag mismatch: br line 0 and td
Below is a rendering of the page up to the first error."

**Comment by Mgsy** [comment] 2019-07-29 13:59
I'm not able to reproduce your issue. Can you paste your editor configuration code and `package.json`?

**Comment by rathiayush** [comment] 2019-07-30 06:21
Hello @Mgsy ,

It is working fine with ckeditor5-build-classic but i am facing this issue when adding new plugins in classsic build.
here is my package.json


{
  "name": "@ckeditor/ckeditor5-build-classic",
  "version": "12.3.1",
  "description": "The classic editor build of CKEditor 5 – the best browser-based rich text editor.",
  "keywords": [
    "ckeditor5-build",
    "ckeditor",
    "ckeditor5",
    "ckeditor 5",
    "wysiwyg",
    "rich text",
    "editor",
    "html",
    "contentEditable",
    "editing",
    "operational transformation",
    "ot",
    "collaboration",
    "collaborative",
    "real-time",
    "framework"
  ],
  "main": "./build/ckeditor.js",
  "files": [
    "build"
  ],
  "devDependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^11.0.4",
    "@ckeditor/ckeditor5-autoformat": "^11.0.4",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.3",
    "@ckeditor/ckeditor5-block-quote": "^11.1.2",
    "@ckeditor/ckeditor5-ckfinder": "^11.0.4",
    "@ckeditor/ckeditor5-core": "^12.2.1",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.0",
    "@ckeditor/ckeditor5-easy-image": "^11.0.4",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.3",
    "@ckeditor/ckeditor5-essentials": "^11.0.4",
    "@ckeditor/ckeditor5-heading": "^11.0.4",
    "@ckeditor/ckeditor5-image": "^13.1.2",
    "@ckeditor/ckeditor5-link": "^11.1.1",
    "@ckeditor/ckeditor5-list": "^12.0.4",
    "@ckeditor/ckeditor5-media-embed": "^11.1.3",
    "@ckeditor/ckeditor5-paragraph": "^11.0.4",
    "@ckeditor/ckeditor5-paste-from-office": "^11.0.4",
    "@ckeditor/ckeditor5-table": "^13.0.2",
    "@ckeditor/ckeditor5-theme-lark": "^14.1.1",
    **"@ckeditor/ckeditor5-alignment": "^11.1.3",
    "@ckeditor/ckeditor5-font": "^11.2.1",
    "@ckeditor/ckeditor5-indent": "^10.0.1",
    "@ckeditor/ckeditor5-remove-format": "^10.0.3",
    "@wiris/mathtype-ckeditor5": "^7.15.0",**
    "eslint": "^5.5.0",
    "eslint-config-ckeditor5": "^2.0.0",
    "husky": "^1.3.1",
    "lint-staged": "^7.0.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^1.0.0",
    "style-loader": "^0.23.0",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "webpack": "^4.15.0",
    "webpack-cli": "^3.0.8"
  },
  "engines": {
    "node": ">=8.0.0",
    "npm": ">=5.7.1"
  },
  "author": "CKSource (http://cksource.com/)",
  "license": "GPL-2.0-or-later",
  "homepage": "https://ckeditor.com/ckeditor-5",
  "bugs": "https://github.com/ckeditor/ckeditor5-build-classic/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/ckeditor/ckeditor5-build-classic.git"
  },
  "scripts": {
    "build": "webpack --mode production",
    "lint": "eslint --quiet '**/*.js'",
    "preversion": "npm run build; if [ -n \"$(git status src/ckeditor.js build/ --porcelain)\" ]; then git add -u src/ckeditor.js build/ && git commit -m 'Internal: Build.'; fi"
  },
  "lint-staged": {
    "**/*.js": [
      "eslint --quiet"
    ]
  },
  "eslintIgnore": [
    "build/**",
    "packages/**"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }
}


**### I am adding few devDependencies in package.json.
and here is ckeditor.js**


import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import Font from '@ckeditor/ckeditor5-font/src/font';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import MathType from '@wiris/mathtype-ckeditor5/src/plugin';

export default class ClassicEditor extends ClassicEditorBase {}

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
	Essentials,
	UploadAdapter,
	Autoformat,
	Bold,
	Italic,
	BlockQuote,
	CKFinder,
	EasyImage,
	Heading,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	Font,
	Underline,
	Alignment,
	RemoveFormat,
	Indent,
	IndentBlock,
	MathType
];

// Editor configuration.
ClassicEditor.defaultConfig = {
	toolbar: {
		items: [
			'removeFormat',
			'bold',
			'Italic',
			'Underline',
			'fontSize',
			'heading',
			'|',
			'alignment:left', 'alignment:right', 'alignment:center', 'alignment:justify',
			'indent', 'outdent',
			'insertTable',
			'undo',
			'redo',
			'MathType',
			'ChemType',
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	fontSize: {
		options: [
			9,
			11,
			13,
			'default',
			17,
			19,
			21
		]
	},

	language: 'en'
	// This value must be kept in sync with the language defined in webpack.config.js.

};

**I hope now you will be able to reproduce.**

**Comment by rathiayush** [comment] 2019-07-30 09:48
@Mgsy , I think @wiris/mathtype-ckeditor5": "^7.15.0 is causing problem. After removing this it is working fine.

**Comment by Mgsy** [comment] 2019-07-30 11:09
I've checked your code and indeed, this behaviour occurs because of MathType. The issue should be fixed on the MathType side.

**Comment by wwalc** [comment] 2019-07-31 07:11
We're in touch with WIRIS and working already on fixing the issue.

**Comment by rathiayush** [comment] 2019-07-31 08:27
> We're in touch with WIRIS and working already on fixing the issue.

sounds great @wwalc ,Thanks

**Comment by rathiayush** [comment] 2019-08-20 11:15
@mlewand @Mgsy Any update on this issue?

**Comment by mlewand** [comment] 2019-08-30 13:00
I'm sorry, but looks like there has been a bit confusion here. Based on the original issue I'm not sure what issue are we talking about, as the original bug report mentioned **two** issues in a single issue.

* One problem was that adding `mathtype` plugin would cause an exception to be thrown when setting the data (and I take this as main issue as it's mentioned in issue title and is more severe). _This issue has been fixed in the latest mathtype release._
* Another problem mentioned is that mathtype plugin is adding extra `br` elements, that would otherwise not be added by the editor. It got it's own issue #2013.

**Closed by mlewand** 2019-08-30 13:00 UTC
Labels: package:mathtype, status:confirmed, type:bug

**Comment by arvindmittal** [comment] 2020-02-10 12:41
i was getting : **Opening and ending tag mismatch:**

_I replaced ending tag, and resolved_
`bookEditor.setData( myContent.replace('</math></math>', '</math>') );`
