### ISSUE TITLE
Table style is lost when pasting content containing tables from Google Docs.

### ISSUE THREAD

**Issue by zoomkoding** [ckeditor/ckeditor5#15193] opened 2023-10-18 03:52 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Copy content containing a table from Google Docs.
2. Paste it to the editor.

https://github.com/ckeditor/ckeditor5/assets/36878344/d8fcab9c-dd76-4279-9a39-6e6729efe191

### ✔️ Expected result

_What is the expected result of the above steps?_
The table style from Google Docs remains.

### ❌ Actual result

_What is the actual result of the above steps?_
The table style is lost.(ex. alignment, width)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome
* Installed CKEditor plugins: 4.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-10-20 08:57
Duplicate of #12023.

**Closed by Witoso** 2023-10-20 08:57 UTC
Labels: type:bug, package:paste-from-office, domain:ui/ux
