### ISSUE TITLE
Autosave is triggered too often with Track Changes/Comments enabled

### ISSUE THREAD

**Issue by chaouiy** [ckeditor/ckeditor5#5796] opened 2019-11-25 14:45 UTC
same times auto save is called even if nothing changed

**Comment by Reinmar** [comment] 2019-11-25 15:17
Hi! Could you explain in what cases that happen? The feature wasn't designed to be 100% correct but you shouldn't get such situations frequently.

**Comment by chaouiy** [comment] 2019-11-25 16:01
It happens for example when you move cursor between characters using
keyboard arrow keys

**Comment by ma2ciek** [comment] 2019-11-26 18:01
Hi!

> It happens for example when you move cursor between characters using
keyboard arrow keys

I can't reproduce it on the https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#demo. Could you write the steps required to reproduce the issue?

**Comment by Reinmar** [comment] 2019-11-26 21:41
Bonus question: what keyboard layout and OS do you have?

**Comment by chaouiy** [comment] 2019-12-01 12:36
it occurs in many cases when you have change tracking active

**Comment by FilipTokarski** [comment] 2020-01-07 10:42
I tried to reproduce it on a custom editor build with real time collaboration plugins + autosave. The autosave seems to fire every time you just touch anything related to Track Changes (for example click on TC comments balloon on the right). So if you just move the caret using arrows, inside a TC selection, it fires, but if you do the same somewhere else on a plain text, nothing happens.

I also checked the docs and it says: `The autosave itself does not check whether the data has really changed. It bases on changes in the model which, in special cases, may not be “visible” in the data.`
My reasoning is that if TC plugin changes anything in the model just by moving a caret, then this seems to be a normal behaviour?

Steps:
1. Open editor with Track Changes and Autosave plugins. I used 
```
autosave: {
			save( editor ) {
				console.log( 'Autosave fired');
			}
		}
```
config, just to see when it happens.
2. Enable Track Changes and play a bit with moving the caret inside and outside the TC selections.

**Comment by ma2ciek** [comment] 2020-01-07 11:16
It looks like the `model.document#change:data` is fired when it shouldn't be. The `Autosave` plugin watches mainly this event.

cc @scofalik

**Comment by ma2ciek** [comment] 2020-01-07 11:39
> My reasoning is that if TC plugin changes anything in the model just by moving a caret, then this seems to be a normal behaviour?

Model changes do not have to indicate data changes. The Autosave plugin returns the same data after each such "click event", so it's clear that this plugin or specifically the `change:data` event should not fire when user clicks a suggestion.

**Comment by chaouiy** [comment] 2020-04-02 15:40
Any news about this bug ?

**Comment by ma2ciek** [comment] 2020-04-29 07:55
Hi,

I'm sorry for not responding.

We're focused on a few bigger features and didn't have much time to work on bug fixes, the situation should improve soon, though it's hard for me to tell the exact date.

**Comment by FilipaBarroso** [comment] 2020-09-08 14:11
I'm having the same issue. Autosave triggers if I simply click on a suggestion.

**Comment by Mgsy** [comment] 2020-10-22 11:34
Another case: `TrackChangesData#getDataWithAcceptedSuggestions()` also triggers autosave.

**Comment by FilipaBarroso** [comment] 2020-10-22 15:11
> 
> 
> Another case: `TrackChangesData#getDataWithAcceptedSuggestions()` also triggers autosave.

Having issues with that as well. Not only does it trigger autosave, it ignores the waiting time

**Comment by ma2ciek** [comment] 2020-10-23 08:16
> Having issues with that as well. Not only does it trigger autosave, it ignores the waiting time

The Autosave uses the throttling mechanism, so it can call the save function just after the data change is detected when there was no other data change in the _waitingTime_ period.

**Comment by Mgsy** [comment] 2021-03-03 08:27
It seems that comments fire `change:data` too after clicking on an item in the sidebar or moving the selection to the marker.

**Comment by scofalik** [comment] 2022-03-08 11:55
This is a duplicate of #9901 which was just closed. The fix will be available in the next CKE5 release.

**Closed by scofalik** 2022-03-08 11:55 UTC
Labels: type:bug, package:cloud-services, support:2, package:autosave, squad:cf
