### ISSUE TITLE
install plugin ,can't find icon,throw error

### ISSUE THREAD

**Issue by cathy0023** [ckeditor/ckeditor5#2057] opened 2019-09-18 07:45 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor
5
## 📋 Steps to reproduce

1.use vue,after installing @wiris/mathtype-ckeditor5
2.show this error
![image](https://user-images.githubusercontent.com/34565525/65127814-d8113a00-da2a-11e9-8576-3b849025103f.png)
can't find icon

## ✅ Expected result
show the icon successfully

**Comment by mlewand** [comment] 2019-09-18 07:56
Duplicate of #2048.

**Closed by mlewand** 2019-09-18 07:56 UTC
Labels: package:mathtype, resolution:duplicate

**Comment by duzhihao-github** [comment] 2019-09-22 06:32
#2048. I offered a temporary solution, hoping to help you。
