### ISSUE TITLE
Can I insert table with content

### ISSUE THREAD

**Issue by hh54188** [ckeditor/ckeditor5#1251] opened 2018-09-20 03:37 UTC
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

CKEditor5

## 📋 Question

I found there is an way to insert an empty table:

```javascript
editor.execute( 'insertTable', { rows: 20, columns: 5 } );
```
But how to insert a table with content ?

**Comment by jodator** [comment] 2018-09-20 11:10
You can use the [`TableUtils#createTable()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_table_tableutils-TableUtils.html#function-createTable) method to insert and create a table programmatically. The [method will be changed](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_table_tableutils-TableUtils.html#function-createTable) in upcoming release so you can use returned table to add content to it:

```js
model.change( ( writer ) => {
	// Create a table of 2 rows and 7 columns:
	const table = tableUtils.createTable( writer, 2, 7);

	// add content to the third table cell in second row paragraph:
	const firstCell = table.getChild( 1 ).getChild( 2 );
	const paragraph = firstCell.getChild( 0 );

	writer.insertText( 'foo', paragraph, 5 );

	// Insert table to the model at the best position taking current selection:
	model.insertContent( table );
}
```

Alternatively you can replace whole editor contents by using [`editor.setData()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_utils_dataapimixin-DataApi.html#function-setData) to set arbitrary markup (the passed HTML will converted to the model by supporting features - in other words it will be striped from the elements the editor isn't aware of).

**Comment by Reinmar** [comment] 2018-09-20 11:27
> `writer.insertText( 'foo', paragraph, 5 );`

Why at index `5`? When the table is empty that paragraph should be empty too.

Also, where to take the `tableUtils` from?

Also, this method will not work with the current (released) version of the table feature because it did not allow `<paragraph>`s inside table cells. So there's one more reason why the above does not work yet :D 

I'm thinking, perhaps it's easier to work on HTML for now, like shown in https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#where-are-the-editorinserthtml-and-editorinserttext-methods-how-to-insert-some-content. Working on the model gives you more precision but forces you to dig deeper into how features are represented in the model. In case of tables, this gets especially tricky due to the [inline vs block content thing](https://github.com/ckeditor/ckeditor5-table/issues/114). 

However, we can also think how to improve features like `tableUtils.createTable()` so they are used in cases like reported here. I'm thinking:

```js
tableUtils.insertInCell( contentToInsert, table, rowNum, colNum );
tableUtils.setCellContent( content, table, rowNum, colNum );
tableUtils.getCell( table, rowNum, colNum );
tableUtils.fillTable( table, [ a1, a2, b1, b2 ] );
```

etc. 

Those methods could help us with hiding the complexity caused by https://github.com/ckeditor/ckeditor5-table/issues/101. E.g. if `fillTable()` would use `model.insertContent()` then missing pargraphs or incorrect content would be correctly added/filtered out.

**Comment by jodator** [comment] 2018-09-20 11:39
@Reinmar I've forgot that this is still undergoing. The `insertText()` was copied - so I update the example.

As for the helpers - they would be awesome mostly for third-party plugins/devs to not break tables and to ease work with them.

**Comment by Reinmar** [comment] 2018-09-20 12:05
I wrote such a function which works on the current `stable` (previous release) and `master` (the next release):

```js
function insertTable( rows, columns, content ) {
	editor.model.change( writer => {
		editor.execute( 'insertTable', { rows, columns } );

		const table = editor.model.document.selection.getFirstPosition().getAncestors().find( item => item.name == 'table' );

		for ( let r = 0; r < rows; r++ ) {
			for ( let c = 0; c < columns; c++ ) {
				const cell = table.getChild( r ).getChild( c );
				const rangeWrappingCellContent = Range.createIn( cell );
				const sel = new Selection( rangeWrappingCellContent );

				const cellContent = content[ r * columns + c ];

				// I'm using `insertContent()` instead of `writer.insertText()` because it's
				// more future-proof (https://github.com/ckeditor/ckeditor5-table/issues/114).
				// Also, we use a <tableCell>[...cell content...]</tableCell> to make sure we
				// override the entire content (there can be an empty paragraph since ckeditor5@12.0.0).
				editor.model.insertContent( writer.createText( cellContent ), sel );

				// or, if `content` contains model docfrags/items:
				// editor.model.insertContent( cellContent, sel );
			}
		}
	} );
}
```

You use it like:

```js
insertTable( 2, 2, [ 'a1', 'a2', 'a3', 'a4' ] );
```

I'm going to create two tickets regarding missing things that'd improve the above code – a util for getting table from the current selection and `createRange()`/`createPosition()`/`createSelection()` utils because importing these classes just for creating those instances is irritating.

**Comment by Reinmar** [comment] 2018-09-20 15:08
I reported the following tickets: https://github.com/ckeditor/ckeditor5-table/issues/119,  https://github.com/ckeditor/ckeditor5-engine/issues/1556, https://github.com/ckeditor/ckeditor5-engine/issues/1555.

**Comment by Reinmar** [comment] 2018-11-29 12:19
I think the question was answered and we have all the followups tracked, so I'm closing this.

**Closed by Reinmar** 2018-11-29 12:19 UTC
Labels: status:pending, type:question
