### ISSUE TITLE
CK Editor 5 + Vue JS + function destroy = Memory leaks

### ISSUE THREAD

**Issue by 505141222** [ckeditor/ckeditor5#1788] opened 2019-05-31 03:12 UTC
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor

11.0.1

## 📋 Steps to reproduce

1. ckeditor5 created
2.use function destroy , ckeditor5  = null  , ckeditor5 destroyed  in vue beforeDestroy
3.collect garbarge in Chrome

## 📃 Other details that might be useful
if I create and destroy ckeditor5  frequently,the Memory  will be too high.
![image](https://user-images.githubusercontent.com/37398280/58679182-017f5a80-8395-11e9-87f0-fb231e94a536.png)

**Comment by jodator** [comment] 2019-05-31 07:38
Hi, we are aware of this: https://github.com/ckeditor/ckeditor5/issues/1731 and I don't think it is related to the vue integration only.

Unfortunately it looks like Chrome `74` introduced some changes that causes more leaks then in previous versions.

I'm closing this as duplicate of #1731 - please subscribe to that one to track it's progress.

**Closed by jodator** 2019-05-31 07:38 UTC
Labels: resolution:duplicate, type:bug
