### ISSUE TITLE
[iOS] Selection on ipad is on a z-layer above the menu dropdowns

### ISSUE THREAD

**Issue by blueknight13** [ckeditor/ckeditor5#7497] opened 2020-06-24 18:57 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Using CkEditor 5 Demo - Document
2. Add some text
3. Select the text
4. Open font or fontsize menu

### ✔️ Expected result

can make a change to the selected text even if menu option overlaps

### ❌ Actual result

    cannot select menu options that overlap selected text
    appears as if the ipads blue selection highlight is above the menu options

## 📃 Other details

* Browser: Safari
* OS: iPad 13
* CKEditor version: 5 v19.1
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2020-06-25 06:43
Hi, thanks for the report. I can reproduce this issue on iPhone 8.

![Brak opisu.](https://scontent.fwaw3-2.fna.fbcdn.net/v/t1.15752-9/105601214_320302825646609_8892386355154719903_n.jpg?_nc_cat=101&_nc_sid=b96e70&_nc_ohc=qmFW0CbgseMAX9JE73p&_nc_ht=scontent.fwaw3-2.fna&oh=321469b0cbf061ae9763f55e869c569c&oe=5F1809D7)

**Comment by jacekbogdanski** [comment] 2021-05-27 08:24
Seems like the previous image is not available, I'm attaching a new one as I encountered this issue also when testing iOS on iPhone 12:
![IMG_5178E5849404-1](https://user-images.githubusercontent.com/10279586/119792077-b0e45e80-bed5-11eb-86c5-c908707f806c.jpeg)

**Comment by oleq** [comment] 2022-09-08 08:38
This is a duplicate of ckeditor/ckeditor5#7497.

**Closed by oleq** 2022-09-08 08:38 UTC
Labels: type:bug, browser:ios, support:2, squad:core
