### ISSUE TITLE
Multilevel List formatting from word is not maintained in CKEditor5

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1617] opened 2019-03-12 06:57 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

CKeditor5

## 📋 Steps to reproduce

1. Copy and paste the content from microsoft word document having multilevel bulletted list.
2. Please see the sample content in attached file

## ✅ Expected result
The list formatting should be maintained as it is in word document.
## ❎ Actual result
After copying the content into ckeditor, only the first level lists are shown and the child level list content is lost.

[SampleNotes.docx](https://github.com/ckeditor/ckeditor5/files/2955490/SampleNotes.docx)

**Comment by Mgsy** [comment] 2019-03-12 09:01
Hello, this is a duplicate of https://github.com/ckeditor/ckeditor5-paste-from-office/issues/19 and the PR introducing these changes in on the review.

**Closed by Mgsy** 2019-03-12 09:01 UTC
Labels: resolution:duplicate
