### ISSUE TITLE
Mentions (@) plugin: suggestions disappears after clicking space bar

### ISSUE THREAD

**Issue by volleybox** [ckeditor/ckeditor5#5659] opened 2019-10-25 08:38 UTC
I have such bug while using **Mentions** plugin for Ckeditor 5:
Some of my autocomplete suggestions have whitespaces between words as you see on screen below.

<img width="862" alt="Zrzut ekranu 2019-10-25 o 10 30 50" src="https://user-images.githubusercontent.com/56996673/67556000-ae76bd00-f712-11e9-84a6-496fa99552ea.png">

After clicking a **space bar** suggestions disappears and first suggestion is choosed. The same story is for slash (/) character.
Maybe you will tell that whitespaces shouldn't be used in hashtags. Ok, but what about users mentions? I just checked that on Slack that works fine.

My implementation is very similar to this example: https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html Of course if there will be such need I can place it here.

Do you have some solutions / workarounds of that bug? In the worst scenario I will just remove whitespaces between words :(

**Comment by jodator** [comment] 2019-10-25 09:04
Yes, this is intended behavior. I agree that this might be misleading for space as we only trigger mention UI for a marker + text (without spaces inside), so we use a space as a trigger to insert a mention. Other keys used for this are <kbd>enter</kbd> and <kbd>tab</kbd>. We probably could add a configuration for allowing/excluding certain keys on Mention UI.

Unfortunately, I don't have anything to overcome that but you can have your [feed callback](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#providing-the-feed) that would look into your feed data excluding space. In other words: for now users could type "adrianpat" and your feed callback should match "Adrian Patucha" for this.

As we already have a ticket for this: https://github.com/ckeditor/ckeditor5/issues/4665 I'm closing this as a duplicate. You can add :+1: reaction to that ticket (issue description) as we look into tickets with many reactions to choose on what to fix in the first place.

As for `/` - the same will happen if you don't match any item in the feed so if there is no item in the feed the mention UI is closed.

**Closed by jodator** 2019-10-25 09:04 UTC
Labels: package:mention, resolution:duplicate, type:bug
