### ISSUE TITLE
[Firefox] Incorrect selection position when tabbing into an editor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#902] opened 2018-03-14 12:35 UTC
1. Open a sample which has at least two editors (e.g. https://docs.ckeditor.com/ckeditor5/latest/examples/builds/inline-editor.html)
2. Put caret in the first editor.
3. Press tab.

Expected: The selection is placed at the beginning of the first line in the second editor.

Actual: The selection is put before the first block of content.

![Mar-14-2018 13-31-55.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/40f8a46b-c482-44a9-bf51-254550e3e9ae/Mar-14-2018+13-31-55.gif)

---

This is one of many issues which will be fixed once we start validating selection position (https://github.com/ckeditor/ckeditor5-engine/pull/1151).

**Comment by scofalik** [comment] 2018-04-12 11:48
Another thing that happens on Firefox is that you can place the caret between `<p>` and `<figure>`:

![apr-12-2018 13-56-35](https://user-images.githubusercontent.com/1502228/38675484-2ee510b0-3e58-11e8-98ff-c04186484ba0.gif)

**Comment by Reinmar** [comment] 2018-04-23 14:51
It's hard to tell who's to blame here.

* It could be Firefox that it places the caret in such a senseless place. Other browsers place it in the first paragraph. However, contentEditable has no spec and sometimes FF's behaviour makes more sense.
* CKEditor 5's engine that it does not fix an incorrect selection created by Firefox. We started to work on this in the past (https://github.com/ckeditor/ckeditor5-engine/pull/1151) but we still need some time to complete it.

In any case, we need to fix this on our side.

**Comment by oleq** [comment] 2018-11-21 11:53
[Another case](https://github.com/ckeditor/ckeditor5-table/issues/150):

![tablefirst](https://user-images.githubusercontent.com/189964/48831575-c2d26d00-ed7f-11e8-89d3-06e65fc2abf4.gif)

**Comment by Reinmar** [comment] 2018-11-21 12:03
Selection validation that we introduced some time ago should fix this... It's strange it didn't. Perhaps we just haven't implemented handling for this scenario yet. I suppose that the selection should end up in the first table cell since this is the first editable location.

**Comment by FilipTokarski** [comment] 2020-01-03 13:23
I was not able to reproduce those issues. It looks like it's all been fixed now and can be closed.

**Closed** 2020-01-03 13:30 UTC
Labels: browser:firefox, status:confirmed, type:bug
