### ISSUE TITLE
[Edge] Error after opening the console while the balloon is active

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#829] opened 2018-02-07 13:27 UTC
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce
There are no specific steps to reproduce, more info below.

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the selection in the link.
3. Open the console.
4. Put the selection in `Heading 1`.

## ✅ Expected result

Selection moves out of the link.

## ❎ Actual result

Selection stays inside the link and there is the error in the console.

## 📃 Other details that might be useful

**Notes**

~I don't know how to reproduce it, but I've noticed this bug some time ago. It occurs randomly and isn't easy to reproduce. It occurs with closed console and caret browsing mode off.~

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/36304322-87241b8c-130f-11e8-9b88-de59a40f8f62.gif)

**Error**
```
SCRIPT5: SCRIPT5: Access is denied.
article.html (1,1)

SCRIPT5: Access is denied.
viewcollection.js (78,1)
```

**Other information**
OS: Windows 10
Browser: Edge 16

**Comment by Mgsy** [comment] 2018-02-16 10:47
Okay, I've figured out where is the problem. This bug occurs only after opening the console while the balloon (link or text alternative) is active. 

I will update the scenario.

**Comment by elbecita** [comment] 2018-06-22 13:12
Hey, I just landed here searching for another different scenario where I get the same error (SCRIPT 5, access denied) after opening closing the dev console. Just FYI, it seems to be a bug on Edge related to opening and closing the console and then having some events triggered: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14146025/
It is marked as solved but it is clearly still happening.
I hope it is somehow useful info for you.

**Comment by Reinmar** [comment] 2018-06-25 09:14
Thanks for the info. @Mgsy could you retest it and, if it's still reproducible, comment under that upstream ticket too?

**Comment by Mgsy** [comment] 2018-06-25 09:32
> @Mgsy could you retest it and, if it's still reproducible, comment under that upstream ticket too?

I'm not able to reproduce this bug in Edge 17.17134 🎉

**Comment by Reinmar** [comment] 2018-06-25 09:35
OK, cool. So, fortunately, our version of this issue was really fixed.

**Closed by Reinmar** 2018-06-25 09:35 UTC
Labels: type:bug
