### ISSUE TITLE
Tables are out of frame in RTL editor in 'Table column resize' manual test on Chrome

### ISSUE THREAD

**Issue by charlttsie** [ckeditor/ckeditor5#14392] opened 2023-06-15 10:48 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open http://localhost:8125/ckeditor5-table/tests/manual/tablecolumnresize.html
2. Scroll down to the RTL editor

### ✔️ Expected result

All table borders are visible

### ❌ Actual result

Right side borders are not visible:

<img width="504" alt="tables-manual test" src="https://github.com/ckeditor/ckeditor5/assets/132071257/6cbe5040-1640-4779-a382-692e62161964">

Additionally, there's white space visible on the left:

<img width="72" alt="white space" src="https://github.com/ckeditor/ckeditor5/assets/132071257/d4499342-4379-465f-b872-14872fc41fe3">

## 📃 Other details
* The issue is visible in RTL demo in docs too: https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#righttoleft-rtl-languages-support, but to a much smaller extent - right borders are thinner than left ones 
* Browser: Chrome
* OS: MacOS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment] 2024-04-11 07:15
Duplicate of https://github.com/ckeditor/ckeditor5/issues/11769.

**Closed by oleq** 2024-04-11 07:15 UTC
Labels: type:bug, package:table, browser:chrome, domain:rtl, squad:core
