### ISSUE TITLE
[Mobile] - Cursor or text selection highlight remains above dropdown and other elements

### ISSUE THREAD

**Issue by OrenMag** [ckeditor/ckeditor5#11217] opened 2022-02-05 21:19 UTC
## 📝 Provide detailed reproduction steps (if any)
CKEditor5 (version below)
Mobile, both IOS  (iphone 11) and Android (galaxy s10)

Steps:
1. Select Text or edit text
2. Open any dropdown menu on top of it

### ✔️ Expected result

Cursor or dropdown should be displayed above the selected text

### ❌ Actual result

Cursor / Highlighted Text stay on top (just the background color of the selection)

<img width="409" alt="Screen Shot 2022-02-05 at 23 14 11" src="https://user-images.githubusercontent.com/78356438/152659241-af673616-59e9-4c01-a3b3-6c1d8f4846ad.png">
<img width="420" alt="Screen Shot 2022-02-06 at 16 59 45" src="https://user-images.githubusercontent.com/78356438/152686877-d26f815d-ae6e-4896-b82f-c8cd26397883.png">

### ❓ Possible solution

Might be related to IOS input blurring issues?

## 📃 Other details

* Browser: Safari
* OS: IOS Iphone 11 SImulator
* First affected CKEditor version: …
* Installed CKEditor plugins:
@ckeditor/ckeditor5-react
"@ckeditor/ckeditor5-adapter-ckfinder": "^24.0.0",
		"@ckeditor/ckeditor5-alignment": "^24.0.0",
		"@ckeditor/ckeditor5-autoformat": "^24.0.0",
		"@ckeditor/ckeditor5-autosave": "^24.0.0",
		"@ckeditor/ckeditor5-basic-styles": "^24.0.0",
		"@ckeditor/ckeditor5-block-quote": "^24.0.0",
		"@ckeditor/ckeditor5-ckfinder": "^24.0.0",
		"@ckeditor/ckeditor5-core": "^24.0.0",
		"@ckeditor/ckeditor5-dev-utils": "^23.6.1",
		"@ckeditor/ckeditor5-dev-webpack-plugin": "^23.6.1",
		"@ckeditor/ckeditor5-easy-image": "^24.0.0",
		"@ckeditor/ckeditor5-editor-balloon": "^24.0.0",
		"@ckeditor/ckeditor5-editor-classic": "^24.0.0",
		"@ckeditor/ckeditor5-essentials": "^24.0.0",
		"@ckeditor/ckeditor5-font": "^24.0.0",
		"@ckeditor/ckeditor5-heading": "^24.0.0",
		"@ckeditor/ckeditor5-horizontal-line": "^24.0.0",
		"@ckeditor/ckeditor5-image": "^24.0.0",
		"@ckeditor/ckeditor5-indent": "^24.0.0",
		"@ckeditor/ckeditor5-link": "^24.0.0",
		"@ckeditor/ckeditor5-list": "^24.0.0",
		"@ckeditor/ckeditor5-media-embed": "^24.0.0",
		"@ckeditor/ckeditor5-paragraph": "^24.0.0",
		"@ckeditor/ckeditor5-paste-from-office": "^24.0.0",
		"@ckeditor/ckeditor5-remove-format": "^24.0.0",
		"@ckeditor/ckeditor5-table": "^24.0.0",
		"@ckeditor/ckeditor5-theme-lark": "^24.0.0",
		"@ckeditor/ckeditor5-mention": "^24.0.0",
"eslint-config-ckeditor5": "^2.0.0",

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2022-02-08 14:42
Hi, thanks for the report. It seems like you're using very old CKEditor version (`24.0.0`). Could you confirm that this also happens on the latest one (`32.0.0`)?

**Comment by OrenMag** [comment] 2022-02-15 09:39
I'll check and update here

**Comment by oleq** [comment] 2022-09-08 08:37
This is a duplicate of ckeditor/ckeditor5#5753.

**Closed by oleq** 2022-09-08 08:37 UTC
Labels: type:bug, pending:feedback
