### ISSUE TITLE
A CSS Syntax Error in ckeditor5-theme-lark@28.0.0

### ISSUE THREAD

**Issue by lvxiaodi1234** [ckeditor/ckeditor5#9890] opened 2021-06-16 10:09 UTC
I got a Syntax Error by css-loader when i upgrade ckeditor5 version to 28：

![image](https://user-images.githubusercontent.com/26077502/122199086-55056800-cecc-11eb-80d5-b3d220ff2361.png)

I found that the Error maybe in “ckeditor5-theme-lark/theme/ckeditor5-ui/components/labeledfield/labeledfieldview.css”

<img width="711" alt="企业微信截图_1d7355d0-df2c-4619-8861-432276d3691a" src="https://user-images.githubusercontent.com/26077502/122198241-921d2a80-cecb-11eb-9195-b146cd7cded9.png">

I think if embed it in “calc()” will resolve this problem？

thank you  for your help!

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by AnnaTomanek** [comment] 2021-07-27 13:11
@ckeditor/qa-team Can you have a look, please? Thanks!

**Comment by Mgsy** [comment] 2021-08-02 08:30
Hi @lvxiaodi1234, sorry for the late reply. Could you please provide more information about your issue? It would be great to know whether you use some framework integration or customizations that might impact your implementation. Also, you can try to update to the latest version and reinstall all packages.

**Comment by oleq** [comment] 2021-08-02 08:57
We definitely need more information to reproduce this issue. What is your `css-loader` version, @lvxiaodi1234? What is your webpack configuration?

**Comment by oleq** [comment] 2021-09-13 14:05
Closed by accident in an unrelated PR.

**Comment by Reinmar** [comment] 2021-09-14 11:36
This ticket can be closed anyway due to lack of feedback.

But if anyone landed here from the v30.0.0's changelog, I was supposed to link to this ticket #9892 :point\_left:

**Closed by Reinmar** 2021-09-14 11:36 UTC
Labels: type:bug, pending:feedback, squad:ux
