### ISSUE TITLE
Edit source code

### ISSUE THREAD

**Issue by AndiLeni** [ckeditor/ckeditor5#1699] opened 2019-04-11 18:27 UTC
Please add a button which makes it possible to edit the sourcecode directly. 
Currently there are so many features missing (f.e. simple `<hr>`), I would like to be able to add these manuallly at least.

Regards
Andi

**Comment by mlewand** [comment] 2019-04-11 19:12
Duplicate of #592.

**Closed by mlewand** 2019-04-11 19:12 UTC
