### ISSUE TITLE
When there is a lot of content in root,paste other content which's first element is a picture. Error.

### ISSUE THREAD

**Issue by misterPeng** [ckeditor/ckeditor5#5843] opened 2019-11-27 09:48 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Copy more than one picture to the clipboard.The content's first item must be a picture,not a empty paragraph.
2. Non-stop pasting into ckeditor which has a lot of content.There is enough content in ckEditor, which can be reproduced in one paste operation.

### ❌ Actual result

*What is the actual result of the above steps?*
![1574847401(1)](https://user-images.githubusercontent.com/23489981/69712102-3b130180-113d-11ea-86a6-bc5a920a2398.png)

## 📃 Other details

* Browser: Chrome  78.0.3904.108
* CKEditor version: 15.0.0
* Installed CKEditor plugins: Reproducible on https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by misterPeng** [comment] 2019-11-27 09:53
I guess it is related to #5601 .

**Comment by Mgsy** [comment] 2019-11-27 12:04
Hi, I'm not able to reproduce the issue. Can you provide more information about it? Do you copy the content from the editor? Can you share the HTML you use to reproduce it?

**Comment by misterPeng** [comment] 2019-11-28 07:46
Hi.Yes, i copy the content from the editor.
I found that the copied content is not an image but can be reproduced.

This init html: 
[initData.txt](https://github.com/ckeditor/ckeditor5/files/3900459/initData.txt)

This clipboard html:
[pasteData.txt](https://github.com/ckeditor/ckeditor5/files/3900460/pasteData.txt)

I ’ve confirmed that it only needs to be pasted once to reproduce on https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html

**Comment by Mgsy** [comment] 2019-12-10 14:19
Thanks. It looks like this is the same issue as https://github.com/ckeditor/ckeditor5/issues/1579, so I'll close it as a duplicate.

**Closed by Mgsy** 2019-12-10 14:19 UTC
Labels: pending:feedback, type:bug
