### ISSUE TITLE
Wiris MathType plugin is not working with ckeditor5 in React/Vue

### ISSUE THREAD

**Issue by mstermaaten** [ckeditor/ckeditor5#2048] opened 2019-09-13 09:58 UTC
Bug report 

@ckeditor/ckeditor5-react: v1.1.3,
@wiris/mathtype-ckeditor5: v7.16.1,
....

![Schermafdruk 2019-09-13 11 52 59](https://user-images.githubusercontent.com/49290062/64854106-271b3180-d61d-11e9-9a12-9f08fa280e0c.png)

I simply try to implement the MathType plugin following this documentation: 
- https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html
- https://ckeditor.com/docs/ckeditor5/latest/features/mathtype.html#usage

I'm getting an error and this only happens when i try to implement the MathType plugin. I'm not sure if i'm missing any config settings that i have to parse to
initialize the plugin but reading trough the documentation i'm not seeing anything i'm missing. Maybe I have to buy a licence or something??

## 📋 Steps to reproduce

1. Clone this Repo: https://github.com/mstermaaten/CKEditor-Issue
2. npm i && npm start

## ✅ Expected result

![Schermafdruk 2019-09-13 11 56 03](https://user-images.githubusercontent.com/49290062/64854336-b45e8600-d61d-11e9-935a-a200ff2b7cc3.png)

**Comment by Mgsy** [comment] 2019-09-16 13:13
Hello, thank you for the report. I'm able to reproduce this issue - adding MathType plugin to the editor built from source with React triggers the error. It looks like some changes in Webpack config are required. 

Steps to reproduce:
1. Follow the [Integrating CKEditor 5 built from source guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source).
1. Add MathType plugin to the editor.
1. Run the application.

We're in touch with Wiris about this issue.

**Comment by SudhirTrisys** [comment] 2019-09-17 06:24
any alternative for the time being?

**Comment by mlewand** [comment] 2019-09-18 07:55
This issue occurs also with vue too, see https://github.com/ckeditor/ckeditor5/issues/2057.

**Comment by duzhihao-github** [comment] 2019-09-22 06:30
Here's how I do it
file vue.config.js
```js
  chainWebpack: config => {
    svgRule.exclude.add(path.join(__dirname, 'node_modules', '@ckeditor'))
    svgRule.exclude.add(path.join(__dirname, 'node_modules', '@wiris'))

 config.module
      .rule('cke-svg')
      .test(/theme[/\\]icons[/\\][^/\\]+\.svg$/)
      .use('raw-loader')
      .loader('raw-loader')

    config.module
      .rule('cke-css')
      .test(/ckeditor5-[^/\\]+[/\\].+\.css$/)
      .use('postcss-loader')
      .loader('postcss-loader')
      .tap(() => {
```
That's not all。Because mathtype does not match the current filtering rules, the icon cannot be found。

**Comment by nnabinh** [comment] 2019-09-22 16:29
@duzhihao-github thanks a lot man, you saved my day! 

I confirm that adding this line
```javascript
svgRule.exclude.add(path.join(__dirname, 'node_modules', '@wiris'))
```

and by updating the `cke-svg` config rule from
**_/ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/_** 
(as being described [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html)) to 
**_/theme[/\\]icons[/\\][^/\\]+\.svg$/_**
it works great since all svg icons are loaded now

```javascript
config.module
      .rule('cke-svg')
      .test(/theme[/\\]icons[/\\][^/\\]+\.svg$/)
      .use('raw-loader')
      .loader('raw-loader')
```

**Comment by mstermaaten** [comment] 2019-09-23 08:10
Okay we are getting closer but it's not very clear for me how i can implement this also for React. 
Anybody that can help me out here?
@nnabinh 
@duzhihao-github
@Mgsy

**Comment by duzhihao-github** [comment] 2019-09-23 08:19
@mstermaaten 
Check the path to read the SVG file in webpack

**Comment by mstermaaten** [comment] 2019-09-24 08:35
This is my first time i had to go add & change stuff in my webpack.config so i find it difficult to find where to add all these additional configs...
If anybody could show me how this would apply in a react webpack.config would be super awesome :)

**Comment by NimithaCherian** [comment] 2019-10-10 10:18
Add two new elements to the exported object under the module.rules array (as new items of the oneOf array). These are SVG and CSS loaders required to handle the CKEditor 5 source:
{
     test: /theme[/\\]icons[/\\][^/\\]+\.svg$/,
    use: [ 'raw-loader' ]
},
{
    test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,
    use: [
        {
            loader: 'style-loader',
            options: {
                injectType: 'singletonStyleTag'
            }
        },
        {
            loader: 'postcss-loader',
            options: styles.getPostCssConfig( {
                themeImporter: {
                    themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
                },
                minify: true
            } )
        }
    ]
},

Note the change:   test: /theme[/\\]icons[/\\][^/\\]+\.svg$/,  

This works in React!!! (Mathtype and Chemtype) . Hope this helps! Thanks!

**Comment by Reinmar** [comment] 2019-11-13 17:49
@mlewand did the recent changes with icons solve this issue?

**Comment by mstermaaten** [comment] 2019-11-14 14:53
I've actually fixed this problem by:

_"and by updating the cke-svg config rule from
`/ckeditor5-[^/\]+[/\]theme[/\]icons[/\][^/\]+.svg$/`
(as being described here) to
`/theme[/\]icons[/\][^/\]+.svg$/`
it works great since all svg icons are loaded now"_

**Comment by Reinmar** [comment] 2019-11-15 08:14
Hm... That makes sense. The problem comes from the fact that MathType comes in `@wiris/mathtype-ckeditor5` and not `@wiris/ckeditor5-mathtype`. That's why the original regexp doesn't work.

I'll talk with guys from Wiris, maybe they'll be fine with renaming their package to follow the convention.

**Comment by tuannd255** [comment] 2020-02-12 07:34
@mstermaaten Hello, I clone your app fixed this issues but I still error when run project. Can you support me fix it? Thank you!!!
![image](https://user-images.githubusercontent.com/14371275/74312731-cac36600-4da4-11ea-8aae-6db750451bd7.png)

**Comment by vmarcosp** [comment] 2020-05-22 13:38
Hey everyone, any news about this issue? @tuannd255

**Comment by vmarcosp** [comment] 2020-05-25 17:58
@tuannd255 I fixed this error making the file loader from the CRA config, something like:
```js
svgRule.exclude.add(/theme[/\]icons[/\][^/\]+.svg$/)
```
Adding this line to your CRA config the file loader will ignore icons from any plugin that you are using with ckeditor.

**Comment by vmarcosp** [comment] 2020-05-25 17:59
@Reinmar what do you think to add to the official docs a section to help people with similar problems with loaders and config for custom builds?

**Comment by vmarcosp** [comment] 2020-05-26 11:43
@Reinmar Take a look at this [PR](https://github.com/ckeditor/ckeditor5/pull/7289) please

**Comment by mohitsehgal** [comment] 2020-09-18 14:01
Frankly this thread saved my day.!! Awesome

**Comment by Reinmar** [comment] 2020-09-21 08:25
Hi all! This issue will be resolved with #8114. We want to change the default regexp that we're proposing to cover packages that are named `sth-ckeditor5` too.

**Closed by Reinmar** 2020-09-21 08:25 UTC
Labels: package:mathtype, type:docs, type:task

**Comment by Rajsolanki7695** [comment] 2024-09-14 13:54
ERROR in ./node_modules/@ckeditor/ckeditor5-core/theme/icons/object-size-custom.svg
Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
SyntaxError: unknown file: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.


![image](https://github.com/user-attachments/assets/eb94a898-3ddb-4822-87f3-39439fc738a6)


getting this when installl and import how to fix this

**Comment by amarbhanu** [comment] 2024-12-02 07:52
Angular 18.2.9 has CKeditor5 integration that is working well but when npm i @wiris/mathtype-ckeditor5


// import MathType from '@wiris/mathtype-ckeditor5';
// import MathType from '@wiris/mathtype-ckeditor5/dist/index.js';
// import MathType from '@wiris/mathtype-ckeditor5/dist/index';
// Suppress the error by using `require`:
 const MathType = require('@wiris/mathtype-ckeditor5/dist/index.js');


 // Editor configuration
   public editorConfig = {
     plugins: [MathType], // Add MathType plugin here
    toolbar: [
      'heading', // Heading styles
      '|',
      'bold', 'italic', 'underline', // Text formatting
      '|',
      'link', // Hyperlink
      'bulletedList', 'numberedList', // Lists
      '|',
      'MathType', 'ChemType', // Add MathType and ChemType buttons
      '|',
      'undo', 'redo' // Undo and redo
    ]
  };

then multiple errors are showing. svg related and multiple others. Can you suggest how to fix this?
