### ISSUE TITLE
Error when click-drag selecting up on text with Horizontal line in FireFox 

### ISSUE THREAD

**Issue by mvhdi** [ckeditor/ckeditor5#7949] opened 2020-08-26 21:23 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open the Collaborative Editor in classic mode, with the horizontal line plugin, in Firefox.
2. Click below a horizontal line 
3. Drag select upward getting the horizontal line and text above it. 

### ✔️ Expected result
We should be able to drag up toward a horizontal line and select the horizontal line and the text above it, without any errors or buggy movement that takes us to the top of the page. 

_What is the expected result of the above steps?_

### ❌ Actual result
1. Error is thrown: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-selection-range-intersects
2. Buggy movement Editor moves up taking us to the top of the page. 

Example: https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14154030/91358153-f1347600-e7b7-11ea-85c6-69cb113671b3.gif)

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: FireFox
* OS: macos
* CKEditor : classic, collaborative editor 
* Horizontal line: @ckeditor/ckeditor5-horizontal-line": "^21.0.0"
* Installed CKEditor plugins: horizontal Line plugin

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2020-08-27 06:58
Hi, thanks for the report. I confirm this bug, it's a regression introduced in version 20.0.0.  
  
Bisection shows this commit: https://github.com/ckeditor/ckeditor5/commit/824d7317de8461773fab4f55cdfd6c585498131d
  
  
Error message:  
  
```js
Uncaught CKEditorError: model-selection-range-intersects: Trying to add a range that intersects with another range in the selection. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…port/error-codes.html#error-model-selection-range-intersects
 {"addedRange":{"start":{"root":"main","path":[8],"stickiness":"toNext"},"end":{"root":"main","path":[9,2],"stickiness":"toPrevious"}},"intersectingRange":{"start":{"root":"main","path":[8,0],"stickiness":"toNone"},"end":{"root":"main","path":[8,0],"stickiness":"toNone"}}}
    i ckeditorerror.js:66
    _checkRange selection.js:758
    _prepareRange documentselection.js:820
    _pushRange documentselection.js:805
    _setRanges selection.js:474
    setTo selection.js:405
    setTo documentselection.js:734
    _setTo documentselection.js:421
    setSelection writer.js:1189
    Ye selection-post-fixer.js:102
    Ye selection-post-fixer.js:65
    _callPostFixers document.js:412
    _handleChangeBlock document.js:311
    _runPendingChanges model.js:826
    change model.js:170
    Rt upcasthelpers.js:412
    fire emittermixin.js:209
    _handleSelectionChange selectionobserver.js:183
    observe selectionobserver.js:104
    fire emittermixin.js:209
    n emittermixin.js:235
    attach emittermixin.js:193
    listenTo emittermixin.js:59
    observe selectionobserver.js:103
    attachDomRoot view.js:286
    init classiceditorui.js:105
    create classiceditor.js:199
    promise callback*create/< classiceditor.js:199
    create classiceditor.js:194
    <anonymous> horizontal-line.js:17
```

**Comment by FilipTokarski** [comment] 2020-08-27 07:11
It seems to be the same issue as in https://github.com/ckeditor/ckeditor5/issues/7892. The same browser, steps and bisection result. I'll close this one for now as a duplicate and let's track it there.

**Closed by FilipTokarski** 2020-08-27 07:11 UTC
Labels: browser:firefox, package:horizontal-rule, type:bug, type:regression
