### ISSUE TITLE
Paste From MS Word. Document with Japanese language set doesn't paste text with images

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor5#8986] opened 2021-02-03 12:38 UTC
## 📝 Provide detailed reproduction steps (if any)

1.  Open attached MS Word file or prepare one yourself in Office 365 by setting preferred language as Japanese in MSWord. You may need to install Japanese Language pack to your MS Office and will have to restart after changing the settings.  

Sample File: [sample.zip](https://github.com/ckeditor/ckeditor5/files/5918352/sample.zip)

![](https://support.ckeditor.com/attachments/token/3qazuuofEaUf6IlTFGo7YReKs/?name=image001.jpg)

![](https://support.ckeditor.com/attachments/token/TSJcviJ6MnkXAn113guVzaESl/?name=image002.jpg)

1.  Cop/paste the MS Word file contents in CKEditor e.g. https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

### ✔️ Expected result

Image gets pasted with text.

### ❌ Actual result

Only text gets pasted.
![result](https://user-images.githubusercontent.com/5314687/106746549-ff1ddb00-6622-11eb-830a-90fc3ac96a6a.png)

## 📃 Other details

*   Browser: Any
*   OS: Windows 10
*   First affected CKEditor version: 
*   Installed CKEditor plugins: paste-from-office

- Ticket for reference - 66877
- data.dataTransfer["text/rtf"] ' is empty in case of Japanese as preferred language. But it contains data in case of English.
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2021-02-08 08:44
It might be the same issue - #2493.

**Comment by jswiderski** [comment] 2021-03-04 16:15
After some testing it turns out this is exactly @[**niegowski**](https://github.com/niegowski) has described in his comment [https://github.com/ckeditor/ckeditor5/issues/2493#issuecomment-749507634.](https://github.com/ckeditor/ckeditor5/issues/2493#issuecomment-749507634.) When you paste whole document, there is no `text/rtf` which we can get to, to obtain image data.

**Comment by AnnaTomanek** [comment] 2021-03-15 15:01
Closing as a duplicate of #2493.

**Closed by AnnaTomanek** 2021-03-15 15:01 UTC
Labels: package:paste-from-office, resolution:duplicate, support:2, type:bug
