### ISSUE TITLE
Typing in dates triggers the fractions auto-correct feature

### ISSUE THREAD

**Issue by authentifydan** [ckeditor/ckeditor5#9614] opened 2021-05-03 20:17 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Started to type in a date of 11/27/2018 and it immediately auto-corrects the 11/27 to 1 **_1/2_** 7

### ✔️ Expected result

Dates should be allowed to be typed in as dates
I'd still like to be able to type in stand-alone 1/2 and have it auto-format nicely.   Perhaps the code should key off a space in front and a space behind? 

### ❌ Actual result

immediately auto-corrects the 11/27 to 1 **_1/2_** 7

## 📃 Other details

* Browser: Chrome (latest)
* OS: Mac
* First affected CKEditor version: unknown
* Installed CKEditor plugins: unknown

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by AnnaTomanek** [comment] 2021-05-06 07:45
Hi @authentifydan, thanks for reporting this issue! It looks like a duplicate of #9170 so I'm closing your report. Please follow the other issue to be notified about any progress with this bug. Thanks again!

**Closed by AnnaTomanek** 2021-05-06 07:45 UTC
Labels: package:typing, resolution:duplicate, squad:ux, type:bug
