### ISSUE TITLE
Horizontal line breaks "Select all + Delete"

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#6331] opened 2020-02-25 21:03 UTC
## 📝 Provide detailed reproduction steps (if any)

1.  Create content ending it with a horizontal line, like the following:

![](https://user-images.githubusercontent.com/630060/75286951-c1f97800-5819-11ea-8071-7375780d8eab.png)

1.  Press `cmd/ctrl+a` to select all.
    1.  **Issue 1**: The horizontal line doesn't get selected.
2.  Press `backspace` to delete all.
    1.  **Issue 2**: Nothing gets deleted. No effect.
3.  Alternatively, press `delete`.
    1.  **Issue 3:** the first character of the text gets deleted and the selection collapses at the beginning of the document.

**Bonus issue**: the horizontal line can't be selected by pressing `arrow-down`, except when the selection is at the end of the text.

## 📃 Other details

*   Tested over the [online demo](https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dkrahn** [comment] 2020-02-26 11:17
If I am not mistaken this is related to #4584, having a widget as first or last element in the editor.

**Comment by mlewand** [comment] 2020-03-02 08:43
That's right, it's a duplicate of #4584. Please, be sure to add a :+1: reaction to the mentioned issue so we see there's a desire in fixing this :slightly\_frowning\_face:

**Closed by mlewand** 2020-03-02 08:43 UTC
Labels: package:horizontal-rule, type:bug
