### ISSUE TITLE
react redux LOCATION_CHANGE ckeditor value not updated

### ISSUE THREAD

**Issue by adamgyongyosi** [ckeditor/ckeditor5#8343] opened 2020-10-26 10:35 UTC
hy
can you help me?

```javascript
<CKEditor
                            editor={ClassicEditor}
                            name="content"
                            config={ckeditorConfig}
                            data={getValue('content', lang)}
                            onChange={ckeditorChange}
                            className={classes.editor}
                        />
```
but input field change value
```javascript
                            <TxtField
                                label="Hír címe"
                                id="news-title"
                                variant="outlined"
                                name="title"
                                error={checkForError(`${this.state.langCode[i]}title`)}
                                helperText={checkForText(`${this.state.langCode[i]}title`)}
                                fullWidth
                                value={getValue('title', lang) || ''}
                                onChange={inputChange}
                            />
```

![image](https://user-images.githubusercontent.com/5511526/97162614-b9c65380-177f-11eb-8684-98949b99c181.png)

1: why working?
2: why not working?

**Comment by Mgsy** [comment] 2020-11-02 08:25
Hi, thanks for the report, however, I'm not sure what is this issue about. Could you please provide the detailed description, provide steps to reproduce and the current/expected result?

**Comment by adamgyongyosi** [comment] 2020-11-02 08:32
sorry my bad
i add special props needCKeditorData and:

![image](https://user-images.githubusercontent.com/5511526/97846141-dfa6a780-1ced-11eb-94e2-c1803b92223c.png)

![image](https://user-images.githubusercontent.com/5511526/97846243-01a02a00-1cee-11eb-91b1-7d5577d1c37d.png)

![image](https://user-images.githubusercontent.com/5511526/97846292-12e93680-1cee-11eb-9838-4b180307d6d8.png)

I don't think it's the best solution, but it works.

**Comment by Mgsy** [comment] 2020-11-02 09:32
I guess that the issue is solved, so I'm closing it.

**Closed by Mgsy** 2020-11-02 09:32 UTC
Labels: pending:feedback
