### ISSUE TITLE
Translation of Special Characters Groups

### ISSUE THREAD

**Issue by panos78** [ckeditor/ckeditor5#11440] opened 2022-03-09 13:26 UTC
## 📝 Description of the improvement

Now characters are grouped into Arrows, Currency, Text, Mathematical and Latin.
These group names should be translated, including the "All" string when everything is visible.

## 📃 Other details

* Browser: All browsers
* OS: All OS
* CKEditor version: 5
* Installed CKEditor plugins: Special Characters

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.
![image](https://user-images.githubusercontent.com/3087817/157450687-77271232-4656-4030-aa68-160b2a57518c.png)

**Comment by mlewand** [comment] 2023-01-11 14:38
Duplicate of #5820 - subscribe to it to get updates. Please add your :+1: reactions too to bump the issue.

**Closed by mlewand** 2023-01-11 14:38 UTC
Labels: type:improvement
