### ISSUE TITLE
Tables and images in lists break the list when pasting from Word

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#15945] opened 2024-02-28 12:11 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Download the sample file: [pfo-list-test.docx](https://github.com/ckeditor/ckeditor5/files/14433689/pfo-list-test.docx) (or create a similar one from scratch)
2. Copy and paste all contents of the file into the [Paste from Office Enhanced demo](https://ckeditor.com/docs/ckeditor5/41.1.0/features/pasting/paste-from-office-enhanced.html#demo)

### ✔️ Expected result

The table and image that are present in the original file should not break the list, as is the case in Word:

![image](https://github.com/ckeditor/ckeditor5/assets/72079603/3cc1a171-9314-4679-a8bb-9cb6f7993017)

### ❌ Actual result

The list breaks and the numbering starts from the begining:

![image](https://github.com/ckeditor/ckeditor5/assets/72079603/3792a896-f10e-4a1a-a1c9-5010b2927753)

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2024-02-28 12:15
Duplicate of #11210.

**Closed by Witoso** 2024-02-28 12:15 UTC
Labels: type:bug, package:paste-from-office, support:2, squad:core
