### ISSUE TITLE
Deleting a leading block quote does not work in Safari

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#14489] opened 2023-06-28 17:17 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Navigate to https://ckeditor.com/docs/ckeditor5/latest/features/block-quote.html using Safari on macOS or iOS (iPadOS was not tested).
2. Clear the editor’s contents.
3. Insert a block quote.
4. Attempt to delete the block quote by hitting backspace.

### ✔️ Expected result

The block quote is removed and the caret is placed in an empty line.

### ❌ Actual result

The bock quote stays in place.

## 📃 Other details

This works flawlessly in the latest versions of both Firefox and Chrome.

Important: The issue only occurs when the block quote is the first child of the editor. Any block quote that appears after any other elements can be removed by backspacing its contents in Safari.

* Browser: Safari 16.5.1
* OS: macOS 13.4.1 / iOS 16.5.1
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: CKEditor’s block quote plugin

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-06-29 11:04
Thanks for the report! Closing as a duplicate of #14390.

**Closed by Witoso** 2023-06-29 11:04 UTC
Labels: type:bug
