### ISSUE TITLE
Docs: improve dropdown guide

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11765] opened 2022-05-16 14:05 UTC
## 📝 Provide a description of requested docs changes

It's seems to be a somewhat popular case when integrators create their custom toolbar dropdowns. It would be nice to improve this guide - https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/ui-library.html#dropdowns - a bit, so that it has something more than just a dummy dropdown (for example insert some content into the editor when choosing an option from dropdown) and also has a simple demo that showcases it.

**Comment by godai78** [comment] 2022-05-17 05:03
Can we somehow use the bottom toolbar example with that?

**Comment by FilipTokarski** [comment] 2022-05-17 06:51
TBH I don't want to mix too many custom things at once. Let's keep this scoped to one case at a time and don't confuse users who just want a dropdown in a normal top toolbar.

**Comment by apadol-cksource** [comment] 2022-08-03 10:52
It seems to be a duplicate of https://github.com/cksource/ckeditor5-internal/issues/1875

**Closed by apadol-cksource** 2022-08-03 10:52 UTC
Labels: type:improvement, type:docs, squad:ccx
