### ISSUE TITLE
Formatting issue for Bold and Italic

### ISSUE THREAD

**Issue by shabab477** [ckeditor/ckeditor5#11152] opened 2022-01-21 14:23 UTC
## 📝 Provide detailed reproduction steps (if any)

1. We found this issue while loading data to our editor. But this issue can be recreated through source editing too. First, go to [the source editor](https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html#demo).
2. Then paste the following HTML in the source editor.

```
<p>
    <strong>abcd</strong>
</p>
```

3. Go back to editing view and put cursor at the end of the word, i.e, after the letter 'b'. Notice that the Bold toolbar icon is enabled.
4. Disable the Bold toolbar icon and start typing. Notice that everything is still in bold even though the Bold formatting is turned off.

### ✔️ Expected result

Not to output in bold when Bold icon is disabled

### ❌ Actual result

Output characters in the editor are in bold even though the Bold icon is toggled off.

### ❓ Possible solution

I noticed that the subsequent chacters continue inside the `<strong>` tag even though the Bold icon is off. There should be a check to be outside of this tag when the Bold icon is off.

## 📃 Other details

This same thing happens for Italic too and probably for underlines.

* Browser: Chrome
* OS: Ubuntu 20.04
* First affected CKEditor version: 30.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2022-01-24 15:18
Thanks for the report, looks like it's a duplicate of https://github.com/ckeditor/ckeditor5/issues/10548.

**Closed** 2022-01-24 15:31 UTC
Labels: type:bug, pending:feedback
