### ISSUE TITLE
image inside list in Table not adjust size

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#11757] opened 2022-05-15 10:12 UTC
## 📝 Provide detailed reproduction steps (if any)

1. create table
2. create list
3. paste big image

### ✔️ Expected result

image will be resized the same as paste image inside table without list
![image](https://user-images.githubusercontent.com/59637560/168467594-f0535613-042e-4903-a12c-9f0b4101dc39.png)

### ❌ Actual result

image insert in original size 
![image](https://user-images.githubusercontent.com/59637560/168467588-2e5c6801-454c-4785-8dde-ff2222812875.png)

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2022-05-16 12:11
Duplicate of https://github.com/ckeditor/ckeditor5/issues/11619?

**Comment by FilipTokarski** [comment] 2022-05-16 13:47
Thanks, I'll close this one then.

**Closed by FilipTokarski** 2022-05-16 13:47 UTC
Labels: type:bug
