### ISSUE TITLE
Spacebar doesn't work after using copied build source code from CDN

### ISSUE THREAD

**Issue by madskunker** [ckeditor/ckeditor5#1738] opened 2019-05-04 18:11 UTC
ClassicEditor 12.1.0

Chrome OSX latest build

Editor opens fine and I can type every key except the space bar. Even tried to cut / paste a single space into a line of text.

**Comment by madskunker** [comment] 2019-05-04 18:12
ClassicEditor 12
Editor opens fine and I can type every key except the space bar. Even tried to cut / paste a single space into a line of text.

**Comment by madskunker** [comment] 2019-05-04 19:54
` const self = this;       
ClassicEditor.create(node[0])
            .then(editor => {
                self.editor = editor;
                self.editor.keystrokes.set('space', (key, stop) => {
                    self.editor.execute('input', {
                        text: ' '
                    });
                    stop();
                });
            })
            .catch(error => {
                console.error(error);
            });`

Resolves the error

**Comment by toxpal** [comment] 2019-06-30 12:49
I have exactly the same problem with 12.2.0 - space doesn't get recorded.

**Comment by aliwaqas333** [comment] 2019-12-12 09:16
Any solution yet?

**Comment by Mgsy** [comment] 2019-12-13 10:30
>Any solution yet?

I'm not able to reproduce the mentioned issue. Can you open a new issue with a detailed description of the problem and steps to reproduce?

**Comment by GMModded** [comment] 2019-12-15 19:36
Got the same issue now tho when pressing space it appends a p-tag into the "ck-content"-div tag.
I was able to insert a space when a char was before my selector.

Not sure but I guess it might be third-party which might manipulating elements CKEditor needs (?)
I'm using:
- CKEditor 5 - 4.12.1 (Standard)
- MDBootstrap (I think it might cause the issue - will try it out)
- Custom CSS/JS stuff

I will try a clean test with CKEditor only and will post it here later.

**Comment by GMModded** [comment] 2019-12-15 19:47
@Mgsy found out the issue (not sure if it also might be a solution for others).

When copy & pasting the code from this URL `https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js` into your local project the space bar (why ever) won't work - but when loading it as scrip-tag using `<script src="https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js"></script>` it'll work fine.

**Comment by xboudsady** [comment] 2020-03-08 03:20
> @Mgsy found out the issue (not sure if it also might be a solution for others).
> 
> When copy & pasting the code from this URL `https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js` into your local project the space bar (why ever) won't work - but when loading it as scrip-tag using `<script src="https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js"></script>` it'll work fine.

Can concur, what a weird bug?

**Comment by gwynhowell** [comment] 2020-04-30 16:09
Anyone got to the bottom of this issue?

**Comment by Mgsy** [comment] 2020-05-04 06:13
It's hard to investigate it as we're not able to reproduce the problem. Could you provide exact steps to reproduce (including information about your environment and the way you implement the editor)?

**Comment by gwynhowell** [comment] 2020-05-11 11:34
I am seeing the issue when using with RequireJS. Have created a demo app here -> https://ckeditor-spacebar.appspot.com. You can see that the "local" page demo's the bug.

**Comment by UltimatePro-Grammer** [comment] 2020-08-16 17:17
Just had the same issue. Using a local copy of the cdn's file, the spacebar didn't record. However, using the CDN works perfectly.

**Comment by Mgsy** [comment] 2020-08-17 06:55
Hi, guys, thanks for sharing the information about the issue. However, I'd like to ask you for more details - could you please prepare a step-by-step instruction explaining how to set up the project and reproduce the mentioned issue (code examples will be much appreciated)? Unfortunately, as I said before, I 'm not able to reproduce it.

**Comment by UltimatePro-Grammer** [comment] 2020-08-24 01:44
@Mgsy Here is what I did:
1. Go to the linked page on the CDN
2. Press ctrl+a
3. Press ctrl+c
4. Make a new file in your preferred text editor and paste.
5. Include the new file in a script tag
6. The spacebar no longer works

**Comment by mishu1999** [comment] 2021-01-09 09:35
did anyone get any solution for this?

**Comment by iammati** [comment] 2021-01-09 11:51
@mishu1999 try this as it worked also for others:

When copy & pasting the code from this URL https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js into your local project the space bar (why ever) won't work - but when loading it as scrip-tag using <script src="https://cdn.ckeditor.com/ckeditor5/12.3.1/classic/ckeditor.js"></script> it'll work fine.

Hope it helps - you might want to change the version since I'm not aware of the latest ckeditor-version.

**Comment by ThatFlashCat** [comment] 2021-01-19 15:17
Same issue here - I copied the latest ckeditor script into a local file instead of using the cdn and the spacebar no longer works.

**Comment by Mgsy** [comment] 2021-01-19 15:24
As the issue seems to be still reproducible, I'm reopening it for further discussions.

**Comment by ThatFlashCat** [comment] 2021-01-19 15:59
Update:
Chrome and Chromium Edge behave differently than Firefox.

- Chrome/Chromium Edge: Spaces cannot be added to the end of a word when typing, but a single space will be added if the cursor is placed in the middle of a word and the spacebar is pressed.
- Firefox: Same as above, except pressing the spacebar at the end of a word will also result in a single space.

In either scenario, pressing the spacebar again will not yield additional spaces. I'm not using any extensions.

**Comment by Reinmar** [comment] 2021-02-15 08:56
This issue is probably caused by an encoding problem. When you copy-paste code from a file that you opened in the browser you're probably losing some information in it. The second option is that something breaks when you save that file using your editor. 

Since many of you pointed out that using a `<script>` tag pointing directly to the CDN resolves the issue, it means that all's fine with CKEditor itself. I'm closing this issue.

**Closed by Reinmar** 2021-02-15 08:56 UTC
Labels: status:discussion, type:bug

**Comment by UltimatePro-Grammer** [comment] 2021-02-16 02:27
@Reinmar This shouldn't be closed, as [not all of us want to use CDNs](https://shkspr.mobi/blog/2020/10/please-stop-using-cdns-for-external-javascript-libraries/). We need a better solution than "just use the cdn."

**Comment by ThatFlashCat** [comment] 2021-02-16 03:11
> This issue is probably caused by an encoding problem. When you copy-paste code from a file that you opened in the browser you're probably losing some information in it. The second option is that something breaks when you save that file using your editor.
> 
> Since many of you pointed out that using a `<script>` tag pointing directly to the CDN resolves the issue, it means that all's fine with CKEditor itself. I'm closing this issue.

This is possible. I tested using Visual Studio's "add client-side library" feature and had no issues.

**Comment by danialk1** [comment] 2021-06-16 23:15
Hi, we solved this issue by downloading CKEditor5 ([link](https://ckeditor.com/ckeditor-5/download/), then copying the contents of the ckeditor.js file directly into our code. This probably works since the copy paste issue that @Reinmar  mentioned before. Hope this helps!

**Comment by banana1982** [comment] 2022-09-21 11:26
> Hi, we solved this issue by downloading CKEditor5 ([link](https://ckeditor.com/ckeditor-5/download/), then copying the contents of the ckeditor.js file directly into our code. This probably works since the copy paste issue that @Reinmar mentioned before. Hope this helps!

Thanks so much, i fixed it

**Comment by stevedivinep** [comment] 2022-11-14 05:31
> ClassicEditor 12.1.0
> 
> Chrome OSX latest build
> 
> Editor opens fine and I can type every key except the space bar. Even tried to cut / paste a single space into a line of text.

Visit the CDN link's associated page.
press the ctrl+s keyboard shortcut.
The download page can be seen.
Simple download and usage.
Put a script tag around the new file.
You now verify that it functions properly in the browser.

Note: It does not work if you copy and paste using the clipboard.

**Comment by rhidwan** [comment] 2022-11-15 06:07
> > ClassicEditor 12.1.0
> > Chrome OSX latest build
> > Editor opens fine and I can type every key except the space bar. Even tried to cut / paste a single space into a line of text.
> 
> Visit the CDN link's associated page. press the ctrl+s keyboard shortcut. The download page can be seen. Simple download and usage. Put a script tag around the new file. You now verify that it functions properly in the browser.
> 
> Note: It does not work if you copy and paste using the clipboard.
> 
> It is Closed.

Thank you so much. It works just fine now!

**Comment by anthoncode** [comment] 2022-12-13 13:07
This problem is caused because the browser no longer supports some of the functions, the solution is to download a new version of ckeditor

**Comment by LemonYang7777** [comment] 2023-03-30 09:19
Not sure if my answer gonna help anyone, since it's been a while, but I'm facing a similar issue when copying the 36.0.1 version from the browser to my local, and my issue was fixed after I read this thread and inspire me to get my local version through postman.

**Comment by MominjonVue** [comment] 2024-12-05 11:02
I found another way out for this situation in the url request and tag request responds differently

To solve this I used postman with the help of postman sent a request copied the result and used it in local then everything works fine

**Comment by ekosuprianto96** [comment] 2025-04-07 18:34
The main issue occurs when pasting code. Some parts of the code are not loaded correctly after pasting. The solution is to visit the 
CDN link, then press CTRL+S to download all the files, without exception.

This worked 100% for me. Thank you!
