### ISSUE TITLE
Implement the unmerge cells command

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6567] opened 2020-04-07 09:27 UTC
## 📝 Provide a description of the new feature

https://github.com/ckeditor/ckeditor5/issues/6486 brought an easy way to merge table cells with a single click.

But there's no way to go the opposite direction, especially when "undo" is no go because you created a lot of content since the cells were merged.

Something like "unmerge cells" command would be great for that and we could even make the "merge cells" button use it when the selection is in a merged region of a table. This way in one click you would be able to merge lots of cells and with another click bring back the initial structure.

![2020-04-07 11 23 38](https://user-images.githubusercontent.com/1099479/78652888-9eb6f380-78c2-11ea-9802-a7b90bf590ed.gif)

cc @Reinmar @jodator 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment] 2020-04-07 09:55
Dup of: #3174.

**Comment by mlewand** [comment] 2020-04-27 08:16
Indeed looks like a duplicate of #3174.

**Closed by mlewand** 2020-04-27 08:16 UTC
Labels: package:table, status:discussion, type:feature
