### ISSUE TITLE
NPM update, new version causing error: "Some CKEditor 5 modules are duplicated"

### ISSUE THREAD

**Issue by jcroucher** [ckeditor/ckeditor5#1821] opened 2019-06-18 05:29 UTC
🐞 Bug report

## 💻 Version of CKEditor

@ckeditor/ckeditor5-core:  ^12.1.1
@ckeditor/ckeditor5-engine: 13.1.1
@ckeditor/ckeditor5-ui: 13.0.0
@ckeditor/ckeditor5-utils: 12.1.1

## 📋 Steps to reproduce

My code has been working fine, until I did an NPM update. 
I reverted the package files, deleted the node-modules directory, re init npm and it works again.
Just to confirm, I did another npm update and it breaks again.

This is the working version
```
@ckeditor/ckeditor5-editor-inline": {
  **"version": "12.1.0",**
  "resolved": "https://registry.npmjs.org/@ckeditor/ckeditor5-editor-inline/-/ckeditor5-editor-inline-12.1.0.tgz",
  "integrity": "sha512-7GPerfMVqrru5xwpIbfFsFw1cz+6fnSPDsaE/lCLu0SwM3Th8AQFZpi3+pNrvuXTxGza6u+n7X9Mf6IaDP1f+w==",
  "dev": true,
  "requires": {
    **"@ckeditor/ckeditor5-core": "^12.1.0",
    "@ckeditor/ckeditor5-engine": "^13.1.0",
    "@ckeditor/ckeditor5-ui": "^12.1.0",
    "@ckeditor/ckeditor5-utils": "^12.1.0",
    "lodash-es": "^4.17.10"**
}


    "@ckeditor/ckeditor5-alignment": "^11.1.0",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.0",
    "@ckeditor/ckeditor5-block-quote": "^11.0.1",
    "@ckeditor/ckeditor5-build-classic": "^12.1.0",
    "@ckeditor/ckeditor5-build-inline": "^12.1.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.0",
    "@ckeditor/ckeditor5-editor-inline": "^12.1.0",
    "@ckeditor/ckeditor5-essentials": "^11.0.1",
    "@ckeditor/ckeditor5-font": "^11.1.0",
    "@ckeditor/ckeditor5-heading": "^11.0.1",
    "@ckeditor/ckeditor5-link": "^11.0.1",
    "@ckeditor/ckeditor5-list": "^12.0.1",
    "@ckeditor/ckeditor5-media-embed": "^11.1.0",
    "@ckeditor/ckeditor5-paragraph": "^11.0.1",
    "@ckeditor/ckeditor5-remove-format": "^10.0.0",
    "@ckeditor/ckeditor5-table": "^12.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^13.0.1",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.2",
```
This version breaks
```
@ckeditor/ckeditor5-editor-inline": {
  **"version": "12.1.1",**
  "resolved": "https://registry.npmjs.org/@ckeditor/ckeditor5-editor-inline/-/ckeditor5-editor-inline-12.1.1.tgz",
  "integrity": "sha512-ZmhF6t8FZIrsssCJ0wm47/S+OAsL0LgL9f5zOBfQHvcQtTCJDDYe+czSvBmZRQ2IR9oNB2WGYMXiF68KX4R1fA==",
  "dev": true,
  "requires": {
    **"@ckeditor/ckeditor5-core": "^12.1.1",
    "@ckeditor/ckeditor5-engine": "^13.1.1",
    "@ckeditor/ckeditor5-ui": "^13.0.0",
    "@ckeditor/ckeditor5-utils": "^12.1.1",
    "lodash-es": "^4.17.10"**
},

    "@ckeditor/ckeditor5-alignment": "^11.1.1",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.1",
    "@ckeditor/ckeditor5-block-quote": "^11.1.0",
    "@ckeditor/ckeditor5-build-classic": "^12.2.0",
    "@ckeditor/ckeditor5-build-inline": "^12.2.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.1",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.1",
    "@ckeditor/ckeditor5-editor-inline": "^12.1.1",
    "@ckeditor/ckeditor5-essentials": "^11.0.2",
    "@ckeditor/ckeditor5-font": "^11.1.1",
    "@ckeditor/ckeditor5-heading": "^11.0.2",
    "@ckeditor/ckeditor5-link": "^11.0.2",
    "@ckeditor/ckeditor5-list": "^12.0.2",
    "@ckeditor/ckeditor5-media-embed": "^11.1.1",
    "@ckeditor/ckeditor5-paragraph": "^11.0.2",
    "@ckeditor/ckeditor5-remove-format": "^10.0.1",
    "@ckeditor/ckeditor5-table": "^12.0.1",
    "@ckeditor/ckeditor5-theme-lark": "^13.0.1",
    "@ckeditor/ckeditor5-vue": "^1.0.0-beta.2",
```
The error is
```
ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. 
```
I also reduced my code to only the one include disabling all the plugins
```
import InlineEditor from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor'
```
It still produced the duplicate modules error.

## 📃 Package Files

[package-lock.json-BROKEN.txt](https://github.com/ckeditor/ckeditor5/files/3299889/package-lock.json-BROKEN.txt)
[package-lock.json-WORKING.txt](https://github.com/ckeditor/ckeditor5/files/3299890/package-lock.json-WORKING.txt)
[package.json.txt](https://github.com/ckeditor/ckeditor5/files/3299891/package.json.txt)

**Comment by jodator** [comment] 2019-06-18 08:27
Looks like more problems related to this are arising: https://github.com/ckeditor/ckeditor5-vue/issues/72.
It's probably due to [outdated ckeditor-vue package](https://github.com/ckeditor/ckeditor5-vue/issues/72#issuecomment-502009765).

> I can see that ckeditor5-vue wasn't updated to the latest versions of the packages and there are packages required in two different versions. First checked was "ckeditor5-build-classic": yours is "12.1.0" and vue's one is: "^11.0.1". So it might looks like before the ckeditor5-vue will not get updated you should use older packages for vue builds.

**Comment by KenLFG** [comment] 2019-06-30 21:34
Any movement on this at all? Is there a workaround for this? I have a demo in two days and this couldn't have come up at a worse time...

**Comment by jcroucher** [comment] 2019-06-30 23:45
Revert your versions in package list. It is the only thing I found at the moment to get around the issue.
It should at least get you through the demo.

**Comment by KenLFG** [comment] 2019-07-01 01:08
I tried that, trying to push everything back to 11.x but didn't seem to do the trick. I ended up switching to a non-custom build for the time being. Just going to have to brush past the fancier features. :)

**Comment by TehWazzard** [comment] 2019-07-18 10:06
I'm getting similar errors. I have noticed the npm dependancy resolution is doing something odd.

what I found is a package such as `ckeditor5-image` has a `ckeditor5-widget` requirement of `^11.02`
however this was being resolved as `^11.0.3` somehow which has a different requirement of other packages such as core. I'm assuming this defaults to the next stable minor version.

I was relying on npm to resolve this for me - it seems it's better to add these packages manually.
running `npm i @ckeditor/ckeditor5-widget@11.0.2` seems to have reduced my duplicate count by 1
so I'm guessing that I just have go through this exercise and ensure that all packages (and their resolved dependancies) are pointing to the same _ckeditor5-core_ version.

**Comment by usb248** [comment] 2019-08-27 20:39
Any news/fix ? Same error...

**Comment by cedx** [comment] 2019-08-29 08:43
Same problem here.
Doing a clean install (i.e. `rm -rf node_modules && npm install`),
followed by a [`npm dedupe`](https://docs.npmjs.com/cli/dedupe.html) fixed the issue.

**Comment by usb248** [comment] 2019-08-30 18:22
`npm dedupe` command change anything after removing node_modules and even package-lock

**Comment by Reinmar** [comment] 2019-11-04 10:30
We changed the versioning policy when working on #1746 (which I think is a DUP of this ticket). The new policy is described in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/versioning-policy.html and should prevent many situations in which npm/yarn will install duplicated packages. The tl;dr is that all CKE5 packages will now be in the same major version (similar to babel and angular).

I'm closing this ticket, assuming that the change will help for the issue described here too. Please correct me if I'm wrong.

**Closed by Reinmar** 2019-11-04 10:30 UTC
Labels: status:confirmed, type:bug

**Comment by zhangkuiworld** [comment] 2019-11-12 03:34
@Reinmar So, what's the final solution ？I can't fix this bug in any way now. Can you update a version to fix this bug.

**Comment by tanmaymishu** [comment] 2019-11-22 03:05
Same issue here!

**Comment by Raggaer** [comment] 2019-11-25 19:45
Same issue, even only importing the Essentials plugin gives me this error.

**Comment by zhangkuiworld** [comment] 2019-11-26 02:56
> Same issue, even only importing the Essentials plugin gives me this error.

me too.

**Comment by syntheticgoo** [comment] 2019-12-04 20:53
> We changed the versioning policy when working on #1746 (which I think is a DUP of this ticket). The new policy is described in https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/versioning-policy.html and should prevent many situations in which npm/yarn will install duplicated packages. The tl;dr is that all CKE5 packages will now be in the same major version (similar to babel and angular).
> 
> I'm closing this ticket, assuming that the change will help for the issue described here too. Please correct me if I'm wrong.

Problem still exists. Specifically for me npm will install ckeditor5-editor-classic ^15.0.0.0, but install ckeditor5-image ^16.0.0

**Comment by ChristophWurst** [comment] 2019-12-09 19:08
Hi, I can confirm that this is still an issue.

**Comment by Ethaan** [comment] 2019-12-11 20:53
getting in this React, by just installing the `Mention` plugin with the ballon plugin

```
const CKEditor = require('@ckeditor/ckeditor5-react');
const BallonEditor = require('@ckeditor/ckeditor5-build-balloon-block');
// const Mention = require('@ckeditor/ckeditor5-mention/src/mention');
```

**Comment by shavidze** [comment] 2020-01-09 12:27
Don't import any modules which are included in the build. 
![image](https://user-images.githubusercontent.com/23502763/72066864-879e4080-3296-11ea-863a-57b81efb6917.png)

you can use them without import

**Comment by kyle-ssg** [comment] 2020-01-27 21:56
Getting this simply trying to add the font plugin, all I want to do is have the ClassicEditor + the ability to select font colour... 

```
            <CKEditor
              config={{
                  plugins: [
                      ...ClassicEditor.builtinPlugins,
                      require('@ckeditor/ckeditor5-font/src/font')
                  ],
                  toolbar: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
              }}
              editor={ClassicEditor}
```

**Comment by robclancy** [comment] 2020-01-28 23:50
Make sure everything is the same version. Then if you have issues still then you need to tell yarn/npm not to get multiple versions.
You can see where I have had to do this for a custom fork:
```json
  "resolutions": {
    "@ckeditor/ckeditor5-upload": "https://github.com/robclancy/ckeditor5-upload.git#patch-2"
  },
```
Find the duplicate module (check for nested `node_modules` in the `@ckeditor` directory) and force them to the correct version.

This information should be part of the error. In fact I think the error should say the different versions that have been loaded.

**Comment by ma2ciek** [comment] 2020-01-29 09:06
Hi!

The other great tool is [https://www.npmjs.com/package/npm-check-updates](https://www.npmjs.com/package/npm-check-updates) - it can check if all your packages are at the same version.

Also, there's a plan to work on the webpack plugin that could check and distinguish most of the duplication errors on the compilation time, so it'd give more accurate hints about the reason of this error - [https://github.com/ckeditor/ckeditor5/issues/1692](https://github.com/ckeditor/ckeditor5/issues/1692).

**Comment by AlexisPro765** [comment] 2020-02-24 16:28
- k

**Comment by sandeepimpressads** [comment] 2020-02-25 06:05
This worked for me https://github.com/ckeditor/ckeditor5-vue/issues/72#issuecomment-502483223
