### ISSUE TITLE
Browser-Addon LanguageTool: one-click-correction stopped working with 35.3.0

### ISSUE THREAD

**Issue by TobiasHartlehnert** [ckeditor/ckeditor5#12824] opened 2022-11-09 15:44 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Install and activate browser-addon "LanguageTool" ([Chrome Webstore](https://chrome.google.com/webstore/detail/grammar-spell-checker-%E2%80%94-l/oldceeleldhonbafppcapldpdifcinji?hl=de), [Firefox Addons](https://addons.mozilla.org/de/firefox/addon/languagetool/))
2. Navigate to [Classic Editor example](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)
3. Click inside the editing area; LanguageTool will underline "earth" in first paragraph as a possible error
4. Click anywhere inside "earth" to open the LanguageTool correction box
5. Click on the suggested correction "earth," (blue button)

### ✔️ Expected result

"earth" should change to "earth,"

### ❌ Actual result

Text is not changed. JS error is thrown, see Console (Chrome: "Uncaught TypeError: Cannot read properties of null (reading 'root') ...", Firefox: "Uncaught CKEditorError: i is null ...").

## 📃 Other details

* Browser: Chrome 107.0.5304.106, Firefox 106.0.5
* OS: Windows 10 Pro
* First affected CKEditor version: 35.3.0

---

We had to downgrade to CKEditor5 35.2.1, because a lot of our clients are using the LanguageTool. Until this is fixed, we can't upgrade to any future version of CKEditor5 :(

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment] 2022-11-09 17:21
It looks like this browser extension is using `beforeInput:insertText` but it is not providing `targetRanges` this might be easy to fix by enabling fallback to the DOM document selection.

**Comment by Reinmar** [comment] 2022-11-10 08:19
Could you also open issue to LanguageTool itself? Even if we can workaround this issue today, let's help them fix this so we have a cleaner situation in the future.

**Comment by TobiasHartlehnert** [comment] 2022-11-15 09:04
There you go: [LanguageTool issue](https://github.com/languagetool-org/languagetool/issues/7427)

**Comment by tiff** [comment] 2022-11-15 17:24
I'm one of the developers behind LanguageTool. First, thanks for being helpful and constructive.

@niegowski it seems there's no way for us to set “target ranges” when simulating the `beforeinput` event. At least, I'm not aware of any viable approach. If you are, I'd be happy if you could point me towards the corresponding documentation.
What do you mean by enabling the document selection fallback? I guess that's something you would have to do on your end?
In general, we are also in favor of solving this on our end and are already investigating this.

**Comment by tiff** [comment] 2022-11-16 07:30
It seems that simply setting `targetRanges` in the second parameter of `new InputEvent(...)` fixes it. We will begin rolling out a fix next week. Feel free to close this issue.

**Comment by tiff** [comment] 2022-11-16 08:55
Hey @Reinmar unfortunately, we do not publish release candidates, but I will notify you once the update is available and promise that we will investigate further problems and regressions ✌️

**Comment by TobiasHartlehnert** [comment] 2022-11-23 10:54
@tiff works for me in Chrome. Thanks for the quick fix!

**Comment by Reinmar** [comment] 2022-11-23 18:56
Confirmed by our team as well. Thank you!

**Closed** 2022-11-24 09:04 UTC
Labels: type:bug, domain:ime, squad:core

**Comment by jensgerdes-dpa** [comment] 2023-04-27 07:47
> It looks like this browser extension is using `beforeInput:insertText` but it is not providing `targetRanges` this might be easy to fix by enabling fallback to the DOM document selection.

We are experiencing the same issue after having upgraded CKEditor with LanguageTool. The LT support has already been contacted to provide us with an update. However, we would very much appreciate if there is the possibility for a quick hotfix in the meantime.

Is "enabling fallback" a configuration option?

**Comment by Witoso** [comment] 2023-04-27 10:09
@jensgerdes-dpa to which version have you upgraded? I have not noticed issues with LT enabled in our docs.

**Comment by jensgerdes-dpa** [comment] 2023-04-27 10:26
@Witoso from 32.0.0 to the current one (37.1.0)

**Comment by tiff** [comment] 2023-04-27 10:38
@jensgerdes-dpa are you using our (LanguageTool's) browser add-on or our JavaScript library?

**Comment by Witoso** [comment] 2023-04-27 10:40
And what problems do you observe?

https://user-images.githubusercontent.com/9881379/234838804-c7ee6daf-d517-44a9-811e-f6e8ddac7499.mov

**Comment by jensgerdes-dpa** [comment] 2023-04-27 12:01
@Witoso When applying suggestions from LanguageTool like below

![applying-suggestion](https://user-images.githubusercontent.com/85099238/234852910-410b93bb-79e6-4425-8adc-902e6a0d5605.png)

we get the following Error in the JS console.

![js-error](https://user-images.githubusercontent.com/85099238/234852995-1c5f29d8-e2ec-459d-8c9c-922a8f90c9bd.png)

@tiff We are using your JS Library in combination with the self-hosted premium version of LanguageTool. For that purpose we received a JS file some years ago. This one - like with the browser add-on - does not provide a targetRange which causes the CKEditor to crash. 

While waiting for the LT support to send me an update I wondered if the change @niegowski mentioned could be a first hotfix: _enabling fallback to the DOM document selection_
