### ISSUE TITLE
When the first input is an image upload it wont let you select all the text and erase

### ISSUE THREAD

**Issue by melanke** [ckeditor/ckeditor5#5590] opened 2019-10-15 17:15 UTC
## 📝 Provide detailed reproduction steps (if any)

1. upload an image
2. press Ctrl+A (windows)
3. press DELETE

### ✔️ Expected result

*All the content get deleted*

### ❌ Actual result

*You only erase the last text character*

## 📃 Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 5 build classic 12.3.1
* Installed CKEditor plugins: upload and vue (but it happens on all CKEditor samples on official website)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2019-10-16 07:09
Hi, we are aware of this issue and your report is a duplicate of https://github.com/ckeditor/ckeditor5/issues/4584.

**Closed by Mgsy** 2019-10-16 07:09 UTC
Labels: type:bug
