### ISSUE TITLE
CKEditor is not working on Android with Gboard

### ISSUE THREAD

**Issue by miskotam** [ckeditor/ckeditor5#1786] opened 2019-05-30 13:30 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

12.0.0.

## 📋 Steps to reproduce

1. Open the classic editor on https://ckeditor.com/ckeditor-5/demo/ on Android
2. Remove every text from the ckeditor's text field
4. Type in "Text"
5. Switch off the Bold formatting option
6. Type in "t"

## ✅ Expected result
The text in the editor is "Text**t**".
## ❎ Actual result
The text in the editor is "Text**Textt**". Also, some formatting options are not working after Step 6. E.g. tapping on Bold, Italic buttons on the toolbar do nothing.
## 📃 Other details that might be useful
It only happens with Google's keyboard, Gboard. I have tried it on Android 7, 8, 9 in Chrome, Firefox, Opera and Mint Browser.

**Comment by jodator** [comment] 2019-05-30 13:54
I can confirm this with GBoard. When using Samsung keyboard you get "Textt" (without bolded "t" at the end). 

ps.: I'm not sure if this wasn't reported already as we are aware of some issues with typing on mobile devices

**Comment by scofalik** [comment] 2019-06-19 15:25
https://github.com/ckeditor/ckeditor5-typing/issues/167#issuecomment-503593962 contains research about GBoard and why it does not work.

**Comment by darkmiru** [comment] 2020-03-03 09:46
use "document.execCommand()" instead of "styleCommand".

1. selection.js - modify line 1472
```
	CKEDITOR.tools.extend( CKEDITOR.dom.selection, {
		_removeFillingCharSequenceString: removeFillingCharSequenceString,
		_createFillingCharSequenceNode: createFillingCharSequenceNode,
		_removeFillingCharSequenceNode: removeFillingCharSequenceNode, // add this line.

```

2. add config
```
        enterMode: CKEDITOR.ENTER_BR,
        coreStyles_bold: {
          element: 'b',
          overrides: 'strong'
        },
        coreStyles_italic: {
          element: 'i',
          overrides: 'em'
        },
        coreStyles_underline: {
          element: 'u'
        }
```

3.  add below code.
```
      var removeFillingChar = function(editor) {
        var selection = ckObj.getSelection();
        var ranges = selection.getRanges();
        var range = ranges[0];
        if (range && range.startContainer.equals(range.endContainer) && range.startOffset == range.endOffset) {
          var fillingChar = editor.editable().getCustomData( 'cke-fillingChar' );
          if (fillingChar) {
            var prevLen = fillingChar.$.length;
            if (prevLen > 7 && range.startContainer.equals(fillingChar)) {
              CKEDITOR.dom.selection._removeFillingCharSequenceNode(editor.editable(), false);
              var changedLen = prevLen - fillingChar.$.length;
              // range.moveToPosition( range.startContainer, range.startOffset - changedLen);
              var sel = selection.getNative();
              range.setStart(range.startContainer, range.startOffset - changedLen);
              range.setEnd(range.endContainer, range.endOffset - changedLen);

              var nativeRange = selection.document.$.createRange();
              nativeRange.setStart( range.startContainer.$, range.startOffset );
              try {
                nativeRange.setEnd( range.endContainer.$, range.endOffset );
              } catch ( e ) {
                // There is a bug in Firefox implementation (it would be too easy
                // otherwise). The new start can't be after the end (W3C says it can).
                // So, let's create a new range and collapse it to the desired point.
                if ( e.toString().indexOf( 'NS_ERROR_ILLEGAL_VALUE' ) >= 0 ) {
                  range.collapse( 1 );
                  nativeRange.setEnd( range.endContainer.$, range.endOffset );
                } else {
                  throw e;
                }
              }

              range.collapse(true);
              sel.removeAllRanges();
              sel.addRange( nativeRange );

              selection.reset();
            }
          }
        }
      }

      CKEDITOR.styleCommand.prototype.execOrigin = CKEDITOR.styleCommand.prototype.exec;

      CKEDITOR.styleCommand.prototype.exec = function( editor ) {
        editor.focus();

        console.log(' -------- ', this.style);
        switch (this.style.element) {
          case 'strong':
          case 'b':
            removeFillingChar(editor);
            editor.document.$.execCommand('bold');
            editor.getCommand('bold').toggleState();
            return;
          case 'em':
          case 'i':
            removeFillingChar(editor);
            editor.document.$.execCommand('italic');
            editor.getCommand('italic').toggleState();
            return;
          case 'u':
            removeFillingChar(editor);
            editor.document.$.execCommand('underline');
            editor.getCommand('underline').toggleState();
            return;
          case 's':
          case 'strike':
            removeFillingChar(editor);
            editor.document.$.execCommand('strike');
            editor.getCommand('strike').toggleState();
            return;
        }

        CKEDITOR.styleCommand.prototype.execOrigin(editor);
      };
```

**Comment by darkmiru** [comment] 2020-03-03 09:53
use "document.execCommand()" instead of "styleCommand"

(test in ckeditor4)
1. selection.js - modify line 1472
```
	CKEDITOR.tools.extend( CKEDITOR.dom.selection, {
		_removeFillingCharSequenceString: removeFillingCharSequenceString,
		_createFillingCharSequenceNode: createFillingCharSequenceNode,
		_removeFillingCharSequenceNode: removeFillingCharSequenceNode, // add this line.

```

2. add config
```
        enterMode: CKEDITOR.ENTER_BR,
        coreStyles_bold: {
          element: 'b',
          overrides: 'strong'
        },
        coreStyles_italic: {
          element: 'i',
          overrides: 'em'
        },
        coreStyles_underline: {
          element: 'u'
        }
```

3.  add below code.
```
      var removeFillingChar = function(editor) {
        var selection = ckObj.getSelection();
        var ranges = selection.getRanges();
        var range = ranges[0];
        if (range && range.startContainer.equals(range.endContainer) && range.startOffset == range.endOffset) {
          var fillingChar = editor.editable().getCustomData( 'cke-fillingChar' );
          if (fillingChar) {
            var prevLen = fillingChar.$.length;
            if (prevLen > 7 && range.startContainer.equals(fillingChar)) {
              CKEDITOR.dom.selection._removeFillingCharSequenceNode(editor.editable(), false);
              var changedLen = prevLen - fillingChar.$.length;
              // range.moveToPosition( range.startContainer, range.startOffset - changedLen);
              var sel = selection.getNative();
              range.setStart(range.startContainer, range.startOffset - changedLen);
              range.setEnd(range.endContainer, range.endOffset - changedLen);

              var nativeRange = selection.document.$.createRange();
              nativeRange.setStart( range.startContainer.$, range.startOffset );
              try {
                nativeRange.setEnd( range.endContainer.$, range.endOffset );
              } catch ( e ) {
                // There is a bug in Firefox implementation (it would be too easy
                // otherwise). The new start can't be after the end (W3C says it can).
                // So, let's create a new range and collapse it to the desired point.
                if ( e.toString().indexOf( 'NS_ERROR_ILLEGAL_VALUE' ) >= 0 ) {
                  range.collapse( 1 );
                  nativeRange.setEnd( range.endContainer.$, range.endOffset );
                } else {
                  throw e;
                }
              }

              range.collapse(true);
              sel.removeAllRanges();
              sel.addRange( nativeRange );

              selection.reset();
            }
          }
        }
      }

      CKEDITOR.styleCommand.prototype.execOrigin = CKEDITOR.styleCommand.prototype.exec;

      CKEDITOR.styleCommand.prototype.exec = function( editor ) {
        editor.focus();

        console.log(' -------- ', this.style);
        switch (this.style.element) {
          case 'strong':
          case 'b':
            removeFillingChar(editor);
            editor.document.$.execCommand('bold');
            editor.getCommand('bold').toggleState();
            return;
          case 'em':
          case 'i':
            removeFillingChar(editor);
            editor.document.$.execCommand('italic');
            editor.getCommand('italic').toggleState();
            return;
          case 'u':
            removeFillingChar(editor);
            editor.document.$.execCommand('underline');
            editor.getCommand('underline').toggleState();
            return;
          case 's':
          case 'strike':
            removeFillingChar(editor);
            editor.document.$.execCommand('strike');
            editor.getCommand('strike').toggleState();
            return;
        }

        CKEDITOR.styleCommand.prototype.execOrigin(editor);
      };
```

**Comment by mlewand** [comment] 2020-09-25 07:44
Another case reported in #8159

**Comment by mlewand** [comment] 2021-02-24 15:57
Another case I faced recently is that after typing a word I can't make a line break.


https://user-images.githubusercontent.com/5353898/109027623-48f95e80-76c1-11eb-8de3-8ed741142ef1.mp4

**Comment by cutlerrickel** [comment] 2021-04-06 02:17
> Another case I faced recently is that after typing a word I can't make a line break.
> 
>  21-02-24-16-14-59.mp4

Having this same exact issue with gboard. Any fixes I can apply to my build for the time being?
**To add:** 
Clicking enter button on gboard on mobile chrome does not do anything(see video above) if cursor is at the end of a line that ends in a regular letter character(a, b, c, etc).
- If the line ends with punctuation, ENTER works.
- If the cursor is in the middle of a line, ENTER works.
- If you select a gboard autocorrect recommendation, ENTER works.
- If you enter a space at the end of the line, ENTER works.

**Comment by StavM** [comment] 2021-04-11 10:22
Since XIAOMI phones have this keyboard as their default keyboard, a huge chunk of android users are unable to benefit from this library. 

-According to google, in India Xiaomi has around **30% market share** while Samsung for reference, has only 25%.

This should be a top priority issue by any scale.

**Comment by thisismeonmounteverest** [comment] 2023-07-09 10:39
We git several reports that CKEditor is not working on Samsung specifically with Firefox browsers. Seems to be related to the GBoard as well. I agree with @StavM this should be higher on the priority list as there are lot of users that never change their keyboard.

**Comment by mabryl** [comment] 2023-08-24 09:38
Just retested this on this kind of setup:

Device: Samsung A52s 5G
OS: Android 13
Keyboard: Gboard 13.2.04
Browsers: Chrome 116.0.5845.92 | Firefox 116.3.0

And I can confirm that the issue is no longer reproducible. Hence, closing the ticket.

**Closed by mabryl** 2023-08-24 09:38 UTC
Labels: type:bug, domain:ui/ux, browser:android
