### ISSUE TITLE
ckeditor5 changes markup when using 'Delete' on newline ('Enter')

### ISSUE THREAD

**Issue by JelleCallewaert** [ckeditor/ckeditor5#1630] opened 2019-03-14 08:58 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

CKEditor version: 1.0.1
Build type: classic and document

## 📋 Steps to reproduce

1. Select 'Heading 1'
2. Type "This is Heading 1" on the first line and press 'Enter'
3. Select 'Heading 3'
4. Type "This is Heading 3" on the second line and press 'Enter'
5. Select the entire first line ("This is Heading 1") and remove it
6. Press 'Delete' to remove the 'Enter'

## ✅ Expected result

The remaining line ("This is Heading 3") keeps its markup: 'Heading 3'

## ❎ Actual result

It changes to 'Heading 1'

## 📃 Other details that might be useful

Don't know if it's meant this way, but it seems counter-intuitive

**Comment by Mgsy** [comment] 2019-03-14 09:07
Hello, the behaviour you've described is not a bug and it's made by design.

**Comment by Reinmar** [comment] 2019-03-14 09:23
> 6\. Press 'Delete' to remove the 'Enter'

Do you mean the "delete" key on the Windows/Linux keyboard which can be understood as "forward delete"? Let's clarify this because on macOS keyboard "delete" means "backward delete", but from your TC I think you mean "forward delete".

In this case, this is actually a valid ticket. And it's a DUP of https://github.com/ckeditor/ckeditor5-typing/issues/146 in which we already discussed the behaviour here could be different.

Could you confirm that I understood your TC correctly?

**Comment by JelleCallewaert** [comment] 2019-03-14 10:30
Yes, that is exactly what I meant. On a Windows pc : the 'delete' key (usually above the 'backspace').
Like the key that removes characters on the right of the cursor.

It is exactly what jodator describes in your reference:
https://github.com/ckeditor/ckeditor5-typing/issues/146#issuecomment-466053048

**Comment by Reinmar** [comment] 2019-03-18 10:14
OK, thanks. So I'm closing this issue as a dup of ckeditor/ckeditor5-typing#146

**Closed by Reinmar** 2019-03-18 10:14 UTC
Labels: resolution:duplicate
