### ISSUE TITLE
Cursor misbehave when invoking bold with cursor placed inside bolded word

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#630] opened 2017-10-25 10:25 UTC
## 🐞 Is this a bug report or feature request?

- [x] Bug report
- [ ] Feature request

## 💻 Version of CKEditor

`alpha-1`

## 📋 Steps to reproduce

1. Place cursor in some text (here I've found that on bolded `us`).
2. Press `ctrl+b` several times.

## ✅ Expected result
Cursor should stay in the same position.

## ❎ Actual result
Cursor 'dances'.

## 📃 Other details that might be useful
This cursor shift happens due to split of `<strong>`( `<strong>u|s<strong>` <=> `<strong>u</strong>|<strong>s</strong>`) in editing area.

![screencast 2017-10-25 11_56_50](https://user-images.githubusercontent.com/247363/31993633-1cfc328e-b97e-11e7-9710-df60c7b37568.gif)

Similar thing happen with Browser's spellchecker which detects word split:
![selection_011](https://user-images.githubusercontent.com/247363/31993983-4cc3ca30-b97f-11e7-843a-d51319f0dc44.png)

**Comment by oleq** [comment] 2017-10-25 10:29
I think I've seen a similar issue in the past but I couldn't find it. @pjasiun @scofalik?

**Comment by scofalik** [comment] 2017-10-25 10:34
The original issue is most probably a browser issue. When bold is turned off, editor data is `<strong>u</strong>[]<strong>s</strong>`. When it is on, the attributes are merged. This probably makes the caret to change its position.

The second issue (native spellchecker) is caused by the very same reason.

**Comment by jodator** [comment] 2017-10-25 10:35
I've found this: https://github.com/ckeditor/ckeditor5/issues/500:

> Clicking on these links gives the impression that we're constantly breaking words in parts. In fact, the spell checking underline goes a bit crazy with it.

**Comment by oleq** [comment] 2017-10-25 11:08
> The second issue (native spellchecker) is caused by the very same reason.

Can we do anything about that? I'm not worried about wiggly caret because it's a minor annoyance. The native spell checker is the real issue here—it's a feature users really use and if it's broken, it could be a serious blocker.

**Comment by oleq** [comment] 2017-10-25 11:12
I see that the issue is gone as soon as the selection changes. I guess the engine merges adjacent elements at that point and this is some generic mechanism. Could it also happen when the command was executed?
![kapture 2017-10-25 at 13 10 26](https://user-images.githubusercontent.com/1099479/31995722-e5a2bcd8-b985-11e7-979b-b6cbc6bccfb2.gif)

**Comment by Reinmar** [comment] 2017-11-15 15:57
The dancing caret is not a bug – I mean – not something worth our time.

The spellchecker is worse but it's something we can't solve with the current state of contentEditable. Actually, the problem with applying bold inside a middle of a word is not important, but the same happens with selections of other users.

I'm closing as "can't fix".

**Closed by Reinmar** 2017-11-15 15:57 UTC
