### ISSUE TITLE
mentions now work after some chars

### ISSUE THREAD

**Issue by xinglie** [ckeditor/ckeditor5#8525] opened 2020-11-25 10:03 UTC
## 📝 Provide detailed reproduction steps (if any)

1. visit https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html 
2. use the demo of the page
3. put caret at the end of editor content ,  press `@`

### ✔️ Expected result

show mentions list

### ❌ Actual result

nothing happen

## 📃 Other details

![gs](https://user-images.githubusercontent.com/1290017/100212605-8591ae80-2f48-11eb-9d99-0fef75adb98b.gif)

if add space and press `@` again , mentions work

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2020-11-25 10:32
Hi, this is not a bug - it's how the `Mentions` plugin is designed. You need a space before the marker in order to trigger rendering of the dropdown list.  
If you would like to propose a change to this behavior, please create a feature/improvement request.  
I'll close this ticket for now.

**Closed by FilipTokarski** 2020-11-25 10:32 UTC
Labels: type:bug
