### ISSUE TITLE
Is content produced by CKEditor 5 accessible?

### ISSUE THREAD

**Issue by darithpen** [ckeditor/ckeditor5#1908] opened 2019-07-23 22:34 UTC
I know this question is a bit odd, but is HTML text produced by CKEditor5 already accessible? Because the way that CKEditor5 works is that users cannot modify HTML elements directly unlike it's predecessor where users can go to source mode to change anything. In CKEditor5, everything users type must go through predefined views, then models, and vise versa. For example, user cannot change a text color to non-predefined colors attribute.
By the way, I tried to find an accessibility checker plugin that is similar to the version 4 but found nothing, any recommendation?

**Comment by juleskuehn** [comment] 2019-07-25 15:26
While it is possible to create content that doesn't follow WCAG 2.1 with the editor (ex. incorrect use of headings, missing alt text, low contrast), it is also possible to create content that does.

**Comment by Mgsy** [comment] 2019-07-30 11:18
cc @Reinmar

**Comment by Reinmar** [comment] 2019-08-05 14:49
Just like @juleskuehn wrote – you can now use CKEditor 5 for good and for evil.

The situation is a bit different than in CKEditor 4 because many features work now differently and there's far less focus on formatting and visual aspects of the content, which turns more of your focus on the semantics of it. Also, the actual HTML that we produce [was designed with a11y in mind](https://ckeditor.com/blog/Editor-Recommendations-Project/). But of course, none of these can ensure that the content is accessible.

In order to ensure that the user filled all the `alt`s and didn't abuse inline styling over proper formatting, etc., we'd have to implement a similar feature to [CKEditor 4's accessibility checker](https://ckeditor.com/ckeditor-4/accessibility-checker/). That's not on our roadmap yet, but we'd certainly like to see such a feature.

**Comment by Reinmar** [comment] 2019-08-05 14:52
I reported https://github.com/ckeditor/ckeditor5/issues/1941 to track accessibility checker for CKE5. I'm closing this ticket because I think the question was answered. If not, feel free to ping me.

**Closed by Reinmar** 2019-08-05 14:52 UTC
