### ISSUE TITLE
angular/cli ckeditor5 InlineEditor - balloon is place outside of app-root and so won't display

### ISSUE THREAD

**Issue by grimace** [ckeditor/ckeditor5#1766] opened 2019-05-20 20:21 UTC
## Is this a bug report or feature request? (choose one)
 **Other**

## 💻 Version of CKEditor
12.1.0 from npm

## 📋 Steps to reproduce

1. build an angular project, add ckeditor5 via npm
2. startEditor on click for html element

## ✅ Expected result
be able to edit and style dom element

## ❎ Actual result
balloon for styling is added outside of app-root
## 📃 Other details that might be useful
is there a way to specify the container for the balloon as well as specify the element that needs editing?

**Comment by Mgsy** [comment] 2019-05-21 07:50
It's a duplicate of https://github.com/ckeditor/ckeditor5-angular/issues/107.

**Closed by Mgsy** 2019-05-21 07:50 UTC
