### ISSUE TITLE
Puppeteer reports a weird warning

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#14063] opened 2023-05-08 11:27 UTC
## 📝 Provide detailed reproduction steps (if any)

1. `yarn run docs`
2. `yarn run docs:serve`
3. In a new tab: `yarn run docs:verify`

### ✔️ Expected result

No errors, or warnings. The process should check if the documentation is built correctly.

### ❌ Actual result

```
  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
```

```
🔥 The following errors have been found:

 RESPONSE FAILURE   ➜  1 error

  ❌ Failed to load resource from fake.ckeditor.com:8080 (HTTP response status code: 404)

    …found on the following pages:
    ➥  http://fake.ckeditor.com:8080/ckeditor5/latest/
    ➥  http://fake.ckeditor.com:8080/ckeditor5/latest/examples/index.html
    ➥  http://fake.ckeditor.com:8080/ckeditor5/latest/installation/index.html
```

**Comment by przemyslaw-zan** [comment] 2023-05-08 17:06
### The error

Initially I've got the same 404 response from `fake.ckeditor.com` error after launching the crawler. However, when I've adjusted my `hosts` file [as our docs suggest](https://github.com/ckeditor/ckeditor5/blob/78466837d66f43ae6609030af05f6a294aec19f8/docs/framework/contributing/development-environment.md?plain=1#LL156C109-L156C109), the crawler passed entire documentation successfully, without any errors. This seems weird, as this script worked for me previously despite the fact that I've never configured my `hosts` file before.

Regardless, current behavior looks correct, and I was not able to reproduce the exact error described in the ticket.

---

### The warning

Puppeteer will be migrating to new implementation of `headless` Chrome in the near future. 

We can test this right now by passing `headless: 'new'` to [browserOptions](https://github.com/ckeditor/ckeditor5-dev/blob/f32f08f4e9aeef99b49063d191d115f33a9f2370/packages/ckeditor5-dev-web-crawler/lib/runcrawler.js#L129) object. Unfortunately, this does not work out of the box, and [this line](https://github.com/ckeditor/ckeditor5-dev/blob/f32f08f4e9aeef99b49063d191d115f33a9f2370/packages/ckeditor5-dev-web-crawler/lib/runcrawler.js#L458) throws this error:

```
ProtocolError: Protocol error (Target.createTarget): Failed to open a new tab
```

More research is needed into the topic of migration. 

The [chrome.com](https://developer.chrome.com/articles/new-headless/#try-out-the-new-headless) article mentions:

>As part of this removal, we’ll make the old Headless available as a separate standalone binary for those users who can’t upgrade yet.

So in case that we are not able to migrate, there will be alternatives for us.

As a temporary measure, we can pass `headless: 'old'` to [browserOptions](https://github.com/ckeditor/ckeditor5-dev/blob/f32f08f4e9aeef99b49063d191d115f33a9f2370/packages/ckeditor5-dev-web-crawler/lib/runcrawler.js#L129) object to disable the warning.

**Comment by pomek** [comment] 2023-05-09 07:07
Let's hide this warning and switch to the new headless browser in the future (as it requires upgrading Puppeteer too).

**Comment by przemyslaw-zan** [comment] 2023-05-10 07:26
Closed in:
- ckeditor/ckeditor5-dev#873

**Closed by przemyslaw-zan** 2023-05-10 07:26 UTC
Labels: type:bug, squad:devops, package:dev, status:in-progress

**Comment by Iano-theDev** [comment] 2023-07-26 15:05
I had this issue while runnig puppeteer on WSL... I thought the issue was wsl but after installing node for windows I got the same issue!

**Comment by aynjel** [comment] 2023-08-20 02:46
how to fix this issue?

**Comment by Witoso** [comment] 2023-08-21 07:10
@aynjel unless you have this error in relation to CKEditor 5, we cannot offer much help here. We solved on our side with a:

> As a temporary measure, we can pass `headless: 'old'` to [browserOptions](https://github.com/ckeditor/ckeditor5-dev/blob/f32f08f4e9aeef99b49063d191d115f33a9f2370/packages/ckeditor5-dev-web-crawler/lib/runcrawler.js#L129) object to disable the warning.
