### ISSUE TITLE
v11.2.0 classic editor build (latest version) blockquote bug

### ISSUE THREAD

**Issue by gongzhiq** [ckeditor/ckeditor5#1442] opened 2019-01-07 02:56 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

v11.2.0 classic editor build (latest version)

## 📋 Steps to reproduce

![small8](https://user-images.githubusercontent.com/5800062/50746036-23eacd00-1268-11e9-9cdc-b1527eb43155.gif)

copy before

![66c648a2-3813-44fc-9c0e-2826cffd1698](https://user-images.githubusercontent.com/5800062/50746116-8774fa80-1268-11e9-95f4-666830843c72.png)

copy after

![31f55799-8298-4660-b9c3-f9586ecaf47f](https://user-images.githubusercontent.com/5800062/50746126-8d6adb80-1268-11e9-8e43-957399e5af70.png)

**Comment by f1ames** [comment] 2019-01-07 10:05
Looks like it might be an issue with list plugin. @gongzhiq could you provide an URL from which you have copied the content? I'm not able to reproduce the issue without it. Which browser have you tested on?

**Comment by gongzhiq** [comment] 2019-01-08 03:01
@f1ames browser is  Safari  12.0.1 (13606.2.104.1.2)

**Comment by gongzhiq** [comment] 2019-01-08 03:09
@f1ames link is https://mp.weixin.qq.com/s/zLU5tZlLRTJNBXpErPePvQ

**Comment by Mgsy** [comment] 2019-03-06 10:10
@gongzhiq, if I correctly understood, your problem is that the last paragraph is merged to the blockquote after paste? 

If so, please retest it on the latest released version, because I'm not able to reproduce it.

**Comment by gongzhiq** [comment] 2019-03-08 03:22
@Mgsy YES

**Comment by Mgsy** [comment] 2019-03-12 10:14
>@Mgsy YES

Okay, so are you able to reproduce it on the latest version of CKEditor 5?

**Comment by gongzhiq** [comment] 2019-03-13 06:50
@Mgsy Hello, I did a test in the new edition. There is no problem. Thank you very much.

**Comment by Mgsy** [comment] 2019-03-13 08:16
That's great to hear!

**Closed by Mgsy** 2019-03-13 08:16 UTC
Labels: status:pending, type:bug
