### ISSUE TITLE
Multi-root editor on Safari: cannot focus root which has table of contents or media inside

### ISSUE THREAD

**Issue by kubaklatt** [ckeditor/ckeditor5#16978] opened 2024-08-27 12:09 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open a manual test that uses multi-root, for example [all-features-rtc-multi-root.html](http://localhost:8125/ckeditor5/external/ckeditor5-commercial/packages/ckeditor5-collaboration/tests/manual/all-features-rtc-multi-root.html)
2. Insert table of contents or media inside one of the roots
3. Focus on the other root and then try focusing the root with content inside (but do not click on the table of contents or the media)

### ✔️ Expected result

Focus should stay in the root, just like it looks on for example Google Chrome

https://github.com/user-attachments/assets/f812543d-99fa-4524-a1e9-bb461cb5ce64

### ❌ Actual result

Focus jumps back to the other root

https://github.com/user-attachments/assets/36482ca7-f863-47c3-902c-1b52dea29a9a

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Safari
* OS: any
* First affected CKEditor version: N/A
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mati365** [comment] 2024-08-29 06:35
It looks like range calculation in Chrome and Safari is not standardized enough to make it work identically. It's not regression on our end, but we can bypass it I think. More explanation here:  https://github.com/ckeditor/ckeditor5/pull/16997

**Comment by pomek** [comment] 2024-09-02 11:54
Fixed in https://github.com/ckeditor/ckeditor5/pull/16997.

**Closed by pomek** 2024-09-02 11:54 UTC
Labels: type:bug, browser:safari, squad:core, release:blocker, status:in-progress, package:editor-multi-root
