### ISSUE TITLE
Text part language dropdown is unusable when having a large number of allowed languages

### ISSUE THREAD

**Issue by DuaelFr** [ckeditor/ckeditor5#15715] opened 2024-01-17 13:22 UTC
## 📝 Provide detailed reproduction steps (if any)

1. configure an editor with the TextPartLanguage plugin enabled
2. allow more than 30-40 languages (more than necessary to have a dropdown bigger than your viewport)
3. open the dropdown and try to get to the end of the list

### ✔️ Expected result

You can scroll inside the dropdown to get to the language you want.

### ❌ Actual result

You need to scroll down the page (if possible) to get to the language you want. Under certain circumstances (global CSS preventing scrolling) you cannot reach the part of the dropdown overflowing the screen.

### ❓ Possible solution

Use CSS to make that dropdown scrollable when its height is bigger than the viewport or the editor.
For example:
```css
.ck-text-fragment-language-dropdown .ck-dropdown__panel {
  overflow-x: auto;
  max-height: var(--ck-dialog-max-height);
}
```

## 📃 Other details

* Browser: All
* OS: All
* First affected CKEditor version: 5
* Installed CKEditor plugins: Doesn't matter

This issue has been detected first on Drupal: https://www.drupal.org/project/drupal/issues/3375157

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment] 2024-01-18 08:11
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/952. We tried to make it work in the past but there were [issues](https://github.com/ckeditor/ckeditor5/issues/3416) and we had to revert changes. I think we could make a second attempt now that [tooltips are floating elements](https://github.com/ckeditor/ckeditor5/pull/12262) and are no longer hosted by buttons.

**Closed** 2024-01-18 08:18 UTC
Labels: type:bug, domain:ui/ux, package:language
