### ISSUE TITLE
Editor loses focus after using styles dropdown

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5#12125] opened 2022-07-22 07:26 UTC
## 📝 Provide detailed reproduction steps (if any)

1.  Open a sample with styles dropdown feature.
2.  Focus somewhere in the editor.
3.  Use the styles dropdown to set a style.

### ✔️ Expected result

After the style is set, the focus should be back in the editor.

### ❌ Actual result

The focus is not back, I cannot type.

## 📃 Other details

This is a regression. Possibly connected with recent a11y changes?

**Comment by mlewand** [comment] 2022-07-22 08:06
The solution should be similar to #12121.

**Comment by mlewand** [comment] 2022-07-22 08:37
We had two options:

*   Do a proper fix in the dropdown UI component to place the focus back to (closed) dropdown component (the button).
*   ~Do dedicated listeners that would put focus to the editor editing view - however we can't do this because it won't work for customers code that already uses this component. So this would break.~

So we need to go with the first option and fix it in the original UI component.

Additionally we'll have to add explicit editing view focus in features that should override this behavior (example: heading dropdown, style dropdown).

**Comment by Reinmar** [comment] 2022-07-22 08:52
Example of a feature that SHOULD but DOESN'T put focus in the editor editing view:

[https://github.com/ckeditor/ckeditor5/blob/77c951c35c676a8deea1569276357e73c841a20b/packages/ckeditor5-style/src/styleui.js#L88-L91](https://github.com/ckeditor/ckeditor5/blob/77c951c35c676a8deea1569276357e73c841a20b/packages/ckeditor5-style/src/styleui.js#L88-L91)

Example of a feature that SHOULD and DOES it:

https://github.com/ckeditor/ckeditor5/blob/77c951c35c676a8deea1569276357e73c841a20b/packages/ckeditor5-heading/src/headingui.js#L106-L110

**Comment by Dumluregn** [comment] 2022-07-25 14:24
List of examined features - with focus on the toolbar button but before adding dedicated focusers in the features:

| Dropdown | Toolbar | Expected focus | Actual | Correct? |
| --- | --- | --- | --- | --- |
| Placeholder (from "Implementing an inline widget" tutorial) | Main | Editing | Editing | :white\_check\_mark:  |
| Text/background colour | Main | Editing | Editing | :white\_check\_mark:  |
| Font family | Main | Editing | Editing | :white\_check\_mark:  |
| Font size | Main | Editing | Editing | :white\_check\_mark:  |
| Heading | Main | Editing | Editing | :white\_check\_mark:  |
| Image resize | Image | Editing | Editing | :white\_check\_mark:  |
| Text part language | Main | Editing | Editing | :white\_check\_mark:  |
| Restricted editing | Main | Editing | Editing | :white\_check\_mark:  |
| Table | Main | Editing | Editing | :white\_check\_mark:  |
| Image break text/wrap text | Image | Editing | Button | :x: |
| Highlight | Main | Editing | Button | :x: |
| List | Main | Editing | Button | :x: |
| Text alignment | Main | Editing | Button | :x: |
| Table column/row | Table | Editing | Editing | :white\_check\_mark:  |
| Table column/row - switch buttons | Table | Dropdown | Editing | :x: |
| Table properties - border style | Table properties popup | Dropdown | Dropdown | :white\_check\_mark:  |
| Table properties - colour pickers | Table properties popup | Dropdown | Body | :x: |
| Cell properties - border style | Cell properties popup | Dropdown | Dropdown | :white\_check\_mark:  |
| Cell properties - colour pickers | Cell properties popup | Dropdown | Body | :x: |
| Table caption button | Table | Caption | Button | :x: |
| Image caption button | Image | Caption | Button | :x: |
| Track changes | Main | Editable | Dropdown | :x: |
| Code block | Main | Editing | Editing | :white\_check\_mark:  |
| Link | Main | Editing | Editing | :white\_check\_mark:  |
| Media embed | Main | Editing | Editing | :white\_check\_mark:  |
| Styles | Main | Editing | Button | :x: |
| Find & replace - options switch buttons | Find & replace | Dropdown | Dropdown | :white\_check\_mark:  |
| Special characters | Main | Editing | Editing | :white\_check\_mark:  |
| Special characters - categories | Special characters | Dropdown | Dropdown | :white\_check\_mark:  |
| WProofReader - disable/enable | Main | Editable | Dropdown | :x:  |
| WProofReader - settings/proofread in dialog | Main | Popups | Dropdown | :x: |

**Comment by Dumluregn** [comment] 2022-07-28 09:00
## Summary of our way towards the final solution

We started with the initial proposal described here: [https://github.com/ckeditor/ckeditor5/issues/12125#issuecomment-1192327029.](https://github.com/ckeditor/ckeditor5/issues/12125#issuecomment-1192327029.) The default dropdown behaviour started working as expected (so moving the focus back to the dropdown button), some tests needed to be adjusted though (they needed the dropdown to be rendered). The second part - enforcing particular features to focus editable - turned out to be more bumpy. For simple dropdowns like `Heading` or `Font size` simply we could put `this.editor.editing.view.focus()` in the same listener as the command execution, like this:

```javascript
 this.listenTo( dropdownView, 'execute', evt => { 
 	editor.execute( evt.source.commandName, evt.source.commandValue ? { value: evt.source.commandValue } : undefined ); 
 	editor.editing.view.focus(); 
 } ); 
```

but splitbuttons like `Highlight` or `List styles` that use `execute` event delegation were more complex. If we tried to move the focus in the button `execute` listener, it was executed too early - before the focus was moved by the dropdown itself. That's because events delegation was executing **all** listeners for the innermost event source first, then moving up to the component it delegates etc, so the priorities are set for each component separately. For that reason e.g. the following code wouldn't work as expected for `Highlight`:

```javascript
splitButtonView.on( 'execute', () => {
	editor.execute( 'highlight', { value: splitButtonView.commandValue } );
	editor.editing.view.focus();
} );
```

It would focus the editing view before moving the focus to the splitbutton view which was not expected. Note that we could not have cancelled the event as it triggers dropdown closing etc.

For that reason in some places we had to add a separate listener on the dropdown view. We don't like it much because it separates the logic, but we couldn't avoid it without big changes in some packages. So e.g. in the `imageStyle` feature there is a following listener now added:

```javascript
this.listenTo( dropdownView, 'execute', () => {
	this.editor.editing.view.focus();
} );
```

while the rest of the `execute` logic is elsewhere:

```javascript
splitButtonView.on( 'execute', () => {
	if ( !buttonViews.some( ( { isOn } ) => isOn ) ) {
		defaultButton.fire( 'execute' );
	} else {
		dropdownView.isOpen = !dropdownView.isOpen;
	}
} );
```

### Relocating the code

The next change was moving the button focus to the dropdown's `isOpen` listener:

```javascript
	this.on( 'change:isOpen', () => {
		if ( !this.isOpen ) {
			// If the dropdown was closed, move the focus back to the button (#12125).
			this.focus();

			return;
		}
		(...)
	} );
```

It looks like a more natural place for this code. Also it allowed to revert changes in unit tests (they no longer required `dropdown` to be rendered in some scenarios).

### Additional remark

Please note, that some buttons that we put in the dropdowns by default are registered as independent UI components. That means they can be put in the toolbar directly. They still need to focus the editable on their own (if that is an expected behaviour of course). We can once again use the code from `Highlight` feature as a reference:

```javascript
_addButton( name, label, icon, value, decorateButton ) {
	const editor = this.editor;

	editor.ui.componentFactory.add( name, locale => {
		const buttonView = new ButtonView( locale );

		const localized = this.localizedOptionTitles[ label ] ? this.localizedOptionTitles[ label ] : label;

		buttonView.set( {
			label: localized,
			icon,
			tooltip: true
		} );

		buttonView.on( 'execute', () => {
			editor.execute( 'highlight', { value } );
			editor.editing.view.focus();
		} );

		// Add additional behavior for buttonView.
		decorateButton( buttonView );

		return buttonView;
	} );
}
```

Button is registered as a UI component, so it has to focus editable on its own, even though this behaviour is duplicated by the dropdown listener. Actually, a little ping-pong happens here:

1.  At first the `buttonView` listener focuses the editable.
2.  Then the `dropdownView.on( 'change:isOpen' () => {} )` listener kicks in and focuses the dropdown button.
3.  After that the `execute` event is delegated to the dropdown and the dedicated listener present in the feature itself focuses the editable again.

**Closed** 2022-07-28 14:19 UTC
Labels: type:bug, type:regression, release:blocker, squad:green, status:in-progress, package:style

**Comment by Reinmar** [comment] 2022-07-29 06:15
Thanks @Dumluregn for writing this down.

It wasn't obvious how to handle the focus in those dropdowns that have to override the defaults because of how the `execute` event is delegated (note: `isOpen` changes as a result of `drodpdownView#execute`, so `dropdownView#change:isOpen === dropdownView#exeute`).

### The default behavior

We decided that the default behavior of a dropdown should be to focus the `dropdownView#buttonView` on dropdown closing. This is done, as @Dumluregn mentions, inside `dropdownView#change:isOpen` because that handler was already focusing the dropdown panel on dropdown opening.

### Overriding the default

In order to override the default behavior, you need to call your `focus()` (e.g. `editor.editing.view.focus()`) after the default behavior is executed. Right now, we don't have a different mechanism (e.g. a state passed via the `execute` chain) that would be order-independent. So, we need to be careful here.

The order in which `execute` event flows through dropdowns and their panel looks like follows (assuming that the user clicked an option inside a dropdown's panel and that a dropdown has a correctly delegated `execute`):

1.  button view inside a panel view
2.  panel view (not always present)
3.  dropdown button view
4.  dropdown view

When we were implementing dropdowns so far, there were 4 (**four**) places where one could handle the execution of an option inside a dropdown.

However, 3 of these places would not allow you to handle the focus. You can only handle (override) focus in the very last `dropdownView#execute` handler. The other 3 would be too early.

### Recommendation

I recommend we review thoroughly this `execute` chain, document it, and find ways to reduce the number of possible ways how one (or at least we) handle execution of a dropdown's option.

From what I saw so far, in all cases except highlight (where panel's buttons themselves are registered in the component factory), it's possible to actually listen to `dropdownView#execute` to handle clicking of an option inside the panel. The data of such event contain information about which option was clicked. We could make sure and recommend doing this.

Another idea would be to make the "what gets focused after button click" order-independent. This could be achieved by passing a state object via the `execute` chain where listener could set what should be focus. If the property wasn't set, the default action would happen.

**Comment by Reinmar** [comment] 2022-07-29 10:59
First issue where the default behavior is not what we expect: #12178
