### ISSUE TITLE
Table not in root element (in Blockuote for example) throws Errors

### ISSUE THREAD

**Issue by CepBoJIk** [ckeditor/ckeditor5#9696] opened 2021-05-13 17:27 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Put table element not into root element (in my case in some custom block plugin, but in Blockquote it's frow error too)
2. Get result html string from editor
3. Put this string in editor

### ✔️ Expected result

Editor work

### ❌ Actual result

I get error - "Uncaught TypeError: Cannot read property 'getAttributeKeys' of null", then editor not working;
Seems like it's from method "hasAnyAttribute" from file downcast.js.
I think then table lay into some element, postfixer "tableCellContentsPostFixer" isnt trigger, trigger only postfixer for outer element. Because of this tag td is empty (exсept b, "hasAnyAttribute" function expects span or p in tableCell), and it's a case of this error

## 📃 Other details

* Browser: Google Chrome
* OS: Ubuntu, Windows
* First affected CKEditor version: 24.0.0 (my version)

**Comment by FilipTokarski** [comment] 2021-05-18 10:38
Hi, thanks for the report. I could not reproduce this using a table inside a block quote. Please make sure that it's not an issue with your custom code. If you are convinced that there's an error inside the editor, we'll need precise steps to reproduce this ( together with your editor configuration, plugin versions, etc. ).

**Comment by CepBoJIk** [comment] 2021-05-25 11:53
Hi, i reproduce this error with editor without any custom plugins.

My package.json
    "@ckeditor/ckeditor5-basic-styles": "^24.0.0",
    "@ckeditor/ckeditor5-block-quote": "^24.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^24.0.0",
    "@ckeditor/ckeditor5-essentials": "^24.0.0",
    "@ckeditor/ckeditor5-paragraph": "^24.0.0",
    "@ckeditor/ckeditor5-table": "^24.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^24.0.0",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^3.1.0",
    "style-loader": "^1.3.0",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"

Webpack.config from [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)

app.js
  `import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
  import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
  import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
  import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
  import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
  import BlockQuote from "@ckeditor/ckeditor5-block-quote/src/blockquote";
  import Table from "@ckeditor/ckeditor5-table/src/table";
  
  ClassicEditor.builtinPlugins = [
      Essentials,
      Paragraph,
      Bold,
      Italic,
      BlockQuote,
      Table
  ];
  
  ClassicEditor.defaultConfig = {
      toolbar: {
          items: [
              'bold',
              'blockquote',
              'insertTable'
          ]
      }
  };
  
  ClassicEditor
      .create( document.querySelector( '#editor' ))
      .then( editor => {
          editor.model.document.on( 'change:data', () => {
              console.log(editor.getData());
          });
  
          console.log( 'Editor was initialized', editor );
      } )
      .catch( error => {
          console.error( error.stack );
      } );
  `

How to reproduce
1) insert blockQuote
2) insert Table into blockQuote
3) get string of content from editor (in this case it will be in the console of browser)
4) put this string into html tag with id "editor"
5) reload page
6) try to write something into cell of table with opened console

![image](https://user-images.githubusercontent.com/41323066/119493481-e7e93180-bd68-11eb-9b26-6cce640c97fa.png)

**Comment by FilipTokarski** [comment] 2021-06-01 13:41
I was finally able to reproduce this, but only until version `25.0.0`. The current one is `27.1.0` and we're just ahead of the next release. So the case you described concerns bugs that have already been fixed.
  
I'd advise to keep your editor packages up to date, so that you have all the latest features and bug fixes. I'll close this ticket for now.

**Closed by FilipTokarski** 2021-06-01 13:41 UTC
Labels: pending:feedback, type:bug
