### ISSUE TITLE
A period does not stick to the preceding word during word-wrap

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#8852] opened 2021-01-17 20:41 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/ckeditor-5/demo/
2. Make sure you have one line that takes the full editor width and has a link at the end
3. Type a period `.` after the link

### ✔️ Expected result

The link and the period are word-wrapped

### ❌ Actual result

The period is detached from the word; if I press Enter after that, everything re-wraps normally

https://user-images.githubusercontent.com/1523306/104855315-5a09bf80-590c-11eb-9eca-dbfdbdc22b7f.mov

## 📃 Other details

* Browser: Chrome
* OS: macOS Catalina
* First affected CKEditor version: ?
* Installed CKEditor plugins: ?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by neongreen** [comment] 2021-01-17 20:42
Is also reproducible in Safari.

**Comment by Mgsy** [comment] 2021-01-18 08:35
Hi, thanks for the report. I can confirm this behaviour.

**Comment by oleq** [comment] 2021-01-26 09:46
This bug is related to the [inline filler logic](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/filler.js#L23-L30) and the filler sequence appearing in the text node

![](https://user-images.githubusercontent.com/1099479/105828607-a071b500-5fc3-11eb-886f-4b8ff06e542c.gif)

**Comment by oleq** [comment] 2021-01-26 09:55
It could be this method is too permissive https://github.com/ckeditor/ckeditor5/blob/428917601db732c6dfab48380eda2d8bbbfc7e19/packages/ckeditor5-engine/src/view/renderer.js#L408-L445

**Comment by oleq** [comment] 2021-01-26 09:59
I'm also not sure why the filler persists in nodes that don't need it. This will require some research. 

![](https://user-images.githubusercontent.com/1099479/105830111-66a1ae00-5fc5-11eb-9e30-05bea74ab460.png)

**Comment by niegowski** [comment] 2021-01-28 18:26
> I'm also not sure why the filler persists in nodes that don't need it. This will require some research.

It's to avoid breaking composition while the selection is inside the text node: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/renderer.js#L343-L345

**Comment by oleq** [comment] 2021-02-01 09:22
So this is a "have your cake and eat it" kind of situation? Either the composition works properly or the trailing punctuation behaves as it should?

Do you think there's a chance that moving to `beforeinput` will allow us to make this filler logic less intrusive?

**Comment by niegowski** [comment] 2021-02-01 09:38
Maybe we could consider switching from "zero-width space" to "zero-width no-break space".

**Comment by niegowski** [comment] 2021-02-02 09:07
I briefly checked it and replacing `'\u200b'` with `'\ufeff'` here [https://github.com/ckeditor/ckeditor5/blob/b278fde89d1eb635be7e4e3a57d8dba2bd0f98a6/packages/ckeditor5-engine/src/view/filler.js#L74](https://github.com/ckeditor/ckeditor5/blob/b278fde89d1eb635be7e4e3a57d8dba2bd0f98a6/packages/ckeditor5-engine/src/view/filler.js#L74) seems to do a trick.

**Comment by niegowski** [comment] 2021-02-02 17:45
Seems that `\ufeff` is deprecated in the context of word joiner but it is not deprecated in general ([https://en.wikipedia.org/wiki/Word_joiner](https://en.wikipedia.org/wiki/Word_joiner)). There is another Unicode character `\u2060` (word joiner) that is supposed to replace the usage as word joiner but it has a side effect that it does not render in dev tools. I would still use `\ufeff` (zero-width non-breaking space) to avoid confusion while debugging in dev tools. WDYT @Reinmar ?

**Comment by Reinmar** [comment] 2021-02-02 21:15
It's weird that a word joiner is not displayed in the dev tools. Could you file them a bug report? Their response may actually shed some light on this.

I laughed when I read that `\ufeff` is BOM :D I forgot about this gem. It makes mi slightly worried to use this character now because there may be some stupid BOM filters implemented in "enterprise" tooling. I've seen such things... But we'll never know if we don't try, so I think we could go with it. However, we'll need to pay attention during QA on whether this works in all browsers and OSes.

**Comment by niegowski** [comment] 2021-02-05 16:19
I noticed that some tests in the `typing` package started to fail after changing ZWS with ZWNBSP because the ZWNBSP does match in regexps to `\s`:

```
/\s/.test( '\u200b' ) -> false (ZWS)
/\s/.test( '\ufeff' ) -> true (ZWNBSP)
/\s/.test( '\u2060' ) -> false (WJ)
```

So there could be many places where this could fail. Taking this and the BOM case I decided to go with WJ option and to report DevTools bug.

**Comment by niegowski** [comment] 2021-02-05 17:27
I reported the issue for DevTools: https://bugs.chromium.org/p/chromium/issues/detail?id=1175133

**Closed** 2021-02-18 08:18 UTC
Labels: package:engine, squad:ux, type:bug
