### ISSUE TITLE
[iOS] Image split button misaligned

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#7927] opened 2020-08-24 13:59 UTC
### ✔️ Expected result

Both parts of the split button should be aligned with one another.

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/91053101-a3d2d000-e622-11ea-8c64-5cb0fd96f285.jpg)

## 📃 Other details

*   Browser: Safari
*   OS: iOS
*   CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment] 2020-08-28 09:29
The problem has been confirmed (iOS only, though). It occurs only in the image upload split dropdown (as opposed to the Highlight feature split button) because the main part of the split button is a wrapper for the upload button (which consists of a regular button and a hidden input) so it's probably something related to line-height.

There's also a problem with border rounding for the same reason: the regular `.ck-button` is wrapped in a span so some styles don't apply.

![image.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/7ce872bf-f88c-4e3d-a310-334358f36444)

**Comment by oleq** [comment] 2020-09-01 13:01
FYI: There's a more general issue for the upload button rendering #7986.

**Comment by Reinmar** [comment] 2020-09-04 09:04
Let's close this as a DUP of #7986.

**Closed by Reinmar** 2020-09-04 09:04 UTC
Labels: domain:ui/ux, package:theme-lark, squad:ux, type:bug
