### ISSUE TITLE
Browser tab freezes after cutting content in specific way

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#787] opened 2018-01-25 11:09 UTC
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret at the end of the `Paragraph`.
3. Open link balloon and press `Save`.
4. Start the selection at `UL List item 1` and move it to `Paragraph[]`.
5. Press <kbd>Ctrl</kbd> + <kbd>X</kbd>.

## ✅ Expected result

Content has been cut.

## ❎ Actual result

Browser tab freezes.

## 📃 Other details that might be useful

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/35385379-659119d2-01c8-11e8-99cc-23bbe892d75a.gif)

**Other information**
OS: All platforms
Browser: All browsers

**Comment by Reinmar** [comment] 2018-01-25 11:28
Confirmed. It's weird that it requires saving the link there (which does, or should do, nothing).

**Comment by scofalik** [comment] 2018-02-21 13:32
This is very weird. Saving link does not do nothing, it sets link on a selection so you can "write link" later. But, after you change selection (which is a step to reproduce the bug), the link is gone and selection attribute is gone too.

**Comment by scofalik** [comment] 2018-02-21 16:08
Looks like an empty text node with `linkHref` attribute is created.

**Comment by scofalik** [comment] 2018-02-22 10:44
Will be fixed by https://github.com/ckeditor/ckeditor5-link/issues/169.

**Comment by Reinmar** [comment] 2018-03-30 11:55
It's fixed.

**Closed by Reinmar** 2018-03-30 11:55 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
