### ISSUE TITLE
extraPlugins no longer takes a function as input

### ISSUE THREAD

**Issue by c4b4d4** [ckeditor/ckeditor5#12696] opened 2022-10-20 21:15 UTC
I used to be able to create my own Upload Adaptar, via:

```
function MyUploadAdapterPlugin( editor ) {
    editor.plugins.get( 'FileRepository' ).createUploadAdapter = function( loader ) {
        // ...
    };
}
...
extraPlugins: [ MyUploadAdapterPlugin ]
```

But not it throws me an error. Expecting `MyUploadAdapterPlugin` to be a constructor.

Fixed it by doing it like this:

```
class MyUploadAdapterPlugin
{
  constructor(context) {
   context.plugins.get("FileRepository").createUploadAdapter = (loader) => {
    //..
   };
  }
}
...
extraPlugins: [ MyUploadAdapterPlugin ]
```

I think Docs should be updated: https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/configuration.html

**Comment by Reinmar** [comment] 2022-10-25 07:25
cc @arkflpc could you look into this? We might've missed when it changed... and I think it should not change – passing a simple function was useful.

**Comment by arkflpc** [comment] 2022-10-25 07:52
I will check the feasibility of accepting plain function again and create a task to restore it or to fix the documentation.

@c4b4d4, your fix may be broken because there is no guarantee that `FileRepository` plugin will be there during your constructor call (it works by chance). You can use `init()` method for that:

```
class MyUploadAdapterPlugin
{
  init() {
   context.plugins.get("FileRepository").createUploadAdapter = (loader) => {
    //..
   };
  }
}
...
extraPlugins: [ MyUploadAdapterPlugin ]
```

**Comment by c4b4d4** [comment] 2022-10-25 10:01
@arkflpc What about the `context` variable? Does it work on that scope? Does it get passed on the `init()` method as well? `init(context)`?

**Comment by arkflpc** [comment] 2022-10-26 09:10
@c4b4d4, Apologies for misleading, but my answer was incorrect.

First, `extraPlugins` will be loaded after buildin ones, so in this case it is ok to access `FileRepository` in constructor.

Second, the example should take `context` (which is an `editor` instance) in constructor as well.

```typescript
class MyUploadAdapterPlugin
{
	constructor( editor ) {
		this.editor = editor;
	}
	
	init() {
		this.editor.plugins.get("FileRepository").createUploadAdapter = (loader) => {
		    //..
		};
	}
}
```

Or you can derive from [Plugin](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_plugin-Plugin.html) class which assign `editor` property:

```typescript
class MyUploadAdapterPlugin extends Plugin
{
	init() {
		this.editor.plugins.get("FileRepository").createUploadAdapter = (loader) => {
		    //..
		};
	}
}
```

However, I couldn't reproduce the error you had. It seems working for me in Chrome, Firefox, and Epiphany. Can you give us more context? Like:

*   What specific error it was,
*   The full invocation of `ClassicEditor.create` function,
*   The browser you used.

**Comment by oldmansutton** [comment] 2023-02-09 21:16
So is this documentation incorrect then?  If so, please do fix the documentation.  I need to implement a custom upload adapter, but if the documentation is wrong, I don't see how I'll be able to do that.

**Comment by arkflpc** [comment] 2023-02-23 13:13
This probably will be fixed by #13527. Let's verify.

**Comment by oldmansutton** [comment] 2023-05-10 18:23
Turns out I was able to fix my problem by starting my CK5 build from scratch, but this time not installing the Base64UploadAdapter, and relying ONLY on my custom upload adapter.  Wasn't ever able to figure out how to turn the Base64UploadAdapter programmatically.

**Comment by Witoso** [comment] 2023-05-12 14:23
Glad you found a solution @oldmansutton. Closing.

**Closed by Witoso** 2023-05-12 14:23 UTC
Labels: type:docs
