### ISSUE TITLE
Custom upload adapter 12.0 not working

### ISSUE THREAD

**Issue by guillome2k** [ckeditor/ckeditor5#1618] opened 2019-03-12 07:51 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

12.0

## 📋 Steps to reproduce

1. Added <script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js"></script>
2. Added the code from https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html
3. Changed 1 piece:
`_initRequest() {
 ....
 xhr.open( 'POST', 'upload.php', true );`

Php: `
  print_r($_FILES);
  print_r($_POST);
`

Returns: `
array(0) {
}
array(1) {
  ["upload"]=>
  string(16) "[object Promise]"
}
`

## ✅ Expected result
Get the file into my php file in $_FILES or $_POST 

## ❎ Actual result
FormData upload is [object Promise]:
![image](https://user-images.githubusercontent.com/3306752/54183111-9152ee00-44a3-11e9-99e7-83d8e813c4e8.png)

In version 11.2 it worked.

**Comment by Reinmar** [comment] 2019-03-12 09:49
cc @Mgsy could you test whether we didn't make some mistake in the upload adapter guide?

**Comment by Mgsy** [comment] 2019-03-13 10:41
I've checked it and indeed, in `12.0.0` the upload parameter contains `[object Promise]`. It's a regression because in `11.2.0` binary data is passed correctly.

**Comment by Reinmar** [comment] 2019-03-13 12:18
Same here: https://stackoverflow.com/questions/55105674/ckeditor-upload-adapter-sends-object-promise-to-server

It must be a problem with the guide. We must fix it ASAP. cc @oleq

**Comment by mlewand** [comment] 2019-03-13 14:42
In 12.0.0 we changed API for [`FileLoader#file`](https://ckeditor.com/docs/ckeditor5/12.0.0/api/module_upload_filerepository-FileLoader.html#member-file). It was a `File` instance before, now it's a promise that resolves to a `File` instance (ckeditor/ckeditor5-upload#87). This change was not reflected in the docs, more precisely: [the line that appends the file in custom upload adapter](https://github.com/ckeditor/ckeditor5-image/blame/3d265a33ade57281f59c3fc2b505ba7e5f49362e/docs/framework/guides/deep-dive/upload-adapter.md#L298) should resolve the promise before sending the request.

I'll prepare the PR for that.

**Comment by oleq** [comment] 2019-03-13 16:22
I merged the updated guide content to `stable`. Next steps:
* rebuilding docs on ckeditor.com
* replying to https://stackoverflow.com/questions/55105674/ckeditor-upload-adapter-sends-object-promise-to-server

**Comment by mlewand** [comment] 2019-03-14 08:28
The docs are updated and the issue is no longer there. Once again, thanks for the report!

**Comment by guillome2k** [comment] 2019-03-14 08:36
My pleasure. Thank you too for fixing it. Works as a charm!

**Comment by Reinmar** [comment] 2019-03-14 08:38
Guys, this change is incomplete. There's more use of `loader.file` in the guide:

```js
const genericErrorText = 'Couldn\'t upload file:' + ` ${ loader.file.name }.`;
```

* The official adapres have been modified differently to avoid this issue – check out CKFinder's one. The one described in the guide should follow that.
* There's also no sense to use ` ''+`` ` in there, BTW :D

We should also look for existing answers on SO because this is an ugly breaking change.

**Comment by mlewand** [comment] 2019-03-15 08:26
Good catch @Reinmar, thanks for getting that.

**Closed** 2019-03-15 08:37 UTC
Labels: must-have, status:confirmed, type:bug, type:docs
