### ISSUE TITLE
I want ckeditor know span, so I create a Plugin like this.  but It's doesn't working, I found the upcastElementToAttribute this is method not working.,,,,,help help

### ISSUE THREAD

**Issue by Ckeyang** [ckeditor/ckeditor5#1262] opened 2018-09-25 10:32 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

## 📃 Other details that might be useful

```js
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import { upcastElementToAttribute } from '@ckeditor/ckeditor5-engine/src/conversion/upcast-converters';
import { downcastAttributeToElement } from '@ckeditor/ckeditor5-engine/src/conversion/downcast-converters';
import bindTwoStepCaretToAttribute from '@ckeditor/ckeditor5-engine/src/utils/bindtwostepcarettoattribute';
import {
	srcsetAttributeConverter,
	modelToViewAttributeConverter
} from './converters';
import { createSpanElement } from './util';
import SpanCommand from './SpanCommand';
const SPAN = 'spanFieldId';
export default class SpanEditing extends Plugin {
	init() {
		const editor = this.editor;
		editor.model.schema.extend('$text', { allowAttributes: SPAN });
		editor.conversion.for('dataDowncast').add(
			downcastAttributeToElement({
				model: SPAN,
				view: createSpanElement
			})
		);
		editor.conversion.for('editingDowncast').add(
			downcastAttributeToElement({
				model: SPAN,
				view: (fieldId, writer) => {
					return createSpanElement(fieldId, writer);
				}
			})
		);
		editor.conversion.for('upcast').add(
			upcastElementToAttribute({
				view: {
					name: 'span',
					attributes: {
						fieldId: true
					}
				},
				model: {
					key: SPAN,
					value: (viewElement) => viewElement.getAttribute('fieldId')
				}
			})
		);
	}
}
```

**Comment by Reinmar** [comment] 2018-09-27 09:43
Hi! Your code looks ok. Maybe except using uppercased attribute names (DOM is case insensitive) and  this bit:

```js
					attributes: {
						fieldId: true
					}
```

Because I'm not sure without checking whether you can match an attribute to `true`. I don't remember if we already implemented it or not. So if you have `fieldid="true"` in the DOM I'd define it as `fieldid: 'true'` here just to be sure.

Other than that, we'll not be able to help you unless your problem is more precisely defined and reproducible for us. We miss an explanation of what doesn't work, what does work, how do you run this code, a repository with a demo, etc.

**Comment by Ckeyang** [comment] 2018-09-28 02:04
Thanks for your response!
![image](https://user-images.githubusercontent.com/17843772/46183877-8e08e300-c305-11e8-8ebb-468f27748f49.png)
This is the result I want. ↑


But it the result like this.↓
![image](https://user-images.githubusercontent.com/17843772/46183889-a2e57680-c305-11e8-925c-15f7d88b10de.png)


I modify the source of the image plugin that work.
but span ...  

```
editor.conversion.for('upcast').add(
			upcastElementToElement({
				view: {
					name: 'span',
					attributes: {
						fieldid: true
					}
				},
				model: {
					key: SPAN,
					value: (viewElement) => viewElement.getAttribute('fieldid')
				}
			})
		);
```

I update the fieldId to fieldid . or not yet
My code is written in imitation of Link plugin.

**Comment by Reinmar** [comment] 2018-09-28 10:32
I'm afraid that's too much for an issue report. We'd need to dive into your code and analyse it. We can't do that for you on GitHub or StackOverflow. If you'd like to get this kind of support, you'd need to [contact CKSource](https://ckeditor.com/contact/).

I'm closing this ticket as invalid. You can open new tickets for bug reports or more specific questions.

**Closed by Reinmar** 2018-09-28 10:32 UTC
Labels: type:question
