### ISSUE TITLE
Anchor being an InlineElement trips up Style feature

### ISSUE THREAD

**Issue by HOFF320** [ckeditor/ckeditor5#13249] opened 2023-01-11 16:16 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Use an editor with the Style plugin.
2. Have some text in the editor.
3. Attempt to apply a style with 'a' as its defined element.

### ✔️ Expected result

If the cursor is not at a link: The style for 'a' elements is greyed out and cannot be applied.
If the cursor is at a link: The selected style is applied.

### ❌ Actual result

If the cursor is not at a link: The editor creates a broken 'a' tag (empty if no text is selected, around selected text otherwise) that doesn't link to anything and can't be modified using the Link feature, but does display the correct style. A link *can* be added to the styled text retroactively though, and it doesn't add a second 'a' tag.

If the cursor is at a link: If the link is fully highlighted, everything functions as expected. If NOT, the existing link is split by the new one, with (in the worst case) one unstyled pre-link, one styled link, and one unstyled post-link, all pointing to the same destination.

### ❓ Possible solution

While 'a' being an inline element is technically true, it makes little sense to treat it as such: it is not a style element by itself, it is a structural element (that must be constructed a certain way) that *can* be styled.

As such, my suggestion is to reclass 'a' to be a block element, achieving expected behaviour.

## 📃 Other details

The style in question is some simple button CSS.

CKEditor version: 35.2.0
Active plugins: AutoLink, Autosave, Bold, ContentLinks*, ContentClipboard*, ContentImagePlugin*, CoreMediaStudioEssentials*, CoreMediaFontMapper*, Differencing*, Essentials, FootNote**, Heading, ImageInline, ImageBlockEditing, ImageStyle, ImageToolbar, Italic, Link, LinkImage, LinkTarget*, DocumentListProperties, Paragraph, PasteFromOffice, RemoveFormat, Strikethrough, Style, Subscript, Superscript, Table, TableToolbar, Underline.
*stock CoreMedia extensions to CKEditor5 for use in CoreMedia Content Cloud
**custom in-house addition

`style: {
      definitions: [
        {
          name: 'Hero Button',
          element: 'a',
          classes: ['btn-green']
        },
        {
          name: 'Column Break',
          element: 'p',
          classes: ['p--column-break-marker']
        }
      ]
    }`
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by RichardDavies** [comment] 2023-03-13 20:23
Another interesting behavior that I've observed is that if you select some text then apply a style with 'a' as its defined element it wraps the selected text in an anchor tag without an `href` attribute as already described. Without deselecting the text, if you then click the link button and provide a URL to link to, after doing this whenever you click inside the link text the usual link bubble showing the URL and allowing you to edit the link does not appear in the editor.

However, if you perform those steps in the opposite order (i.e. create a link first and then apply the style) the link bubble does appear as expected when the link text is clicked. Interestingly, either order of operations results in the exact same HTML being applied to the text.

**Comment by Witoso** [comment] 2023-03-22 08:28
Duplicate of #11709. Moving discussion there. Thank you for reporting!

**Closed by Witoso** 2023-03-22 08:28 UTC
Labels: type:bug, package:style
