### ISSUE TITLE
Integrate inline images with table feature

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#9117] opened 2021-02-26 07:53 UTC

**Comment by magda-chrzescian** [comment] 2021-03-17 12:39
**Since the inline images are nested in the `span` elements in the tables, their sizes are also defined relative to this element.
It causes problems if this span's width is smaller than the table cell - so, practically, if the cell is empty.**

* When the user presses enter in this `span`, it is converted into the `paragraph`, which takes the whole cell width -> the image is being enlarged.
* When the user adds a caption or changes a style and the inline image is being converted into the block image -> the image is being enlarged.
* Pasting the image into the cell with another width doesn't change the image size.

**Comment by oleq** [comment] 2021-03-19 09:03
Related recent regression https://github.com/ckeditor/ckeditor5/issues/9300.

**Comment by magda-chrzescian** [comment] 2021-03-22 15:15
This is also related to https://github.com/ckeditor/ckeditor5/issues/7433#issuecomment-799246289.

**Comment by magda-chrzescian** [comment] 2021-03-22 18:39
Another issue is that the inline image doesn't affect the table column size if set to `original size` if the table has a fixed width. The image in the table below has the original size 50x50px, but in the editor it's 32x32px, even if set to the `original size`:
![image](https://user-images.githubusercontent.com/14334820/112040685-cb9cfe80-8b45-11eb-8fb5-07426441473e.png)

This problem is strictly related to the editing styles only (it is caused by the `span` wrapping the `img` element which doesn't exist in the data output).

**Comment by magda-chrzescian** [comment] 2021-03-23 10:13
There is also an issue related to the data upcasting. Inline images nested in the tables are getting upcasted to the block images. It also affects other inline elements in the cell, all of the spans are becoming paragraphs in the editor.

**Comment by oleq** [comment] 2021-04-01 09:17
Closed in #9352.

**Closed by oleq** 2021-04-01 09:17 UTC
Labels: package:image, package:table, squad:ux, type:task
