### ISSUE TITLE
Wrong docs for DataController#set()

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor5#8691] opened 2020-12-16 11:06 UTC
## 📝 Provide a description of requested docs changes

Current docs for [`DataController#set()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_controller_datacontroller-DataController.html#function-set) describes the [`Observable#set()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_observablemixin-Observable.html#function-set) one, however this method is overwritten by `DataController`. It has [correct API docs in the code](https://github.com/ckeditor/ckeditor5/blob/e56051e89f01664114ac0a9abd9e99dad155f2b5/packages/ckeditor5-engine/src/controller/datacontroller.js#L321-L341), but they are not reflected in the documentation.

**Comment by Reinmar** [comment] 2021-08-24 19:08
Notes from a meeting that we had:

*   This problem affects also for instance `execute()` (many commands override it)
*   Initially, we wanted to change JSDoc's behavior for this
*   But `@override` resolves this issue too...
*   In Java, if you have mistakenly overridden a method (so you didn't add `@override` then), you will be warned
*   Probably, JSDoc went in the same direction intentionally but they didn't implement a warning
*   @inheritdoc should also do `@override` + inherit the docs
*   Empty `@override` will not inherit the docs (will take the current one)
*   Side note: DataController#set was a wrong method choice (no viable action now - let's leave it as it is)
*   Question: Command#execute should be marked as abstract? Then, we wouldn't need to use @override?
*   TODO
    *   What about TypeScript? How does it work there?

**Comment by ma2ciek** [comment] 2021-09-06 10:27
I suspect there might be a bug in [https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/jsdoc-plugins](https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/jsdoc-plugins) that causes this behavior. It could work in the past.

**Comment by jodator** [comment] 2021-09-20 12:06
> \* What about TypeScript? How does it work there?

Just stumbled upon this bug while reading the docs ;)

ps.: The TS [will not allow that](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8CwAoa7oQKYBcAUAZgPZEBcmOATgJYB2A5gJSKoZvSW4Cult0ArKwwBfVKJSpQkGACFoWAB44stACYx4yNBmz5iZCjQbMt7DJxw8+BMCGxD048ZPBRoAYXlKV6uC23ouoQk5LRcALYARliUJg7sFlYC8U6oLtLQACJeymoa-mxB+uQQVHT0ADTQkWAAXiVlxgVmHNy8yQHQqShAA).

**Comment by pomek** [comment] 2021-11-10 12:49
There is a bug in the `getMissingDocletsData()` function.

https://github.com/ckeditor/ckeditor5-dev/blob/eced4b49237958b5a0237d1da14bd84f368dbf17/packages/jsdoc-plugins/lib/relation-fixer/getmissingdocletsdata.js#L42-L44

I didn't dig deep, but sometimes `clonedDoclet.name` starts with a hash (`#`). 

After replacing the above function with the following code, docs are generated correctly.

```js
const docletsOfSameMember = docletCollection.get( `memberof:${ clonedDoclet.memberof }` ).filter( d => {
			// Different types..
			if ( d.kind !== clonedDoclet.kind ) {
				return false;
			}

			// Comparing methods from classes.
			if ( d.name === clonedDoclet.name ) {
				return true;
			}

			// Comparing methods from objects.
			if ( '#' + d.name === clonedDoclet.name ) {
				return true;
			}

			return false;
		} );
```

**Comment by pomek** [comment] 2021-11-18 21:45
See: https://github.com/ckeditor/ckeditor5/issues/10560#issuecomment-973297450.

**Comment by pomek** [comment] 2021-11-19 16:16
There are a few areas where we can improve the code and documentation.

### Bug in the jsdoc plugin

As pointed out in https://github.com/ckeditor/ckeditor5/issues/8691#issuecomment-965100824, we can fix an issue in the `getMissingDocletsData()` function. Thanks to that, documentation for the `DataController#set` method will be rendered correctly.

### Missing `@override` annotations

In this comment – https://github.com/ckeditor/ckeditor5/issues/10560#issuecomment-973297450 – I pointed that 182 doclets in the code miss the `@override` property. 

I filtered out the following doclets to see whether the validator works at all:

* `#constructor`
* `#event:change:isEnabled`
* `#event:change:value`
* `#value`
* `#isEnabled`

Here is a list of 44 doclets where adding `@override` makes sense.

<details>
<summary>44 invalid doclets</summary>

* `module:heading/heading~HeadingOption#model` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-heading/src/heading.js#L108), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/conversion/conversion.js#L600)), 
* `module:heading/heading~HeadingOption#view` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-heading/src/heading.js#L108), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/conversion/conversion.js#L600)), 
* `module:ui/viewcollection~ViewCollection#delegate` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-ui/src/viewcollection.js#L141), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-utils/src/emittermixin.js#L449)), 
* `module:ui/viewcollection~ViewCollection#delegate` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-ui/src/viewcollection.js#L141), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-utils/src/emittermixin.js#L449)), 
* `module:engine/controller/datacontroller~DataController#set` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/controller/datacontroller.js#L365), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-utils/src/observablemixin.js#L761)), 
* `module:engine/model/element~Element#is` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/element.js#L117), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/node.js#L390)), 
* `module:engine/model/liveposition~LivePosition._createAfter` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/liveposition.js#L105), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/position.js#L959)), 
* `module:engine/model/liveposition~LivePosition._createBefore` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/liveposition.js#L115), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/position.js#L985)), 
* `module:engine/model/liveposition~LivePosition._createAt` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/liveposition.js#L125), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/position.js#L909)), 
* `module:engine/model/text~Text#is` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/text.js#L86), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/node.js#L390)), 
* `module:engine/view/element~Element#is` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/element.js#L212), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/node.js#L296)), 
* `module:engine/view/element~Element#isSimilar` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/element.js#L338), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/node.js#L352)), 
* `module:engine/view/element~Element#_clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/element.js#L611), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/node.js#L344)), 
* `module:engine/view/text~Text#is` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/text.js#L65), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/node.js#L296)), 
* `module:engine/view/text~Text#isSimilar` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/text.js#L118), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/node.js#L352)), 
* `module:engine/view/text~Text#_clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/text.js#L132), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/view/node.js#L344)), 
* `module:utils/dom/emittermixin~ProxyEmitter#_addEventListener` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-utils/src/dom/emittermixin.js#L251), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-utils/src/emittermixin.js#L481)), 
* `module:utils/dom/emittermixin~ProxyEmitter#_removeEventListener` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-utils/src/dom/emittermixin.js#L268), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-utils/src/emittermixin.js#L494)), 
* `module:engine/model/operation/attributeoperation~AttributeOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/attributeoperation.js#L97), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/attributeoperation~AttributeOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/attributeoperation.js#L106), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/attributeoperation~AttributeOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/attributeoperation.js#L193), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 
* `module:engine/model/operation/insertoperation~InsertOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/insertoperation.js#L84), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/insertoperation~InsertOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/insertoperation.js#L98), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/insertoperation~InsertOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/insertoperation.js#L164), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 
* `module:engine/model/operation/markeroperation~MarkerOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/markeroperation.js#L84), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/markeroperation~MarkerOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/markeroperation.js#L93), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/markeroperation~MarkerOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/markeroperation.js#L139), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 
* `module:engine/model/operation/mergeoperation~MergeOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/mergeoperation.js#L112), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/mergeoperation~MergeOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/mergeoperation.js#L121), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/mergeoperation~MergeOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/mergeoperation.js#L203), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 
* `module:engine/model/operation/moveoperation~MoveOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/moveoperation.js#L83), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/moveoperation~MoveOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/moveoperation.js#L110), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/moveoperation~MoveOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/moveoperation.js#L197), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 
* `module:engine/model/operation/nooperation~NoOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/nooperation.js#L32), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/nooperation~NoOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/nooperation.js#L41), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/renameoperation~RenameOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/renameoperation.js#L71), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/renameoperation~RenameOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/renameoperation.js#L80), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/renameoperation~RenameOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/renameoperation.js#L147), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 
* `module:engine/model/operation/rootattributeoperation~RootAttributeOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/rootattributeoperation.js#L91), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/rootattributeoperation~RootAttributeOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/rootattributeoperation.js#L100), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/rootattributeoperation~RootAttributeOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/rootattributeoperation.js#L192), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 
* `module:engine/model/operation/splitoperation~SplitOperation#clone` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/splitoperation.js#L120), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L56)), 
* `module:engine/model/operation/splitoperation~SplitOperation#getReversed` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/splitoperation.js#L129), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L63)), 
* `module:engine/model/operation/splitoperation~SplitOperation.fromJSON` ([source](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/splitoperation.js#L241), [parent](https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-engine/src/model/operation/operation.js#L132)), 


</details>

### `Command#execute()`

I'd consider marking the `Command#execute()` as an abstract method and removing it from the base class.

https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-core/src/command.js#L216-L232

```js
/**
 * Executes the command.
 *
 * ...
 *
 * @fires execute
 * @abstract
 * @method #execute
 */
```

Thanks to that, API docs for all classes (that inherit `Command`) contain proper descriptions. Unfortunately, 19 tests in the entire project fail. All of them are because of the `CKEditorError: observablemixin-cannot-decorate-undefined` which most probably is caused by the following line:

https://github.com/ckeditor/ckeditor5/blob/b261a41ae2ac8b4cea6dc24d99b93e62b6f47f2a/packages/ckeditor5-core/src/command.js#L123

Wrapping it in an `if` should resolve the issue, but a few tests require adjustments to the change.

![image](https://user-images.githubusercontent.com/2270764/142653037-f789041c-ae25-40e7-aa70-44130bd187ce.png)

If we disagree with changing the `Command#execute` definition, let's add the `@override` annotation to all classes based on it.

**Comment by Reinmar** [comment] 2021-11-21 21:48
> I'd consider marking the `Command#execute()` as an abstract method and removing it from the base class.

Changing the implementation should not be justified by a bug in a documentation generator. Especially that this would be a major BC. I think we should stop at think twice when we start thinking about changing the code in a task that was supposed to improve the documentation generator.

As for the general approach to this entire topic, my view is that:

*   The research showed that the current implementation of the documentation generator is a mess due to various reasons.
*   This entire task was full of surprises and it's unclear how many more will come.
*   Most likely, it's worth dropping this entire project and starting from scratch. It took more than a week to try to create a PoC and due to the state of the codebase, it's still unclear what the heck is going on there.
*   Due to all that, let's close our eyes and do the absolute minimum which is... probably to do what you explained in [https://github.com/ckeditor/ckeditor5/issues/8691#issuecomment-965100824](https://github.com/ckeditor/ckeditor5/issues/8691#issuecomment-965100824) and nothing more.
*   The feature that I proposed (overriding validator) would only make real sense if it was absolutely stable. Otherwise, we risk running into weird issues where we'll have false positives and won't know how to deal with them.

**Closed** 2021-11-22 12:34 UTC
Labels: type:bug, type:docs, squad:devops
