### ISSUE TITLE
ckeditor-duplicated-modules in Ckeditor 5 vue js 3 composition api

### ISSUE THREAD

**Issue by subhamghimire** [ckeditor/ckeditor5#11706] opened 2022-05-05 10:44 UTC
I am using CKEditor 5 in Vue js with composition api. I want to upload image in base64

```<template>
  <div class="text-editor">
    <span class="text-md font-bold text-grey-grey">{{ name }}</span>
    <ckeditor :editor="editor" :config="editorConfig" v-model="value">
      white
    </ckeditor>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, ref, onBeforeMount, onMounted } from "vue";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import CKEditor from "@ckeditor/ckeditor5-vue";
import Base64UploadAdapter from "@ckeditor/ckeditor5-upload/src/adapters/base64uploadadapter";

export default defineComponent({
  props: {
    name: String,
    modelValue: String,
  },
  components: {
    ckeditor: CKEditor.component,
  },

  emits: ["update:modelValue"],
  setup(props, context) {
    const value = ref("");
    onMounted(() => {
      value.value = "";
    });

    return {
      editor: ClassicEditor,
      editorConfig: {
        plugins: [Base64UploadAdapter],
      },
      value: computed({
        get() {
          return props.modelValue;
        },
        set(value) {
          context.emit("update:modelValue", value);
        },
      }),
    };
  },
});
</script>```

CKEditor versions:

"@ckeditor/ckeditor5-build-classic": "^31.1.0",
    "@ckeditor/ckeditor5-upload": "^34.0.0",
    "@ckeditor/ckeditor5-vue": "^2.0.1",

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2022-05-12 13:43
Duplicate of https://github.com/ckeditor/ckeditor5-vue/issues/215. Closing.

**Closed by FilipTokarski** 2022-05-12 13:43 UTC
Labels: type:bug

**Comment by sama510** [comment] 2024-09-29 14:07
![samandehi](https://github.com/user-attachments/assets/f71090ea-f7c1-46f8-b153-846bc02c0e4a)

**Comment by sama510** [comment] 2024-09-29 14:07
ftyhujg
