### ISSUE TITLE
The to-do list checkbox covers caret when a list item is empty on Chrome

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#15032] opened 2023-09-20 10:02 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/latest/features/lists/todo-lists.html on Chrome.
2. Add empty to-do list element

### ✔️ Expected result

The checkbox is not covering the caret:
<img width="50" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/32898551/7bef3fd7-6c66-4c89-92c2-bcec3e109154">

### ❌ Actual result

The checkbox covers the caret.
<img width="37" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/32898551/286d51d0-0dfe-418a-b131-84a140c7892f">

## 📃 Other details

* Browser: Chrome

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-09-21 15:11
If it's not related to todos in Document list, then I will close it. We don't plan to enhance in any way the List v1 implementation (see: #14767).

**Comment by niegowski** [comment] 2023-09-21 16:50
It is related to both implementations.

**Comment by neongreen** [comment] 2024-01-06 15:25
Duplicate of: https://github.com/ckeditor/ckeditor5/issues/9141

**Closed** 2024-01-08 09:49 UTC
Labels: type:bug, package:list, browser:chrome, squad:core
