### ISSUE TITLE
Tab key is blocked (doesn't leave the editable)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#472] opened 2017-06-13 09:41 UTC
As we discussed in https://github.com/ckeditor/ckeditor5/issues/457#issuecomment-306058137 we don't want to block the <kbd>Tab</kbd> key by default. But somehow, we do it now in all creators.

**Comment by oleq** [comment] 2017-06-13 14:50
## The problem 

The reason why this issue is here lies in listeners like [this one](https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L198-L203) and the [general principles](https://github.com/ckeditor/ckeditor5-core/blob/master/src/editingkeystrokehandler.js#L75-L77) driving the `EditingKeystrokeHandler`.

Long story short is that if there's any <kbd>X</kbd> keystroke listener registered in the `EditingKeystrokeHandler`, the handler will always `preventDefault()` such keystroke, whether it makes sense or not. 

Usually it makes sense and shortens the code because you always expect <kbd>Ctrl</kbd>+<kbd>B</kbd> to get `preventDefault()` – it doesn't do anything else.

But when it comes to <kbd>Tab</kbd>, which indents lists, focuses link form, navigates the webpage, such generic `preventDefault` kicks in when it's not necessary.

## Solutions

1. Remove the generic `preventDefault()` in `EKH`. It doesn't make much sense because each single feature would need to [call `cancel()`](https://github.com/ckeditor/ckeditor5-utils/blob/master/src/keystrokehandler.js#L95-L98) in the listener. Even less sense if the callback is a command name.
1. Use the generic `preventDefault()` in `EKH` for all command keystrokes and disable it for callbacks. Each callback will need to call [`cancel()`](https://github.com/ckeditor/ckeditor5-utils/blob/master/src/keystrokehandler.js#L95-L98) in the listener if it actually handled the keystroke (e.g. <kbd>Tab</kbd> **actually** focused the link form). It looks clean to me.
1. Leave `EKH` as it is and be more careful when using it. It probably means moving keystrokes like aforementioned <kbd>Tab</kbd> to another keystroke handler, probably associated with the link form. I checked which keystrokes are handled in `EKH` ATM and they're
    ```
   CTRL+Z: undo
   CTRL+Y: redo
   CTRL+SHIFT+Z: redo
   CTRL+B: bold
   CTRL+I: italic
   CTRL+K: () => this._showPanel( true )
   Tab: ( data, cancel ) => { ... }
   Esc: ( data, cancel ) => { ... }
   Alt+F10: ( data, cancel ) => { ... }
   ```
   so all we need to do is find a new place for <kbd>Tab</kbd> and <kbd>Esc</kbd> listeners which are related exclusively to the Link feature.

**Comment by Reinmar** [comment] 2017-06-13 20:55
I think that I'm for 2. A callback should have a control over whether it wants to handle a keystroke or not.

If EKH is configured to execute a command it should prevent the default action. Always, regardless of the command's state. Why? Because it may happen that e.g. `bold` is disabled locally, but we don't want the default action anyway.

If EKH is configured with a callback that callback needs to be very specific whether it's handling the event or not. If it doesn't, there may be other callback executed... which moves us again to https://github.com/ckeditor/ckeditor5-core/issues/20 and the topic that perhaps KH should be an event dispatcher and nothing more.

**Comment by oleq** [comment] 2017-06-14 09:22
Should we go with 2. or wait for https://github.com/ckeditor/ckeditor5-core/issues/20? The issue is quite annoying, TBH.

**Comment by Reinmar** [comment] 2017-06-14 09:33
I think that some basic patch may easily be provided without waiting for the other issue.

**Comment by oleq** [comment] 2017-06-20 08:58
Can we consider this issue resolved since https://github.com/ckeditor/ckeditor5-core/issues/90 has been merged?

**Closed** 2017-06-20 09:15 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
