### ISSUE TITLE
Link tool has no ability to set target="_blank"

### ISSUE THREAD

**Issue by imkane** [ckeditor/ckeditor5#1441] opened 2019-01-05 20:00 UTC
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 💻 Version of CKEditor

5

## 📋 Steps to reproduce

1. Link tool has no ability to set target="_blank" to open in a new tab.

![screenshot - 1_5_2019 11_58_51 am](https://user-images.githubusercontent.com/2041683/50728607-603ff100-10e1-11e9-94f2-39e92ca49a7a.png)

This seems like a **crucial** feature ... I really am baffled that it's not currently possible.

**Comment by hiteshr882** [comment] 2019-01-05 20:14
I'm also interested in this

**Comment by oleq** [comment] 2019-01-07 15:07
Duplicate of https://github.com/ckeditor/ckeditor5/issues/1441.

**Closed by oleq** 2019-01-07 15:07 UTC

**Comment by ma2ciek** [comment] 2019-01-07 15:14
@oleq, your link links to the same page. Do you mean https://github.com/ckeditor/ckeditor5/issues/760?

**Comment by oleq** [comment] 2019-01-07 15:17
Actually, I meant https://github.com/ckeditor/ckeditor5-link/issues/186 😃
