### ISSUE TITLE
Pasted nested list from MS Word Desktop has large left margin

### ISSUE THREAD

**Issue by danman01** [ckeditor/ckeditor5#14619] opened 2023-07-19 16:02 UTC
## 📝 Provide a description of the improvement

Copy / paste nested list items between source MS Word desktop document and the other document could use some attention.

Nested items in a list (pasted from MS Word Desktop) should not have a large left margin before the content starts:
<img width="1299" alt="Screen Shot 2023-07-19 at 11 51 29 AM" src="https://github.com/ckeditor/ckeditor5/assets/58710/6d816544-3da1-4937-962b-fcf8383bcb81">

While doing testing for https://github.com/ckeditor/ckeditor5/issues/14611 I was able to secure a MS Word desktop license, and in the [full featured demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) I see a large left margin for nested items due to the p tag receiving margin-left 1in. However in the Paste from Word demo https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html this p tag is not present.

## 📃 Other details

Browser: Chrome for Mac v 114
MS Word Desktop for Mac v 16.75

## Steps to reproduce

Create a nested list in MS Word Desktop
Copy list into clipboard
Paste into full featured editor
Observe large left margin on the nested items
Paste the same content into the Paste From Word demo, observe it pastes without the large left margin.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-07-24 10:46
Hey @danman01, thanks for the report, would you mind confirming if you use Indent block plugin? Most likely it's this issue: #12466.

**Comment by danman01** [comment] 2023-07-24 18:24
Hey @Witoso ,yes we are using that plugin, so that is likely the issue. Thank you!

**Comment by Witoso** [comment] 2023-07-25 09:05
Thanks for the confirmation, will close this one as a duplicate of #12466.

**Closed by Witoso** 2023-07-25 09:05 UTC
Labels: type:improvement, package:list, domain:ui/ux, pending:feedback, squad:core
