### ISSUE TITLE
List Style plugin doesn't seem to show  dropdown in the latest classic build

### ISSUE THREAD

**Issue by KshamaShrey** [ckeditor/ckeditor5#10839] opened 2021-11-15 06:50 UTC
**Steps to Reproduce :**

 1. Go to https://ckeditor.com/ckeditor-5/online-builder/
 2. Choose editor type as Classic
 3. Choose editor plugins required. 
     

     - Select both List and List style plugin
    
4. Go to Next step and check that both bulleted and numerical listing are without dropdowns as shown below

<img width="937" alt="Liststylenew" src="https://user-images.githubusercontent.com/39548087/141734442-d540a7ae-09e2-4397-902a-d964f3ce7523.png">
 

Expected Result:

Since list style and list plugins are included in the build , both numerical and bulleted listing should include 3 styles for unordered lists and 6 styles for ordered list  as mentioned in the document 

#List styles
The list style feature introduces some more styles for the list item markers. When enabled, it adds 3 styles for unordered lists and 6 styles for ordered lists to choose from. The styles can be changed via the dropdown that opens when you click the arrow next to the appropriate list button in the toolbar.
<img width="676" alt="liststyleold" src="https://user-images.githubusercontent.com/39548087/141735029-8b4289c9-c9c0-4d33-80e3-fb12c5ce3a60.png">

Actual Result:

No dropdown is displayed for both bulleted and numerical listing as shown in the first screenshot.

**Comment by FilipTokarski** [comment] 2021-11-16 09:05
Duplicate of #10840.

**Closed by FilipTokarski** 2021-11-16 09:05 UTC
