### ISSUE TITLE
[Edge] Support for uploading images with base64 source

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#5173] opened 2018-11-14 11:00 UTC
This is a follow up ckeditor/ckeditor5#5172.

Since the [`File API`](https://developer.mozilla.org/en-US/docs/Web/API/File) is used during [image base64 to file conversion](https://github.com/ckeditor/ckeditor5-image/blob/t/246/src/imageupload/imageuploadediting.js#L327-L336), it doesn't work on Edge as `File` constructor is not supported there (see https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9551546/).

Alternatively the `Blob` object could be used, however blobs itself do not provide a way to define a filename. This is problematic since during upload the filename is read from the file object and send with other data:

![image](https://user-images.githubusercontent.com/1061942/48478166-c73cda00-e803-11e8-85bc-ff8d49e71b99.png)

and with `Blob` instance, the filename is always set to "blob":

![image](https://user-images.githubusercontent.com/1061942/48478297-2a2e7100-e804-11e8-88f2-136e4f036f29.png)

which doesn't work well with upload integration:

* File with the same name is always send to the server.
* File name doesn't have the extension so checking file type by extension fails.

---

We need to figure out a way to provide custom filename so it can be send with upload request. It may be done by adjusting blob object so the browser uses custom name which was added (not 100% sure, my initial tests failed here). The second option is to pass filename to a loader so it is used further in the uploading process (added to `formData` object).

**Comment by tomalec** [comment] 2020-04-20 10:50
Seems the issue is solved by Edge switching to Chromium. I run automated tests and a few manual ones. Checked http://localhost:8125/ckeditor5-image/tests/manual/imageupload.html precisely. 

So, from a newbie perspective seems, as solved.

**Comment by tomalec** [comment] 2020-04-20 10:54
Closing as no longer a problem.

**Closed by tomalec** 2020-04-20 10:54 UTC
Labels: package:image, type:enhancement
