### ISSUE TITLE
[iOS] Horizontal line is missing some spacing 

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7470] opened 2020-06-19 13:49 UTC
## 📝 Provide detailed reproduction steps (if any)

[In it 33 we introduced new styles for horizontal lines.](https://github.com/ckeditor/ckeditor5/issues/7418)

1.  Visit https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/horizontal-line.html

### ✔️ Expected result

![](https://user-images.githubusercontent.com/1099479/85139047-24044000-b244-11ea-9240-fb2a031a23d3.png)

### ❌ Actual result

![](https://user-images.githubusercontent.com/1099479/85139058-28c8f400-b244-11ea-9ac7-2ee601e08e80.jpeg)

## 📃 Other details

*   Browser: Safari
*   OS: iOS
*   CKEditor version: master

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment] 2020-09-09 09:25
TODO: Let's first make sure this occurs in new devices.

**Comment by magda-chrzescian** [comment] 2021-01-04 09:30
The error occurs on the \< 13 versions of the iOS system. It is caused by the not supported `display: flow-root` property and can be fixed by adding the clearfix in the `::before` and `::after` of the horizontal line element.

**Comment by oleq** [comment] 2021-01-04 10:32
That's good news! According to [Apple's website,](https://developer.apple.com/support/app-store/) 72% of all iOS devices already use iOS 14 where the problem does not occur. Given how fast the iOS adoption rate is and the rather low severity of the issue, I see no good reason to touch the code.

**Closed** 2021-01-04 14:36 UTC
Labels: domain:mobile, intro, package:horizontal-rule, squad:ux, type:bug
