### ISSUE TITLE
Paste from Word nested lists do not nest

### ISSUE THREAD

**Issue by danman01** [ckeditor/ckeditor5#14611] opened 2023-07-18 18:57 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open Microsoft Word ( I'm using MS Word Online )
2. Add a nested list ( ordered or non ordered )
3. Copy content into clipboard 
4. paste into CKEditor [full featured demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) ( [Or the paste from word demo ](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html))

See video here: https://www.loom.com/share/24778c10b3d34f13b6d6f51b5eb1b08d?sid=e213adf7-e855-4d6e-9515-27ecf6f6d522

### ✔️ Expected result

The nested list maintains its nested structure

### ❌ Actual result

The nested list turns into one single level list

### ❓ Possible solution

I see there are a few PRs that were merged in early 2020 to fix pretty similar issues, but I am not sure if something may have been reverted since then ( regression ), or if I am not understanding those merged PRs correctly...does it seem like this issue was already reported and fixed in the following?

PRs and issue fixes which lead me to believe this should be fixed:

https://github.com/ckeditor/ckeditor5-paste-from-office/pull/94 and https://github.com/ckeditor/ckeditor5-paste-from-office/pull/53 seem to fix https://github.com/ckeditor/ckeditor5/issues/2518

## 📃 Other details

* Browser: Chrome 114.0.5735.133
* OS: Mac OS 12.3
* First affected CKEditor version:
* Installed CKEditor plugins:[ full-featured demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) has the following installed:

```
@ckeditor/ckeditor5-alignment \
    @ckeditor/ckeditor5-autoformat \
    @ckeditor/ckeditor5-basic-styles \
    @ckeditor/ckeditor5-block-quote \
    @ckeditor/ckeditor5-ckbox \
    @ckeditor/ckeditor5-cloud-services \
    @ckeditor/ckeditor5-code-block \
    @ckeditor/ckeditor5-dev-utils \
    @ckeditor/ckeditor5-document-outline \
    @ckeditor/ckeditor5-editor-classic \
    @ckeditor/ckeditor5-essentials \
    @ckeditor/ckeditor5-export-pdf \
    @ckeditor/ckeditor5-export-word \
    @ckeditor/ckeditor5-find-and-replace \
    @ckeditor/ckeditor5-font \
    @ckeditor/ckeditor5-format-painter \
    @ckeditor/ckeditor5-heading \
    @ckeditor/ckeditor5-highlight \
    @ckeditor/ckeditor5-horizontal-line \
    @ckeditor/ckeditor5-html-embed \
    @ckeditor/ckeditor5-image \
    @ckeditor/ckeditor5-indent \
    @ckeditor/ckeditor5-language \
    @ckeditor/ckeditor5-link \
    @ckeditor/ckeditor5-list \
    @ckeditor/ckeditor5-media-embed \
    @ckeditor/ckeditor5-mention \
    @ckeditor/ckeditor5-page-break \
    @ckeditor/ckeditor5-paste-from-office \
    @ckeditor/ckeditor5-remove-format \
    @ckeditor/ckeditor5-slash-command \
    @ckeditor/ckeditor5-source-editing \
    @ckeditor/ckeditor5-special-characters \
    @ckeditor/ckeditor5-table \
    @ckeditor/ckeditor5-table-of-contents \
    @ckeditor/ckeditor5-template \
    @ckeditor/ckeditor5-theme-lark \
    @ckeditor/ckeditor5-typing \
    @ckeditor/ckeditor5-word-count \
    @webspellchecker/wproofreader-ckeditor5
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment] 2023-07-19 08:42
Hey! The problem lies in the usage of the online version of the MS Word. The PRs you linked are for the desktop version, which unfortunately has different structures of the content than the MS Word Online. It's a duplicate of #8539, please +1 the post, and contact our support if you're the client so that we could record your feedback.

**Closed by Witoso** 2023-07-19 08:42 UTC
Labels: type:bug, package:paste-from-office, domain:ui/ux

**Comment by danman01** [comment] 2023-07-19 11:48
Thank you @Witoso , I will start testing the desktop version soon and see if it meets our needs. We had reports of formatting issues with pasting lists, hence the deep dive.
