### ISSUE TITLE
Pasting table from Word is placed at Center instead of left

### ISSUE THREAD

**Issue by navaneethibm** [ckeditor/ckeditor5#11814] opened 2022-05-23 06:18 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Create a table in Microsoft Word. The Table itself is left aligned. 
2. Copy the Table as a whole in Word
3. Paste the contents into ckeditor5

### ✔️ Expected result

The table is pasted successfully and the table as a whole is left aligned. 

### ❌ Actual result

The whole table is positioned at center.

## 📃 Other details

* Browser:  Google Chrome v101.0.4951.67 (64-bit)
* OS: macOS Monterey 12.4
* First affected CKEditor version: v31.0.0
* Installed CKEditor plugins: PasteFromOffice, 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by navaneethibm** [comment] 2022-05-23 06:21
<img width="1341" alt="Word_Table_Left" src="https://user-images.githubusercontent.com/106056230/169755996-f55278f3-2360-43b3-8dea-9754a688db30.png">
<img width="893" alt="PasteFromOffice_Table_Center" src="https://user-images.githubusercontent.com/106056230/169756029-a2842ee5-3ce4-41c4-a8d8-b8179543e26f.png">

**Comment by FilipTokarski** [comment] 2022-05-30 12:24
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/8752. Closing.

**Closed by FilipTokarski** 2022-05-30 12:24 UTC
Labels: type:bug, package:paste-from-office, squad:core
