### ISSUE TITLE
[IME][Firefox] Confirming composition throws an `view-createPositionAt-offset-required` error

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5#3134] opened 2019-01-09 13:00 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest `master` (`v11.1.1`)

## 📋 Steps to reproduce

1. Switch keyboard to Japanese (Hiragana).
1. Go to https://ckeditor5.github.io/.
1. Put caret somewhere in the editor content.
1. Type something.
1. Confirm composition with <kbd>enter</kbd>.

## ✅ Expected result

Composition confirmed, no error is thrown.

## ❎ Actual result

Composition confirmed, `view-createPositionAt-offset-required` error is thrown.

![ff bug1](https://user-images.githubusercontent.com/1061942/50900731-5e926800-1416-11e9-9d3e-fb7ef954bc0d.gif)

## 📃 Other details that might be useful

Doesn't happen in other browsers. Tested on FF 64 and 65 (beta).

Looks like a recent regression, did not occured in `v11.0.0` (https://ckeditor5.github.io/releases/v11.0.0/).

**Comment by FilipTokarski** [comment] 2020-03-17 08:40
I just checked it with Firefox 74.0 (64-bit) on [demo page](https://ckeditor.com/ckeditor-5/demo/#classic) and `manual article test` on latest master and cannot reproduce this issue. Confirming composition in Hiragana works just fine, no errors. I'm closing this.

**Closed by FilipTokarski** 2020-03-17 08:40 UTC
Labels: browser:firefox, domain:ime, package:typing, status:confirmed, type:bug, type:regression
