### ISSUE TITLE
Allow support for sticky toolbar with decoupled editor

### ISSUE THREAD

**Issue by pruhstal** [ckeditor/ckeditor5#1808] opened 2019-06-10 17:07 UTC
## Is this a bug report or feature request? (choose one)

🆕 Feature request

## 💻 Version of CKEditor
```
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-editor-decoupled": "^11.0.2",
```

## ✅ Expected result
`viewportTopOffset:  number`

passed in to the decoupled editor config would activate the sticky toolbar.

## ❎ Actual result
`viewportTopOffset: 30` when passed in to the decoupled editor config has no effect.

## 📃 Other details that might be useful

I recall reading about some of the reasoning behind not allowing the decoupled-editor to support the sticky toolbar on scroll.

I attempted to use the classic editor build, and while it does supports the sticky toolbar, I run into some other issues related to using my custom upload adapter.

I can easily attach a scroll handler once my editor component is mounted and handle this myself, but ideally, I'd like to just be able to pass an additional param to the config (like above) and get the support for the sticky scrollbar on the decoupled editor (and not just the classic build), considering the support exists and the edge cases have been handled (but only for classic build).

**Comment by Mgsy** [comment] 2019-06-13 07:52
@oleq, can you take a look at this one?

**Comment by oleq** [comment] 2019-06-24 10:48
A duplicate of https://github.com/ckeditor/ckeditor5-build-decoupled-document/issues/7.

By design, the decoupled editor leaves all the UI management up to developers. All it offers is a static toolbar and an editable and it is not supposed to bring any additional logic like sticky containers etc..

But if you think this feature is a must-have, please chime in https://github.com/ckeditor/ckeditor5-build-decoupled-document/issues/7.

**Closed by oleq** 2019-06-24 10:48 UTC
