### ISSUE TITLE
Todo list with link in part of item text results in entire text as link

### ISSUE THREAD

**Issue by oliverguenther** [ckeditor/ckeditor5#6455] opened 2020-03-17 12:37 UTC
## 📝 Provide detailed reproduction steps (if any)

1.Use CKEditor with Todo list feature enabled with any version including 17.0 (e.g., https://ckeditor.com/docs/ckeditor5/latest/features/todo-lists.html)
2. Enter a todo list item "Foo bar"
3. Make "Foo" a link to some web page
4. Observe the resulting HTML data

### ✔️ Expected result

Only the `Foo` part becomes a link

### ❌ Actual result

The entire line `Foo bar` becomes the content of the link.

Here's a screenshot with the view HTML and the resulting `getData()` output on your todo list demo page.

![Screenshot from 2020-03-17 13-33-44](https://user-images.githubusercontent.com/459462/76856848-718f9c00-6854-11ea-8e14-f12614e70006.png)

## 📃 Other details

* Browser: Appears not to matter, tested in current Chrome and Firefox
* CKEditor version: Confirmed in versions 15.0 and 17.0
* Installed CKEditor plugins: List

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2020-03-17 14:20
Hi, thanks for the report. It's a known issue, so I'm closing it as a duplicate of https://github.com/ckeditor/ckeditor5/issues/5779.

**Closed by Mgsy** 2020-03-17 14:20 UTC
Labels: type:bug

**Comment by oliverguenther** [comment] 2020-03-17 14:22
Thanks and sorry @Mgsy , I failed to find the other issue for some reason.
