### ISSUE TITLE
Heading not working in List

### ISSUE THREAD

**Issue by lingling7250** [ckeditor/ckeditor5#10550] opened 2021-09-17 08:22 UTC
## 📝 reproduction steps (if any)

1. As usual, tried in the demo https://ckeditor.com/docs/ckeditor5/latest/features/lists.html
2. Select the text (which is in the list item)
![image](https://user-images.githubusercontent.com/90304055/133749031-f37ba2aa-a9ad-4d86-a9e0-f5bc5478ef12.png)

3. Choose heading
![image](https://user-images.githubusercontent.com/90304055/133748963-bb04e537-f0c0-4284-b3a4-7d890e3ce433.png)

4. Choose the numbered list again
![image](https://user-images.githubusercontent.com/90304055/133749460-d56581d9-0c29-4487-bf4b-f5bc108089e3.png)

### ✔️ Expected result

![image](https://user-images.githubusercontent.com/90304055/133749218-640319d0-aee4-4348-aa89-9b96b28b30aa.png)

Any possible solution to get the expected result?

## 📃 Other details

* Browser: Chrome v93 (64 bits)
* OS: Windows
* CKEditor version: CKeditor 5
* Installed CKEditor plugins: online builder

**Comment by FilipTokarski** [comment] 2021-09-20 07:12
Hi, thanks for the report. Currently lists work like that by design, so it's not a bug. We have a [feature request for advances lists](https://github.com/ckeditor/ckeditor5/issues/2973), which will most probably cover this use case and it's currently on our roadmap.
  
I'll close this one as a duplicate.

**Closed by FilipTokarski** 2021-09-20 07:12 UTC
Labels: type:bug
