### ISSUE TITLE
beforeInput: Undo breaks the backspace behaviour

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12564] opened 2022-10-05 07:32 UTC
Tested on:

*   `ck/11438-beforeinput-ime-research-vol1.1-android` branch
*   Nexus 10 emulator
*   GalaxyTab real device

## 📝 Provide detailed reproduction steps (if any)

1.  Switch to GBoard.
2.  Open the all features manual test.
3.  Select the table.
4.  Press Backspace.
5.  Undo.
6.  Put the caret at the end of some word.
7.  Hold Backspace.

### ✔️ Expected result

The text is removed.

### ❌ Actual result

Some additional characters appear. Sometimes simply nothing happens.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment] 2022-10-10 12:59
This looks like that keyboard ignores changes in the DOM and fires next events with previously known data:

![](https://user-images.githubusercontent.com/1232187/194871698-2abce191-2dd8-4bff-8ed4-05178b36e526.png)

**Comment by niegowski** [comment] 2022-10-11 12:22
Same reason as in #12569 - should be fixed already in #12446.

**Comment by Acrophost** [comment] 2022-10-12 10:16
I can't reproduce it anymore - @dufipl please confirm and close if you can't either :)

**Comment by dufipl** [comment] 2022-10-12 11:37
Same for me - the issue does not reproduce anymore on the `ck/11438-beforeinput-ime-research-vol1.1-android`, so closing.

**Closed by dufipl** 2022-10-12 11:37 UTC
Labels: type:bug, browser:android, domain:ime, squad:core, status:in-progress
