### ISSUE TITLE
Getting error `Maximum call stack size exceeded` when have very long text

### ISSUE THREAD

**Issue by gauravjain028** [ckeditor/ckeditor5#1875] opened 2019-07-10 13:15 UTC
🐞 Bug report 

Version : 12.1.0

## 📋 Steps to reproduce

I have copied a very long text. It got hang and saw the error `Maximum call stack size exceeded`

Screenshot of Error : 
<img width="729" alt="Screenshot 2019-07-10 at 5 15 35 PM" src="https://user-images.githubusercontent.com/2246860/60971055-f67afb00-a340-11e9-838d-4f3bb41a7272.png">

Text which I have used has 248kb in size when saved in a txt file.

---
Added by @wwalc:

Temporary workaround for anyone experiencing this issue: if you are trying to load an existing huge text document, that is not split into multiple paragraphs, then first convert this text document into HTML document that contains paragraphs of a reasonable size, then load it into the editor. 

CKEditor 5 should handle easily documents with 500-1500 pages of text (500,000 words), as long as it's not a single paragraph.

**Comment by Mgsy** [comment] 2019-07-10 13:25
Hi, can you share the text which you've pasted to the editor?

**Comment by gauravjain028** [comment] 2019-07-11 07:26
Here is the test which I have used
[text.txt](https://github.com/ckeditor/ckeditor5/files/3380700/text.txt)

**Comment by Mgsy** [comment] 2019-07-11 07:52
I'm able to reproduce it with the given text file. The content is pasted after a few seconds, but the editor is unusable, because of freezes. cc @mlewand @Reinmar

**Comment by Reinmar** [comment] 2019-07-11 08:59
I did some checks on CKEditor 4 and other editors and the interesting thing is that in some editors scrolling the content stays responsive, while in others it doesn't. And that indicates rendering/layouting issues, not something that the editor itself does with the content. I wonder why this problem occurs on certain websites.

E.g. here, there's no interaction from our side – it's just the browser taking so long to render all this on scroll:

![image](https://user-images.githubusercontent.com/156149/61037001-81540800-a3ca-11e9-9908-21d3171457b9.png)

So, there could be something about the styling (maybe the floating toolbar with its shadow) which causes this. 

But, of course, the other problem is that pasting it takes some good time too. I don't think it's long enough to justify this so we would need to look into this.

**Comment by Reinmar** [comment] 2019-07-11 09:05
Pasting profile:

![image](https://user-images.githubusercontent.com/156149/61037568-9da47480-a3cb-11e9-9ec3-0f73332c8446.png)

`Differ#getChanges()` takes the great majority of time on paste. So, that's where we'd need to look for improvements.

**Comment by Reinmar** [comment] 2019-07-11 09:26
More findings:

* it's none of the function calls inside `getChanges()` – it's `getChanges()`'s body itself,
* out from 420ms spent in it, this is how much each line took:

![image](https://user-images.githubusercontent.com/156149/61039246-aea2b500-a3ce-11e9-954a-9739ef3e3647.png)

**Comment by scofalik** [comment] 2019-07-16 13:22
I was never proud of this part of the code and refactoring/optimizing `Differ` was always in our minds. At the moment, this method is written in... let's call it _simplistic_ way.

**Comment by scofalik** [comment] 2019-07-16 13:23
It seems that there are a lot of entries in `diffSet`. This is interesting, cause I'd guess that when pasting you shouldn't have more than several operations.

**Comment by oskarwrobel** [comment] 2019-07-17 11:19
You don have to paste a long text. It's enough to initialize the editor with long text. But it has to be one long paragraph. Bigger document but with multiple paragraphs works fine.

**Comment by oskarwrobel** [comment] 2019-07-17 12:19
I found the problem.

Adding items to the array using `repeat`, `split` and `destructive` is too much for JS when there are `125380` items or more to add.

https://github.com/ckeditor/ckeditor5-engine/blob/917115059abaee4a8d7617ae0dff28829e8f154e/src/model/differ.js#L1115

**Comment by Reinmar** [comment] 2019-07-17 19:42
Let's review the code in this iteration and fix:

* the maximum call stack exception,
* if it doesn't require rewriting the whole thing – the splice call that I identified in https://github.com/ckeditor/ckeditor5/issues/1875#issuecomment-510407811.

And let's see where this moves us.

**Comment by Reinmar** [comment] 2019-07-17 19:44
BTW, great catch @oskarwrobel! I did some more checks on how big can the number of params be for fun: https://twitter.com/reinmarpl/status/1151577520539668493. When reviewing this code I'd never spot this issue :D  Interesting lesson.

**Comment by mlewand** [comment] 2019-07-30 08:16
Issue fixed with #1762.

**Closed** 2019-07-30 08:30 UTC
Labels: status:confirmed, type:bug, type:enhancement
