### ISSUE TITLE
Reverse list order when paste by keyboard event

### ISSUE THREAD

**Issue by malecki-se** [ckeditor/ckeditor5#1264] opened 2018-09-26 12:21 UTC
🐞 Bug report

Hello guys, I found problem when I copy and paste list from Google Docs to CKEditor5. The order is reversed and numbers of list are removed. See video:

![ezgif-1-bc00a4ee48](https://user-images.githubusercontent.com/23338674/46079098-66473d00-c196-11e8-9998-bd51fe22ca14.gif)

**Comment by ma2ciek** [comment] 2018-09-26 15:12
cc @f1ames

**Comment by Reinmar** [comment] 2018-09-26 15:38
Turns out that https://github.com/ckeditor/ckeditor5/issues/1263 may be explaining why the order is reversed.

**Comment by f1ames** [comment] 2018-09-27 05:57
@ma2ciek I just noted that in Google Docs:

> list (has structure like `ul > li > p` so instead of list, paragraphs are created)

during [`paste-from-office` research](https://github.com/ckeditor/ckeditor5/issues/1184#issuecomment-409828069), probably missed the order reversal, but I can see it happens. And as @Reinmar suggested it is the same case as #1263 caused by the `li > p` markup when pasting from Google Docs.

**Comment by f1ames** [comment] 2018-09-27 06:05
So there are two separate issues here:

1. The list formatting is lost when pasting from Google Docs (which is not supported for now - https://github.com/ckeditor/ckeditor5/issues/1264#issuecomment-424757952).
1. When content with structure like `ul|ol > li > p` is pasted or set in the editor, its order is reversed - this is already covered in #1263.

**Comment by Reinmar** [comment] 2018-10-01 10:15
I reported a ticket for Google Docs support. 👍 if you'd like to see it.

**Comment by Reinmar** [comment] 2018-10-01 10:15
I reported a ticket for Google Docs support. 👍 if you'd like to see it: https://github.com/ckeditor/ckeditor5-paste-from-office/issues/20.

**Comment by Reinmar** [comment] 2018-10-01 10:16
I'll close this ticket because it DUPs two other ticekts: https://github.com/ckeditor/ckeditor5-paste-from-office/issues/20 and https://github.com/ckeditor/ckeditor5/issues/1263.

**Closed** 2018-10-01 10:19 UTC
Labels: type:bug
