### ISSUE TITLE
Add support for definition list

### ISSUE THREAD

**Issue by ShaggyDude** [ckeditor/ckeditor5#9114] opened 2021-02-25 17:10 UTC
# Definition lists are one of the greatest seldom used HTML structures but, I have never seen a WYSIWYG implementation.

It would have to work similarly to existing lists but with some filler value for the `<dt>` part?

The default styling just renders the children as blocks which is not very exciting but my styles render them side by side which is very useful.

```
<dl>
    <dt>key:</dt> 
    <dd>value<dd>
</dl>
```

Style example of side by side which should be the default IMHO/

```
dl {
    margin-bottom: unset;
    display: grid;
    grid-template-columns: minmax(2rem, max-content) auto;
    row-gap: 0.5rem;
}

dt {
    opacity: 0.5;
}

dd {
    margin-left: 1rem;
    align-self: center;
}
```

**Comment by Mgsy** [comment] 2021-03-04 07:45
It's a duplicate of #775.

**Closed by Mgsy** 2021-03-04 07:45 UTC
Labels: resolution:duplicate, type:feature
