### ISSUE TITLE
Using ckeditor from source can not build in vuejs

### ISSUE THREAD

**Issue by umi-soft** [ckeditor/ckeditor5#8650] opened 2020-12-13 10:13 UTC
## 📝 Provide detailed reproduction steps (if any)

I have same problem with [8027](https://github.com/ckeditor/ckeditor5/issues/8027)
I am trying to remove CKEditorWebpackPlugin, but i am failed
=====my step ====

I uploaded a clean project,  created by `vue create name`

[clean project with ckeditor5](https://github.com/umi-soft/for-a-ckeditor-issue)

### ✔️ Expected result

running success with vue 2.6.11

* Browser: chrome 
* OS macos

**Comment by umi-soft** [comment] 2020-12-13 10:15
vue.config.js:
`
{
transpileDependencies: [
    /ckeditor5-[^/\\]+[/\\]src[/\\].+\.js$/
  ],
  chainWebpack: config => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap(o => {
        const options = o
        options.compilerOptions.preserveWhitespace = true
        return options
      })
      .end()
    config
      // https://webpack.js.org/configuration/devtool/#development
      .when(process.env.NODE_ENV === 'development', o => {
        const options = o
        options.devtool('cheap-source-map')
        options.optimization.runtimeChunk('single')
      })
    config.module
      .rule('svg')
      .exclude
      /* 本地 svg icon文件 */
      .add(resolve('src/icons'))
      /* ckeditor icon文件 */
      .add(path.join(__dirname, 'node_modules', '@ckeditor'))
      .end()
    /* 本地 svg icon文件 */
    config.module
      .rule('icons')
      .test(/\.svg$/)
      .include.add(resolve('src/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })
      .end()
    /* ckeditor icon文件 */
    config.module
      .rule('cke-svg')
      .test(/ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/ )
      .use('raw-loader')
      .loader('raw-loader')
    config.module
      .rule('cke-css')
      .test(/ckeditor5-[^/\\]+[/\\].+\.css$/)
      .use('postcss-loader')
      .loader('postcss-loader')
      .tap(() => (
        styles.getPostCssConfig({
          themeImporter: {
            themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
          },
          minify: true
        })
      ))
  }

}
`

**Comment by Mgsy** [comment] 2020-12-14 08:22
Hi, did you follow our guide for [Vue 2 integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html)?

**Comment by umi-soft** [comment] 2020-12-14 10:21
Yes, I am following guide for [Vue 2 integration?](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html)
There are no errors in the compilation process。

**Comment by umi-soft** [comment] 2020-12-14 10:22
> Hi, did you follow our guide for [Vue 2 integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html)?

Yes, I am following guide for [Vue 2 integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html)
There are no errors in the compilation process。

**Comment by umi-soft** [comment] 2020-12-14 10:25
> Hi, did you follow our guide for [Vue 2 integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html)?

Yes, I have followed guide for [Vue 2 integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html)
There are no errors in the compilation process。but in Chrome console，I found：

- plugincollection-load
- TypeError: Cannot read property 'getAttribute' of null

**Comment by FilipTokarski** [comment] 2021-03-08 14:42
Hi, sorry for the late reply. I cloned the repository you linked and it works fine. Please make sure this is not caused by browser cache. If you are still experiencing this problem, we'll need detailed information on how to reproduce this. Otherwise I think we can close this ticket, as it seems that the problems are not caused by the editor itself.

**Closed** 2021-04-13 13:19 UTC
Labels: pending:feedback, type:bug
