### ISSUE TITLE
Conclude the research about inserting images via URL

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7439] opened 2020-06-16 11:53 UTC
## Provide a description of the task

Related: #5161 and #5039.

**Comment by jodator** [comment] 2020-07-22 08:48
@Reinmar , @oleq & @panr - It looks like we had a clash with #7476. So after a suggestion I've merged those into one as both are about the same and there's no reason to duplicate work.

**Comment by Reinmar** [comment] 2020-07-31 07:14
Some concerns to be addressed on the sync:

*   If the system uses an upload adapter like EasyImage or CKFinder, showing the URL of that image when the user presses the image button does not make much sense to me. That URL is an internal thing. However, we don't have the means to detect which image is which... Which one was inserted via URL and which one was uploaded. So, I'd consider not having the "replace image" functionality at all for now and see if inability to change a URL of an image is a big deal.
*   The integrations must not be limited to the balloon. E.g. CKFinder must open in a new modal anyway. So, things like rotators or tabs don't seem to be useful. In fact, having 2 options (file browser, URL) in the first tab and some "open CKFinder" button in the other tab would we odd. Therefore, I'd rather try to figure out how we can enable extending the primary view.

**Comment by panr** [comment] 2020-07-31 08:26
> However, we don't have the means to detect which image is which... Which one was inserted via URL and which one was uploaded. So, I'd consider not having the "replace image" functionality at all for now and see if inability to change a URL of an image is a big deal.

Get it, but the problem is that the users need to delete images first — losing all additional attributes/styling — then insert the new images and add those attributes once again... 

However, we can simplify it by:
- removing `Insert image` and `Replace image` from the Basic view for good.
- clicking on the plugin icon (primary option) always triggers the native picker:
  - if there's no selected image -> the plugin will insert it to the content

![image](https://user-images.githubusercontent.com/1303365/89015890-1e584a80-d318-11ea-93a8-dc781b3001cf.png)

  - if there's already selected image -> the plugin will replace it (we just replace the `src` attribute)

![image](https://user-images.githubusercontent.com/1303365/89015779-e9e48e80-d317-11ea-80c9-0ed26e8da7e9.png)

- the dropdown contains only the `Insert image via URL` form (and maaaaaaybe "integration view" — without any tabs/rotator).

**Comment by Reinmar** [comment] 2020-07-31 09:46
> *   If the system uses an upload adapter like EasyImage or CKFinder, showing the URL of that image when the user presses the image button does not make much sense to me. That URL is an internal thing. However, we don't have the means to detect which image is which... Which one was inserted via URL and which one was uploaded. So, I'd consider not having the "replace image" functionality at all for now and see if inability to change a URL of an image is a big deal.

We discussed this problem and decided that it's not cool, but it's ok to show the URL of an uploaded image. 

However, we need to consider:

*   base64 upload adapter – displaying the entire URL in an `<input>` does not make sense
*   `srcset`, `sizes` – those attrs need to be removed when an image is being replaced with a new one via URL

> However, we can simplify it by:
> 
> removing `Insert image` and `Replace image` from the Basic view for good.
> 
> clicking on the plugin icon (primary option) always triggers the native picker:
> 
> *   if there's no selected image -> the plugin will insert it to the content
> 
> ![image](https://user-images.githubusercontent.com/1303365/89015890-1e584a80-d318-11ea-93a8-dc781b3001cf.png)

This UX represents the modularity of this feature very well. The face of the button is the base feature that we have right now – it always opens the native file picker. The "arrow" is an opt-in feature, something that we'll be implementing now.

> ## Balloon toolbar for an image

We discussed that it's a bit superfluous right now. That the balloon editor case is not critical – it's a limited editor anyway. We can always add this button in the future if we'll see a need.

**Comment by Reinmar** [comment] 2020-07-31 09:52
Features:

*   base image
*   panel view
    *   insert via URL
    *   custom integrations

**Comment by Reinmar** [comment] 2020-07-31 09:55
As for custom integrations, we agreed that the panel view will be configurable just like a toolbar – you will specify names of components registered in the component factory.

E.g., like this:

```
image: {
    panel: {
    	items: [
    		'insertImageViaUrl', 
    		'openCKFinder'
    	]
    }
}
```

**Closed** 2020-08-05 09:14 UTC
Labels: squad:ux, type:task
