### ISSUE TITLE
How Can We Get HTML with CSS Styles?

### ISSUE THREAD

**Issue by TuguldurJ** [ckeditor/ckeditor5#5923] opened 2019-12-07 14:49 UTC
**Purpose:**
We need HTML data with CSS styles for email templates and / or for many other purposes.

**Action:**
`...editor.getData()
`

**Result:**
`<figure class="image image-style-align-left image_resized" style="width:146px;">...</figure>`

**Question:**
How can we get those`class="image image-style-align-left image_resized"` css styles?

**Comment by Mgsy** [comment] 2019-12-09 08:28
Closing it as a duplicate of https://github.com/ckeditor/ckeditor5/issues/5925.

**Closed by Mgsy** 2019-12-09 08:28 UTC
