### ISSUE TITLE
The table chooses not to show a border and still appears 

### ISSUE THREAD

**Issue by yurichi** [ckeditor/ckeditor5#11743] opened 2022-05-11 07:38 UTC
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/11832664/167794911-bb97b1d6-71ae-4c2f-9395-ec96b733e8bb.png">

**Comment by FilipTokarski** [comment] 2022-05-17 08:52
Hi, the table looks is by default controlled by the [content styles](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html), which are bundled together with the editor. Table and cell properties features are used to modify them to apply different styling (until you actually use table/cell properties, it will always display default table styles). In other words, it's by design.

**Comment by jswiderski** [comment] 2022-05-19 09:44
This issue is a duplicate of https://github.com/ckeditor/ckeditor5/issues/6841. @yurichi please refer to 6841 for a potential solution which might work for you.

**Closed by jswiderski** 2022-05-19 09:44 UTC
Labels: type:bug, pending:feedback
