### ISSUE TITLE
Widget editing UI visible when the editor is blurred

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7817] opened 2020-08-10 11:21 UTC
## 📝 Provide detailed reproduction steps (if any)

1.  Open [the document editor demo](https://ckeditor.com/docs/ckeditor5/20.0.0/examples/builds/document-editor.html).
2.  Insert a few images so that the issue with widget is more visible.
3.  Select all the editor contents.
4.  Move the focus out of the editor (e.g. to a search box).

### ✔️ Expected result

Widget UI such as type around icons, widget border, select icon are hidden.

### ❌ Actual result

The UI helpers are visible.

## 📃 Other details

*   Browser: Any
*   OS: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment] 2020-08-31 08:07
WDYT @oleq?

**Comment by oleq** [comment] 2020-09-01 10:55
> The UI helpers are visible.

It's by design. 

Thanks to that, focused editor or not, you can simply click a widget type around button and type text straight away (like putting the caret in some new place). Same with the selection handle. 

It's always one (especially annoying on mobiles) click less.

**Comment by Reinmar** [comment] 2020-10-05 07:45
Closing as invalid.

**Closed** 2020-10-05 08:10 UTC
Labels: domain:ui/ux, intro, package:widget, resolution:invalid, type:bug
