### ISSUE TITLE
Insert table to the numbered list cause of the list reset

### ISSUE THREAD

**Issue by sathit** [ckeditor/ckeditor5#9378] opened 2021-03-28 04:29 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Go to List feature https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html
2. Try to add table to the numbered list,
2.1 At "1. Gather the ingredients." row, use "Shift + Enter"
2.2 Insert table at the current cursor

![Bug](https://lh3.googleusercontent.com/fife/ABSRlIonKYPjBQOz_4GftnoDFHyxxv4WcjNirpmC6yjZHpjgn4blgr6PWb8-IMgydbSH9wZH0N4bGOZ1uniEIMteykGdqijhX8dys8V-jR5vTQIhCxh3n2JkqQPW1cROau-2Ru-NK3zQTCHyEqjNYRGR2IJcA15FZ2RIJI8wNK-JDWWu1QWsC9q7yk3l8Os_rvb4L_YQgDmG0unUWAMzsxl4LBeajsQ89Pw0XTZutsRRjjwCH7UU0luqjyROHjLp2qZit_gomHb3JIAlgaxqnTOgIhK6GWV01iRS1cpKdLXAyV2c4z-vI3u1S-IfGl0PkmZH5318TSpHqZdf9U-uB79Pu0JyRf4CpSWryiLjyoIyTgXZJ01Sewp9Q-UGqtLNkDFlS3exnY78-9N47szXNMMyr5aH6CQOscizLTjuCQ3uSij1y_IluKGBgehhpaIKsw_lCvrmekoMJoSNNtfHUHOl7YhzOdOel9nMSwhSK0qgtdT07qZSWkuOJ_MdfqHYk2hxLUncgu98UyAFr7YtLmq2R1moQQKWveZTDp2sicSP2Vpy4vSIL5y5XU9QitCGxfy1jW5U8xTH4Ig3kHS6TQIM8ZicPcZdYi3S522SoV9HAZolJ_e2L8CdkbjP3rvHLEScsEUJZKXT5ZpRPMwGHvtqaEAGar1QqpSwqR_y28LNZQPW6VVbz3JxziDzQzT7fNyG0NJS9ekgTwYM9B6UiumXHjArdudn5vHkUg=w1920-h880-ft)

### ✔️ Expected result

Row "2. Put 15g of ground coffee in the cup." should not be changed.

### ❌ Actual result

Row "2. Put 15g of ground coffee in the cup." changed to "1. Put 15g of ground coffee in the cup."

## 📃 Other details

* Browser: any
* OS: any
* First affected CKEditor version: 5
** version 4 is working correctly
* Installed CKEditor plugins: @ckeditor/ckeditor5-list 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-03-29 06:44
Hi, thanks for the report. That's a feature, not a bug. Currently lists cannot contain any block elements, that's why in this case the list is split into two separate lists.  
We have a [feature request for more advanced lists](https://github.com/ckeditor/ckeditor5/issues/2973). Please feel free to join the discussion there and add 👍  to increase its popularity. I'm closing this as a duplicate.

**Closed by FilipTokarski** 2021-03-29 06:44 UTC
Labels: type:bug
