### ISSUE TITLE
Add spell checker feature (WProofreader) to Features documentation

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#1916] opened 2019-07-26 12:56 UTC
We will be launching the new spell checking solutions product page on our website soon, so it's time to add a dedicated Features page for WProofreader to our documentation.

Their demo of CKEditor 5 integration is here: https://webspellchecker.com/wsc-proofreader/#proofreader-ckeditor5

**Comment by AnnaTomanek** [comment] 2019-07-30 05:42
Some Proofreader documentation [that @f1ames found](https://github.com/ckeditor/ckeditor-dev/issues/3301#issuecomment-516043526) 😉 May come in handy when creating the sample.

* https://docs.webspellchecker.net/pages/viewpage.action?pageId=442663877
* http://dev.webspellchecker.net/api/wscbundle/AutoSearchCreation.html
* https://github.com/WebSpellChecker/wproofreader

**Comment by mlewand** [comment] 2019-07-31 12:15
Duplicate of #1583.

**Closed by mlewand** 2019-07-31 12:15 UTC
Labels: status:confirmed, type:docs
