### ISSUE TITLE
Errors Headings

### ISSUE THREAD

**Issue by atoledogithub** [ckeditor/ckeditor5#11345] opened 2022-02-28 05:50 UTC
An error was detected when applying the Heading to the text, so that, even if an h3 heading is applied, it becomes an H4 in the source code. Although it occurs in all modes of the editor, you can check this erroneous behavior in the example that integrates the source option.

https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html

That said, when reviewing the build code I was able to verify that the view parameter of the array does not correspond to the option of the selected heading

{model:"heading1",view:"h2",title:"Heading 1",class:"ck-heading_heading1"},
{model:"heading2",view:"h3",title:"Heading 2",class:"ck-heading_heading2"},
{model:"heading3",view:"h4",title:"Heading 3",class:"ck-heading_heading3"}

The correct way should be

{model:"heading1",view:"h1",title:"Heading 1",class:"ck-heading_heading1"},
{model:"heading2",view:"h2",title:"Heading 2",class:"ck-heading_heading2"},
{model:"heading3",view:"h3",title:"Heading 3",class:"ck-heading_heading3"}

**Comment by Reinmar** [comment] 2022-03-02 09:47
cc @ckeditor/qa-team

**Comment by FilipTokarski** [comment] 2022-03-09 10:21
Hi, this is not a bug but intentional behaviour. [By default headings start from `<h2>` element](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#heading-levels) and `<h1>` is reserved for the [title plugin](https://ckeditor.com/docs/ckeditor5/latest/features/title.html). You can change this default behaviour in [headings plugin configuration](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuration).
I'll close this ticket for now.

**Closed by FilipTokarski** 2022-03-09 10:21 UTC
Labels: type:bug
