### ISSUE TITLE
[Windows] Uploaded images disappear when dragged if no alt tag is set in Chromium browsers

### ISSUE THREAD

**Issue by rossbearman** [ckeditor/ckeditor5#15700] opened 2024-01-16 09:28 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open a CKEditor instance (including the [demo builds at ckeditor.com](https://ckeditor.com/ckeditor-5/demo/feature-rich/)) in a Chromium browser
2. Upload an image, either by clicking the "Upload image from computer" button, or dragging one onto the editor
3. Wait for the image to fully upload
4. Drag the image to a new location without setting the alt tag

### ✔️ Expected result

The image should reappear in the location it was dragged to, or stay in the same place if the carat hasn't been moved.

### ❌ Actual result

The image disappears when you release the mouse button after dragging it to move it, even if you only move the mouse a single pixel in any direction. When viewing the source, the element has been removed entirely.

## 📃 Other details

The issue is reproducible during the session that they are first uploaded and during subsequent sessions.

The behaviour is consistent when adding or removing the alt tag using the source browser. Without an alt tag, or with an empty alt tag (`alt=""`), the image disappears as soon as it moves, with an alt tag (even containing just a space), the image moves around as you'd expect.

* Browser: Tested in Chrome and Edge on Windows, does not affect Firefox
* OS: Tested in Windows 10 and 11
* First affected CKEditor version: Discovered in 40.2.0 on Drupal, and whatever version is running on the ckeditor.com demos

**Comment by Witoso** [comment] 2024-01-16 09:55
Hi, thanks for the report! Could you record a video, and explain a bit more this step:

> Drag the image to a new location without setting the alt tag

I completed the steps and dragged the image to a different app, worked. Also dragging the picture in the [multi-root works](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/multi-root-editor.html) (it has multiple different editable).

Thanks!

**Comment by FilipTokarski** [comment] 2024-01-16 12:07
I checked it and it looks like the `LinkImage` plugin is the problem. If I remove this plugin from the editor, then I'm no longer able to reproduce the problem.

Also, I'm able to reproduce it only on Windows, macOS seems to work fine.

@rossbearman could you check on your side if it helps when you remove the `LinkImage` plugin?

**Comment by FilipTokarski** [comment] 2024-01-16 12:16
Also, looks like it was introduced in `40.2.0`, as I'm not able to reproduce it on older demos.

**Comment by TheSpyder** [comment] 2024-01-16 20:21
My change (#15134) was designed to be limited to user pasting - but it looks like drag and drop triggers the clipboard pipeline? So that's plausible. It first checks if the entire "pasted" content is a URL, so it should be doing nothing (the drag and drop implementation doesn't appear to even set `text/plain` on the data transfer).

**Comment by Witoso** [comment] 2024-01-23 11:14
Closed via #15737.

**Closed by Witoso** 2024-01-23 11:14 UTC
Labels: type:bug, package:image, package:upload, browser:chrome, browser:edge, type:regression, squad:core, status:in-progress
