### ISSUE TITLE
Classic editor shoul support Font + improve build aspect

### ISSUE THREAD

**Issue by bert-w** [ckeditor/ckeditor5#1892] opened 2019-07-16 15:46 UTC
🆕 Feature request 

It is really cumbersome to create a new custom build. The guide on https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html is way too complicated; I am not going to create a new project just to add 1 "Font" plugin to my build. The design for this is bad.

Npm packages created by the community (example https://www.npmjs.com/package/ckeditor-build-font ) are just pretty useless and in my view misuse the concept of npm. The npm module contains only a minified build. This cant be the preferred way of doing things.

It would be much easier to have a webpack type of solution, consisting of a single npm package with all the plugins as dependencies, and a unified script that allows you to build whichever plugin combination you'd like. Does such solution exist?

Any opinions/alternatives are welcome.

**Comment by Mgsy** [comment] 2019-07-17 14:13
Hello, thanks for the feedback. Actually, we're aware of this issue and definitely, we'll be working on improving current solution. [Here](https://github.com/ckeditor/ckeditor5/issues/667#issuecomment-507061479) you'll find a short explanation of why we decided to implement it this way.

I'm closing this report as a duplicate of https://github.com/ckeditor/ckeditor5/issues/667.

**Closed by Mgsy** 2019-07-17 14:13 UTC
