### ISSUE TITLE
Cut, copy and paste create additional undo step

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#781] opened 2018-01-23 14:05 UTC
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Select some word.
3. Cut it.
4. Undo.

## ✅ Expected result

There is only one undo step.

## ❎ Actual result

There are two undo steps. After performing second undo, editor crashes.

## 📃 Other details that might be useful

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/35279892-bca72124-004e-11e8-99bf-16379eabe5bb.gif)

**Error**
```
ckeditorerror.js:46 Uncaught CKEditorError: model-history-wrong-version: Given base version points to the middle of a delta. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#model-history-wrong-version
    at History._getIndex (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:48363:10)
    at History.getDeltas (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:48265:24)
    at getDeltas.next (<anonymous>)
    at transformRangesByDeltas (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:36548:14)
    at transformSelectionRange (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:36523:22)
    at UndoCommand._restoreSelection (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:36440:30)
    at Object.editor.model.enqueueChange [as callback] (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:54118:9)
    at Model._runPendingChanges (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:66437:58)
    at Model.enqueueChange (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:66417:9)
    at UndoCommand.execute (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:54114:21)
```

**Notes**
Here is first bad commit - https://github.com/ckeditor/ckeditor5/commit/b279e7e9523a21f47d3d1cca9461b9a4bf96b052

**Other information**
OS: Windows 10, macOS X
Browser: All browsers

**Comment by Mgsy** [comment] 2018-01-24 08:32
It turned out that it's not only cut. If you try to copy some word or paste something, additional undo step will appear.

![bug_cke5](https://user-images.githubusercontent.com/20988892/35322150-7ae23b98-00e9-11e8-8bb9-1a8b3fe77817.gif)

**Comment by Reinmar** [comment] 2018-01-25 11:58
> Here is first bad commit - b279e7e

While this is a bit strange, I confirmed that this is the first bad revision. Unfortunately, we've been merging so many things at that moment (e.g. license updates) that it didn't help in understanding what caused the problem.

**Comment by Reinmar** [comment] 2018-01-25 12:05
I confirmed that this issue can be reproduced with only the `EssentialPreset` so most likely, the issue  is caused by...

* https://github.com/ckeditor/ckeditor5-engine/commit/f56bddf
* https://github.com/ckeditor/ckeditor5-typing/commit/8a4c498
* https://github.com/ckeditor/ckeditor5-undo/commit/325a684

Which doesn't help at all.

**Comment by scofalik** [comment] 2018-02-21 11:41
Will be fixed by https://github.com/ckeditor/ckeditor5-undo/pull/80

**Closed** 2018-02-22 22:12 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
