### ISSUE TITLE
[Chrome] Can't remove the whole content when the widget is at the beginning/end of the document

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11904] opened 2022-06-10 08:05 UTC
Branch `ck/11438-beforeinput-ime-research-vol1.2-android`

## 📝 Provide detailed reproduction steps (if any)

Steps updated 13.09.2022 as explained here: https://github.com/ckeditor/ckeditor5/issues/11904#issuecomment-1245109027

1.  Open http://localhost:8125/ckeditor5/tests/manual/all-features.html in Chrome.
2.  Create a new paragraph at the beginning of the document.
3.  Put an image at the document's beginning (inside a previously created paragraph).
4.  Select all.
5.  Press Delete.

### ✔️ Expected result

The content is removed.

### ❌ Actual result

Nothing happens.

## 📃 Other details

Can't reproduce it on `master`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment] 2022-06-10 09:32
I can confirm that this issue is not reproducing on Firefox, Safari and Safari@iOS, so I've marked it as Chrome related.

**Comment by Acrophost** [comment] 2022-08-29 11:17
Still persists on branch ck/11438-beforeinput-ime-research-vol1.1-android in case of placing image at the beginning of document.
The focus after adding image goes to insert image button on toolbar.
This issue is still occuring only on Chrome.


https://user-images.githubusercontent.com/66953380/187189065-3f18e97c-cc6d-41ed-ad09-01a2f4710ed8.mov

**Comment by Reinmar** [comment] 2022-08-31 09:24
There's no beforeInput fired in this case :\< It's a Chrome bug.

We need to create a minimal test case with a plain contenteditable and report this to Blink guys.

**Comment by Reinmar** [comment] 2022-08-31 09:28
As for a workaround – the idea is to detect the situation when we had `keydown:Backspace` + `keyup:Backspace` without a `beforeInput` in the middle. Let's make it precise.

**Comment by Reinmar** [comment] 2022-08-31 09:31
Note, this can be reproduced on ckeditor/ckeditor5#11456 and it has nothing to do with Android.

**Comment by Reinmar** [comment] 2022-09-13 07:32
I'm on Version 105.0.5195.102 (Official Build) (x86\_64) and it's still reproducible for me. What branch are you checking?

**Comment by Reinmar** [comment] 2022-09-13 07:34
I'm still getting the same events logged:

![](https://user-images.githubusercontent.com/156149/189839156-79428a02-a1fc-44b2-8f40-856ffc3c6398.png)

I'm testing this on the before input branches (either the epic one `ck/epic/11438-migrate-to-beforeinput` or the Android one `ck/11438-beforeinput-ime-research-vol1.1-android`, doesn't matter).

**Comment by arkflpc** [comment] 2022-09-13 08:49
Ok, it still happens on `ck/11438-beforeinput-ime-research-vol1.1-android` but doesn't happen on `ck/11438-beforeinput-ime-research-vol1.2-android` anymore.

When **backspace** is pressed, `keyup` follows `keydown` directly, but when **delete** is pressed, there is unrelated `beforeinput` event between them.

![](https://user-images.githubusercontent.com/8916871/189856692-da9f5ca8-d8c6-4911-9c98-1447a7eb83c2.png)

**Comment by dufipl** [comment] 2022-09-13 08:59
@Reinmar, @arkflpc I think I see where the misunderstanding might be: when you put the image at the beginning of the document, but **within existing paragraph** issue does not reproduce, but when you create **a new paragraph at the beginning** and put the image there, the issue is still reproducing as shown here:
![image cant delete](https://user-images.githubusercontent.com/32898551/189858011-7c9b753d-e1d8-4900-a40c-2297b5c2ae3a.gif)

I've added this step to the issue description for clarification.

For the record, I'm using the `ck/11438-beforeinput-ime-research-vol1.1-android` branch and the 105.0.5195.102 (arm64) Chrome version.

**Comment by arkflpc** [comment] 2022-09-14 11:25
In case of forward delete (key code 46) there is `beforeinput` event with `inputType == 'insertText'` and `data == '\x7f'` (Unicode "Delete" symbol) between `keydown` and `keyup`. It has to be ignored, because it add garbage to the end and messes with selection.

**Comment by arkflpc** [comment] 2022-09-19 10:16
I've filled a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1365311.

**Comment by niegowski** [comment] 2022-09-19 11:37
Closed in #12474.

**Closed by niegowski** 2022-09-19 11:37 UTC
Labels: type:bug, browser:chrome, domain:ime, squad:core
