### ISSUE TITLE
Editor breaks when setting data with '&' in the content

### ISSUE THREAD

**Issue by mstermaaten** [ckeditor/ckeditor5#5675] opened 2019-10-28 11:04 UTC
Using the & while writing the articles is no problem, saving it and parsing it on the frontend is not problem but when I want to edit an article that as a & anywhere in the content the editor breaks...

Recreate:

1. Setup React/editor component (npm i @ckeditor/ckeditor5) with firebase.
2. Write article only an "&" and store editor content with getData() in Firebase.
3. Edit document by initialising editor with content parsed in the CKEditor.data={Firebase content}.

![Schermafdruk 2019-10-28 11 47 45](https://user-images.githubusercontent.com/49290062/67673159-b2584880-f979-11e9-8387-fdd8f3d14ee5.png)

![Schermafdruk 2019-10-28 11 59 07](https://user-images.githubusercontent.com/49290062/67673442-5a6e1180-f97a-11e9-9719-b9868625929b.png)

### ✔️ Expected result

Expected result is that it would be possible to edit saved data even if there is a & symbol anywhere in the content.

### ❌ Actual result

![Schermafdruk 2019-10-28 11 51 20](https://user-images.githubusercontent.com/49290062/67672982-55f52900-f979-11e9-9e63-a40c8643ccc5.png)

## 📃 Other details

* Browser: Chrome v77
* OS: macOS
* CKEditor version: "@ckeditor/ckeditor5-react": "^1.1.3"
* Installed CKEditor plugins:
 plugins: [
    Essentials,
    SimpleUploadAdapter,
    Base64UploadAdapter,
    UploadAdapter,
    MathType,
    Bold,
    Italic,
    Subscript,
    Superscript,
    Underline,
    BlockQuote,
    HorizontalRule,
    Heading,
    Image,
    ImageCaption,
    Font,
    ImageStyle,
    Indent,
    IndentBlock,
    ImageToolbar,
    ImageUpload,
    List,
    MediaEmbed,
    Link,
    Paragraph,
    Code,
    PasteFromOffice,
    Table,
    TableToolbar,
    Alignment
  ]

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mstermaaten** [comment] 2019-10-28 11:05
Maybe some additional webpack config needed?

**Comment by Mgsy** [comment] 2019-10-29 08:11
Hello, thank you for the report. Can you prepare some live example where we'll be able to reproduce this issue?

**Comment by mstermaaten** [comment] 2019-10-29 09:55
[https://github.com/mstermaaten/test-editor](https://github.com/mstermaaten/test-editor)

This is a basic version of my product with fake credentials but using the same configs and packages.

[https://objective-blackwell-ced0b4.netlify.com/](https://objective-blackwell-ced0b4.netlify.com/)
username: test@editor.com
pw: testing

**Comment by Reinmar** [comment] 2019-11-13 17:44
Ah! I figured this out now – the problem is caused by the MathType plugin. We've just had another bug report about this: https://github.com/ckeditor/ckeditor5/issues/5732.

I'll close this ticket as a DUP of https://github.com/ckeditor/ckeditor5/issues/5732.

**Closed by Reinmar** 2019-11-13 17:44 UTC
Labels: pending:feedback, type:bug
