### ISSUE TITLE
Source View

### ISSUE THREAD

**Issue by agluck3** [ckeditor/ckeditor5#629] opened 2017-10-23 13:32 UTC
- [X ] Feature request

## 💻 Version of CKEditor
V5

I would love to see the View Source option become available. When I write my posts I like to be able to add custom html into it.

**Comment by pjasiun** [comment] 2017-10-23 14:05
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/592.

**Closed by pjasiun** 2017-10-23 14:05 UTC

**Comment by bhojkamal** [comment] 2021-01-27 14:30
Yes, I also want to see the source code like in CKEditor 4.

**Comment by robozb** [comment] 2021-02-10 01:34
+1

**Comment by webivan1** [comment] 2021-03-26 15:32
+1
