### ISSUE TITLE
[Question] Table: Turn off auto-resize when width has been set

### ISSUE THREAD

**Issue by Madejczyk** [ckeditor/ckeditor5#10938] opened 2021-12-02 12:33 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/table.html#configuring-styling-tools
2. Set max width for table
3. Add long text

### ✔️ Expected result

Threshold for width limit will be not exceeded. Text with ellipsis? Decrease font size?

### ❌ Actual result

Threshold for width limit has been exceeded

![image](https://user-images.githubusercontent.com/11577626/144422081-4218ff7e-e2c2-4be5-af49-ed4e41c1f403.png)
![image](https://user-images.githubusercontent.com/11577626/144422152-38705f8b-e219-414a-aefe-29c799ce1fd9.png)
![image](https://user-images.githubusercontent.com/11577626/144422498-6e908d0f-74e0-4fbd-907b-6fc32f0c956a.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-12-02 13:37
Hi, thanks for the report. This behaviour is basically how the table width works and it is not a bug. You can see the [explanation in this comment](https://github.com/ckeditor/ckeditor5/issues/7377#issuecomment-640374827). 
I'll closing this one as a duplicate.

**Closed by FilipTokarski** 2021-12-02 13:37 UTC
Labels: type:bug
