### ISSUE TITLE
Element in the block quote doesn't remove if selection contains three block elements

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#733] opened 2017-12-19 09:12 UTC
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Start the selection in the first block quote's paragraph and move it to the `OL List item 2`.
3. Press delete.

## ✅ Expected result

Paragraph, image and list item have been removed.

## ❎ Actual result

Only image and list item have been removed.

## 📃 Other details that might be useful

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/34149073-24cd585c-e4a4-11e7-9496-ab7e264d5320.gif)

**Notes**
If you try to put the selection in the paragraph which should be deleted, you'll get the notification in the console:

```
model-selection-range-in-graveyard: Trying to add a Range that is in the graveyard root. Range rejected. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#model-selection-range-in-graveyard
 undefined
```

If you try to make `undo`, the paragraph will be restored.

This bug is reproducible only if the selection contains at least one block from the block quote and two blocks from outside the block quote.

**I'm not able to reproduce it in https://ckeditor5.github.io/, so it might be a regression**

**Other information**
OS: Windows 10, MacOS X
Browser: All browsers

**Comment by Reinmar** [comment] 2018-01-17 11:34
It's indeed some kind of a regression. Looks like a differ, but I'm not sure whether on 19 Dec we had a differ already.

cc @scofalik

**Comment by scofalik** [comment] 2018-02-20 14:36
Yes, I found what causes the bug and it is indeed a bug in differ. I am on it.

**Comment by scofalik** [comment] 2018-02-21 11:42
Will be fixed by https://github.com/ckeditor/ckeditor5-engine/pull/1316

**Closed** 2018-02-22 23:10 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
