### ISSUE TITLE
[Word] Image not uploaded when copying full document content

### ISSUE THREAD

**Issue by fubar-coder** [ckeditor/ckeditor5#2493] opened 2019-02-08 10:45 UTC
The image is not uploaded when copying the full contents of the Word document.

When copying only the image with the surrounding paragraphs, the image is uploaded again.

Test Word file:
[PasteFromWordTest.docx](https://github.com/ckeditor/ckeditor5-paste-from-office/files/2844717/PasteFromWordTest.docx)

EDIT: I used Word 2016 (Office 365 ProPlus), version 1808

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2019-10-23 08:17
Finally, I was able to reproduce this issue, however only in our manual tests. My environment:
- Windows 10
- MS Word 365 (16.0.12026.20334)

The scenario which worked for me:

1. Add `PFO` plugin to Easy Image manual test.
1. Insert an image to the Word document.
1. <kbd>Ctrl + A</kbd>.
1. <kbd>Ctrl + C</kbd>.
1. Paste inside the Easy Image manual test.

**Comment by tuannd255** [comment] 2020-02-18 08:57
@Mgsy Hello!
With problem https://github.com/ckeditor/ckeditor5/issues/2493#issuecomment-545326729
Now, I'am stuck in this mistake.
Do you have a solution for this issues?

**Comment by Mgsy** [comment] 2020-02-18 09:48
Hi @tuannd255. Unfortunately, we haven't worked on this issue yet, so I'm afraid I can't propose any solution. However, you can add 👍 to the first post to raise the popularity of the issue.

**Comment by Adaer** [comment] 2020-03-17 07:15
Windows 7(64bit)
Google Chrome 80.0.3987.132
Microsoft Office Professional Plus 2013
Classic editor5
...
   "@ckeditor/ckeditor5-editor-classic": "^17.0.0",
    "@ckeditor/ckeditor5-editor-decoupled": "^17.0.0",
    "@ckeditor/ckeditor5-editor-inline": "^17.0.0",
    "@ckeditor/ckeditor5-engine": "^17.0.0",
    "@ckeditor/ckeditor5-enter": "^17.0.0",
    "@ckeditor/ckeditor5-essentials": "^17.0.0",
    "@ckeditor/ckeditor5-font": "^17.0.0",
...
--------------------
Not allowed to load local resource: file:///C:/Users/**/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg

**Comment by Adaer** [comment] 2020-03-17 07:16
#### Windows 7(64bit)
#### Google Chrome 80.0.3987.132
#### Microsoft Office Professional Plus 2013
#### Classic editor5

```
"@ckeditor/ckeditor5-editor-classic": "^17.0.0",
"@ckeditor/ckeditor5-editor-decoupled": "^17.0.0",
"@ckeditor/ckeditor5-editor-inline": "^17.0.0",
"@ckeditor/ckeditor5-engine": "^17.0.0",
"@ckeditor/ckeditor5-enter": "^17.0.0",
"@ckeditor/ckeditor5-essentials": "^17.0.0",
"@ckeditor/ckeditor5-font": "^17.0.0",
...
```
Not allowed to load local resource: file:///C:/Users/**/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg

**Comment by Adaer** [comment] 2020-03-17 07:55
> #### Windows 7(64bit)
> #### Google Chrome 80.0.3987.132
> #### Microsoft Office Professional Plus 2013
> #### Classic editor5
> ```
> "@ckeditor/ckeditor5-editor-classic": "^17.0.0",
> "@ckeditor/ckeditor5-editor-decoupled": "^17.0.0",
> "@ckeditor/ckeditor5-editor-inline": "^17.0.0",
> "@ckeditor/ckeditor5-engine": "^17.0.0",
> "@ckeditor/ckeditor5-enter": "^17.0.0",
> "@ckeditor/ckeditor5-essentials": "^17.0.0",
> "@ckeditor/ckeditor5-font": "^17.0.0",
> ...
> ```
> 
> Not allowed to load local resource: 
file:///C:/Users/**/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg
--------------
@Mgsy Hi，

- Test link: https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html

- Test word: CKEditor5.PFO.Sample.Recognition_of_Achievement.docx.

#### Problem description:
When the Paste from Office content has a headline and image.
<h2 style="text-align:center;">
<span style="color:#4472C4;">Recognition of Achievement</span>
</h2>
```
error: Not allowed to load local resource: file:///C:/Users/**/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg
```
Not headline, will be pasted successfully!

**Comment by Adaer** [comment] 2020-03-17 08:42
When copying 'heading 1'  and image from word.
error: Not allowed to load local resource: 
file:///C:/Users/**/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg

**Comment by FilipTokarski** [comment] 2020-03-17 09:12
Hi @Adaer, thanks for this insight! 
I can reproduce this - when you copy whole content containing some image it throws the usual error:   `file:///C:/Users/**/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg`
But when you copy the whole content ( + image ) without the Word header, it pastes just fine.

**Comment by Reinmar** [comment] 2020-03-18 12:20
Out of curiosity – does it work well in CKEditor 4?

**Comment by Adaer** [comment] 2020-03-18 12:50
> Out of curiosity – does it work well in CKEditor 4?
Test link: https://ckeditor.com/ckeditor-4/demo/
Google Chrome  80.0.3987.132.
Paste test screenshot：
![img_error](https://user-images.githubusercontent.com/29849694/76962303-f57f7c00-6959-11ea-8513-796bee3084cd.png)
![img_normal](https://user-images.githubusercontent.com/29849694/76962310-f7e1d600-6959-11ea-9227-24967aee50d4.png)

**Comment by mlewand** [comment] 2020-08-12 07:19
I was able to reproduce this issue last week, but today I'm unable to reproduce the problem. Might be that the Chrome team fixed this overnight (`v84.0.4147.105` @ Win10).

@Adaer @tuannd255 @lasfin @fubar-coder can any of you confirm that the issue is no longer reproducible?

Repro steps:

1.  Open https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html
2.  Open [test.docx](https://github.com/ckeditor/ckeditor5-paste-from-office/files/3447389/test.docx) in MS Word.
3.  Copy all the content in Word (<kbd>ctrl</kbd>\+ <kbd>a</kbd> , <kbd>ctrl</kbd> + <kbd>c</kbd>).
4.  Paste into the editor.

Expected and current result: Image gets pasted.

Unexpected (can no longer repro): Console error like \`NI was able to reproduce this issue last week, but today I'm unable to reproduce the problem. Might be that the Chrome team fixed this overnight (`v84.0.4147.105` @ Win10).

@Adaer @tuannd255 @lasfin @fubar-coder can any of you confirm that the issue is no longer reproducible?

Repro steps:

1.  Open https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html
2.  Open [test.docx](https://github.com/ckeditor/ckeditor5-paste-from-office/files/3447389/test.docx) in MS Word.
3.  Copy all the content in Word (<kbd>ctrl</kbd>\+ <kbd>a</kbd> , <kbd>ctrl</kbd> + <kbd>c</kbd>).
4.  Paste into the editor.

Expected and current result: Image gets pasted.

Unexpected (can no longer reproduce): Console error like `Not allowed to load local resource: file:///C:/Users/****/AppData/Local/Temp/msohtmlclip/01/clip_image001.png`

**Comment by marcellofuschi** [comment] 2020-08-24 09:43
Bumped into a bug that may be related, described here: https://github.com/ckeditor/ckeditor5/issues/7915

Word version: 16.40
Browser: Chrome 84 on macOS (Catalina)
CKEditor version: 21.0.0
List of CKEditor plugins in use:
`SimpleUploadAdapter,
    Autoformat,
    BlockQuote,
    Bold,
    Essentials,
    Heading,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Italic,
    Link,
    List,
    MediaEmbed,
    Paragraph,
    PasteFromOffice,
    Strikethrough,
    Subscript,
    Superscript,
    TextTransformation,
    Underline,
    Code,`

**Comment by Mgsy** [comment] 2020-10-05 08:04
Some time ago, while testing this issue, I was not able to reproduce it. However, now I can reproduce it, e.g. in our all-features manual test with [this test file](https://github.com/ckeditor/ckeditor5/files/5137627/TextAndImgForPasteTest.docx). 

Note: I can't reproduce it in the default sample from our online builder (with the default set of plugins).

**Comment by fubar-coder** [comment] 2020-10-09 01:10
@mlewand I can still reproduce the bug, but I only tested it with the Word document I provided in this issue (initial comment).

**Comment by niegowski** [comment] 2020-12-22 12:04
> Test Word file:  
> [PasteFromWordTest.docx](https://github.com/ckeditor/ckeditor5-paste-from-office/files/2844717/PasteFromWordTest.docx)

In the case of copying the whole content (including styled headings), the `text/rtf` is not available in the `DataTransfer` object which is used for retrieving image data. Moreover, if the copied text does not include any images but includes any styles (for example Heading 1) the `text/rtf` is not available but this isn't an issue for the editor, because RTF is used only to access images from pasted content. OTOH if the copied document fragment does include an image but there are no styled elements (like heading 1) the `text/rtf` is available so an image is pasted properly. This is happening on macOS 10.14.6, Word for Mac 16.44. The same seems not to happen on Windows and Word 16.0 (2011). But this seems to be a case in some other configurations.

While checking other text editors I noticed that some of them just ignore the image in the content, and some are displaying a warning that some images failed to import. 

I guess the only solution would be to remove unhandled images from pasted content (so the editor won't throw an error while trying to access local file) and maybe display some notification.

> [test.docx](https://github.com/ckeditor/ckeditor5-paste-from-office/files/3447389/test.docx)

This is a different case. In this file there is no `<img>` element in pasted data, there is just `<v:shape><v:imagedata src="...."/></v:shape>` and this case is not implemented in the CKEditor 5. This seems to be handled in CKEditor 4: https://github.com/ckeditor/ckeditor4/blob/5380706bb4ceb6092dadb2b7067d6c14efec6b26/plugins/pastefromword/filter/default.js#L368

**Comment by Reinmar** [comment] 2020-12-22 16:52
I don't understand one thing. What does CKEditor 4 do differently that it handles one of the cases well? I mean this: https://github.com/ckeditor/ckeditor5/issues/2493#issuecomment-600604339

It'd be great if you could describe each case in terms of:

*   what happens and on which OSes?
*   did anyone solve it?
*   if so or if you see that it's solvable anyway – what do we have to do to also solve it? is it expensive?
*   if no one solved it and it really can't be solved, what can we do to ensure the best UX?

**Comment by niegowski** [comment] 2020-12-22 17:05
> I don't understand one thing. What does CKEditor 4 do differently that it handles one of the cases well? I mean this: [#2493 (comment)](https://github.com/ckeditor/ckeditor5/issues/2493#issuecomment-600604339)

It's handling that case in the exact same way as CKEditor 5 - notice that in that screenshots one paste includes "A Test" heading and the other does not.

> *   what happens and on which OSes?

I tested only on 2 computers (a different OS, a different version of Word), and on the other one it worked just ok.

> *   did anyone solve it?

I checked 3 editors and none of them solved it (image is ignored or warning notification appears as mentioned above).

> *   if so or if you see that it's solvable anyway – what do we have to do to also solve it? is it expensive?

I can't see any reasonable solution (I consider asking users to allow HD access would not be reasonable).

> *   if no one solved it and it really can't be solved, what can we do to ensure the best UX?

I think that displaying notification would be reasonable. And of course, the editor should not try accessing local files - that also should be fixed.

**Comment by oleq** [comment] 2021-03-15 12:51
Related #8934.

**Comment by quangvinh-gulang** [comment] 2021-07-27 16:57
here it is 
https://ckeditor.com/cke4/addon/imagesfromword

**Comment by Chainery** [comment] 2021-08-25 08:56
So this problem has not been solved yet, right?

**Comment by mabryl** [comment] 2023-03-08 10:54
Just retested this on macOS Ventura running Chrome and Windows 10 running Firefox and it looks like the issues are no longer reproducible - images are now pasted correctly into our [Paste from Word demo](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo).

I used the desktop Microsoft Word app on macOS and the Microsoft 365 web app on Windows to handle the original files.

**Closed** 2023-03-08 13:32 UTC
Labels: type:bug, package:paste-from-office, support:2, pending:feedback, squad:core, resolution:resolved
