### ISSUE TITLE
Commented Text overlaps other text at large font sizes

### ISSUE THREAD

**Issue by dil-darmstrong** [ckeditor/ckeditor5#10318] opened 2021-08-05 19:31 UTC
## 📝 Provide detailed reproduction steps (if any)

This is reproducible on the comment demo page:
1) Select a paragraph which contains text that has been commented.
2) Change it font size to "Huge"
3) Unselect the paragraph. You'll see that the yellow highlight over the commented text now overlaps the line above it, hiding part of the text. 

### ✔️ Expected result

Font changes do not impact readability of a paragraph.

### ❌ Actual result

Commented text has a yellow highlight that overlaps the line above it, blocking the lower part of the text.

## 📃 Other details

* Browser: Chrome
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-08-06 06:29
Hi, thanks for the report! I can confirm this bug.
Because this repo is dedicated for the open source part of the CKEditor project and Comments is a commercial plugin, I'll transfer the ticket to the proper repo and close this one.
Apart from that, if you're a licensed user and have any problems with the editor, please fell free to contact us via the dedicated [support channel](https://ckeditor.com/contact/) or directly to support@cksource.com. Our team will look into the issue and respond as soon as possible.

**Closed by FilipTokarski** 2021-08-06 06:29 UTC
Labels: type:bug
