### ISSUE TITLE
Not able to preserve table properties when copying 

### ISSUE THREAD

**Issue by cyril-rl** [ckeditor/ckeditor5#14800] opened 2023-08-16 11:47 UTC
I have a table in ckeditor which I would like to copy and paste in an email, however the table does not properly retain all of its properties 

Table in ckeditor: 
<img width="1298" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/138459926/799f7448-3763-40f1-a16e-1b97be063016">

Pasted table in email:
<img width="225" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/138459926/a64a5bc7-9ff6-4366-b0e5-4417356b07b4">

How do i retain the column width properly? 
Also how can i add a border when pasting? (even if the ckeditor table does not have a border)

Copying from `sheets.google.com` for example, retains the column width properly

**Comment by Witoso** [comment] 2023-08-17 13:37
Could you share info into which email client you paste the data?

**Comment by Witoso** [comment] 2023-08-18 10:49
> resizing the column width using the drag handler does not affect

This is something I cannot reproduce, I changed the [size of columns in the demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html), and it was reflected in Gmail.

![](https://github.com/ckeditor/ckeditor5/assets/9881379/bacd0819-e9d5-43e8-9c0a-5d4e9cdb4229)

> Ive tried setting the default border as solid 0.5px, this is reflecting when creating a new table, but when pasting it elsewhere it does not retain the styles. There seems to already be an issue for this #12808 

Pasting with border works for me as well:

![](https://github.com/ckeditor/ckeditor5/assets/9881379/368abaa2-d9c8-4224-bfa5-e6c6c5c2956e)

As the docs state, the CSS also needs to be configured the same way as the default configuration:

> [The table styles feature allows for configuring the default look of the tables in the editor. The configuration object **should be synchronized with the editor content styles**.](https://ckeditor.com/docs/ckeditor5/latest/features/tables/tables-styling.html#default-table-and-table-cell-styles)

**Comment by cyril-rl** [comment] 2023-08-18 11:14
https://github.com/ckeditor/ckeditor5/assets/138459926/2b6d3c7e-e533-43b2-a8f1-9fe8b348904a

**Comment by Witoso** [comment] 2023-08-21 11:28
Ok, found an issue that's related to this one #11988 (I will close this one as duplicate, please +1 the linked one).

The difference was in my selecting the whole table, not cells.

**Closed by Witoso** 2023-08-21 11:28 UTC
Labels: type:bug, pending:feedback
