### ISSUE TITLE
Report " The requested module '..../build/ckeditor.js' does not provide an export named 'default'" when in Vite3 vue3

### ISSUE THREAD

**Issue by sdlddr** [ckeditor/ckeditor5#12963] opened 2022-12-04 07:13 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Create a vite3 project for vue3.
2. Custom a CKEditor5 base on classic edition and download it.
3. Install the custom editon into the vite3 project , and use it like official demo.
```
// @ts-ignore
import ClassicEditor from 'ckeditor5-custom-build/build/ckeditor'
```
5. npm run dev.
6. In the F12 console window, we can see the error report like this issue's title.
7. But, when I use the normal classic edition from '`npm install @ckeditor/ckeditor5-build-classic`', there is no error. and the editor can be used well.

### ✔️ Expected result

resolve the problem.

### ❌ Actual result
The error report is followed:

```
vue-router.mjs:3451 
        
       SyntaxError: The requested module '/@fs/D:/WsProjects/weg-element-platform/ckeditor5/build/ckeditor.js' does not provide an export named 'default' (at RichEditor.vue:25:1)
```

### ❓ Possible solution

Vite can only support the package from 'import' but not from 'required'. Then we can improve CKEditor5 for Vite3 with supporting 'import' in those custom editions when build them online.

## 📃 Other details

* Browser: edge
* OS: win10
* First affected CKEditor5 version: 5-35.3.2
* Installed CKEditor5 plugins: custom base on Classic Editon

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by 269957022** [comment] 2022-12-08 10:19
+1+1+1+1

**Comment by ron26031893** [comment] 2022-12-15 13:54
normally, vite will transform the umd module into esm, but when you use the ckeditor-custom-build and add it into node_modules in your project, it seems vite ignored the umd code. (ckeditor-custom-build is an umd module). you can see the file requested through the network, and find out it sitll an umd module. 

based on that, i tried to tell vite to transform the ckeditor-custom-build into esm, and see what's coming.
i added this configuration in my vite.config.ts
```
optimizeDeps: {
  include: ['ckeditor5-custom-build/build/ckeditor'],
},
build: {
  commonjsOptions: {
    include: ['ckeditor5-custom-build/build/ckeditor'],
  },
},
```
and i relaunched my project
🎉 it worked!!!!

so, i think  it's not a bug.

Hope this can help you! 😃

**Comment by 269957022** [comment] 2022-12-16 01:19
🎉 🎉 🎉 🎉 🎉 🎉 
it worked!!!!

**Comment by ron26031893** [comment] 2022-12-16 08:51
> normally, vite will transform the umd module into esm, but when you use the ckeditor-custom-build and add it into node_modules in your project, it seems vite ignored the umd code. (ckeditor-custom-build is an umd module). you can see the file requested through the network, and find out it sitll an umd module.
> 
> based on that, i tried to tell vite to transform the ckeditor-custom-build into esm, and see what's coming. i added this configuration in my vite.config.ts
> 
> ```
> optimizeDeps: {
>   include: ['ckeditor5-custom-build/build/ckeditor'],
> },
> build: {
>   commonjsOptions: {
>     include: ['ckeditor5-custom-build/build/ckeditor'],
>   },
> },
> ```
> 
> and i relaunched my project 🎉 it worked!!!!
> 
> so, i think it's not a bug.
> 
> Hope this can help you! 😃

add more infomation to this answer, this method can solve the problem in dev mode, but when you build your project to production based on the config, you will get some error which you have no clue what caused it. 
So, i dig deeper, and find out `include:['ckeditor5-custom-build/build/ckeditor']` will override vite's defalut @rullup/plugin-commonjs config which is `include:[/node_modules/]`, and vite's transofromation process will only transform file `ckeditor5-custom-build/build/ckeditor` (if it's a directory, it will only transform the files in that directory). additionally, the `ckeditor5-custom-build/build/ckeditor` is also wrong , casue the `ckeditor5-custom-build` is a symlink in `node_modules`, you need use the real directory name to replace it.(if there is any wrong, pls correct me, thanks 😃 )

eg. my directory structure is
-project
--node_modules
--ckeditor5 //ckeditor5-custom-build contents is in this direcitory.
--src
so i replaced `ckeditor5-custom-build/build/ckeditor` with `ckeditor5`

**CONCLUSTION**, to solve the build problem, you need change the `include:['ckeditor5-custom-build/build/ckeditor']` to `include:[/node_modules/,'${real name of directory in which ckeditor-custom-build lives in}']`

Tip: yes, i changed the specific file to a directory, logically you specify either a file or a directory, don't limit yourself

**Comment by mabryl** [comment] 2022-12-23 12:54
Hi @sdlddr,

Thanks for reaching out. I can see that you're using Vite as your build environment and that's something that, until very recently, we didn't support - we used webpack for all our official integrations.

Having said that, as of Decemeber 22nd, we do have an experimental plugin that allows for building CKEditor 5 from source using Vite. You can lear more about it https://github.com/ckeditor/ckeditor5/issues/9807#issuecomment-1363284224.

I'll be closing this issue now and I encourage you to continue discussing the CKE5 + Vite integration in the linked thread.

If you're still facing issues with integrating our editor with Vite, feel free to open a new issue in the repo dedicated to the Vite plugin available [here](https://github.com/ckeditor/vite-plugin-ckeditor5).

**Closed by mabryl** 2022-12-23 12:54 UTC
Labels: type:bug

**Comment by sdlddr** [comment] 2022-12-27 02:06
Thank you l lot ! @mabryl @ron26031893

**Comment by delebash** [comment] 2023-10-10 18:13
See https://stackoverflow.com/questions/73180352/how-can-i-use-a-custom-build-of-ckeditor-5-with-react-and-vite

Update for vite 4.4.8:

"vite": "4.4.8",

vite.config.ts

```
import commonjs from "vite-plugin-commonjs";

export default defineConfig(() => {
  return {
    plugins: [
      react(),
      commonjs({
        filter(id) {
          if (["libs/ckeditor5/build/ckeditor.js"].includes(id)) {
            return true;
          }
        },
      }),
    ],
    optimizeDeps: {
      include: ["ckeditor5-custom-build"],
    },
    build: {
      commonjsOptions: { exclude: ["ckeditor5-custom-build"] },
    },
  };
```
});

**Comment by nguyentienanh59** [comment] 2024-06-04 13:47
> > normally, vite will transform the umd module into esm, but when you use the ckeditor-custom-build and add it into node_modules in your project, it seems vite ignored the umd code. (ckeditor-custom-build is an umd module). you can see the file requested through the network, and find out it sitll an umd module.
> > based on that, i tried to tell vite to transform the ckeditor-custom-build into esm, and see what's coming. i added this configuration in my vite.config.ts
> > ```
> > optimizeDeps: {
> >   include: ['ckeditor5-custom-build/build/ckeditor'],
> > },
> > build: {
> >   commonjsOptions: {
> >     include: ['ckeditor5-custom-build/build/ckeditor'],
> >   },
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and i relaunched my project 🎉 it worked!!!!
> > so, i think it's not a bug.
> > Hope this can help you! 😃
> 
> add more infomation to this answer, this method can solve the problem in dev mode, but when you build your project to production based on the config, you will get some error which you have no clue what caused it. So, i dig deeper, and find out `include:['ckeditor5-custom-build/build/ckeditor']` will override vite's defalut @rullup/plugin-commonjs config which is `include:[/node_modules/]`, and vite's transofromation process will only transform file `ckeditor5-custom-build/build/ckeditor` (if it's a directory, it will only transform the files in that directory). additionally, the `ckeditor5-custom-build/build/ckeditor` is also wrong , casue the `ckeditor5-custom-build` is a symlink in `node_modules`, you need use the real directory name to replace it. (it seems that esbuild can work with symlink, and @rollup/plugin-commonjs can't) (if there is any wrong, pls correct me, thanks 😃 )
> 
> eg. my directory structure is -project --node_modules --ckeditor5 //ckeditor5-custom-build contents is in this direcitory. --src so i replaced `ckeditor5-custom-build/build/ckeditor` with `ckeditor5`
> 
> **CONCLUSTION**, to solve the build problem, you need change the `include:['ckeditor5-custom-build/build/ckeditor']` to `include:[/node_modules/,/${real name of directory in which ckeditor-custom-build lives in}/]` (note that i use the RegExp to specify directory. if you want use string, you need use the absolute path of the target file, directory won't work)
> 
> Tip: yes, i changed the specific file to a directory, logically you specify either a file or a directory, don't limit yourself

@ron9726 are you here, i have the same problem. Can you help me check it?
