### ISSUE TITLE
[GHS] There was a problem initializing the editor. TypeError: target[key] is not iterable

### ISSUE THREAD

**Issue by shahzebgit** [ckeditor/ckeditor5#10951] opened 2021-12-04 07:11 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Enable GHS plugin with enabled all HTML features.
2.  Use this HTML data in editor(I'm using decoupled-document)
```html
<p><span id='1'><span class='wrapped manual-map' id='2'>hello</span></span></p>
```
3. it will throw error
4.  Use this HTML data
```html
<p><span class='wrapped manual-map' id='1'><span id='2'>hello</span></span></p>
```
5. It works.

### ✔️ Expected result

```html
<p><span id='1'><span class='wrapped manual-map' id='2'>hello</span></span></p>
```

### ❌ Actual result

![image](https://user-images.githubusercontent.com/51449693/144701088-36e246dc-1e2e-45e6-bb50-2f9453354e86.png)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome
* OS: Ubuntu 20.0.4 LTS
* First affected CKEditor version: v31.0.0
* Installed CKEditor plugins: 

<details>

<summary>Plugin config</summary>

```js
/**
 * @license Copyright (c) 2003-2021, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

// The editor creator to use.
import DecoupledEditorBase from '@ckeditor/ckeditor5-editor-decoupled/src/decouplededitor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import ListStyle from '@ckeditor/ckeditor5-list/src/liststyle';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting';
import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport';

export default class DecoupledEditor extends DecoupledEditorBase { }

// Plugins to include in the build.
DecoupledEditor.builtinPlugins = [
	Essentials,
	FontSize,
	FontFamily,
	FontColor,
	FontBackgroundColor,
	Autoformat,
	Bold,
	Italic,
	Strikethrough,
	Underline,
	Heading,
	Indent,
	IndentBlock,
	Link,
	List,
	ListStyle,
	Paragraph,
	PasteFromOffice,
	SourceEditing,
	GeneralHtmlSupport,
];

// Editor configuration.
DecoupledEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'sourceEditing',
			'fontfamily',
			'fontsize',
			'fontColor',
			'fontBackgroundColor',
			'|',
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'|',
			'numberedList',
			'bulletedList',
			'|',
			'undo',
			'redo'
		]
	},
	htmlSupport: {
		allow: [
			{
				name: /^(div|section|span)$/,
				attributes: true,
				classes: true,
				styles: true
			}
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'en'
};
```

</details>
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment] 2021-12-06 08:24
Hi, thanks for the report. This case looks like it's a duplicate of https://github.com/ckeditor/ckeditor5/issues/10657, closing.

**Closed by FilipTokarski** 2021-12-06 08:24 UTC
Labels: type:bug
