### ISSUE TITLE
beforeInput: adding text to the end of link is not working correctly

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#12574] opened 2022-10-05 11:24 UTC
Tested on:
- `ck/11438-beforeinput-ime-research-vol1.1-android`
- Nexus 10 emulator
- Moto g(9) play /w Android 11 - real device

## 📝 Provide detailed reproduction steps (if any)

1. Use GBoard Keyboard
2. Open all features manual test
3. Put caret at the end of the link that says "Quoted"
4. Type something

### ✔️ Expected result

Text is correctly typed in - compositions work as they should

### ❌ Actual result

The first character is placed outside of link, selection is placed before the character we just inserted. Following text is inserted inside the link.

If the text was typed in composition language: 
- the first character is not composed (still outside link), but the rest is as it should
- the first character also gets duplicated
- on attempt to delete the one character that was placed outside the link, it deletes one of the duplicated, but then puts it back

https://user-images.githubusercontent.com/66953380/194049301-13a5fd8c-c05a-4073-b5f2-f83e15dc26ea.mov

### 📃 Additional info 

The error doesn't occur if there is no content after the link in the same paragraph.
Occurs on both composition and non-composition languages, although slightly differently.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment] 2022-10-10 15:16
This looks like an additional text node is inserted by the IME (with the typed letter). The diff mechanism recognizes it as a not-needed node and removes it. Note that it's a text node next to an existing one, it should be a single text node.

![](https://user-images.githubusercontent.com/1232187/194896412-fc78245a-c26f-46af-893a-919d84e18f06.png)

**Comment by Acrophost** [comment] 2022-10-12 10:06
I can't reproduce it anymore. @dufipl please confirm and close the issue if that is your case as well :)

**Comment by dufipl** [comment] 2022-10-12 10:40
I can confirm that issue does not reproduce anymore on the `ck/11438-beforeinput-ime-research-vol1.1-android` branch, so I'm closing the issue.

**Closed by dufipl** 2022-10-12 10:40 UTC
Labels: type:bug, browser:android, domain:ime, squad:core, status:in-progress
