### ISSUE TITLE
[Firefox, Edge] Typing without spaces moves paragraph downwards after touching a side image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#462] opened 2017-06-07 14:33 UTC
## Steps to reproduce
1. Open a sample with an image.
2. Transform an image into a side image.
3. Put a caret at a paragraph on the left side of an image.
4. Press i.e. <kbd>t</kbd> and hold it until letters-chain touches a side image.

## Current result
Paragraph moves under an image.

## Notes
- Bug isn't reproducable when you type with spaces.
- Bug isn't reproducable if you insert different letter into a chain.

## GIF
![bug](https://user-images.githubusercontent.com/20988892/26883917-c69ca3f8-4b9e-11e7-9d43-6d22a501fef3.gif)

## Other information
OS: Windows 10
Browser: Firefox, Edge
Release: 0.10.0

**Comment by Reinmar** [comment] 2017-06-07 14:37
This is how browsers render text by default. I guess that breaking of such long "words" can be controlled by some CSS. If so, then perhaps we could change it by default for the editor content.

I would normally close this ticket as "the developer can change it themselves", but I remember similar reports from the past. Apparently, it's what the developers expect and they don't know that it's up to them so maybe we could change it on our side.

WDYT, @oleq?

**Comment by Reinmar** [comment] 2017-06-12 12:33
A slightly different case was reported in https://github.com/ckeditor/ckeditor5/issues/470.

**Comment by oleq** [comment] 2017-06-12 12:50
I couldn't reproduce the issue:
![image](https://user-images.githubusercontent.com/1099479/27034323-77995840-4f7d-11e7-9ea7-9001e383a1b9.png)

But even if I could, it's hardly a bug (unless you type in German in a very narrow window). More like an edge case. 

Most certainly this is how web browsers render things in `contenteditable` and there isn't much we can do about it (some [`word-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap), maybe?), especially that according to the report it works cross–browser and cross–platform in the same way. 

We'll get back to this issue when we clear all issues in all bug trackers we have ;-)

**Comment by fredck** [comment] 2017-06-13 16:24
I tried this at the [developer preview](https://ckeditor5.github.io/) and the line gets broken as well. But well, somehow @Mgsy reproduced it, so maybe he can give us more details.

But the thing that really called me attention is that the "press and hold" thing didn't work for me. Just one letter is typed.

**Comment by oleq** [comment] 2017-06-13 16:29
> But the thing that really called me attention is that the "press and hold" thing didn't work for me. Just one letter is typed.

[Welcome to MacOS Sierra](https://apple.stackexchange.com/questions/258513/delete-key-repeat-on-macos-sierra-10-12-0-broken), @fredck ;-)

**Comment by fredck** [comment] 2017-06-13 16:47
> Welcome to MacOS Sierra, @fredck ;-)

:D Thanks for the tip, @oleq :D

It's such a useful feature, that I didn't notice it earlier :D

**Comment by Mgsy** [comment] 2017-06-14 07:46
@fredck, @oleq - I checked this issue one more time and to my suprise I couldn't reproduce it on Chrome, Safari and Opera. I'm sure when I was writing this issue it was possible :D 

All in all, this issue still occur on Firefox and Edge (I'd be grateful if you could confirm it). I'm going to edit this ticket.

**Comment by oskarwrobel** [comment] 2017-06-19 10:32
On FF horizontal scrollbar appears:

![jun-19-2017 12-28-10](https://user-images.githubusercontent.com/1057056/27281200-221acf8e-54eb-11e7-96df-4a55db1f3c0f.gif)

and here is a fix from @dkonopka

![jun-19-2017 12-30-41](https://user-images.githubusercontent.com/1057056/27281242-55b0f60c-54eb-11e7-907d-f96b733ad488.gif)

**Comment by oleq** [comment] 2017-06-19 10:35
I guess we could use the fix in [`reset.scss`](https://github.com/ckeditor/ckeditor5-theme-lark/blob/master/theme/components/reset.scss).

**Comment by Reinmar** [comment] 2017-06-22 10:33
Adding to iteration 11 as it's a quick win.

**Closed** 2017-07-25 17:21 UTC
Labels: module:theme-*, status:confirmed, type:bug
