### ISSUE TITLE
The caret isn't visible at the end of the highlighted link

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#897] opened 2018-03-14 09:23 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Select some `Heading 1` element.
2. Add a link.
3. Put the caret at the end of the link.

## ✅ Expected result
The caret is visible.

## ❎ Actual result
The caret isn't visible.

## 📃 Other details that might be useful
**Notes**

It doesn't occur in Edge.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/37393461-71e18306-2771-11e8-8978-0bcb8e5aa683.gif)

OS: All platforms
Browser: Chrome, Firefox, Safari

**Comment by Reinmar** [comment] 2018-03-14 09:30
I encountered this as well, but it's a bit random. Sometimes it works, sometimes it doesn't.

Do I remember correctly that we had a similar issue in Letters (comments/selection markers)? cc @dkonopka @oskarwrobel

**Comment by FilipTokarski** [comment] 2020-01-03 12:49
Cannot reproduce it anywhere, I guess we can close this.

**Closed** 2020-01-03 12:59 UTC
Labels: package:link, status:confirmed, type:bug
