### ISSUE TITLE
Cannot delete all the content selected, when image is the end of document

### ISSUE THREAD

**Issue by Donny2333** [ckeditor/ckeditor5#993] opened 2018-04-24 00:35 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKEditor Version: 5
Plugins: 
		'@ckeditor/ckeditor5-essentials/src/essentials',
		'@ckeditor/ckeditor5-alignment/src/alignment',
		'@ckeditor/ckeditor5-font/src/fontsize',
		'@ckeditor/ckeditor5-font/src/fontfamily',
		'@ckeditor/ckeditor5-highlight/src/highlight',
		'@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter',
		'@ckeditor/ckeditor5-autoformat/src/autoformat',
		'@ckeditor/ckeditor5-basic-styles/src/bold',
		'@ckeditor/ckeditor5-basic-styles/src/italic',
		'@ckeditor/ckeditor5-basic-styles/src/strikethrough',
		'@ckeditor/ckeditor5-basic-styles/src/underline',
		'@ckeditor/ckeditor5-block-quote/src/blockquote',
		'@ckeditor/ckeditor5-easy-image/src/easyimage',
		'@ckeditor/ckeditor5-heading/src/heading',
		'@ckeditor/ckeditor5-image/src/image',
		'@ckeditor/ckeditor5-image/src/imagecaption',
		'@ckeditor/ckeditor5-image/src/imagestyle',
		'@ckeditor/ckeditor5-image/src/imagetoolbar',
		'@ckeditor/ckeditor5-image/src/imageupload',
		'@ckeditor/ckeditor5-link/src/link',
		'@ckeditor/ckeditor5-list/src/list',
		'@ckeditor/ckeditor5-paragraph/src/paragraph',

## 📋 Steps to reproduce

1. Import image **at the end of document**
2. Press Command + A to select all docuement
3. Press Delete to remove all the things

## ✅ Expected result
Everything is going to delete

## ❎ Actual result
Nothing happend

## 📃 Other details that might be useful
Cannot copy all the document too, when pressing Command + C

**Comment by Mgsy** [comment] 2018-04-24 07:13
It's a duplicate of https://github.com/ckeditor/ckeditor5-widget/issues/25.

**Closed by Mgsy** 2018-04-24 07:13 UTC
