### ISSUE TITLE
[CI] Verify why BrowserStack times out all the time

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1778] opened 2019-05-28 10:32 UTC
About 50% of jobs end with BrowserStack time outing. Not sure if the problem is on BS's or Travis's side or an integration between Karma and BS. We need to figure this out because it makes our CI useless.

![image](https://user-images.githubusercontent.com/156149/58471597-89baf100-8144-11e9-99b4-f2e96ceecc4c.png)

![image](https://user-images.githubusercontent.com/156149/58472126-d3f0a200-8145-11e9-9ce7-f1542547fde0.png)

![image](https://user-images.githubusercontent.com/156149/58472143-e10d9100-8145-11e9-9c74-40f6d950d589.png)

```
28 05 2019 10:38:21.586:WARN [Safari 12.0.0 (Mac OS X 10.14.0)]: Disconnected (0 times)reconnect failed before timeout of 2000ms (ping timeout)
Safari 12.0.0 (Mac OS X 10.14.0) ERROR
  Disconnectedreconnect failed before timeout of 2000ms (ping timeout)
Safari 12.0.0 (Mac OS X 10.14.0): Executed 89 of 136 DISCONNECTED (39.483 secs / 4.376 secs)
28 05 2019 10:38:21.588:ERROR [reporter.browserlabs]: ✖ Test Disconnected
28 05 2019 10:38:21.595:WARN [Edge 17.17134.0 (Windows 10.0.0)]: Disconnected (0 times)reconnect failed before timeout of 2000ms (ping timeout)
Edge 17.17134.0 (Windows 10.0.0) ERROR
  Disconnectedreconnect failed before timeout of 2000ms (ping timeout)
Edge 17.17134.0 (Windows 10.0.0): Executed 54 of 136 DISCONNECTED (37.973 secs / 3.518 secs)
28 05 2019 10:38:21.597:ERROR [reporter.browserlabs]: ✖ Test Disconnected
Error: Karma finished with "1" code.
```

```
Firefox 67.0.0 (Linux 0.0.0): Executed 740 of 740 SUCCESS (11.985 secs / 1.416 secs)
28 05 2019 10:35:03.441:WARN [launcher.browserstack]: safari (OS X Mojave) has not captured in 60000 ms, killing.
28 05 2019 10:35:05.947:WARN [launcher.browserstack]: edge 17.0 (Windows 10) has not captured in 60000 ms, killing.
28 05 2019 10:35:12.259:INFO [launcher.browserstack]: edge 17.0 (Windows 10) session at https://automate.browserstack.com/builds/50bb1296aaa5a16b5572b691a0578d2e4fbad046/sessions/849b410c19e2b71c10f549a0a7b98c681fe033f3
28 05 2019 10:35:13.460:INFO [launcher.browserstack]: safari (OS X Mojave) session at https://automate.browserstack.com/builds/50bb1296aaa5a16b5572b691a0578d2e4fbad046/sessions/de30968e8efbddc3c88dbe09c7c29e1636387d7c
28 05 2019 10:36:15.935:WARN [launcher.browserstack]: safari (OS X Mojave) has not captured in 60000 ms, killing.
28 05 2019 10:36:17.352:WARN [launcher.browserstack]: edge 17.0 (Windows 10) has not captured in 60000 ms, killing.
28 05 2019 10:36:22.794:INFO [launcher.browserstack]: edge 17.0 (Windows 10) session at https://automate.browserstack.com/builds/50bb1296aaa5a16b5572b691a0578d2e4fbad046/sessions/f9e33bec3d32a32924c8a83eb1ceb3d89db5c136
28 05 2019 10:36:30.553:INFO [launcher.browserstack]: safari (OS X Mojave) session at https://automate.browserstack.com/builds/50bb1296aaa5a16b5572b691a0578d2e4fbad046/sessions/d54c053208ea4e72d0327ef4c57522ee4d52f4f4
28 05 2019 10:37:28.012:WARN [launcher.browserstack]: edge 17.0 (Windows 10) has not captured in 60000 ms, killing.
28 05 2019 10:37:34.703:INFO [launcher.browserstack]: edge 17.0 (Windows 10) session at https://automate.browserstack.com/builds/50bb1296aaa5a16b5572b691a0578d2e4fbad046/sessions/a77313017b5158b2e93cf27051f36fe5e45787d6
28 05 2019 10:37:40.386:WARN [launcher.browserstack]: safari (OS X Mojave) has not captured in 60000 ms, killing.
28 05 2019 10:37:51.948:INFO [launcher.browserstack]: safari (OS X Mojave) session at https://automate.browserstack.com/builds/50bb1296aaa5a16b5572b691a0578d2e4fbad046/sessions/0543736aae2684d19a951e18fdb64594a03d457c
28 05 2019 10:38:54.358:WARN [launcher.browserstack]: edge 17.0 (Windows 10) has not captured in 60000 ms, killing.
28 05 2019 10:38:54.360:WARN [launcher.browserstack]: safari (OS X Mojave) has not captured in 60000 ms, killing.
Error: Karma finished with "1" code.
```

**Comment by pomek** [comment] 2019-05-28 10:49
https://github.com/ckeditor/ckeditor5/issues/1742

**Comment by mlewand** [comment] 2019-05-28 10:54
It's a duplicate of #1742, not the other way around.

**Closed** 2019-05-28 14:04 UTC
Labels: must-have, resolution:duplicate, status:confirmed, type:task
