### ISSUE TITLE
In Safari on iOS 12.2 iPhone, content does not scroll and becomes obscured at the bottom.

### ISSUE THREAD

**Issue by Yermo** [ckeditor/ckeditor5#1756] opened 2019-05-12 21:52 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

## 📋 Steps to reproduce

1. on IOS 12.2 Safari on an iPhone tap at the bottom of the content in the classic-editor.html example linked above.
2. hit return
3. note that the content does not scroll so now the cursor and whatever you type is obscured by the keyboard.

## ✅ Expected result
The content should scroll so I can see what I'm typing.

## ❎ Actual result
The content does not scroll so I cannot see what I am typing.

**Comment by Yermo** [comment] 2019-05-12 22:08
Implementing this hack: https://stackoverflow.com/questions/46559354/how-to-set-the-height-of-ckeditor-5-classic-editor 

and setting an explicit height to the editable area seems to work around this issue.

**Comment by Mgsy** [comment] 2019-05-13 07:27
This is a duplicate of https://github.com/ckeditor/ckeditor5/issues/1321.

**Closed by Mgsy** 2019-05-13 07:27 UTC
