### ISSUE TITLE
Text alternative balloon disappears after clicking on it

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#490] opened 2017-07-03 07:46 UTC
## Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-presets/tests/manual/article.html
2. Select the image.
3. Choose `Change image text alternative` from the contextual toolbar.
4. Click somewhere on the balloon (except the input).

## Current result
The balloon closes immediately. 

## Notes
It's a twin of https://github.com/ckeditor/ckeditor5-link/issues/126

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27782689-cd0aff02-5fd3-11e7-8dc8-61c3c459d8df.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Edge, Opera
Release: 0.10.0

**Comment by Reinmar** [comment] 2017-08-15 12:45
I can reproduce this issue.

**Comment by oleq** [comment] 2017-08-24 09:18
This [line](https://github.com/ckeditor/ckeditor5-image/blob/master/src/imagetextalternative.js#L130-L134) is the source of the problem.

Things to check:
* Why this listener has been created in the first place? I couldn't find anything similar in the Link feature.
* Why doesn't it work anyway? `ContextualBalloon` registers its `#view` in `editor.ui.focusTracker`, so clicking it shouldn't make `editor.ui.focusTracker#isFocused` `false`.

**Comment by oleq** [comment] 2017-08-24 09:23
It looks like the solution from https://github.com/ckeditor/ckeditor5-link/commit/866fa49be261bbcb2fa93ca6675cff92d6214469 (https://github.com/ckeditor/ckeditor5-link/issues/90) helps here. It does not answer the questions, though.

**Comment by oskarwrobel** [comment] 2017-09-04 11:16
> Why doesn't it work anyway? ContextualBalloon registers its #view in editor.ui.focusTracker, so clicking it shouldn't make editor.ui.focusTracker#isFocused false.

It doesn't work because `ContextualBalloon#view` (`BalloonPanelView`) is not focusable anymore (doesn't have tabindex="-1") https://github.com/ckeditor/ckeditor5-ui/issues/206.

**Comment by oskarwrobel** [comment] 2017-09-04 11:18
Link balloon works like it should even after removing these hacks from the BPV:

https://github.com/ckeditor/ckeditor5-ui/blob/a21b0976641db4a6d45592b4369e22adece2b930/src/panel/balloon/balloonpanelview.js#L135-L141

**Comment by Reinmar** [comment] 2017-09-05 14:51
Is it fixed now?

**Comment by oskarwrobel** [comment] 2017-09-05 14:54
Nope, ImageBalloon has to be improved. It should be focusable and use FocusCycler.

**Closed** 2017-09-20 14:33 UTC
Labels: candidate:1.0.0, module:image, module:ui, status:confirmed, type:bug
