### ISSUE TITLE
Crash in downcast conversion when moving selection between table cells

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7899] opened 2020-08-21 11:18 UTC
## 📝 Provide detailed reproduction steps (if any)

Check out the screencast. I'm attaching everything I did starting from the moment I reloaded the webpage (this may be yet another bugfoot).

Note: I came across this issue when trying to reproduce [another one](https://github.com/ckeditor/ckeditor5/issues/7897) (hence all the noise).

I was testing the Document Editor sample (http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/examples/builds/document-editor.html)

![](https://user-images.githubusercontent.com/1099479/90884739-9a423180-e3b0-11ea-9b9b-6252deb45349.gif)

```
ckeditorerror.js:70 Uncaught TypeError: element.getCustomProperty(...) is not a function
    at DowncastDispatcher.eval (downcasthelpers.js:1342)
    at DowncastDispatcher.fire (emittermixin.js:218)
    at DowncastDispatcher.convertMarkerRemove (downcastdispatcher.js:391)
    at DowncastDispatcher.convertChanges (downcastdispatcher.js:136)
    at eval (editingcontroller.js:104)
    at View.change (view.js:502)
    at Document.EditingController.listenTo.priority (editingcontroller.js:103)
    at Document.fire (emittermixin.js:218)
    at Document._handleChangeBlock (document.js:331)
    at Model._runPendingChanges (model.js:854)
CKEditorError @ ckeditorerror.js:70
rethrowUnexpectedError @ ckeditorerror.js:122
fire @ emittermixin.js:253
convertMarkerRemove @ downcastdispatcher.js:391
convertChanges @ downcastdispatcher.js:136
eval @ editingcontroller.js:104
change @ view.js:502
EditingController.listenTo.priority @ editingcontroller.js:103
fire @ emittermixin.js:218
_handleChangeBlock @ document.js:331
_runPendingChanges @ model.js:854
change @ model.js:196
_hideFakeVisualSelection @ linkui.js:690
_removeFormView @ linkui.js:395
_hideUI @ linkui.js:464
callback @ linkui.js:303
eval @ clickoutsidehandler.js:45
fire @ emittermixin.js:218
domListener @ emittermixin.js:253
```

## 📃 Other details

*   Browser: Chrome
*   OS: Mac
*   CKEditor version: master

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment] 2020-08-24 07:52
Duplicate of #7907

**Closed by mlewand** 2020-08-24 07:52 UTC
Labels: package:link, package:table, type:bug
