### ISSUE TITLE
[Chrome] Dropdown content looks blurry on LoDPI screen

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#2059] opened 2019-09-18 15:15 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

master on **Chrome**.

Firefox and Safari are not affected.

## 📋 Steps to reproduce

Open any dropdown in the table toolbar or the alignment dropdown.

## ✅ Expected result

Content is sharp.

## ❎ Actual result

Content is blurry.

![image](https://user-images.githubusercontent.com/1099479/65161271-9044df80-da37-11e9-828a-ec665fed78d2.png)

![image](https://user-images.githubusercontent.com/1099479/65161283-9470fd00-da37-11e9-9196-4557fdcbf36a.png)

## 📃 Other details that might be useful

AFAIR we fixed something like this in the past. Do you remember what was it, @dkonopka?

**Comment by dkonopka** [comment] 2019-09-19 07:31
@oleq it's related to the height of dropdown, try to round this value to e.g. `122px` (alignment case) or `154px` (table toolbar) and it looks sharp. 

Can we round dropdowns height to avoid this issue?

**Comment by mlewand** [comment] 2019-09-19 09:11
Since this is chrome-specific, isn't it by the way upstream bug? Would be nice to track the upstream issue too since this is a recurring issue.

**Comment by mlewand** [comment] 2019-10-24 14:03
Let's track it in a single ticket, marking as a duplicate of #1053.

**Closed by mlewand** 2019-10-24 14:03 UTC
Labels: package:ui, pending:browser-bug, status:confirmed, type:bug
