### ISSUE TITLE
how can i let all the toolbar items display whatever the screen size is？

### ISSUE THREAD

**Issue by xwillmadeit** [ckeditor/ckeditor5#5694] opened 2019-10-31 06:55 UTC
## Provide a description of the task

Hello there.

I don't want to take an extra step to click the dropdown button to expand the hide items when the screen size is small, i want all the toolbar items display whatever the screen size is.  Are there any config that i can do to let it flow like normal？

![企业微信截图_15725046679249](https://user-images.githubusercontent.com/8340253/67925439-564a2a00-fbee-11e9-8224-282eab7b1ab6.png)

**Comment by Mgsy** [comment] 2019-11-04 12:13
Hi! We're aware of this case and we've decided to work on it in the current iteration. I'll close this report as a duplicate of https://github.com/ckeditor/ckeditor5/issues/5692.

**Closed by Mgsy** 2019-11-04 12:13 UTC
Labels: type:task
