### ISSUE TITLE
How to arrange text side by side in Export to Word?

### ISSUE THREAD

**Issue by amoltupe** [ckeditor/ckeditor5#9845] opened 2021-06-10 07:37 UTC
In Export to Word, I want to arrange content side by side, Just like float in CSS as seen in below image.
How can I achieve this functionality here? Content will be dynamic here.
![image](https://user-images.githubusercontent.com/13763588/121466187-9d0c2280-c9d4-11eb-8b7a-3d44da71b2f1.png)

But it should be same in same line. What I could do is in below image.
![image](https://user-images.githubusercontent.com/13763588/121484330-be790880-c9ec-11eb-805b-90c234a18f0a.png)

**Comment by jswiderski** [comment] 2021-06-15 14:10
The only way to do this is either by entering 2-column table or text inside it (which you can align) or better prepare a widget which allows column layout. For a simple PoC of such a widget, please have a look at [https://github.com/ckeditor/ckeditor5/issues/7515#issuecomment-651603651.](https://github.com/ckeditor/ckeditor5/issues/7515#issuecomment-651603651.)

I'm closing this one as duplicate of #7515

**Closed by jswiderski** 2021-06-15 14:10 UTC
Labels: type:bug
