### ISSUE TITLE
Fix the links to the collab guides so they don't crash the CI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5855] opened 2019-11-28 08:37 UTC
```
Error: Failed while convert {@link features/collaboration collaboration plugins} tag in ckeditor5/15.0.0/builds/guides/frameworks/angular.md.
Error: Failed while convert {@link features/collaboration collaboration plugins} tag in ckeditor5/15.0.0/builds/guides/frameworks/react.md.
```

**Comment by Reinmar** [comment] 2019-11-28 08:38
I guess we already have some links to the collab features somewhere, so it's just a matter of finding them and figuring out how they are written.

**Comment by mlewand** [comment] 2019-11-28 08:38
Duplicate of #5853

**Closed by mlewand** 2019-11-28 08:38 UTC
Labels: type:docs
