### ISSUE TITLE
To-do list returns incorrect markdown output

### ISSUE THREAD

**Issue by milojennings** [ckeditor/ckeditor5#5970] opened 2019-12-13 00:28 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Build ckeditor with markdown support (`ckeditor5-markdown-gfm`) and list support (`ckeditor5-list`)
2. Create a checkbox list using the markdown syntax `* [ ] checkbox list item` 

### ✔️ Expected result

The output should be the same markdown syntax: 
```
* [ ] checkbox list item
```

### ❌ Actual result

Instead of markdown, it outputs HTML:
```html
* <label class="todo-list__label">
    <input type="checkbox" disabled="disabled">
    <span class="todo-list__label__description">checkbox list item</span>
</label>
```

## 📃 Other details

I put together a Codepen example here: [https://codepen.io/rsmm/pen/09735e4abf0d204206ceca97aa2e5c28](https://codepen.io/rsmm/pen/09735e4abf0d204206ceca97aa2e5c28)

And [this is the ckeditor.js source file](https://s3-us-west-2.amazonaws.com/s.cdpn.io/88150/ckeditor-source.js) used in the Codepen example above.

* Browser: Chrome 78.0.3904.108
* OS: Mac OS 10.13.6 
* CKEditor version: 16.0.0
* Installed CKEditor plugins: ckeditor5-markdown-gfm and ckeditor5-list

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2019-12-13 11:43
Hi! Thanks for the report. I can confirm this issue.

**Comment by jodator** [comment] 2020-08-18 07:26
Looks like it fixed on the latest master.

**Closed by jodator** 2020-08-18 07:26 UTC
Labels: package:list, package:markdown-gfm, type:bug

**Comment by jodator** [comment] 2020-08-18 07:27
Related PR #7307.
