### ISSUE TITLE
[iOS] Predictive text suggestion doesn't update properly

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10887] opened 2021-11-23 14:07 UTC
## 📝 Provide detailed reproduction steps (if any)

1.  Enable the [predictive text option](https://support.apple.com/en-gb/guide/iphone/iphd4ea90231/ios).
2.  Type something.
3.  Delete it.
4.  Type something else.

### ✔️ Expected result

The text from step 4 is visible in the predictive text suggestion.

### ❌ Actual result

The text from step 2 is merged with the text from step 4 in the predictive text suggestion.

## 📃 Other details

**After step 2**

![](https://user-images.githubusercontent.com/20988892/143038669-11653440-735f-4df1-a8be-11ebfd4f1583.jpg)

**After step 4**

![](https://user-images.githubusercontent.com/20988892/143038703-2adb1c9f-3e19-42d9-a8bd-e0555cd899c4.jpg)

Tested on iPhone (iOS 15) and iPad (iOS 12).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment] 2022-12-12 13:24
@ckeditor/qa-team could you retest this?

**Comment by dufipl** [comment] 2022-12-13 06:55
@Reinmar I can't reproduce it on the latest version of the editor in online docs (here: https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) whereas I was able to do so on docs for v.30.0.0, so the issue is fixed now:

https://user-images.githubusercontent.com/32898551/207247136-5c067413-4277-41e4-b2d5-23fa43364529.MP4

**Comment by uaza** [comment] 2023-02-06 10:47
Can you already foresee when this bugfix will be included in the next release? I and our customers would be very happy about it.

**Comment by Witoso** [comment] 2024-06-27 15:18
This is no longer reproducible in the latest documentation (v42.0.0) and iOS 17.5.1.

**Closed by Witoso** 2024-06-27 15:18 UTC
Labels: type:bug, browser:ios, support:3, squad:core
