### ISSUE TITLE
Add support for translating Special characters categories

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12630] opened 2022-10-11 11:55 UTC
## 📝 Provide a description of the improvement

Currently, it's impossible to add a translation for a special characters group (https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-special-characters/src/ui/specialcharactersnavigationview.js#L120). It would be nice to add such a possibility.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment] 2022-12-28 10:18
Duplicate of #5820

**Closed by mlewand** 2022-12-28 10:18 UTC
Labels: type:improvement, support:2, package:special-characters, domain:i18n
