### ISSUE TITLE
CK classic editor || Image upload 

### ISSUE THREAD

**Issue by ThenmozhiD** [ckeditor/ckeditor5#6616] opened 2020-04-16 09:12 UTC
## 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2020-04-16 09:24
Hi, please don't open multiple issues for one problem and remember to describe your case in details. I'll close it as a duplicate of https://github.com/ckeditor/ckeditor5/issues/6617.

**Closed by Mgsy** 2020-04-16 09:24 UTC
Labels: type:bug
