### ISSUE TITLE
BalloonPanelView  Out of editor range

### ISSUE THREAD

**Issue by chenyx1934** [ckeditor/ckeditor5#12864] opened 2022-11-17 09:00 UTC
![image](https://user-images.githubusercontent.com/12790656/202401510-a49fb029-1ad2-4d42-bf9e-790843181762.png)

**expect：Hide when out of editor range**

**Comment by mabryl** [comment] 2022-11-28 09:16
Hi @chenyx1934,  
  
Thank you for your report. We're aware of this issue and are tracking it in [this thread](https://github.com/ckeditor/ckeditor5/issues/5328). Feel free to join the discussion there. I'll close your ticket since it's a duplicate of the linked issue.

**Comment by chenyx1934** [comment] 2022-11-28 09:16
来信已收到。

**Closed by mabryl** 2022-11-28 09:16 UTC
Labels: resolution:duplicate, type:feature

**Comment by shenyi-dra** [comment] 2023-06-08 02:50
Anything new about this issue? Seems this issue comes from 2017... but still open, is there any information about this? Hope it can be resolved asap.

**Comment by chenyx1934** [comment] 2023-06-08 02:50
来信已收到。

**Comment by Witoso** [comment] 2023-06-09 07:18
@shenyi-dra the issue will be most probably researched by us pretty soon in #5328. Thanks for your message!

**Comment by shenyi-dra** [comment] 2023-06-12 07:24
@Witoso 
ok, great, i thought that one is not updated anymore.
I will keep following issue #5328
