### ISSUE TITLE
Top/Left borders of Table's cell are not shown

### ISSUE THREAD

**Issue by votuanphong1983** [ckeditor/ckeditor5#15559] opened 2023-12-19 08:08 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Go to the demo page of CKEditor  https://ckeditor.com/docs/ckeditor5/latest/features/tables/tables.html#demo
2. Create a 4x4 table
3. Select random cell and select "Cell properties".
Set border for this cell `1px solid black` as the below
![image](https://github.com/ckeditor/ckeditor5/assets/10540791/0ffb1d44-d382-4df0-aecd-c2a60e0b8822)

### ✔️ Expected result

 All the borders are shown correctly

### ❌ Actual result

The top and left border are not shown as the below image
![image](https://github.com/ckeditor/ckeditor5/assets/10540791/56855db2-a1d1-4c03-b782-fc177c8c6089)

### ❓ Possible solution

N/A

**Comment by Witoso** [comment] 2023-12-20 08:32
Duplicate of #12713. Works with 2px.

**Closed by Witoso** 2023-12-20 08:32 UTC
Labels: type:bug
