### ISSUE TITLE
Wrong default bulleted list style applied (circle instead of disc)

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#12983] opened 2022-12-07 10:39 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Open [full-featured editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) v. 35.2.0 or newer.
2. Place the caret in the text and click `bulleted list` button.

### ✔️ Expected result

The default (disc) list style is applied.

### ❌ Actual result

The circle list style is applied.
However in the dropdown, the correct (disc) style is selected.

https://user-images.githubusercontent.com/95343030/206156911-21ce1a01-2b2e-4b95-adb9-3047865894b8.mov

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: 35.2.0
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment] 2022-12-07 11:09
As far as I can see, it is reproducing only on the Full-featured example. @mmotyczynska do you confirm? If so, I think we can assume that this is a docs issue instead of a bug and assign this to the CCX team 🤔

**Comment by mmotyczynska** [comment] 2022-12-07 11:12
Unfortunately not. It can be reproduced also in other examples and in manual tests.

**Comment by dufipl** [comment] 2022-12-07 11:19
That's weird 🤔 I can actually confirm that on the Full-featured example it's not working starting from 35.2.0, but it's working normally on every other example I've tested. In the Full-featured example, it is reproducible in the online docs, so maybe someone from the @ckeditor/qa-team could take a look if they can reproduce it on other demos?

**Comment by dufipl** [comment] 2022-12-07 11:28
Okay, after @FilipTokarski checking that also we've agreed that it reproduces probably only on demos using document lists. 
It does not reproduce e.g. here: https://ckeditor.com/docs/ckeditor5/35.2.0/examples/builds/classic-editor.html
@mmotyczynska do we agree on that? 
If so, it's not the docs issue then, but it is also not touching all the lists.

**Comment by mmotyczynska** [comment] 2022-12-07 11:28
Maybe this will also help:  
I can reproduce it e.g. in online docs here https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html.   
And also on release branch in the manual test http://localhost:8125/ckeditor5-list/tests/manual/list-style.html.

**Comment by mmotyczynska** [comment] 2022-12-07 11:30
> It does not reproduce e.g. here: https://ckeditor.com/docs/ckeditor5/35.2.0/examples/builds/classic-editor.html  
> @mmotyczynska do we agree on that?

Yes. In classic editor it works fine.

**Comment by dufipl** [comment] 2022-12-07 11:34
And I confirm that it reproduces here: https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html 
but not here e.g. https://ckeditor.com/docs/ckeditor5/latest/features/lists/todo-lists.html
🤔

**Comment by oleq** [comment] 2023-01-03 12:48
I'm closing this issue as a duplicate of #13206 even though the latter is newer. Mostly because I've already broken down the problem and proposed a solution there and moving it here feels like work 😜

**Closed by oleq** 2023-01-03 12:48 UTC
Labels: type:bug, package:list, type:regression
