### ISSUE TITLE
Keyboard focus not moving inside Special Characters and Table Popups

### ISSUE THREAD

**Issue by RoopanV** [ckeditor/ckeditor5#12126] opened 2022-07-22 08:10 UTC
If we expand the Special Characters and Table dropdown the focus is not moving to the popup. We can't able to select or navigate through symbols popup. And there is a null pointer exception in console as below:

Uncaught TypeError: this.children.first.focus is not a function
    at mh.focus (snippet.js:4:334301)
    at snippet.js:4:347481
    at _listener.listenTo.priority (snippet.js:4:136496)
    at Object.fire (snippet.js:4:2958)
    at ur.<anonymous> (snippet.js:4:136364)
    at ur.fire (snippet.js:4:2958)
    at HTMLDivElement.t (snippet.js:4:115973)

You can reproduce the behavior in this page : [https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)

Use Alt + F10. (To move focus to toolbar) Use Arrow keys (Left) to move to Symbols tool. And hit Enter or Arrow Down to open the popup. Ideally the first element inside the popup should be opened and we can navigate inside through Arrow Keys. But it is not happening. Instead focus is still on toolbar level.

![image](https://user-images.githubusercontent.com/30289851/180394692-a8920004-c278-4add-8d5d-cf2673719a37.png)

**Comment by FilipTokarski** [comment] 2022-07-22 08:34
Thank you for the report. It's a duplicate of https://github.com/ckeditor/ckeditor5/issues/10423.

**Closed by FilipTokarski** 2022-07-22 08:34 UTC
Labels: type:bug
