### ISSUE TITLE
After inserting the link it continues typing inside

### ISSUE THREAD

**Issue by dovydaskukalis** [ckeditor/ckeditor5#5860] opened 2019-11-28 10:44 UTC
## 📝 Provide detailed reproduction steps (if any)

1. Go to any editor which has links plugin enabled (https://ckeditor.com/ckeditor-5/demo/)
2. Paste any link or click insert link in a toolbar and insert from there
3. If you pasted the link, try to type. If you inserted the link, place cursor at the end and try to type.

### ✔️ Expected result

Types text outside of link (<a>)

### ❌ Actual result

Types text inside link and unable to move out of it.

## 📃 Other details

All the browsers I tested are affected.

---

**Comment by jodator** [comment] 2019-11-28 11:14
Hi @dovydaskukalis, did you see our demo about [typing around links in CKEditor5](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#typing-around-links)? Does this helps, if not tell us why?

**Comment by dovydaskukalis** [comment] 2019-11-28 13:02
@jodator Oh, that actually makes sense but once we added CKEditor to our app we started getting reports like the issue I created and I actually thought it's a bug. Maybe on paste/insert link it should get out of edit link mode automatically? Because for example if you add a link at the edge, even clicking outside of it doesn't quite the edit mode so unless you press arrow key, you are stuck.

**Comment by Mgsy** [comment] 2020-02-04 08:07
We've created a ticket for this case, so let's make it a duplicate of https://github.com/ckeditor/ckeditor5/issues/6053.

**Closed by Mgsy** 2020-02-04 08:07 UTC
Labels: pending:feedback, type:bug
