### ISSUE TITLE
There is a possibility to nest tables, what should not happen

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor5#1691] opened 2019-04-08 13:19 UTC
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Open classic example
2. Make content and selection as on a screen below
3. Copy and paste it to the table cell
![Screen Shot 2019-04-08 at 15 10 23](https://user-images.githubusercontent.com/9017322/55726993-5051e900-5a11-11e9-95bc-36ea70101cff.png)
![Screen Shot 2019-04-08 at 15 16 29](https://user-images.githubusercontent.com/9017322/55727009-55af3380-5a11-11e9-8479-ea33fa887e9c.png)

## ✅ Expected result

A table is not pasted inside a table.

## ❎ Actual result

A table is paste as a part of a blockquote.

**Comment by jodator** [comment] 2019-04-08 13:32
The `ClipboardObserver` uses `model.insertContent()` which does not check if whole input chain is allowed.

The check is: `blockQuote` inside tree: `["$root", "blockQuote", "table", "tableRow", "tableCell"]` which passes. The check we need is tricky as it should check whole tree in tree which AFAIR current schema does not support. /cc @Reinmar

**Comment by Reinmar** [comment] 2019-04-08 19:41
This can and should be prohibited by checking whether there's any `tableCell` in `Schema#checkChild`'s context. Whenever you'll be checking if `table` is allowed, we'll check that somewhere up the ancestors tree there's another `tableCell`, so it will be disabled.

That, however won't totally prevent from creating such structures. Plugins like typing and functions like deleteContent don't check the schema too extensively so by doing some block level operations you may be able to end up with a table being merged into a block quote :D But this is a known issue to be resolved one day.

**Comment by msamsel** [comment] 2019-05-17 07:40
@Reinmar can you give more information what you have on your mind with:
> This can and should be prohibited by checking whether there's any `tableCell` in `Schema#checkChild`'s context. Whenever you'll be checking if `table` is allowed, we'll check that somewhere up the ancestors tree there's another `tableCell`, so it will be disabled.

I'm not sure if  you mean that fix should be applied to `Schema#checkChild` to check entire tree, or just applied exclusively for `tables` to patch this specific case.

--- 

I've made small research and I agree with @jodator as it's quite tricky issue.
`Schema#checkChild` simplifies checked element and only analyze **most outer** element if this element can be placed in current context or not.
So when we have `blockQuote` which contains `table`, then during `Schema#checkChild` is only verified where `blockQuote` is allowed. Childs of `blockQuote` are omitted during this process.

So generally this approach allows on pasting/inserting any element anywhere as long as forbidden element is wrapped with allowed one. In this case `table` wrapped with `blockQuote` can be placed inside another `table`.

block which converts input argument:
https://github.com/ckeditor/ckeditor5-engine/blob/e0de1586620918f08854962e3ee323122c4e2059/src/model/schema.js#L57-L60

and place where node with childs is translate to name of most outer block (omitting all childs)
https://github.com/ckeditor/ckeditor5-engine/blob/e0de1586620918f08854962e3ee323122c4e2059/src/model/schema.js#L170-L184

**Comment by Reinmar** [comment] 2019-05-21 13:06
I talked with @msamsel and we found the root of the issue. I assumed that it's only about the schema not being configured correctly, but it's a bigger problem. This issue is caused by the conversion on paste happening in a virtual context (`$clipboardHolder`) instead of happening in a more realistic place (table -> blockquote).

The conversion itself has a builtin filtering mechanism. It uses schema to figure out whether certain view element can be converted to a certain model element.

We could repeat the same login inside `Model#insertContent()` but it'd be a duplication. Plus, it wouldn't be extensible there.

Therefore, I'd prefer if we made the clipboard feature use the current selection position as the context. Which, is a bigger task so I'd ignore this thing now. Until we add schema rules disallowing `table > * > table`, the content that you'll create will load fine. It will change once we add the schema rule disallowing that because then you'll be able to create such content (clipboard issue), but loading it back to the editor will not work.

**Comment by mlewand** [comment] 2021-10-01 09:03
We added support for nested tables (and an option to disable this behavior) back in 27.1.0.

See [https://ckeditor.com/blog/ckeditor-5-v27.1.0-with-table-and-block-quote-nesting/](https://ckeditor.com/blog/ckeditor-5-v27.1.0-with-table-and-block-quote-nesting/) for more.

**Closed by mlewand** 2021-10-01 09:03 UTC
Labels: type:bug
