### ISSUE TITLE
Editor crashes after pasting the content multiple times

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1579] opened 2019-02-26 12:28 UTC
Originally reported here - https://github.com/ckeditor/ckeditor5/issues/1578#issuecomment-467381058

## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

Latest master

## Steps to reproduce
1. Open the article sample.
1. Copy the whole content.
1. Put the caret at the end of the `UL List item 2`.
1. Hold <kbd>Ctrl/Cmd</kbd> + <kbd>V</kbd> (editor should hang for a while).
1. Keep pressing <kbd>Ctrl/Cmd</kbd> + <kbd>V</kbd> repeatetly (it should be quick).

## ✅ Expected result
There's no error.

## ❎ Actual result
The editor crashes.

## 📃 Other details that might be useful
**Error**
```
remove.js:16 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at remove (remove.js:16)
    at Renderer._updateChildren (renderer.js:557)
    at Renderer.render (renderer.js:203)
    at View._render (view.js:673)
    at View.on (view.js:182)
    at View.fire (emittermixin.js:204)
    at View.change (view.js:475)
    at View._disableRendering (view.js:660)
    at Model.EditingController.listenTo (editingcontroller.js:82)
    at Model.fire (emittermixin.js:204)
```

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/53404441-fee82000-39b5-11e9-9955-fc9434bc393c.gif)

**Comment by jodator** [comment] 2019-02-26 12:33
This is what happens there: https://github.com/ckeditor/ckeditor5/issues/1578#issuecomment-467396516.

It seems that fastDiff gives different output then diff (because it is fast) but on the other hand it also gives incorrect ones (too big IMO).

**Comment by Reinmar** [comment] 2019-02-26 14:59
> It seems that fastDiff gives different output then diff (because it is fast) but on the other hand it also gives incorrect ones (too big IMO).

Different is kinda obvious – it's meant to be different. But the question is – is it incorrect? Or perhaps it's renderer's fault because maybe it cannot handle `fastDiff()` valid output correctly?

**Comment by Reinmar** [comment] 2019-02-26 15:27
I encountered a simbling of this error. Just like in #1578, here you can get two stacktraces as well. I think they are caused by the same bug.

The way how I was able to reproduce this is by pasting the content of this GH page to the editor and applying/removing list to part of that content. In general, applying lists is a pretty complex case, so it worked well in reproducing this.

![image](https://user-images.githubusercontent.com/156149/53424241-273a4380-39e3-11e9-8d01-a0cc9fa0a476.png)

**Comment by jodator** [comment] 2019-02-26 15:59
@Reinmar I'm still trying to figure out what exactly happens. So some findings here.

The renderer does couple of things:

1. Updates nodes mappings (uses diff)
2. Updates children of marked children (uses diff)
3. Updates texts

Let's say someone pastes "cylic" content (same structure to similar structure):

Starting HTML:
```html
<h1>h1</h1>
<ul><li>[]foo</li></ul>
<blockquote><p>p</p></blockQuote>
```
the content is pasted before `foo`:

```html
<h1>h1</h1>
<h1>h1</h1>
<ul><li>foo</li></ul>
<blockquote><p>p</p></blockQuote>
<ul><li>[]foo</li></ul>
<blockquote><p>p</p></blockQuote>
```
the curious for me is what happens with mappings because the (1) update mappings will detect that `ul` is similar to `ul`, will update mappings and then will look that texts are the same (if they are different then it will replace them) so the content before and after a paste is the same in the editor but the differ in step (2) will output changes:

```
// Before mappings (1):
equal.insert.insert.insert.insert.delete.equal

// After mappings (2):
equal.insert.equal.insert.insert.equal
```

but the `fastDiff()` will output:

```
fastDiff():
// Before mappings (1):
equal.insert.insert.insert.insert.insert.delete

// After mappings (2):
equal.insert.insert.insert.insert.insert.delete
```

It looks like that after changing mappings of dome nodes the method that updates view (DOM) children acts differently on those inputs because `diff()` always matches actual nodes while `fastDiff()` only simulates output based on changed indexes in children arrays.

**Comment by Reinmar** [comment] 2019-03-18 10:45
Another TC: https://github.com/ckeditor/ckeditor5-engine/issues/1685

**Comment by Reinmar** [comment] 2020-01-21 10:44
It seems that it's related to couple other issues that we've seen. Closing for now as DUP of [https://github.com/ckeditor/ckeditor5/issues/6092](https://github.com/ckeditor/ckeditor5/issues/6092).

**Closed by Reinmar** 2020-01-21 10:44 UTC
Labels: status:confirmed, support:2, type:bug
