### ISSUE TITLE
Generated html with embed tag doesn't workout outside of CKeditor.

### ISSUE THREAD

**Issue by cbarraford** [ckeditor/ckeditor5#1695] opened 2019-04-10 09:58 UTC
## Is this a bug report or feature request? (choose one)
🐞 Bug report

## 💻 Version of CKEditor
@ckeditor/ckeditor5-build-classic@^12.0.0
@ckeditor/ckeditor5-react@^1.1.1

## 📋 Steps to reproduce

1. Embed a video, and run `getData()` to get the raw html generated by CKEditor. Should look something like.... 
```
<figure class='media'>
  <oembed url='https://www.youtube.com/watch?v=xQW1fEwYZVA'></oembed>
</figure>
```
2. Write that into a blank HTML document. For clarity, we're taking the generated html from ckeditor and pasting it into a plan html doc (no editor imported/etc).

## ✅ Expected result
See an embedded youtube video
## ❎ Actual result
see blank screen (no video)

## 📃 Other details that might be useful
Is there a recommended way to display the generated html of CKeditor in a browser WITHOUT the editing capabilities/etc (i tried setting readOnly = true, removing the toolbars, and setting disabled=true, but there still some weirdness that makes people think they can edit (ie the yellow square in the top left hand corder of a table).

**Comment by Mgsy** [comment] 2019-04-10 11:02
Hello, it's a duplicate of https://github.com/ckeditor/ckeditor5-engine/issues/1695.

Please take a look at our [media embed documentation](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#including-previews-in-data). You'll find there information about displaying media on your website.

If you want the plugin to produce non-semantic output, just set this [config option](https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembed-MediaEmbedConfig.html#member-previewsInData) to `true`.

**Closed by Mgsy** 2019-04-10 11:02 UTC

**Comment by cbarraford** [comment] 2019-04-10 13:05
@Mgsy thanks so much for your quick response, got my issue straightened out. thanks again.
