### ISSUE TITLE
Merging of table cells when tables are pasted one inside the other

### ISSUE THREAD

**Issue by sbelms** [ckeditor/ckeditor5#15777] opened 2024-01-30 08:20 UTC
## 📝 Ask a question

Can we paste two tables one nested inside the other without the cells merging?

For instance if we have a table as follows-

<img width="962" alt="Screenshot 2024-01-30 at 1 45 28 PM" src="https://github.com/ckeditor/ckeditor5/assets/64519478/b98e452d-83b9-40d3-9add-bb0ea10472c8">

If we paste a different table into the cell of the second column, the tables merge instead of nesting and the second column data is fully lost.

<img width="1045" alt="Screenshot 2024-01-30 at 1 47 06 PM" src="https://github.com/ckeditor/ckeditor5/assets/64519478/1ca09c78-eb4e-48ba-84e8-8d5ec1198384">

**Comment by Witoso** [comment] 2024-01-31 11:10
Duplicate of #9420, more information there.

**Closed by Witoso** 2024-01-31 11:10 UTC
Labels: type:question
