### ISSUE TITLE
Text element inside the svg is not supported in ckeditor 5

### ISSUE THREAD

**Issue by lingamwin** [ckeditor/ckeditor5#6206] opened 2020-02-07 04:01 UTC
I am trying to rendering dynamic svg element into the ckeditor 5. Refer this [https://github.com/ckeditor/ckeditor5/issues/6155]

Its working with simple svg, But If svg having text element getting below error

core.js?f18e:6014 ERROR TypeError: Cannot read property 'charAt' of undefined
at DomConverter._processDataFromViewText (domconverter.js?c3df:954)
at DomConverter.viewToDom (domconverter.js?c3df:199)
at DomConverter.viewChildrenToDom (domconverter.js?c3df:272)
at viewChildrenToDom.next ()
at DomConverter.viewToDom (domconverter.js?c3df:244)
at XmlDataProcessor.toData (xmldataprocessor.js?3ed2:77)
at UpcastDispatcher.eval (highchart.ts?70a9:186)
at UpcastDispatcher.fire (emittermixin.js?da0d:209)
at UpcastDispatcher._convertItem (upcastdispatcher.js?51fb:239)
at UpcastDispatcher.convert (upcastdispatcher.js?51fb:198)

I think library using the 'text' keyword. How to solve this?

**Comment by ma2ciek** [comment] 2020-02-07 08:25
I see that it's a duplicate of this issue actually. Let's not split the discussion.

**Closed by ma2ciek** 2020-02-07 08:25 UTC
Labels: type:bug
