### ISSUE TITLE
Bug with using css framework bootstrap with insert media

### ISSUE THREAD

**Issue by b01110011** [ckeditor/ckeditor5#1480] opened 2019-01-23 12:42 UTC
Css Framework Bootstrap using class .media and change display's parameter to flex, so insert media has height value equal 0 and becomes invisible.
https://dropmefiles.com/YN8mA
https://dropmefiles.com/CfPJG

**Comment by oleq** [comment] 2019-01-28 11:01
Thanks for being alert! It's a duplicate of https://github.com/ckeditor/ckeditor5/issues/1373. The issue has been addressed and the patch will land in the upcoming release.

**Closed by oleq** 2019-01-28 11:01 UTC
