### ISSUE TITLE
Decide what should be included in zip packages with CKEditor builds

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#541] opened 2017-09-04 08:34 UTC
I'm having some doubts what will be included in zip packages:

For sure generic things such as:
 - `LICENSE.md`
 - `README.md` (something simple, ideally generic for all builds, with a link to the documentation website)
 - `CHANGES.md`

In case of `CHANGES.md` I assume that it will list also all the changes done to related features, not changes to the build itself. A side note: will the changelog contain just changes for features included in that build and skip features that are not included in that build?

The most trouble some part: what with the editor itself? Should the package contain just the bare minimum to run the build? 

 - `build/ckeditor.js`
 - `build/ckeditor.js.map`
 - `sample/index.html`

Imho zip packages should not contain too much stuff. The should be designed for people that just want to include `ckeditor.js` on their page and run the editor. Anyone looking to customize the build, editor etc. should use other forms of distributions.

Note: the same structure as for zip files will be used in CDN.

**Comment by wwalc** [comment] 2017-09-04 14:15
Note: the reason why I'd love to reduce the number of files in zip packages is trying to not repeating mistakes from the past where the default setup contained too many files and resulted in lots of questions about what can be removed on production (which ended up with a dedicated article: http://docs.cksource.com/CKEditor_3.x/Developers_Guide/Minimum_Setup).

**Comment by fredck** [comment] 2017-09-05 09:49
As a starting point, I like your proposal, @wwalc. I would even remove `CHANGES.md`, making it a link inside `README.md`.

Also, we want to make it easy for one to change the build for their own needs. That's the reason why the source `ckeditor.js` (which is small), `package.json` and `build-config.js` are proposed to be included in the build.

Summed up, that's my proposal:

 * `README.md`: the generic description so one can figure out what to do next and where to search for help.
 * `/ckeditor.js`: source entry point, for bundling and re-building (?).
 * `/package.json`: includes all dependencies needed for the builder.
 * `/build-config.js`: the build configuration file, which can be easily manipulated.
 * `/build/ckeditor.js`: bundled, production version. Can be easily re-built.
 * `/build/ckeditor.js.map`: for errors debugging.
 * `/samples/*`: some samples just to check the build. Usually just one sample, but maybe we could have more than one for a specific build.

The missing point may be multi-language localization support. How is this handled @Reinmar?

**Comment by Reinmar** [comment] 2017-09-05 10:08
> Also, we want to make it easy for one to change the build for their own needs.

👍 

So, it seems that we need exactly the same content as published on npm (which is cool cause there will be less to maintain). However, this means that you missed the `bin/` directory in your list.

**Comment by wwalc** [comment] 2017-09-05 10:22
Don't you think that having `ckeditor.js` in a root folder of a zip package with an editor that is not "production ready", and the "real one, minified and working out of the box" hidden in the build folder is a correct solution for an average user interested in using the library "as is" to not get confused?

What I meant in this ticket is that we might be doing the same as we did in CKEditor 3, distributing CKEditor "source" via channel which is not dedicated to that.

IMO if someone wants to work with source files e.g. to bundle CKEditor by himself, he should use npm or GitHub (ideally, at this point one should also be mentioned articles about customising builds, setting up CKEditor dev environment, to understand precisely first which way to go). The point is that such person will be able to understand how to access the source version easily by reading the readme and will not require these extra files in zip files anyway.

The opposite, people which have little to do with JavaScript, may get lost with too many options and/or may use the wrong version of CKEditor.

**Comment by Reinmar** [comment] 2017-09-05 10:47
> IMO if someone wants to work with source files e.g. to bundle CKEditor by himself, he should use npm or GitHub (ideally, at this point one should also be mentioned articles about customising builds, setting up CKEditor dev environment, to understand precisely first which way to go).

Good points.

Since, on CDN we won't have all these files (`bin/`, `build-config.js`, etc.), then maybe ZIP package should follow closely?

**Comment by fredck** [comment] 2017-09-05 10:50
> So, it seems that we need exactly the same content as published on npm

Yes, that was the initial idea and I think we should stick to that, so we'll have one way to do things.

> What I meant in this ticket is that we might be doing the same as we did in CKEditor 3, distributing CKEditor "source" via channel which is not dedicated to that.

Note that this is not the CKEditor source, but just the "unbundled" entry point file for the build, which is pretty small. This means that, one could point directly to this file as well and bundle CKEditor inside their app bundle. This may definitely be wanted by those practicing modern development.

> The opposite, people which have little to do with JavaScript, may get lost with too many options and/or may use the wrong version of CKEditor.

Information about this would be in `README.md`, documentation, sample... added by the fact that we `build` folder will be there. We can't do much if one will decide to ignore all that.

@Reinmar... there is little chance that the root ckeditor.js will work directly in the browser, right? Are we able to make it smart enough so it shows a better error if one decides to go with it?

**Comment by fredck** [comment] 2017-09-05 10:52
> Since, on CDN we won't have all these files (bin/, build-config.js, etc.), then maybe ZIP package should follow closely?

The different with the CDN is that it is not customizable and that it is not made for working in a local dev environment, for producing bundles for example.

**Comment by Reinmar** [comment] 2017-09-05 10:58
> @Reinmar... there is little chance that the root ckeditor.js will work directly in the browser, right? Are we able to make it smart enough so it shows a better error if one decides to go with it?

It's not going to work at all (source is nowhere near being available). And I don't think there's an option to make it throw nicely, but I'll check.

**Comment by wwalc** [comment] 2017-09-05 10:58
> This means that, one could point directly to this file as well and bundle CKEditor inside their app bundle. This may definitely be wanted by those practicing modern development.

That's my point, isn't it that if you practice modern development, you don't download a zip file, but prefer npm/git instead?

**Comment by wwalc** [comment] 2017-09-05 11:29
> I would even remove CHANGES.md, making it a link inside README.md.

There must be a very easy way for end users to understand what exactly version of editor they are running, we ask it all the time when someone reports an issue via support channel. Will there be any other way to do that?

**Comment by Reinmar** [comment] 2017-09-05 12:08
> @Reinmar... there is little chance that the root ckeditor.js will work directly in the browser, right? Are we able to make it smart enough so it shows a better error if one decides to go with it?

We get a syntax error caused by `import` statement. And there's no way to do anything before or after that – code simply isn't executed due to the syntax error.

**Comment by fredck** [comment] 2017-09-05 13:18
> That's my point, isn't it that if you practice modern development, you don't download a zip file, but prefer npm/git instead?

That's a difficult thing to say, as well. It may depend a lot on the practices in place in specific projects. We're simply talking about different ways to download the code and I assume zip is in any case common. Meanwhile, script bundling is a pretty common practice.

But most importantly, we're also talking about builds which will not be available in GH, npm or whichever other remote location. Think about custom builds. They'll work exactly like the ones we distribute. They'll have the very same directory structure. They'll have the same documentation.

Therefore, I'll be more focused on what's inside and not how we distribute them.

**Comment by fredck** [comment] 2017-09-05 13:19
> There must be a very easy way for end users to understand what exactly version of editor they are running, we ask it all the time when someone reports an issue via support channel. Will there be any other way to do that?

What about having it at the very top of `README.md`? It makes even more sense.

**Comment by fredck** [comment] 2017-09-05 13:30
> We get a syntax error caused by import statement. And there's no way to do anything before or after that – code simply isn't executed due to the syntax error.

Well... there is.... `eval()`... hahahaha. 

No. There is not.

So we can not make it masochist-dummy-proof, but there should be in any case enough resources to point people to the right direction.

In fact, I remember we raised this problem when we talked originally, @Reinmar, and we mutually agreed that this would be the best approach.

In the other hand, I remember that we also talked about a different option that we dismissed, having the entry-point file with a different name or inside a folder, while `build` stuff would be in the root. I think it just sounded counterintuitive when you're working to customize the build.

**Comment by wwalc** [comment] 2017-09-05 13:55
> That's a difficult thing to say, as well. It may depend a lot on the practices in place in specific projects. We're simply talking about different ways to download the code and I assume zip is in any case common. Meanwhile, script bundling is a pretty common practice.

My point is that when I download a zip with an application, I don't want the whole "code". I just want the library that will work OOTB and to be reasonably intuitive to setup. But I guess that's already clear from my previous comments.

> But most importantly, we're also talking about builds which will not be available in GH, npm or whichever other remote location. Think about custom builds. They'll work exactly like the ones we distribute. They'll have the very same directory structure. They'll have the same documentation.
> 
> Therefore, I'll be more focused on what's inside and not how we distribute them.

Okay, last comment then, really :) I just see other "add-on" libraries like for example Underscore, Lodash or Prism.js, which are included in many modern projects and when you download them from their site, they don't come with lots of extra stuff like package.json, tools to build them from source etc. You just get the minified build. Absolutely simple. Maybe I checked too little libraries. Hence my doubts about the way we plan to go. I just got used to the fact that when I download a library from a website it comes minified and with a minimum set of files. And when I want to do more with it, I always have the documentation and/or GitHub repo. 

Regarding bundling itself - I don't deny it. Yes, it's a common practice, even if at the same time people do not bundle large libraries many times, because it may kill caching benefits. The whole point is not about the fact if people will bundle CKEditor or not, it's about the initial impression we will make on less-advanced backend developers that try to use the library and fail during their very first attempt to use it.

**Comment by Reinmar** [comment] 2017-09-05 13:59
> In fact, I remember we raised this problem when we talked originally, @Reinmar, and we mutually agreed that this would be the best approach.
> 
> In the other hand, I remember that we also talked about a different option that we dismissed, having the entry-point file with a different name or inside a folder, while build stuff would be in the root. I think it just sounded counterintuitive when you're working to customize the build.

TBH, I don't recall what we came up with. I only remember that we saw this as an issue to have `ckeditor.js` in the root.

One option could be to have `src/` directory like we have in the other repositories. There would be:

```
/
    ckeditor.js
    ckeditor.js.map
    src/
        ckeditor.js
        build-config.js ?
        webpack-config.js ?
        bin/ ?
```

Then, it would be quite consistent with the package repos where `src/` contains the source. But I'm not sure where the stuff needed to build all that could land.

**Comment by wwalc** [comment] 2017-09-05 14:00
It can be even `/src/` and `/build/`, that will be still way better than having "wrong" ckeditor.js in zip distribution in the root folder.

**Comment by Reinmar** [comment] 2017-09-05 14:24
I think that I agree with @wwalc on the fact that ZIPs are mostly for guys who're not used to npm. And the fewer files the easier it will be for them to not get lost.

BTW, it realised one thing – we have to also rethink how build dependencies are defined. Right now, they are split into deps and devdeps like this:

```js
  "dependencies": {
    "@ckeditor/ckeditor5-editor-balloon-toolbar": "^0.1.0",
    "@ckeditor/ckeditor5-presets": "^0.3.0",
    "@ckeditor/ckeditor5-autoformat": "^0.6.0",
    "@ckeditor/ckeditor5-basic-styles": "^0.9.0",
    "@ckeditor/ckeditor5-block-quote": "^0.2.0",
    "@ckeditor/ckeditor5-heading": "^0.10.0",
    "@ckeditor/ckeditor5-image": "^0.7.0",
    "@ckeditor/ckeditor5-link": "^0.8.0",
    "@ckeditor/ckeditor5-list": "^0.7.0",
    "@ckeditor/ckeditor5-paragraph": "^0.9.0"
  },
  "devDependencies": {
    "@ckeditor/ckeditor5-dev-utils": "^3.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^2.0.11",
    "babel-minify-webpack-plugin": "^0.2.0",
    "css-loader": "^0.28.5",
    "node-sass": "^4.5.3",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "webpack": "^3.5.5"
  },
```

But it makes no sense. It means that when installing this package through npm, you'll also get `ckeditor5-*` packages which makes no sense because it's all slower then but you still can't rebuild it without additional work.

So, deps should be empty. But this means that npm package is not useful for rebuilding unless there's an option to install a package with its dev deps somehow. There's `npm i --dev` but I'm not sure how useful it'd be anyway.

This means that the easiest way to customize a build is by cloning the repo.

Now, if this situation looks like this – npm doesn't allow rebuilding, GH does – how does it affect what ZIP download should allow?

**Comment by fredck** [comment] 2017-09-05 14:40
> TBH, I don't recall what we came up with. I only remember that we saw this as an issue to have ckeditor.js in the root.

The funny fact is that it was you, @Reinmar, that convinced me that we needed this entry-point file at the root. I got so well convinced that I'm the only one now defending this approach here :D 

> I think that I agree with @wwalc on the fact that ZIPs are mostly for guys who're not used to npm.

When it comes to customization, npm is not the right answer, most probably. Mainly because it pushes everything inside node_modules, which is a mystical blackhole. People will not work on customizing things there. So I never talk about npm, but mostly about GH.

So let's think about npm and zip as distribution channels for build bundles and forget about the customization thing here, leaving it exclusive to GH.

But wait, we still need to provide the CommonJS version, for bundling. So maybe we can leave it exclusive on npm, as a dedicated package.

So, whenever a release happens:

 * The "source" version is pushed to GH, which allows for customization. This is the one used to created custom builds (clone + build).
 * The "bundled" version is pushed to npm. The same code ends up in the zip.
 * The "CommonJS" version is pushed to npm.

The "bundled" version contains:

```
README.md
ckeditor.js
ckeditor.js.map
```

The "CommonJS" version contains:

```
README.md
ckeditor.js
package.json
```

How it looks like?

**Comment by fredck** [comment] 2017-09-05 14:43
Actually, `package.json` is in any case needed in the "bundled" version, so I've edited the above comment.

**Comment by Reinmar** [comment] 2017-09-05 15:10
> The funny fact is that it was you, @Reinmar, that convinced me that we needed this entry-point file at the root. I got so well convinced that I'm the only one now defending this approach here :D

Fortunately, I have a bad memory (as I don't remember what I said at all :D) and we can rethink this seeing it clearer now :P

> But wait, we still need to provide the CommonJS version, for bundling.

I'm not sure about this.

It seems that we provide everything that's needed.

The `ckeditor.js` (source) is an ES6 module which is fully supported by Webpack and Rollup. And I guess by all other modern bundlers. I can't think of a case which would require something else. 

So, until we don't have a case in our case, I'd not do anything.

Also because releasing a fully CommonJS build means releasing *ALL* the source files. Not just `ckeditor.js`. And it won't be fully compatible anyway due to the way we import SVGs.

So it just doesn't seem to be needed nor possible.

**Comment by Reinmar** [comment] 2017-09-05 15:39
> So let's think about npm and zip as distribution channels for build bundles and forget about the customization thing here, leaving it exclusive to GH.

So, to sum up.

### npm, zip and CDN

Those channels will only need to contain the following files:

```js
ckeditor.js
ckeditor.js.map
README.md
LICENSE.md
```

The README should contain:

* a version number,
* links to docs,
* info that if you want to customize this, go to docs.

Question:

* no sample?

### GitHub

Will contain all files which we have already, but differently located. We yet need to decide whether we go with:

* `build/` and `src/`,
*  or just `src/` (where the build is in the root).

The README, in this case, will differ from the one used on npm, zip and CDN versions. The one that we have now is mostly ok, yes?

**Comment by fredck** [comment] 2017-09-05 15:40
> I can't think of a case which would require something else.

The only case that comes to my mind is that one wants to bundle the editor "directly" without having to build the editor first. It's just a matter of changing the entry-point file, the npm dependencies and you're ready to bundle the editor inside your application with more or less plugins included.

Actually, there is also the theoretical case where you have more than one build to be bundled in your app and so modules that are common on both builds will not be bundled twice.

Again... you're the one that convinced about all this in the past... but if you're not convinced anymore, then who am I to argue?! We can drop the idea of the dedicated CommonJS package then.

**Comment by fredck** [comment] 2017-09-05 15:42
> no sample?

I don't think we need a sample. Go to docs, as you said ;)

> or just src/ (where the build is in the root).

I would go exactly like we have now... `src` on root and `build/`.



> The README, in this case, will differ from the one used on npm, zip and CDN versions.

Yes.

**Comment by wwalc** [comment] 2017-09-05 15:43
I'm so happy seeing how this discussion evolves :)

> Question:
> 
> no sample?

I would not argue here much, however due to the fact that each editor (build) has a different class, a sample with which one may start playing with may further reduce the risk of confusion.

**Comment by fredck** [comment] 2017-09-05 15:43
> The missing point may be multi-language localization support. How is this handled @Reinmar?

@Reinmar ?

**Comment by Reinmar** [comment] 2017-09-05 15:46
> I would not argue here much, however due to the fact that each editor (build) has a different class, a sample with which one may start playing with may further reduce the risk of confusion.

We've talked with Wiktor about a problem caused by the names of the builds. Basically, each build export a different global variable ;| `ClassicEditor`, `InlineEditor`, `BalloonToolbarEditor`. I actually think that we either need this name to be included in the README (of npm, zip and CDN) or a sample. The first option may be better. 

Also, which is an off-topic, these names conflict with names of editor constructors ;|||| Basically, we use the same names for two different things and I don't like this. Neither will users... Do we want a separate ticket for that?

**Comment by Reinmar** [comment] 2017-09-05 15:48
> The missing point may be multi-language localization support. How is this handled @Reinmar?

This is not handled at all, yet. You can change the language and rebuild. But we're not able to generate multiple language files at the moment. We tried to write such a Webpack plugin but it was really tricky, so it was postponed after alpha :(.

**Comment by wwalc** [comment] 2017-09-05 15:51
> I actually think that we either need this name to be included in the README (of npm, zip and CDN) or a sample. The first option may be better.

I was also thinking about reusing README but then thought that it would include a code snippet which one has to copy, add the rest of HTML markup and save as HTML to try out the downloaded editor.

**Comment by Reinmar** [comment] 2017-09-05 15:51
> I would go exactly like we have now... src on root and build/.

Since, according to the current plan, this will be for Git only, this setup makes sense. I'm only a bit hesitant regarding putting `ckeditor.js` into root. Since the moment I noticed that this is is not consistent with the rest of our packages, I'm thinking about `src/`. Would such a repo setup be acceptable?

```
/
    bin/
        ...
    build/
        ckeditor.js
        ckeditor.js.map
    src/
        ckeditor.js
    build-config.js
    webpack-config.js
    package.json
```

**Comment by wwalc** [comment] 2017-09-05 16:10
Just to clarify my last comment about whether to include a sample or not. I see two options:

1) (no sample) README mentions what kind of editor is included and links to the builds documentation, to a place where one will be able to easily find out on how to run precisely his editor (how easy it would be depends whether each readme will link to docs for that particular build).  From that documentation page one should also easily find further links that might be interesting for him, like for example on how to configure the editor and where to find the list of config options. Some really short & easy quick start for builds, basically.

OR

2) (sample) Readme mentions what kind of editor is included and links to the same documentation as above. At the same time, README tells the user that to get a taste of freshly downloaded editor and to see how to initialise it, he can check the attached sample. 

In both cases README does not contain any kind of "documentation" nor code snippets, because it will be just cumbersome and harder to maintain for us. The second option reduces a bit the chance that one will start copying code snippets for the wrong editor as a starting point he will have the fully working sample.

**Comment by fredck** [comment] 2017-09-06 08:10
> Also, which is an off-topic, these names conflict with names of editor constructors ;|||| Basically, we use the same names for two different things and I don't like this. Neither will users... Do we want a separate ticket for that?

I think that this was on purpose because these are mutually exclusive and at the same time they point to the very same thing. Either you go with the global or with the class constructor. Having them sharing the same name makes the documentation simpler.

**Comment by fredck** [comment] 2017-09-06 08:15
> In both cases README does not contain any kind of "documentation" nor code snippets, because it will be just cumbersome and harder to maintain for us.

Well, if we're ok with the idea of maintaining a sample, we should be even more ok with the idea of maintaining a bit of code in the README.

I don't think the README needs to be extremely short. It can be extensive and if we feel that including some lines of code in it as a "try out now" helper, it should be fine. Linking to the documentation is as well fine.

I think we'll figure this out once the first README will be ready. We can decide this later on, much probably.

**Comment by wwalc** [comment] 2017-09-06 08:58
> I don't think the README needs to be extremely short. It can be extensive and if we feel that including some lines of code in it as a "try out now" helper, it should be fine. Linking to the documentation is as well fine.

The reason why I'm reluctant to put more information to readme is that it is a plain text file. Readme looks fine on GitHub when it's processed by the markdown parser.

**Comment by Reinmar** [comment] 2017-09-06 10:00
I'd like to create the README based on some template that we'd keep somewhere outside of build repos. It'd be filled with data read from various of files in the build repo (e.g. the creator name would be read from the `build-config.js`, the link to docs from `package.json`, and so on). 

I thought that it would allow us to have a code snippet in the README – we'd just fill in the variable name. But then I realised that the code needed to start the editor may differ between builds. Right now we'd be able to create a generic code snippet but with more builds we may stop being able to do that. So we'd put that code somewhere in the repo (there's a sample actually...) but then it means more work and everything. And a high chance that the included sample will stop working at some point.

So, I'm also for a simple README. At least for now – to avoid thinking about this. We can extend it with time.

**Comment by wwalc** [comment] 2017-09-13 13:45
Just a quick proposal for README.md: https://gist.github.com/wwalc/fb9d4c4808bf512ab45dbc8724e806dc
The link to docs will change once the documentation site is live.

**Comment by Reinmar** [comment] 2017-09-14 08:04
1. Do we have to capitalize the entire title? "CKEditor 5 classic build 0.11.0" looks so much more pleasant to me :)
2. I prefer "v0.11.0" but I can see that we've been using "0.11.0" notation so far (in emails e.g.), so I guess it should be "0.11.0".
3. Instead of: "In order to start using CKEditor 5 Builds ..."

I'd link directly to some kind of Quick start for zips. Like "See the quick start guide: ..." and later "Read more about how to configure and customize the editor in ...".

Sending people to the index page leaves them with the trouble of finding where in this documentation they can learn how to start the editor. And, in fact, there's a quick start guide which mentions CDN, but very little about using zips.

**Comment by fredck** [comment] 2017-09-14 11:20
> Do we have to capitalize the entire title? "CKEditor 5 classic build 0.11.0" looks so much more pleasant to me :)

That's the name of the build, not only a title. It must be capitalized, always.

> I prefer "v0.11.0" but I can see that we've been using "0.11.0" notation so far (in emails e.g.), so I guess it should be "0.11.0".

I agree with you... especially when it starts with zero.

**Comment by wwalc** [comment] 2017-09-14 13:51
Last thing to set, the full structure of a zip file:

1)  No root folder

```
ckeditor.js
ckeditor.js.map
README.md
LICENSE.md
```
Cons: someone may extract it in a project and have to look for files among other files. Also README.md may overwrite other README.md

2) With root folder

```
<folder>
   |----ckeditor.js
   |----ckeditor.js.map
   |----README.md
   |----LICENSE.md
```
This is the setup we successfully used with CKEditor 4, where the root folder was called "ckeditor".

Which name to use for CKEditor 5?

a) `ckeditor`
b) `ckeditor-classic`, `ckeditor-inline`, `ckeditor-balloon`
c) `build` (as we have inside repositories)
d) `build-ckeditor-classic`, `build-ckeditor-inline`, `build-ckeditor-balloon`

The more I think about this, the more I'm willing to use `ckeditor` again. Why:
 - With CKEditor 4 we also had different "builds" (basic, standard, full, custom builds thanks to the online builder)
 - It's easier to put into the lib/vendor folder which is already called "ckeditor" than "build", that does not mean anything.

At the same time "b" seems to be acceptable as well. "d" seems to be too long. After all there will be no zip files with "`framework-ckeditor-classic`", "`frmework-ckeditor-inline`" folders etc. so maybe its safe to call whats inside just "ckeditor-classic".

**Comment by Reinmar** [comment] 2017-09-14 14:26
I'm somewhere between `ckeditor`, `ckeditor5-build-classic` and `ckeditor-classic` :D.

Definitely not `build`. That I know for sure because I couldn't find the unpacked content after you sent me a test zip ;)

**Comment by fredck** [comment] 2017-09-14 15:58
I'm for "1".

The zip will match the contents of the npm package. npm uses the package name as the directory that holds its contents. If we put an additional directly inside, it'll just make the path longer, pointlessly.

**Comment by wwalc** [comment] 2017-09-14 19:43
@fredck my comment was about the structure of a **zip** file only.
If you prefer to make the zip package in line with npm then the zip file should contain `ckeditor5-build-classic` folder, not just 4 files (option 1 you mentioned). However npm and zip will not be entirely equal anyway because npm has an additional @ckeditor folder.

**Comment by pomek** [comment] 2017-09-27 08:14
Could I ask about some summary of the whole topic?

**Comment by Reinmar** [comment] 2017-09-29 22:20
AFAICS, everything is set already so I'm closing this ticket.

**Closed by Reinmar** 2017-09-29 22:20 UTC
Labels: status:discussion, type:docs
