### ISSUE TITLE
Select All + Delete leaves two paragraphs

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#306] opened 2016-08-22 13:05 UTC
1. Go to the [online demo](https://ckeditor5.github.io/).
 2. Click in the editor contents.
 3. `Cmd+A` to "Select All".
 4. `Backspace` to "Delete".

Actual results: two empty paragraphs are left (heading and normal paragraph).

Expected result: only one paragraph is left, the heading one (beginning of the selection).

**Comment by fredck** [comment] 2016-08-22 13:07
I can see that both the first and the last paragraphs are left after deleting. This can be checked by changing the last one the h2 before deleting.

**Comment by fredck** [comment] 2016-08-22 13:07
The same happens if you manually select more than one paragraph.

**Comment by Reinmar** [comment] 2016-08-22 18:56
This is a duplicate of https://github.com/ckeditor/ckeditor5-engine/issues/520. Perhaps there are couple of cases to solve, but let's keep all of them together.

**Closed by Reinmar** 2016-08-22 18:56 UTC
