### ISSUE TITLE
[IME] Not possible to create a new line with the `enter` key on GBoard at the end of the Heading paragraph

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#12390] opened 2022-09-01 09:28 UTC
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the all features manual test.
2.  Try to enter a new line using the English GBoard keyboard after the end of some Heading 1 paragraph

### ✔️ Expected result

Enter possible

### ❌ Actual result

Enter not working
![enter ime not working](https://user-images.githubusercontent.com/32898551/187881050-7dacbd79-5315-4f04-be50-08a032b4675f.gif)

## 📃 Other details

Branch: `ck/11438-beforeinput-ime-research-vol1.1-android`  
Language: English
Keyboards: Tested on  GBoard
Device: Pixel C emulator@Android v13 (API 33)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment] 2022-09-01 09:33
Duplicate of ckeditor/ckeditor5#11906.

**Closed by Mgsy** 2022-09-01 09:33 UTC
Labels: type:bug, browser:android, domain:ime, squad:core
