### ISSUE TITLE
Calling create() more than once on an element completely freezes the browser

### ISSUE THREAD

**Issue by thedavidmeister** [ckeditor/ckeditor5#746] opened 2017-12-24 11:31 UTC
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

alpha2

## 📋 Steps to reproduce

1. call create more than once on an element
2.

## ✅ Expected result

nothing happens, or a warning, or an error

## ❎ Actual result

browser completely freezes

## 📃 Other details that might be useful

https://codepen.io/anon/pen/NXbvMV?editors=1111

**Comment by Mgsy** [comment] 2018-01-02 08:57
I can reproduce this issue. It's reproducible only for `InlineEditor` and `BalloonEditor`. `ClassicEditor` loads properly. cc @Reinmar

**Comment by Reinmar** [comment] 2018-01-02 15:13
We know about this issue. It's caused by both editors overriding each other's changes. This is actually... the expected result for us. It means that everything works fine.

But I understand that this may be awful to debug for developers. We need to add some checks – e.g. mark elements (with `data-*` attrs) on which editor was created and throw when trying to create one on already marked element.

**Comment by oleq** [comment] 2018-01-19 10:24
Classic editors work fine because they create own root editables. The issue occurs in Inline and Balloon because the instances share pre-existing DOM elements and use them as editables. 

Anyway, do you think https://github.com/ckeditor/ckeditor5-ui/issues/176 could solve the issue? Would it work with asynchronous editors, e.g. the creation of the first one had started but it hasn't set any CSS class yet, while another one is about to be created and since there's no class (or attribute, whatever...) it starts using the same DOM element? Or is a complete edge case?

**Comment by Reinmar** [comment] 2018-01-19 10:56
It must be done synchronously and immediately, otherwise, it will not be a reliable check. So it needs to be done by the core – possibly by the editor utils (since the base `Editor` doesn't know about the element now).

**Comment by jodator** [comment] 2019-07-23 12:33
Closed by: https://github.com/ckeditor/ckeditor5-core/commit/6a590580548aae2b9f4d61c99899fd495d2721a3

**Closed** 2019-07-23 12:32 UTC
Labels: status:confirmed, type:enhancement
